### PR TITLE
Reference Seller App Tech Logs for Verification

### PR DESCRIPTION
**Pull request by Avijeet-Blocsol**
Hello ONDC Team,

We are submitting tech logs for verification for our reference Seller App on ONDC FS: GST Invoice Based Financing. We are submitting logs for all the transaction flows i.e. Flow 1 to Flow 6. This exercise is to show our readiness for the RQF for our seller application.

Looking forward to your comments.

Regards,
Avijeet

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Avijeet-Blocsol, below are the issues related to invoice-based-loans only, **please raise a separate PR for personal-loans**

INVOICE_BASED_LOAN
on_search
- headings should contain 'Organization Information' instead of 'Personal Information' (on_search_1 only)
- tag-group name should be 'INFO' instead of 'GENERAL_INFO' at items (on_search_1 only)
- tag BUYER_FINDER_FEES_TYPE value must be in a genric enum format i.e. 'PERCENT_ANNUALIZED'
- tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group
- tag INVOICE_NUMBER is missing in 'INFO' tag-group (on_search_3 only)

on_select
- tag INVOICE_NUMBER is missing in 'INFO' tag-group
- additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group
- headings should contain 'Individual KYC' instead of 'Know your Customer' at xinput
- tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group
- additional title OTHER_UPFRONT_CHARGES present in quote.breakup
- if quote object is not changed then quote.id should be same as sent in past on_select_1 call (for /on_select_2 only)

on_init
- cancellation_terms is missing 'DISBURSED' descriptor.code
- additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group
- tag INVOICE_NUMBER is missing in 'INFO' tag-group
- additional title OTHER_UPFRONT_CHARGES present in quote.breakup
- start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array (for /on_init_4 only)

on_confirm
- cancellation_terms is missing 'DISBURSED' descriptor.code
- additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group
- tag INVOICE_NUMBER is missing in 'INFO' tag-group
- additional title OTHER_UPFRONT_CHARGES present in quote.breakup
- start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array

on_update
- tag INVOICE_NUMBER is missing in 'INFO' tag-group
- additional title OTHER_UPFRONT_CHARGES present in quote.breakup
- tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group
- start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array
- CONSENT_INFO tag-group should be part of items[0] only, no need to create a new index i.e. items[1] (for /on_update_1 only)

on_status
- tag INVOICE_NUMBER is missing in 'INFO' tag-group
- additional title OTHER_UPFRONT_CHARGES present in quote.breakup
- tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group
- start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array

FLow-3
on_update_(3 & 4)
- MISSED_EMI_PAYMENT status should be NOT-PAID instead of DELAYED
- INSTALLMENT object with status as DELAYED is missing

on_update_5
- INSTALLMENT object with status as DEFERRED is missing
- post PAID payment status, url is not required in object in the MISSED_EMI_PAYMENT object

Flow-4
on_update_3
- code should change to COMPLETED at fulfillments.state
- post PAID payment status, url is not required in object with in the FORECLOSURE object
- status should change to DEFERRED for INSTALLMENT which had status as NOT-PAID

Flow-2
on_update_3
- INSTALLMENT object with status as NOT-PAID is missing(to which PRE_PART_PAYMENT object is refr.)

on_update_4
- post PAID payment status, url is not required in object with in the PRE_PART_PAYMENT object
- INSTALLMENT object with status as DEFERRED is missing(to which PRE_PART_PAYMENT object is refr.)

**Comment by Avijeet-Blocsol** [comment]
Points noted. We will fix the issues and re-upload the tech logs

**Comment by Avijeet-Blocsol** [comment]
Heelo Saurabh,



We require a few clarifications on the points raised:

1. 


INSTALLMENT object with status as DEFERRED is missing(to which PRE_PART_PAYMENT object is refr.)

When the payment is pre part payment, nothing is deferred. Why would there be an object with the Deferred Status? We dont get it when testing our buyer application with Pramaan as well.

2. 


Flow-4

on_update_3


code should change to COMPLETED at fulfillments.state

post PAID payment status, url is not required in object with in the FORECLOSURE object

status should change to DEFERRED for INSTALLMENT which had status as NOT-PAID




The fulfillment state will change to completed on on_update_4 when the payment has been successfully made and not on on_update_3. Also since the loan is being foreclosed, why would there by any deferred status for any of the payments?


Looking forward to your response



Regards,













---- On Fri, 14 Jun 2024 16:32:57 +0530 sourabhsaini11 ***@***.***> wrote ---





https://github.com/Avijeet-Blocsol, below are the issues related to invoice-based-loans only, please raise a separate PR for personal-loans

INVOICE_BASED_LOAN
 on_search
headings should contain 'Organization Information' instead of 'Personal Information' (on_search_1 only)

tag-group name should be 'INFO' instead of 'GENERAL_INFO' at items (on_search_1 only)

tag BUYER_FINDER_FEES_TYPE value must be in a genric enum format i.e. 'PERCENT_ANNUALIZED'

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

tag INVOICE_NUMBER is missing in 'INFO' tag-group (on_search_3 only)


on_select

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group

headings should contain 'Individual KYC' instead of 'Know your Customer' at xinput

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

if quote object is not changed then quote.id should be same as sent in past on_select_1 call (for /on_select_2 only)


on_init

cancellation_terms is missing 'DISBURSED' descriptor.code

additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array (for /on_init_4 only)


on_confirm

cancellation_terms is missing 'DISBURSED' descriptor.code

additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array


on_update

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array

CONSENT_INFO tag-group should be part of items[0] only, no need to create a new index i.e. items[1] (for /on_update_1 only)


on_status

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array


FLow-3
 on_update_(3 & 4)
MISSED_EMI_PAYMENT status should be NOT-PAID instead of DELAYED

INSTALLMENT object with status as DELAYED is missing


on_update_5

INSTALLMENT object with status as DEFERRED is missing

post PAID payment status, url is not required in object in the MISSED_EMI_PAYMENT object


Flow-4
 on_update_3
code should change to COMPLETED at fulfillments.state

post PAID payment status, url is not required in object with in the FORECLOSURE object

status should change to DEFERRED for INSTALLMENT which had status as NOT-PAID


Flow-2
 on_update_3
INSTALLMENT object with status as NOT-PAID is missing(to which PRE_PART_PAYMENT object is refr.)


on_update_4

post PAID payment status, url is not required in object with in the PRE_PART_PAYMENT object

INSTALLMENT object with status as DEFERRED is missing(to which PRE_PART_PAYMENT object is refr.)

**Comment by Avijeet-Blocsol** [comment]
Hello Saurabh,

We have updated the logs for invoice based credit as per the recommendations.

Please have a look and provide feedback on the same.

Regards

**Comment by Avijeet-Blocsol** [comment]
Hello Saurabh,

We have updated the logs for invoice based credit as per the recommendations.

Please have a look. Looking forward to your feedback.

Regards,












---- On Sat, 15 Jun 2024 10:15:13 +0530 Avijeet ***@***.***> wrote ---



Heelo Saurabh,



We require a few clarifications on the points raised:

1. 


INSTALLMENT object with status as DEFERRED is missing(to which PRE_PART_PAYMENT object is refr.)

When the payment is pre part payment, nothing is deferred. Why would there be an object with the Deferred Status? We dont get it when testing our buyer application with Pramaan as well.

2. 



Flow-4

on_update_3



code should change to COMPLETED at fulfillments.state

post PAID payment status, url is not required in object with in the FORECLOSURE object

status should change to DEFERRED for INSTALLMENT which had status as NOT-PAID




The fulfillment state will change to completed on on_update_4 when the payment has been successfully made and not on on_update_3. Also since the loan is being foreclosed, why would there by any deferred status for any of the payments?



Looking forward to your response



Regards,














---- On Fri, 14 Jun 2024 16:32:57 +0530 sourabhsaini11 ***@***.***> wrote ---















https://github.com/Avijeet-Blocsol, below are the issues related to invoice-based-loans only, please raise a separate PR for personal-loans

INVOICE_BASED_LOAN
 on_search
headings should contain 'Organization Information' instead of 'Personal Information' (on_search_1 only)

tag-group name should be 'INFO' instead of 'GENERAL_INFO' at items (on_search_1 only)

tag BUYER_FINDER_FEES_TYPE value must be in a genric enum format i.e. 'PERCENT_ANNUALIZED'

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

tag INVOICE_NUMBER is missing in 'INFO' tag-group (on_search_3 only)


on_select

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group

headings should contain 'Individual KYC' instead of 'Know your Customer' at xinput

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

if quote object is not changed then quote.id should be same as sent in past on_select_1 call (for /on_select_2 only)


on_init

cancellation_terms is missing 'DISBURSED' descriptor.code

additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array (for /on_init_4 only)


on_confirm

cancellation_terms is missing 'DISBURSED' descriptor.code

additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array


on_update

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array

CONSENT_INFO tag-group should be part of items[0] only, no need to create a new index i.e. items[1] (for /on_update_1 only)


on_status

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array


FLow-3
 on_update_(3 & 4)
MISSED_EMI_PAYMENT status should be NOT-PAID instead of DELAYED

INSTALLMENT object with status as DELAYED is missing


on_update_5

INSTALLMENT object with status as DEFERRED is missing

post PAID payment status, url is not required in object in the MISSED_EMI_PAYMENT object


Flow-4
 on_update_3
code should change to COMPLETED at fulfillments.state

post PAID payment status, url is not required in object with in the FORECLOSURE object

status should change to DEFERRED for INSTALLMENT which had status as NOT-PAID


Flow-2
 on_update_3
INSTALLMENT object with status as NOT-PAID is missing(to which PRE_PART_PAYMENT object is refr.)


on_update_4

post PAID payment status, url is not required in object with in the PRE_PART_PAYMENT object

INSTALLMENT object with status as DEFERRED is missing(to which PRE_PART_PAYMENT object is refr.)

**Comment by Avijeet-Blocsol** [comment]
Hello Saurabh,

Looking forward to your comments on our last PR request.

Regards,












---- On Sat, 15 Jun 2024 11:43:37 +0530 Avijeet ***@***.***> wrote ---



Hello Saurabh,

We have updated the logs for invoice based credit as per the recommendations.

Please have a look. Looking forward to your feedback.

Regards,












---- On Sat, 15 Jun 2024 10:15:13 +0530 Avijeet ***@***.***> wrote ---









Heelo Saurabh,



We require a few clarifications on the points raised:

1. 


INSTALLMENT object with status as DEFERRED is missing(to which PRE_PART_PAYMENT object is refr.)

When the payment is pre part payment, nothing is deferred. Why would there be an object with the Deferred Status? We dont get it when testing our buyer application with Pramaan as well.

2. 



Flow-4

on_update_3



code should change to COMPLETED at fulfillments.state

post PAID payment status, url is not required in object with in the FORECLOSURE object

status should change to DEFERRED for INSTALLMENT which had status as NOT-PAID




The fulfillment state will change to completed on on_update_4 when the payment has been successfully made and not on on_update_3. Also since the loan is being foreclosed, why would there by any deferred status for any of the payments?



Looking forward to your response



Regards,














---- On Fri, 14 Jun 2024 16:32:57 +0530 sourabhsaini11 ***@***.***> wrote ---















https://github.com/Avijeet-Blocsol, below are the issues related to invoice-based-loans only, please raise a separate PR for personal-loans

INVOICE_BASED_LOAN
 on_search
headings should contain 'Organization Information' instead of 'Personal Information' (on_search_1 only)

tag-group name should be 'INFO' instead of 'GENERAL_INFO' at items (on_search_1 only)

tag BUYER_FINDER_FEES_TYPE value must be in a genric enum format i.e. 'PERCENT_ANNUALIZED'

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

tag INVOICE_NUMBER is missing in 'INFO' tag-group (on_search_3 only)


on_select

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group

headings should contain 'Individual KYC' instead of 'Know your Customer' at xinput

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

if quote object is not changed then quote.id should be same as sent in past on_select_1 call (for /on_select_2 only)


on_init

cancellation_terms is missing 'DISBURSED' descriptor.code

additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array (for /on_init_4 only)


on_confirm

cancellation_terms is missing 'DISBURSED' descriptor.code

additional tags NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, REPAYMENT_FREQUENCY, ANNUAL_PERCENTAGE_RATE, INSTALLMENT_AMOUNT & COOL_OFF_PERIOD present in INFO tag-group

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array


on_update

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array

CONSENT_INFO tag-group should be part of items[0] only, no need to create a new index i.e. items[1] (for /on_update_1 only)


on_status

tag INVOICE_NUMBER is missing in 'INFO' tag-group

additional title OTHER_UPFRONT_CHARGES present in quote.breakup

tags GRO_DESIGNATION, GRO_ADDRESS are additionally added in CONTACT_INFO tag-group

start & end time must have milliseconds precise upto 3 decimal places, in INSTALLMENT objects at payments array


FLow-3
 on_update_(3 & 4)
MISSED_EMI_PAYMENT status should be NOT-PAID instead of DELAYED

INSTALLMENT object with status as DELAYED is missing


on_update_5

INSTALLMENT object with status as DEFERRED is missing

post PAID payment status, url is not required in object in the MISSED_EMI_PAYMENT object


Flow-4
 on_update_3
code should change to COMPLETED at fulfillments.state

post PAID payment status, url is not required in object with in the FORECLOSURE object

status should change to DEFERRED for INSTALLMENT which had status as NOT-PAID


Flow-2
 on_update_3
INSTALLMENT object with status as NOT-PAID is missing(to which PRE_PART_PAYMENT object is refr.)


on_update_4

post PAID payment status, url is not required in object with in the PRE_PART_PAYMENT object

INSTALLMENT object with status as DEFERRED is missing(to which PRE_PART_PAYMENT object is refr.)

**Comment by Avijeet-Blocsol** [comment]
Hello Sourabh,

Please provide clarification on the below mentioned point:

1. 
on_init_4

mime_type should be text/html at xinput


The loan agreement form we send is an application html form and not a text html form. Why do we need to have text/html for on_init_4?



Regards,












---- On Tue, 18 Jun 2024 19:34:49 +0530 sourabhsaini11 ***@***.***> wrote ---





https://github.com/Avijeet-Blocsol, please get the below issues fixed
 search_1
keys bpp_id & bpp_uri are not part of /search_1 call

additional object provider present in message


on_search_3

tags COOL_OFF_PERIOD, INSTALLMENT_AMOUNT,ANNUAL_PERCENTAGE_RATE, REPAYMENT_FREQUENCY, NUMBER_OF_INSTALLMENTS_OF_REPAYMENT are not part of INFO tag-group for /on_search call at items[1]

tags PRINCIPAL, INTEREST, PROCESSING_FEE, OTHER_CHARGES, OFFER_VALIDITY & INVOICE_NUMBER are missing in INFO tag-group at items[1]

tag INVOICE_NUMBER is not part of INFO tag-group at items[0]


select

incorrect attributes Context & Message present

additional object Error present

xinput is not part of /select_1 call (for /select_1 only)


init

additional object error present

id is not part of /init_1 call(for /init_1 only)


on_init_4

mime_type should be text/html at xinput


confirm

additional object error present


on_confirm

tags GRO_DESIGNATION & GRO_ADDRESS are missing in CONTACT_INFO tag-group


Flow-2
 update_2
additional attribute payments present


Flow-3
 update_2
additional attribute payments present


update_3

additional attribute params present in payments


on_update 3 & 4

label should be 'MISSED_EMI_PAYMENT' for payment object having id: 1 & status as NOT-PAID & PAID

LATE_FEE_AMOUNT is missing in quote.breakup


Flow-4
 update_2
additional attribute payments present


update_3

additional attribute params present in payments


on_update_4

upon foreclosure, INSTALLMENT with NOT-PAID as status should change to DEFERRED

**Comment by sourabhsaini11** [comment]
@Avijeet-Blocsol, please get the below issues fixed
common_issues
- additional select api pair call's present, please remove those additional calls

search_1
- bpp_id & bpp_uri are not part of /search_1 call
- provider is not part of /search_1 call

on_search_3
- tag INVOICE_NUMBER is not part of INFO tag-group at items[0]
- tags COOL_OFF_PERIOD, INSTALLMENT_AMOUNT, ANNUAL_PERCENTAGE_RATE, REPAYMENT_FREQUENCY, NUMBER_OF_INSTALLMENTS_OF_REPAYMENT are not part of INFO tag-group at items[1]
- tags PRINCIPAL, INTEREST, PROCESSING_FEE, OTHER_CHARGES, OFFER_VALIDITY & INVOICE_NUMBER are missing in INFO tag-group at items[1]

select_1
- invalid attributes Context, Error & Message
- values for form.id, status & submission_id should not be empty

init
- invalid attribute error present in payload
- attribute id is additionally send in payments (init_1 only)

on_init
- tag-group CONTACT_INFO is not required in provider

confirm
- invalid attribute error present in payload

update_2
- additional attribute payments present in payload

Flow-2
update_3
- additional attribute fulfillments present in payload

Flow-3
update_3
- additional attribute fulfillments present in payload
- additional attribute params present in payments

Flow-4, 5
update_3
- additional attribute fulfillments present in payload
- additional attribute params present in payments

on_update_4
- upon loan foreclosure, installments having NOT-PAID status should change to DEFERRED

**Comment by 92shreyansh** [comment]
@Avijeet-Blocsol Can we please have 1 PR for one use case, I see u have submitted 3 use cases in this PR

**Comment by Avijeet-Blocsol** [comment]
Hello Shreyansh,


I will make the changes and submit individual PR's.

Regards,












---- On Mon, 15 Jul 2024 18:45:49 +0530 Shreyansh Shah ***@***.***> wrote ---





https://github.com/Avijeet-Blocsol Can we please have 1 PR for one use case, I see u have submitted 3 use cases in this PR

**Comment by sourabhsaini11** [comment]
@Avijeet-Blocsol Can we please provide the comments on the PR and also update the PR with new logs in case you have made the changes in your application for any fix. We will be closing this PR going forward if in case no new modifications are being made.

**Pull request closed without merging**
