### PR TITLE
log submission for Earnest BAP TSP util (GC v2, flow 1 and flow 3)

### PR DESCRIPTION
**Pull request by adarshsingh87**
@Rishabh-ondc can you please review the logs.

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@adarshsingh87, kindly get the below issues fixed
on_search (flow-1 only)
- Timestamp for /on_search api should be greater than timestamp of /search api 

select (flow-1 only)
- Transaction Id for /on_search and /select api should be same

on_select
- Additional attribute offered_value at item.price in quote.breakup[0]
- either of duration or timestamp should be present at items.time

init
- Empty arrays should not be present(offers)
- In-correct tag-group DENOMINATION present in items, should contain CUSTOMIZATION instead

on_init
- Additional attribute offered_value at item.price in quote.breakup[0]

confirm
- Payment.params should not be null
- Id is missing in payments
- Url must contain a valid link instead of value being "NA", at payments
- updated_at & created_at are missing
- In-correct tag-group DENOMINATION present in items, should contain CUSTOMIZATION instead

on_confirm
- Payment.params should not be null
- Id is missing in payments
- Url must contain a valid link instead of value being "NA", at payments
- created_at is missing
- In-correct tag-group DENOMINATION present in items, should contain CUSTOMIZATION instead

on_status
- Payment.params should not be null
- Id is missing in payments
- Url must contain a valid link instead of value being "NA", at payments
- Empty arrays should not be present(offers)
- In-correct tag-group DENOMINATION present in items, should contain CUSTOMIZATION instead
- Additional tag-group CANCELLATION present in fulfillments (flow-3 only)
- Cancellation is missing (flow-3 only)

Flow-3
/search, /on_search & /on_cancel api's are missing

**Comment by adarshsingh87** [comment]
@sourabhsaini11 We've fixed the changes requested, can you review them again?

The platform syncs the catalogue once a day so the transaction id between the on_search and select won't be the same.

And the cancellation tag in the fulfilment object is correct and verified by rishabh

**Comment by sourabhsaini11** [comment]
@adarshsingh87, please get the below issues fixed
on_search
- remove empty string from item id's 290e01b5-9cab-4f26-b0a8-264bd2b58f1a, 18b35d42-7a40-4901-aaf2-79288fca2ce5
- timestamp at provider.time should be lesser or equal to context.timestamp

select
- message_id & transaction_id mismatch between /select & /on_select api (Flow-1)
- provider.id & item.id doesn't match with the one provided in /on_search (Flow-3)

init
- timetsamp should be less than on_init timestamp (Flow-3)

confirm, on_init, on_confirm
- price is missing in items (Flow-3)

status
- transaction_id mismatch from what was sent in past calls

on_status
- null values shouldn't be present in the payload
- price is missing in items (Flow-3)
- on_status should reflect order cancellation only if on_cancel call had been initiated in the past else should contain the latest order status (Flow-3)

on_cancel
- null values shouldn't be present in the payload
- price is missing in items
- CANCELLATION tag-group should'nt be present if order isn't cancelled at fulfillment level

**Comment by sourabhsaini11** [comment]
@adarshsingh87, please fix below issues
on_search
- time.timestamp can't be greater than context.timestamp

select
- fulfillments.id should not be present

Flow-1
select
- item.id doesn't match with item id's provided on /on_search

on_init
- offers are included but isn't present in other calls

on_status
- updated_at should be equal to context.timestamp 

Flow-3
common_issue
- title OFFER is missing from quote.breakup

select
- provider.id & item.id doesn't match with id's provided on /on_search

confirm
- payload present is of /on_confirm call

on_status
- updated_at should be equal to context.timestamp 
- order cancellation should be done through on_cancel call hence either /on_cancel should be called before status pair calls or /on_status shouldn't reflect order cancellation

**Comment by adarshsingh87** [comment]
@sourabhsaini11 updates logs, can you review them again?

Few things to note:
1. Our model for search/on_search is a catalogue sync so finding the correct on_search is a bit of a chore and the data for brands is in test mode.
2. for FLOW 3, quote.breakup has OFFER entry only if the order has any offer applied

**Comment by sourabhsaini11** [comment]
@adarshsingh87, kindly fix the below issues
common_issues(Flow-1 & 3)
select
- offers.id doesn't match with offer.id's shared in /on_search (Flow-1)
- provider & item id doesn't match with id's shared in /on_search (Flow-3)

on_init, confirm, on_confirm, on_status
- price is missing in items

Flow-3
on_cancel
- At quote.breakup, object with title ITEM is changed from what was sent in past call

on_status
- tag-group "CANCELLATION" should only be present if item level cancellation is being done, in your case as order level cancellation is being made hence tag-group CANCELLATION must be removed
- order.cancellation is missing

Note: If only one fulfillment is present, then order level cancellation should be made instead of fulfillment level.

**Comment by adarshsingh87** [comment]
@sourabhsaini11 The logs have been updated

In flow 3 for the on_cancel request the quote object is changed as the request carries quote implications, the same is reflected in the api contact and was verified with rishabh.

**Comment by sourabhsaini11** [comment]
@adarshsingh87, kindly get the below issues fixed as well
common_issue
- for descriptor.images, object containing url is missing inside images array

search
- remove additional attributes apart from context & message

on_select
- either of duration or timestamp should be present at items.time

Flow-1
confirm
- price is missing in items

on_status
- price.offered_value should not be 0

Flow-3
status
- timestamp should be greater than /on_cancel timestamp as your /on_status is reflecting cancellation state.

**Comment by adarshsingh87** [comment]
> for descriptor.images, object containing url is missing inside images array

I don't understand what's missing, can you point out what's missing? @sourabhsaini11

**Comment by adarshsingh87** [comment]
@sourabhsaini11 fixed rest of the issues

**Comment by sourabhsaini11** [comment]
@adarshsingh87, transactional logs are cleared.

**Pull request merged**
