### PR TITLE
Jtechnoparks IGM logs submission

### PR DESCRIPTION
**Pull request by sudhakara11**
Kindly review and confirm

### CODE REVIEW

**Comment by RupalSingla** [comment]
Issue close :
 There are some not required attributes that are present in the payload , kindly check the API contract 
@sudhakara11

**Comment by sudhakara11** [comment]
Dear @RupalSingla 

Thank you for the feedback.

We have verified with pramaan and it succeeded. 

And also verified with API contract payload, it looks all similar. 

https://docs.google.com/document/d/1UYGIo1fSOcA4ypnk5FuaCgUgNnu9dBQt/edit#heading=h.3znysh7

Can you please mention if any specific fields are not available.

Regards,
Sudhakar G

**Comment by RupalSingla** [comment]
Hi.
issue _close :
In issue close attributes mentioned below are not needed :

  "category": "PAYMENT",
        "sub_category": "PMT01",
        "complainant_info": {
          "person": {
            "name": "Tafique B"
          },
          "contact": {
            "phone": "9938867639",
            "email": "test@gmail.com"
          }
        },
"order_details": {
          "id": "3baa14f4-6bd8-4477-b1a1-946720893f92",
          "state": "DISBURSED",
          "provider_id": "c29d8cf3-5eeb-4aac-9eff-f5fadfd4dbc3"
        },
        "description": {
          "short_desc": "TUSHAR is issue",
          "long_desc": "SANDHYA is issue",
          "additional_desc": {
            "url": "https://storage.googleapis.com/nslive/1726048673698",
            "content_type": "text/plain"
          },
          "images": [
            "https://storage.googleapis.com/nslive/1726048673698"
          ]
        },
        "source": {
          "network_participant_id": "stagingondcfs.jtechnoparks.in",
          "type": "CONSUMER"
        },
        "expected_resolution_time": {
          "duration": "PT2H"
        },
        "expected_response_time": {
          "duration": "P1D"
        },
@sudhakara11

**Comment by 92shreyansh** [comment]
IGM logs Approved

**Pull request merged**
