### PR TITLE
Added RSF logs

### PR DESCRIPTION
**Pull request by g-arpit**
Removed RSF logs from [this](https://github.com/ONDC-Official/verification-logs/pull/1567) PR and raised a separate PR for them.

### CODE REVIEW

**Comment by g-arpit** [comment]
@92shreyansh When can we merge this PR?

**Comment by g-arpit** [comment]
@92shreyansh Any updates on this?

**Comment by RupalSingla** [comment]
Receiver_recon:
Many attributes are having null values , that is not allowd.
settlement_timestamp , created_at _updated_at cannot have same values

Two Flows needed , success and correction

@g-arpit

**Comment by RupalSingla** [comment]
There are two flows :suceess and correction in RSF , kindly submit both
@g-arpit

**Comment by 92shreyansh** [comment]
@g-arpit Please update the logs

**Comment by g-arpit** [comment]
@RupalSingla @92shreyansh Added correction logs as well.

**Comment by RupalSingla** [comment]
Error in json , please check there is a comma missing in the payload 

"receiver_recon": {
                "schemaErr0": "/context must have required property 'core_version'",
                "schemaErr1": "/context/domain must be equal to one of the allowed values (ONDC:NTS10)",
                "schemaErr2": "/message/orderbook/orders must NOT have fewer than 5 items",
                "schemaErr3": "/message/orderbook/orders/0 must have required property 'invoice_no'",
                "schemaErr4": "/message/orderbook/orders/0 must have required property 'state'",
                "schemaErr5": "/message/orderbook/orders/0 must have required property 'payerdetails'",
                "schemaErr6": "/message/orderbook/orders/0/provider must have required property 'address'",
                "schemaErr7": "/message/orderbook/orders/0/payment must have required property 'uri'",
                "schemaErr8": "/message/orderbook/orders/0/payment must have required property 'tl_method'",
                "schemaErr9": "/message/orderbook/orders/0/payment/params/amount must be number",
                "schemaErr10": "/message/orderbook/orders/0/payment/type must be equal to one of the allowed values (ON-ORDER)",
                "schemaErr11": "/message/orderbook/orders/0/payment/@ondc~1org~1buyer_app_finder_fee_type must be equal to one of the allowed values (percent,amount)",
                "schemaErr12": "/message/orderbook/orders/0/payment/@ondc~1org~1buyer_app_finder_fee_amount must be number",
                "schemaErr13": "/message/orderbook/orders/0/payment/@ondc~1org~1buyer_app_finder_fee_amount must be number",
                "schemaErr14": "/message/orderbook/orders/0/payment/@ondc~1org~1return_window_status must be equal to one of the allowed values (Assert)",
                "schemaErr15": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_basis must be equal to one of the allowed values (Collection)",
                "schemaErr16": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/settlement_phase must be string",
                "schemaErr17": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/settlement_phase must be equal to one of the allowed values (sale-amount,withholding-amount,refund)",
                "schemaErr18": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/settlement_type must be equal to one of the allowed values (upi,neft,rtgs)",
                "schemaErr19": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/settlement_bank_account_no must be string",
                "schemaErr20": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/settlement_ifsc_code must be string",
                "schemaErr21": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/bank_name must be string",
                "schemaErr22": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/branch_name must be string",
                "schemaErr23": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/beneficiary_address must be string",
                "schemaErr24": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/beneficiary_name must be string",
                "schemaErr25": "/message/orderbook/orders/0/withholding_tax_gst/value must be number",
                "schemaErr26": "/message/orderbook/orders/0/withholding_tax_tds/value must be number",
                "schemaErr27": "/message/orderbook/orders/0/deduction_by_collector/value must be number"
            },
            "on_receiver_recon": {
                "schemaErr0": "/context must have required property 'bpp_id'",
                "schemaErr1": "/context must have required property 'bpp_uri'",
                "schemaErr2": "/context must have required property 'timestamp'",
                "schemaErr3": "/context must have required property 'ttl'",
                "schemaErr4": "/context/domain must be equal to one of the allowed values (ONDC:NTS10)",
                "schemaErr5": "/context/core_version must be equal to one of the allowed values (1.0.0)",
                "schemaErr6": "/message/orderbook/orders must NOT have fewer than 5 items",
                "schemaErr7": "/message/orderbook/orders/0/counterparty_diff_amount/value must be number",
                "schemaErr8": "/message/orderbook/orders/0/counterparty_diff_amount must be null"
            }
        },

@g-arpit

**Comment by g-arpit** [comment]
@RupalSingla One of the comment states that `domain` value must be `ONDC:NTS10`, but we are onboarded for the domain `ONDC:TRV11`. Can you please check if we are validating the logs for the wrong domain?

For example: `settlement_basis must be equal to one of the allowed values (Collection)` here I think value `Delivery` is also allowed.

**Comment by ashitoshd-chalo** [comment]
@RupalSingla Can you please share the JSON Schema which you are using to validate the payloads?

**Comment by RupalSingla** [comment]
@g-arpit  Kindly please avoid the domain error , it was an understanding gap that you are submitting logs for NTS10

**Comment by ashitoshd-chalo** [comment]
@RupalSingla Can you please let us know if there is a need to rerun the schema validation checks again? Does it change based on the domain for ONDC:TRV11? If yes, can you please rerun and share the errors accordingly? 
Thanks.

**Comment by g-arpit** [comment]
@RupalSingla Can we connect once if possible? I went through your comments and documentation of RSF, it seems like many of your comments are mentioned as optional or wrong.

For ex: You have mentioned below params are mandatory, but it is marked as optional in documentation
"schemaErr7": "/message/orderbook/orders/0/payment must have required property 'uri'",
"schemaErr8": "/message/orderbook/orders/0/payment must have required property 'tl_method'"

Similarly, for below comment, it seems wrong. In documentation, string type is mentioned.
"schemaErr12": "/message/orderbook/orders/0/payment/https://github.com/ondc1org1buyer_app_finder_fee_amount must be number"

These are true for most of the above comments. Either schema validation is incorrect or documentation. It'll be much faster if we can connect and resolve this.

**Comment by g-arpit** [comment]
@RupalSingla I have addressed the applicable comments as discussed over call.

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @g-arpit

**Pull request merged**
