### PR TITLE
First draft

### PR DESCRIPTION
**Pull request by ankitaTranzita**

### CODE REVIEW

**Comment by ankitaTranzita** [comment]
Hi @92shreyansh, I have done the required changes.Please review this PR.

**Comment by sourabhsaini11** [comment]
@ankitaTranzita, kindly get the below issues fixed

common_issues
- message_id must be in uuid format

select_2
- status should be APPROVED at items.xinput

init
- id is missing in payments (init_2 & 3 only)

status
- message_id should be different to the message_id of /confirm call

**Comment by ankitaTranzita** [comment]
@sourabhsaini11 I have fixed the mentioned issues:

- message_id changed to UUID format
- in select_2 the items.xinput status is set to APPROVED
- added payment.id in init_2 & init_3
- message_id is is different in status & confirm call

Please review this [PR](https://github.com/ONDC-Official/verification-logs/pull/1570).

**Comment by sourabhsaini11** [comment]
@ankitaTranzita, please fix the below issue
select_3
- status should be SUCCESS at items.xinput
- unsolicited on_update & update pair calls are missing (capturing MONITORING_CONSENT flow)
Also, kindly submit rest of the flows as well.

**Comment by 92shreyansh** [comment]
@ankitaTranzita Why are the other flows missing? Please submit all the flows so that we can review all at once

@sourabhsaini11 Please make all flows as a pre-requsite to any PR.

**Pull request closed without merging**
