### PR TITLE
Tech Logs submission for Marine Insurance (ONDC:FIS13)

### PR DESCRIPTION
**Pull request by Nirdosh3312**
* Logs for Flow 1, Flow 2, Flow 3

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please get the below issue's resolved
init
- person.name is missing in fulfillments
- payments.type value must be in a generic enum format i.e. ON-ORDER
- person object is missing in fulfillments

on_init
- person.name is missing in fulfillments
- payments.type value must be in a generic enum format i.e. ON-ORDER
- person & organization object are missing in fulfillments

confirm
- Timestamp for /confirm API should be greater than the timestamp of /on_init API.
- payments.type value must be in a generic enum format i.e. ON-ORDER
- person object is missing in fulfillments

on_confirm
- organization object is missing in fulfillments
- person & organization object are missing in fulfillments
- payments.type value must be in a generic enum format i.e. ON-ORDER

**Comment by Nirdosh3312** [comment]
@sourabhsaini11, I have resolved the issues that you have mentioned. Kindly review the pull request.

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kIndly fix the below issues
common_issues
- CONVIENCE_FEE is additional in quote.breakup
- POLICY_START_DATE, INVOICE_NUMBER, INVOICE_DATE are missing in POLICY_DETAILS tag-group

on_search
- tag OFFLINE_CONTRACT is missing in payments

on_select_1
- policy price must be 1000 at item.price

on_select_2
- policy price must be 1000 at item.price

init
- start & end time should not be same at item.time

on_init
- dob & gnder are missing in person
- start & end time should not be same at item.time
- end time can't be less than start time in payment.time

confirm
- person object is incomplete.
- start & end time should not be same at item.time

on_confirm
- docs CLAIM_DOC, RENEW_DOC are missing in documents
- person object is incomplete.
- start & end time should not be same at item.time
- end time can't be less than start time in payment.time

on_status
- end time can't be less than start time in payment.time

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11, I have fixed the issues that you have mentioned and updated the logs. Kindly verify the updated logs

**Comment by 92shreyansh** [comment]
Transaction Logs Approved for Pramaan Tool

**Pull request merged**
