### PR TITLE
DMI Preprod Flow1 Logs

### PR DESCRIPTION
**Pull request by harsh-refo**
DMI Pre-prod Flow1 Log files.

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
on_search
- timestamp must be greater than the timestamp of previous call
- code in categories.descriptor must be in a standard enum format(PERSONAL_LOAN)
- code in items.descriptor must be in a standard enum format(PERSONAL_LOAN)
- Tag group name must be in a standard enum format (GENERAL_INFO)

select (all)
- bpp_id & bpp_url must be present in context
- form.id is missing

on_select (all)
- timestamp must be greater than the timestamp of previous call
- bpp_id & bpp_url must be present in context
- code in categories.descriptor must be in a standard enum format(PERSONAL_LOAN)
- In form_response.status should be PENDING instead of CONSENT_CREATED.

init (all)
- bpp_id & bpp_url must be present in context
- form.id is missing
- type is missing in payments

on_init (all)
- timestamp must be greater than the timestamp of previous call
- bpp_id & bpp_url must be present in context
- code in categories.descriptor must be in a standard enum format(PERSONAL_LOAN)
- cancellation_terms should not have N/A
- name in fulfillments.state.descriptor should not be null

confirm
- bpp_id & bpp_url must be present in context
- COURT_JURISDICTION & PAYMENT_COLLECTOR should not be part of tag 
- cancellation_terms should not have N/A


on_confirm
- timestamp must be greater than the timestamp of previous call
- city code is missing in context
- code in categories.descriptor must be in a standard enum format(PERSONAL_LOAN)
- title in quote must be in a standard enum format
- name in fulfillments.state.descriptor should not be null
- cancellation_terms should not have N/A

status
- bpp_id & bpp_url must be present in context

onStatus
- timestamp must be greater than the timestamp of previous call
- city code is missing in context
- xinput can't be null in items
- title in quote must be in a standard enum format
- name in fulfillments.state.descriptor should not be null


please resolve above issues
@harsh-refo

**Comment by harsh-refo** [comment]
@sourabhsaini11 I have resolved the issues you mentioned. Kindly review the pull request and approve.

**Comment by harsh-refo** [comment]
@sourabhsaini11 I have updated the PR to make the clarified changes in settlement terms today.

**Comment by sourabhsaini11** [comment]
Common issue
- city code should be * in each call

search
- bpp_uri & bpp_id should not be present in context for search

init 1, 2
- type is missing on on payments

on_init 1, 2
- percentage can't be empty, should be a value between 0-100

on_init 3
- percentage can't be empty, should be a value between 0-100
- label for each installment must be in a standard enum format (INSTALLMENT)

confirm
- type is missing on on payments
- PAYMENT_COLLECTOR should not be part of tag

on_confirm
- label for each installment must be in a standard enum format (INSTALLMENT)
- percentage can't be empty, should be a value between 0-100

on_status
- label for each installment must be in a standard enum format (INSTALLMENT)
- percentage can't be empty, should be a value between 0-100

@harsh-refo, kindly resolve above issues as well

**Comment by harsh-refo** [comment]
@sourabhsaini11  I have updated PR based on your feedback. Please review and approve.

**Comment by sourabhsaini11** [comment]
confirm
- PAYMENT_COLLECTOR should not be part of tag

on_update (call missing)

@harsh-refo, please resolve above issues also

**Comment by harsh-refo** [comment]
@sourabhsaini11 I have resolved the 'PAYMENT_COLLECTOR' issues you mentioned. Monitoring consent for PL is not required, so we haven't update/on_update for flow1. Kindly review the pull request and approve.

**Comment by sourabhsaini11** [comment]
@harsh-refo, kindly submit rest of the flows also

**Comment by harsh-refo** [comment]
@sourabhsaini11  I have added logs for rest of the flow, Please review and approve.

**Comment by sourabhsaini11** [comment]
Hii @harsh-refo, please resolve the below issues as well
flow 3
update
- update_target is missing

on_update (unsolicated)
- payment status should be DEFERRED for objects whose status were NOT-PAID before foreclose

flow 4
- on_update (solicated & unsolicited) calls missing, only PRE_PART_PAYMENT & FORECLOSURE calls are present

flow 5
update
- update_target is missing

on_update
- payment object with DELAYED status is missing
- range is missing for payment object of MISSED_EMI_PAYMENT

**Comment by harsh-refo** [comment]
Hi @sourabhsaini11, Please find the inline comments below. Request you to review and approve. 

flow 3
update

update_target is missing  - **Resolved**
on_update (unsolicated)

payment status should be DEFERRED for objects whose status were NOT-PAID before foreclose- **Will be fixed post GoLive**
flow 4

PRE_PART_PAYMENT on_update (solicated & unsolicited) calls missing, only MISSED_EMI_PAYMENT & FORECLOSURE calls are present - **DMI doesn't support Pre/Part payment. I have added Nack response in flow4**
flow 5
update

update_target is missing - **Resolved**
on_update

payment object with DELAYED status is missing - **It has been implemented, but we are unable to test it since the date has not passed yet.**
range is missing for payment object of MISSED_EMI_PAYMENT  - **Resolved**

**Comment by sourabhsaini11** [comment]
@harsh-refo,  below are the issues related to IGM logs

issue
- description.images must be string
- updated_by must have required property person
- org.name should be NP's subscriber_id::domain
- context timestamp should be greater than or equal to updated_at in issue

on_issue
- org.name should be NP's subscriber_id::domain
- context timestamp should be greater than or equal to updated_at in issue

on_issue_status
- message_id should be the same as sent in issue_status call
- action_triggered must be equal to one of the allowed values (REFUND,REPLACEMENT,RETURN,CANCEL,NO-ACTION)
- created_at should match issue's created_at
- gro_type value should be TRANSACTION-COUNTERPARTY-NP-GRO

issue_close
- updated_by must have required property 'person'
- context timestamp should be greater than or equal to updated_at in issue
- org.name should be bap_id::domain

**Comment by harsh-refo** [comment]
@sourabhsaini11  I have updated IGM logs as per above comments. 

As discussed on call Deferred and Delayed part will be done by 30th Jan.

**Comment by 92shreyansh** [comment]
Logs Approved under exceptions to fix the few findings by January 30th, 2024.

**Pull request merged**
