### PR TITLE
Kanpur metro verification logs

### PR DESCRIPTION
**Pull request by PradeepKumarAurion**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@PradeepKumarAurion, kindly get the below issues fixed

common_issues
- gps should be precise upto 6 digit only 
- message_id & transaction_id should'nt be same

search
- message_id should be different for both search_1 & search_2

on_search
- timestamp should be greater than the timestamp of search call
- message_id should be different for both on_search_1 & on_search_2
- cancellation_terms is not part of on_search
- For stop.type INTERMEDIATE_STOP & TRANSIT_STOP,  parent_stop_id is required
- category_ids should map/refer to one of the ids in categories array
- fulfillment_ids should map/refer to one of the ids in fulfillments array
- collected by is missing inside payment.

on_init
- timestamp should be greater than the timestamp of init call
- TRANSIT_STOP is missing in items.stops

confirm
- timestamp should be greater than the timestamp of on_init call

on_confirm
- timestamp should be greater than the timestamp of confirm call
- For stop.type INTERMEDIATE_STOP & TRANSIT_STOP,  parent_stop_id is required
- authorization value should be eiher of CLAIMED or UNCLAIMED as defined in developer contract under enum.

status
- timestamp should be greater than the timestamp of on_confirm call

on_status
- timestamp should be greater than the timestamp of status call
- For stop.type INTERMEDIATE_STOP & TRANSIT_STOP,  parent_stop_id is required
- authorization value should be eiher of CLAIMED or UNCLAIMED as defined in developer contract under enum.

cancel
- message_id should be different for both cancel_1 & cancel_2

on_cancel_1
- timestamp should be greater than the timestamp on cancel(SOFT_CANCEL)

on_cancel_2
- TICKET_INFO tag should not be part of on_cancel_2 (confirm)

FLow-3
cancel(confirm)
- cancellation_reason_id should be 0.


IGM
issue
- complainant_actions.org.name should be bap_id::domain

on_issue
- context.action should be on_issue
- Phone Number for /on_issue api is not in the valid Range
- respondent_actions.org.name should be bpp_id::domain
- created_at & updated_at are missing

on_issue_status
- context.action should be on_issue_status
- Phone Number for /on_issue api is not in the valid Range
- respondent_actions.org.name should be bpp_id::domain
- organization.name should be bpp_id::domain in resolution_provider.org
- created_at & updated_at are missing

**Comment by RupalSingla** [comment]
Receiver_recon:
orderbook needs to have atleast 5 orders in the orderbook.
contex.domain is incorrect.
settlementtimestamp cannot be more than context.timestamp.
must be equal to one of the allowed values (ONDC:NTS10)


@PradeepKumarAurion

**Comment by sourabhsaini11** [comment]
@PradeepKumarAurion, kindly get these issues resolved as well
common_issues
- gps should be precise upto 6 digit only

on_search_1
- message_id should be same as message_id of search_1 call
- collected by is missing inside payment.
- For stop.type TRANSIT_STOP, parent_stop_id is required

on_search_2
- message_id should be same as message_id of search_2 call
- collected by is missing inside payment.
- For stop.type TRANSIT_STOP, parent_stop_id is required
- type should be TRIP instead of ROUTE at fulfillments
- missing stations (TRANSIT_STOP/INTERMEDIATE_STOP) between Rawatpur & Kalyanpur

on_init
- message_id should be same as message_id of init call
- missing stations (TRANSIT_STOP/INTERMEDIATE_STOP) between Rawatpur & Kalyanpur

on_confirm
- message_id should be same as message_id of confirm call
- For stop.type TRANSIT_STOP, parent_stop_id is required

on_status
- message_id should be same as message_id of status call
- gps coordinates are not same for few stations as sent in past call


flow-2
on_cancel_1
- message_id should be same as message_id of cancel_1 call
- For stop.type TRANSIT_STOP, parent_stop_id is required

cancel-2
- timestamp should be greater than the timestamp of on_cancel_1 call

on_cancel_2
- message_id should be same as message_id of cancel_2 call
- TICKET_INFO tag should not be part of on_cancel_2


IGM
issue
- complainant_actions.org.name should be bap_id::domain

on_issue
- Phone Number for /on_issue api is not in the valid Range
- created_at & updated_at are missing

on_issue_status
- created_at & updated_at are missing

**Comment by sourabhsaini11** [comment]
@PradeepKumarAurion, kindly fix the below issues
on_search_1
- collected_by is missing in payments
- parent_stop_id is required for stops.type 'TRANSIT_STOP'

search_2
- invaid date 2024-04-119, timestamp should be in date-time format

on_search_2
- collected_by is missing in payments
- invalid descriptor.code 'GROUP' at items[1], valid enums are SJT, RJT, PASS, SFSJT
- missing stations (TRANSIT_STOP/INTERMEDIATE_STOP) between Rawatpur & Kalyanpur

on_init
- missing stations (TRANSIT_STOP/INTERMEDIATE_STOP) between Rawatpur & Kalyanpur

confirm
- bpp_uri mismatch in /on_init and /confirm

on_confirm
- parent_stop_id is required for stops.type 'TRANSIT_STOP'

on_status
- parent_stop_id is required for stops.type 'TRANSIT_STOP'

Flow-2
cancel_2
- timestamp should be greater than the timestamp of on_cancel_1 call

Flow-3
on_cancel_1
- message_id should be same as message_id of cancel_1 call
- parent_stop_id is required for stops.type 'TRANSIT_STOP'

on_cancel_2
- message_id should be same as message_id of cancel_2 call
- timestamp should be greater than the timestamp of cancel_2 call
- parent_stop_id is required for stops.type 'TRANSIT_STOP'


IGM
on_issue
- created_at & updated_at are missing

on_issue_status
- created_at & updated_at are missing
- issue_actions/respondent_actions[0]/cascaded_level is missing
- issue_actions/respondent_actions[0]/updated_at is not matching with on_issue call
- issue_actions/respondent_actions[0]/contact/phone is not matching with on_issue call

**Comment by RupalSingla** [comment]
@PradeepKumarAurion  


receiver_recon:
settlement_timestamp cannot have same context.timestamp

**Comment by RupalSingla** [comment]
on_receiver_recon

- "counterparty_recon_status": null, cannot be null
- schema errors in the message object - needs to be in this format
- message": {
              "name": "lesser amount",
              "code": "less"

@PradeepKumarAurion

**Comment by sourabhsaini11** [comment]
@PradeepKumarAurion, issues related to transactional-flow & IGM are still open, kindly submit new iterations for those as well.

**Comment by 92shreyansh** [comment]
@PradeepKumarAurion Please create seprate PR for RSF, Also As mentioned by @sourabhsaini11 please fix the transaction log comments as those are still open, Please check the PR trail for comments

**Comment by sourabhsaini11** [comment]
@PradeepKumarAurion, kindly get the below issues fixed
common_issues
- parent_stop_id is missing for stops.type 'END' & 'INTERMEDIATE_STOP'

on_search_1
- collected_by is missing in payments
- 'SETTLEMENT_DETAILS' tag-group is incorrect, tag 'SETTLEMENT_TYPE' sould be part of 'SETTLEMENT_TERMS' tag-group instead

on_search_2
- stops.type 'INTERMEDIATE_STOP' are missing
- descriptor.code 'GROUP' is invalid, valid codes are SJT, SFSJT, RJT, PASS
- collected_by is missing in payments
- 'SETTLEMENT_DETAILS' tag-group is incorrect, tag 'SETTLEMENT_TYPE' sould be part of 'SETTLEMENT_TERMS' tag-group instead

on_init
- stops.type 'INTERMEDIATE_STOP' are missing
- 'SETTLEMENT_DETAILS' tag-group is incorrect, tag 'SETTLEMENT_TYPE' sould be part of 'SETTLEMENT_TERMS' tag-group instead

on_confirm
- stops.type 'INTERMEDIATE_STOP' are missing
- 'SETTLEMENT_DETAILS' tag-group is incorrect, tag 'SETTLEMENT_TYPE' sould be part of 'SETTLEMENT_TERMS' tag-group instead

on_status
- stops.type 'INTERMEDIATE_STOP' are missing
- 'SETTLEMENT_DETAILS' tag-group is incorrect, tag 'SETTLEMENT_TYPE' sould be part of 'SETTLEMENT_TERMS' tag-group instead

on_cancel
- order.id doesn't match with the order_id sent in /cancel_1 (on_cancel_1 only)
- stops.type 'INTERMEDIATE_STOP' are missing
- 'SETTLEMENT_DETAILS' tag-group is incorrect, tag 'SETTLEMENT_TYPE' sould be part of 'SETTLEMENT_TERMS' tag-group instead

**Comment by sourabhsaini11** [comment]
@PradeepKumarAurion, please get the below issues fixed
on_search_1
- timestamp should be greater than the timestamp of /search(1) call

search_2
- message_id should be different from message_id sent in /search(1) call

on_search_2
- collected_by is missing

init
- remove tag-group SETTLEMENT_DETAILS 
- tag SETTLEMENT_TYPE value should be one of upi, neft or rtgs

on_init, on_confirm
- provided payload is incorrect

on_status
- timestamp, message_id & updated_at should not be same as sent in /on_confirm call
- provided payload is incorrect

on_cancel(soft)
- transaction_id & virtual_payment_address are missing in payments.params
- provided payload is incorrect

cancel(hard)
- message_id should be different from message_id sent in /cacnel(soft) call

on_cancel(hard)
- message_id should be different from message_id sent in /on_cancel(soft) call
- item is not required in title 'CANCELLATION_CHARGES' at quote.breakup
- provided payload is incorrect

**Comment by pradeep-kumar-dev** [comment]
@sourabhsaini11 this is the updated logs of the kanpur seller app. please review it and share the observations.

**Comment by PradeepKumarAurion** [comment]
@sourabhsaini11 this is the updated logs of the kanpur seller app. please review it and share the observations.

**Comment by sourabhsainii** [comment]
@PradeepKumarAurion, kindly get the below issues fixed
common_issues
- bap_id & bap_uri must remain same throughout the journey
- tag BUYER_FINDER_FEES_TYPE is missing in BUYER_FINDER_FEES tag-group
- gps should be precise upto 6 digit only
- price.value should be precise upto 2 decimal places only.
- timestamp of /on_action calls should be greater than the timestamp of /action calls

search_2
- timestamp should be greater than timestamp of /search_1 call

on_search_2
- type should be TRIP at fulfillments.
- invalid descriptor.code 'GROUP' at items[2], valid enums are SJT, RJT, PASS, SFSJT

init
- If collector is BAP then params should be sent by BPP.

on_confirm
- authorization.status should be either of UNCLAIMED or CLAIMED only.
- invalid tag TICKET SERIAL NUMBER, should be NUMBER instead at TICKET_INFO tag-group
- remove tag-group SETTLEMENT_DETAILS sent in payments

on_status
- authorization.status should be either of UNCLAIMED or CLAIMED only.
- invalid tag TICKET SERIAL NUMBER, should be NUMBER instead at TICKET_INFO tag-group
- remove tag-group SETTLEMENT_DETAILS sent in payments
- multiple stops with same code present in stops

Flow-2
cancel(hard)
- message_id should be different from message_id sent in /cacnel(soft) call
- timestamp should be greater than timestamp of /cacnel(soft) call

on_cancel(hard)
- remove tag-group TICKET_INFO 
- timestamp should be greater than timestamp of /on_cacnel(soft) call

Flow-3
cancel(hard)
- cancellation_reason_id should be 0 for technical cancellation
- message_id should be different from message_id sent in /cacnel(soft) call
- timestamp should be greater than timestamp of /cacnel(soft) call

on_cancel(hard)
- remove tag-group TICKET_INFO 
- timestamp should be greater than timestamp of /on_cacnel(soft) call

**Comment by PradeepKumarAurion** [comment]
@sourabhsaini11 this is the updated logs of the kanpur seller side. please review it and share the observations.

**Comment by sourabhsaini11** [comment]
@PradeepKumarAurion, please get the below issues fixed
common_issues
- BASE_FARE price & quote.price should be 40

search
- tag STATIC_TERMS is missing in tag-group SETTLEMENT_TERMS

init
- remove attribute params if value will be null

on_init
- invalid attributes categoryIds & fulfillmentIds, should be category_ids & fulfillment_ids instead

confirm
- bank_account_number & bank_code value should not be null, at payments.params

on_status
- invalid status UNUSED, should be one of CLAIMED or UNCLAIMED instead, at stops.authorization
- timestamp should be greater than the timestamp of /status call

Flow-2
on_cancel_2
- tag SETTLEMENT_TYPE value is changed from NEFT(past call) to UPI

**Comment by PradeepKumarAurion** [comment]
@sourabhsaini11 This is the rectified log for all the issues mentioned above. Please clear it from the seller's side.

**Comment by sourabhsaini11** [comment]
@PradeepKumarAurion, please get the below issues fixed
common_issues
- /on_action timestamp should be greater than the timestamp of /action calls 
- virtual_payment_address is required in params if SETTLEMENT_TYPE is upi
- created_at & updated_at timestamp can't be greater than context.timestamp

on_status
- created_at & updated_at timestamp can't be greater than context.timestamp
- multiple SETTLEMENT_AMOUNT tags present in SETTLEMENT_TERMS tag-group
- tag SETTLEMENT_WINDOW value got changed from what was sent in /on_confirm
- message_id mismatches with /status message_id
- timestamp should be greater than /select timestamp

cancel(soft)
- message_id should be different for both cancel_1 & cancel_2

cancel(confirm)
- timestamp should be greater than the timestamp of on_cancel_1 call

on_cancel(confirm)
- TICKET_INFO tag should not be part of /on_cancel(confirm)

**Comment by PradeepKumarAurion** [comment]
@sourabhsaini11  I have fixed all the issues you mentioned above, and some of the issues were already fixed in the previous log. Please check and confirm.

**Comment by sourabhsaini11** [comment]
@PradeepKumarAurion, please raise a seperate PR for RSF & IGM logs

**Comment by 92shreyansh** [comment]
Transaction logs for Seller NP.

**Pull request merged**
