### PR TITLE
Vaipratech logs

### PR DESCRIPTION
**Pull request by Janak2401**
Submitting updated metro logs for the TRV11 domain.

### CODE REVIEW

**Comment by Janak2401** [comment]
@92shreyansh Logs for TRV11 domain, could you add the respective label?

**Comment by Janak2401** [comment]
@92shreyansh Hey, any updates on this?

**Comment by sourabhsaini11** [comment]
@Janak2401, kindly get the below issues fixed
search_1
- collected_by is missing

search_2
- bpp_id & bpp_uri are missing

**Comment by Janak2401** [comment]
@sourabhsaini11 changes done according to the review comment, please review.

**Comment by Janak2401** [comment]
@92shreyansh @sourabhsaini11 any updates on this? I've updated the logs in this PR in the new commit.

**Pull request merged**
