### PR TITLE
Pahal Logs Added - Disbursement + IGM

### PR DESCRIPTION
**Pull request by Het1919**
Pahal finance verification logs added

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Het1919, Please provide json payload for each action call under flows as defined in logs submission on api contract. Also, logs from staging env will not be considered for verification. Kindly submit the same from pre-prod env.

**Comment by Het1919** [comment]
@sourabhsaini11 Any update on review ?

**Comment by Het1919** [comment]
@sourabhsaini11 added separate payload for each action call, can you please check now?

**Comment by sourabhsaini11** [comment]
@Het1919, please get the below issues fixed
IGM
common_issue
- should contain only igm calls, remove additional calls

Flow-1
common_issue
- cancellation_fee.percentage should consist valid value instead of NA
- Remove additional IGM(/issue ,/on_issue) api calls
- The total of the quote breakup (139,554) does not match the price value (139,254)

on_select_2
- total of the quote breakup (326,738) does not match the price value (326,438).

Flow-4
on_update(unsolicated)
- upon foreclosure, descriptor.code should be COMPLETE at fulfillments

Flow-5
on_update(unsolicated)
- status should be PAID for FORECLOSURE object in payment

Flow- 2 & 3 on_update(ACK) calls are missing

**Comment by Het1919** [comment]
@sourabhsaini11 issue resolved, and for flow2 and flow3, which are missed EMIs and part payments, are not supported yet, so we have not received the on_update (ACK). Rest things you can check.

**Comment by sourabhsaini11** [comment]
@Het1919, kindly get the below issues fixed as well
common_issues
- remove signature from each payload

flow- 4 & 5
on_update_1
- descriptor.code should be DISBURSED at fulfillments.state

**Comment by Het1919** [comment]
@sourabhsaini11 fixed the above issues, kindly request you to check.

**Comment by sourabhsaini11** [comment]
@Het1919, kindly get the below issues fixed
on_select_2 (all flows except flow-1)
- mismatch of 300 INR between breakup summation and quote.price

on_status(1 & 2)
- documents either shouldn't be empty or not present at all

on_status(4)
- payments should not be empty

on_update_1 (flow-4 & 5)
- for FORECLOSURE object in payment, status must be NOT-PAID

on_update_2 flow(5)
- for FORECLOSURE object in payment, url should not be present

**Comment by Het1919** [comment]
@sourabhsaini11 above issue are fixed.

**Comment by 92shreyansh** [comment]
Transaction & IGM logs for seller NP is Approved

**Pull request merged**
