### PR TITLE
Triffy Metro

### PR DESCRIPTION
**Pull request by prithvi-triffy**

### CODE REVIEW

**Comment by mofahsan** [comment]
Hi @prithvi-triffy, kindly resolve the below issues


Gps based flow -  
common : 
- bap_uri not https

search 
- payment.tags/settlement terms missing

on_search
- message/catalog/providers id missing
- message/catalog/providers/payments object missing
- message/catalog/providers/time precision is upto seconds it should be into milliseconds
- stops 
    - start :id missing
    -  end:  id and parent_stop_id missing

select
- provider id mismatch to the one received on on_search

on_select
- stops 
    - start: id missing
    - end : id , instructions , parent_stop_id missing
- time/range precision should be in millliseconds
- breakup/item object, id && price object missing , quote/id is extra


on_init 
- payments tags are missing
- breakup/item object, id && price object missing , quote/id is extra

confirm
- payments/params/transaction id should be uuid

on_confirm
- stops
    - start
        -  id missing
        - authorization/status missing
        - gps missing
    - end
        - gps missing
        - id missing
        - parent_stop_id  missing
        - instructions object missing
- payment tags are missing
- order/updatedat && created_at missing
- TICKET_INFO tags list descriptor name should be code instead of name
- breakup/item object, id && price object missing , quote/id is extra

on confirm m jo aya h 

on_status
- fulfilment/stops/authorization extra -doubtful if right or wrong
- fulfilment/stops/gps missing
- stops
    - start :  id, gps missing , authorization object is extra
    - end : id , parent_stop_id missing
- payment tags missing
- payments/params/transactionid missing
- settlement_details and settlement_terms tags missing
- created_at , updated_at missing
- quote/id extra
- TICKET_INFO tags list descriptor name should be code instead of name
- breakup/item object, id && price object missing , quote/id is extra

Station code flow-  
common : 
- bap_uri not https

search-1
- payment.tags/settlement terms missing 

on_search-1
- message/catalog/providers/payments object missing
- message/catalog/providers/time precision is upto seconds it should be into milliseconds
- stops 
    - start :id, instructions object missing
    -  end:  id and parent_stop_id missing
    - INTERMEDIATE_STOP: id , instructions , parent_stop_id missing

search-2
- payment.tags/settlement terms missing 

on_search-2
- message/catalog/providers/payments object missing
- message/catalog/providers/time precision is upto seconds it should be into milliseconds
- stops 
    - start :id and gps missing
    -  end:  id,instructions,gps, parent_stop_id missing


select
- provider id mismatch to the one received on on_search

on_select
- stops 
    - start: id,gps missing
    - end : id , instructions, gps, parent_stop_id missing
- time/range precision should be in millliseconds
- breakup/item object, id && price object missing , quote/id is extra


on_init 
- breakup/item object, id && price object missing , quote/id is extra
- stops:
    - start: id,gps missing
    - end: id, instructions,gps,parent_stop_id missing
- payments tags missing

confirm
- payments/params/transaction id should be uuid

on_confirm
- order/updatedat && created_at missing
- stops
    - start
        -  id missing
        - authorization/status missing
        - gps missing
    - end
        - gps missing
        - id missing
        - parent_stop_id  missing
        - instructions object missing
- payment tags are missing
- TICKET_INFO tags list descriptor name should be code instead of name
- breakup/item object, id && price object missing , quote/id is extra


on_status
- created_at , updated_at missing
- fulfilment/stops/authorization extra 
- TICKET_INFO tags list descriptor name should be code instead of name
- stops
    - start :  id, gps missing , authorization object is extra
    - end : id , gps, instructions, parent_stop_id missing
- payment tags missing
- payments/params/transactionid missing
- settlement_details and settlement_terms tags missing
- quote/id extra
- breakup/item object, id && price object missing , quote/id is extra


Cancel flow

on_cancel1
- stops:
    - start: id, gps missing
    - end: id , instructions, gps, parent_stop_id missing
- TICKET_INFO tags list descriptor name should be code instead of name
- payment tags missing
- SCHEDULED_INFO tags are missing
- breakup/item object, id && price object missing , quote/id is extra

on_cancel2
- stops:
    - start: id, gps missing
    - end: id , instructions, gps, parent_stop_id missing
    - SCHEDULED_INFO tags missing
    - TICKET_INFO are extra
    - SETTLEMENT_DETAILS,BUYER_FINDER_FEES,SETTLEMENT_TERMS tags missing
    - time/range precision should be upto milliseconds
    - breakup basefare item object, id missing,price object missing
    - breakup/REFUND_AMOUNT:  price,quantity missing

**Comment by 92shreyansh** [comment]
@prithvi-triffy Please submit the logs by testing with one of the subscibed BAP in pre-prod as all NPs should have a valid https enabled dns

**Comment by prithvi-triffy** [comment]
Logs added for:
- Flow 1 - (Happy Booking Flow)
- Flow 2 - (Cancellation Flow)

**Comment by sourabhsaini11** [comment]
Hii @prithvi-triffy, kindly get these below issues fixed

Flow-1
common_issues
- SETTLEMENT_TERMS tag list is incomplete

on_search
- payments object is part of providers array

confirm
- SETTLEMENT_DETAILS is not part of confirm 

on_confirm 
- authorization.status should be UNCLAIMED instead of UNUSED


Flow-2
cancel
- millisecond should be precise upto 3 digit at timestamp

on_cancel
- message_id should be same as sent in cancel call


please submit flow-2 also

**Comment by prithvi-triffy** [comment]
Added the logs with the feedback implemented.

**Comment by sourabhsaini11** [comment]
@prithvi-triffy, kindly get the below issues fixed as well

search
- STATIC_TERMS is missing in SETTLEMENT_TERMS

init
- STATIC_TERMS, SETTLEMENT_TYPE & SETTLEMENT_AMOUNT is missing in SETTLEMENT_TERMS

confirm
- SETTLEMENT_DETAILS is not part of confirm
- SETTLEMENT_TERMS tag list is incomplete

on_cancel
- message_id should be same as sent in cancel call

please submit gps based flow also

**Comment by prithvi-triffy** [comment]
Logs submitted with the on_cancel fix

**Comment by sourabhsaini11** [comment]
@prithvi-triffy, please get these issues resolved

search
- STATIC_TERMS is missing in SETTLEMENT_TERMS

init
- STATIC_TERMS, SETTLEMENT_TYPE & SETTLEMENT_AMOUNT is missing in SETTLEMENT_TERMS

confirm
- SETTLEMENT_DETAILS is not part of confirm
- SETTLEMENT_TERMS tag list is incomplete

also provide a successful technical cancellation flow

**Comment by sourabhsaini11** [comment]
@prithvi-triffy , please get the below fixed as well

cancel (confirm)
- millisecond should be precise upto 3 digit at context.timestamp

**Comment by prithvi-triffy** [comment]
Logs submitted with the feedback implemented

**Comment by 92shreyansh** [comment]
@prithvi-triffy Please provide dates for IGM and RSF dates by when you would be submitting the logs.

All Transaction Tech logs are fine

**Comment by 92shreyansh** [comment]
Transaction logs approved, IGM logs in https://github.com/ONDC-Official/verification-logs/pull/1376

**Pull request merged**
