### PR TITLE
Redbus Preprod logs

### PR DESCRIPTION
**Pull request by yashb042**

### CODE REVIEW

**Comment by yashb042** [comment]
params must consist of only bank_code, bank_account_number & virtual_payment_address for init call & they should not be empty

In init call, we don't have any info about bank_code, etc

**Comment by yashb042** [comment]
on_init - params is incomplete

This is the response from seller, should we ask the seller to send something here?

**Comment by yashb042** [comment]
Confirm,
email & phone must be same as sent in past calls at billing


We don't know the info about user till confirm call, so the billing in info API is random
Then in confirm itself we will know the actual data

**Comment by yashb042** [comment]
Search (code)

name, gps & id must be valid at stops

Didn't get this ^^^

**Comment by sourabhsaini11** [comment]
Hii @yashb042, kindly get these below issues fixed as well

init
- email & phone must be in valid format at billing

confirm
- email & phone must be in valid format at billing
- SETTLEMENT_BASIS value must be a generic enum as defined in developer guide

**Comment by yashb042** [comment]
As per the discussion, the scheduled go-live date for Metro live is 2nd Feb.
The IGM phase is planned for Feb 17th
Followed by the RSF flow on April 2nd

**Comment by sourabhsaini11** [comment]
Hii @yashb042, please get this issue fixed 

on_confirm & on_status
- params object is incomplete. Missing bank_code, bank_account_number & virtual_payment_address.

**Comment by 92shreyansh** [comment]
Transaction logs are Approved with exception based on dates for IGM and RSF as mentioned

**Pull request merged**
