### PR TITLE
Pre-Prod log submission for FIS:12(Personal Loan)

### PR DESCRIPTION
**Pull request by rashid-rb**
RupeeBoss folder Added with sub folder and with all log files

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@rashid-rb, kindly get the below issues cleared
common_issues
- please provide valid json for each api call
- remove additional attribute 'error' present in payload

select_1
- timestamp should be greater than the timestamp of /on_search call

select_2
- timestamp should be greater than the timestamp of /on_select_1 call

select_3
- timestamp should be greater than the timestamp of /on_select_2 call

init_1
- timestamp should be greater than the timestamp of /on_select_3 call

init_2
- timestamp should be greater than the timestamp of /on_init_1 call

init_3
- timestamp should be greater than the timestamp of /on_init_2 call

confirm
- timestamp should be greater than the timestamp of /on_init_3 call

update
- timestamp should be greater than the timestamp of /on_update_1 call

Flow-2, 3, 4, 5
- unsolicated on_update call capturing payment & updated flow status is missing

Flow-7
- Flow-7 should only consist of issue, issue(close), issue_status api pair-calls only.

issue
- context timestamp should be greater than or equal to updated_at in issue

issue(close)
- context timestamp should be greater than or equal to updated_at in issue
- complainant_actions is missing object with 'OPEN' complainant_action

on_issue_status
- org.name should be bpp_id::domain at resolution_provider

**Comment by rashid-rb** [comment]
All the issue has been cleared if you find anything please let me know.

**Comment by sourabhsaini11** [comment]
@rashid-rb, please get the below issues cleared as well
common_issue
- for Monitoring Consent, unsolicated_on_update must be called earlier by the seller before calling update-on_update pair api calls.

on_init
- email is missing in fulfillments.contact

on_confirm
- email is missing in fulfillments.contact

on_update
- email is missing in fulfillments.contact


Flow-3
update_foreclosure
- label should be FORECLOSURE, at payments.time

on_update_foreclosure
- object with label as FORECLOSURE & payment url is missing

on_update(unsolicated)_foreclosure
- quote object should remain same as sent in past on_update call
- upon foreclosure, fulfillments.code should change to 'COMPLETED'
- label should be 'FORECLOSURE' instead of 'MISSED_EMI_PAYMENT' at payments
- upon foreclosure, Installments with status 'NOT-PAID' should change to 'DEFERRED'


Flow-4
- unsolicated on_update(pre_part-payment) call is missing

update_pre_part_payment
- label should be PRE_PART_PAYMENT, at payments.time

on_update_pre_part_payment
- label should be 'PRE_PART_PAYMENT' instead of 'FORECLOSURE' at payments


Flow-5
- unsolicated on_update(missed_emi_payment) call is missing

update_missed_emi_payment
- label should be MISSED_EMI_PAYMENT, at payments.time

on_update_missed_emi_payment
- label should be 'MISSED_EMI_PAYMENT' instead of 'FORECLOSURE' at payments

IGM
issue(close)
- context timestamp should be greater than or equal to updated_at in issue
- created_at time should match to /issue's created_at time.

**Comment by rashid-rb** [comment]
@sourabhsaini11 can you please let me know how to set email in on_init, on_confirm, on_update(email is missing in fulfillments.contact ) because we are receiving  response on that from lender side.

**Comment by rashid-rb** [comment]
@sourabhsaini11 Please check and revert we have resolved above mentioned issues.

**Comment by sourabhsaini11** [comment]
@rashid-rb, please get the below issues fixed as well
on_select_1
- required is send additionally in xinput

on_select_3
- OTHER_UPFRONT_CHARGES is missing in quote.breakup

Flow-3
- on_update_foreclosure (unsolicated) call is missing

on_update_foreclosure
- OTHER_UPFRONT_CHARGES is send additionally in quote.breakup

Flow-4
- on_update_pre_part_payment (unsolicated) call is missing

on_update_pre_part_payment
- OTHER_UPFRONT_CHARGES is send additionally in quote.breakup

Flow-5 & 6
on_update_mark_missed_emi
- OTHER_UPFRONT_CHARGES is send additionally in quote.breakup

on_update_unsolicited_mark_missed_emi
- INSTALLMENT status should change to DEFERRED instead of being DELAYED
- payment object having label MISSED_EMI_PAYMENT is missing
- LATE_FEE_AMOUNT is missing in quote.breakup
- OTHER_UPFRONT_CHARGES is send additionally in quote.breakup

IGM
issue(close)
- created_at time should match to /issue's created_at time.

**Comment by rashid-rb** [comment]
@sourabhsaini11 I have fixed all the issues related to IGM and unsolicated API call rest of the issues need to resolve from lender side. Please check and revert as well.

**Comment by 92shreyansh** [comment]
Transaction and IGM logs approved

**Pull request merged**
