### PR TITLE
RSF Logs (DMRC)

### PR DESCRIPTION
**Pull request by Nirdosh3312**
Submitting RSF Tech Logs for Verification

### CODE REVIEW

**Comment by RupalSingla** [comment]
Flow 1:
on_receiver_recon:
order_recon _stataus for  both the flows are mentioned as 02 , which is not possible 
@Nirdosh3312

**Comment by Nirdosh3312** [comment]
Hey @RupalSingla , I have updated the logs for the issue you have mentioned, Kindly verify the PR. Looking forward to your response.

**Comment by RupalSingla** [comment]
Logs cleared for RSF version @Nirdosh3312

**Comment by Nirdosh3312** [comment]
Thanks @RupalSingla for the prompt the action and the support

**Comment by 92shreyansh** [comment]
RSF logs are Approved

**Pull request merged**
