### PR TITLE
Log Submission of Metro TRV11 (TSP Seller App)

### PR DESCRIPTION
**Pull request by vikas-Innvonix**
Preprod logs added. 
domain: TRV11
subscriber-id: ondc.dev.innvonix.in

### CODE REVIEW

**Comment by 92shreyansh** [comment]
@vikas-Innvonix Please create seprate PRs for IGM and for RSF we will validate these logs for Transaction APIs

**Comment by sourabhsaini11** [comment]
@vikas-Innvonix, kindly get the below issues fixed
common_issue
- GPS coordinates must be precise upto six decimal places

search
- collected_by is missing in payments

on_search_1
- fulfillments.type should be ROUTE
- Invalid tag-group TICKET_INFO at /on_search

on_search_2
- descriptor.code should be SFSJT instead of SFJT at items
- Invalid tag-group TICKET_INFO at /on_search

on_select
- Invalid tag-group TICKET_INFO at /on_select

on_init
- Invalid tag-group TICKET_INFO at /on_init

on_confirm
- order.status must be equal to one of the allowed values (ACTIVE,COMPLETED)
- updated_at & created_at should match context.timestamp

on_cancel(soft)
- updated_at & cancellation.time should not be greater than context.timestamp
- authorization.status & tag-group TICKET_INFO shouldn't be part of payload post cancellation (on_cancel_confirm only)

issue
- name should be equal to bap_id::domain

on_issue
- additional call on_issue with message_id aa2f93d8-ff41-4602-81c4-474db587b03f
- org.name should be euqal to bpp_id::domain
- context timestamp should be greater than or equal to updated_at & created_at

on_issue_status
- context timestamp should be greater than or equal to updated_at
- 'created_at' should match issue's 'created_at'
- org.name should be euqal to bpp_id::domain

**Comment by vikas-Innvonix** [comment]
@sourabhsaini11 can you please provide more details for the given point 

**> additional call on_issue with message_id aa2f93d8-ff41-4602-81c4-474db587b03f**

**Comment by vikas-Innvonix** [comment]
Hi @sourabhsaini11, I have updated the logs. please check them.

**Comment by sourabhsaini11** [comment]
@vikas-Innvonix, please get the below issues fixed
common_issues
- ROUTE_INFO tag-group is missing

on_status, cancel, on_cancel
- timestamp, created_at & updated_at are not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

cancel(confirm)
- timestamp must be greater than cancel(soft)'s timestamp

on_cancel
- message_id mismatch with /cancel(confirm) (/on_cancel_confirm only)
- timestamp must be greater than on_cancel(soft)'s timestamp (/on_cancel_confirm only)
- stops.end are not part of /on_cancel call. Additionally, attribute time should also be present in stops.start

**Comment by sourabhsaini11** [comment]
@vikas-Innvonix, kindly get the below issues fixed
common_issues
- additional tag-group SETTLEMENT_DETAILS sent in payments
- virtual_payment_address is not required if SETTLEMENT_TYPE is NEFT

on_search
- code should be either of TICKET or PASS at categories.descriptor
- tags are not part of on_search_1 call, at fulfillments (/on_search_1 only)

on_select
- INTERMEDIATE_STOP are missing in fulfillments.stops
- additional tag-group TRIP_DETAILS present in fulfillments

init
- params is not required in /init if collector is BAP
- multiple COURT_JURISDICTION tags present in payments

on_init, on_confirm
- INTERMEDIATE_STOP are missing in fulfillments.stops
- additional tag-group TRIP_DETAILS present in fulfillments

on_status
- INTERMEDIATE_STOP are missing in fulfillments.stops
- additional tag-group TRIP_DETAILS present in fulfillments
- incorrect value present for collected_by at payments

on_cancel(soft)
- status should be SOFT_CANCEL instead of SOFT_CANCELLED
- INTERMEDIATE_STOP are missing in fulfillments.stops
- additional tag-group TRIP_DETAILS present in fulfillments
- incorrect value present for collected_by at payments

on_cancel(confirm)
- authorization.status value should be either of UNCLAIMED & CLAIMED only
- INTERMEDIATE_STOP are missing in fulfillments.stops
- additional tag-group TRIP_DETAILS present in fulfillments
- incorrect value present for collected_by at payments

IGM
- Post issue(close) from buyer no api call(on_issue_2) should be sent from Seller Side

issue
- org.name should be bap_id::domain

issue(close)
- org.name should be bap_id::domain

on_issue
- The 'updated_at' of message/issue/issue_action/respondent_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue
- context timestamp should be greater than or equal to updated_at in on_issue

on_issue_status
- The 'updated_at' of message/issue/issue_action/respondent_actions/index[1]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue_status
- 'created_at' should match issue's 'created_at'

RSF
Correction flow
receiver_recon
- /context must have required property 'country'
- /context must have required property 'core_version'
- context must have required property 'city'
- /context/domain must be equal to one of the allowed values (ONDC:NTS10)
- /message/orderbook/orders must NOT have fewer than 5 items
- /message/orderbook/orders/0 must have required property 'invoice_no'
- created_at and updated_at should be equal

on_receiever_recon
- /message/orderbook/orders/0 must NOT have additional properties (receiver_app_uri)

**Comment by vikas-Innvonix** [comment]
Hi @sourabhsaini11 and @92shreyansh, we have updated the logs. please check them.

**Comment by sourabhsaini11** [comment]
@vikas-Innvonix, kindly get the below issues fixed
common_issues
- value mismatch for tag DELAY_INTEREST mismatch between /action & /on_action calls

search
- collected_by is missing in payments

on_search_1
- tags are send additionally in fulfillments
- type must be TRANSIT_STOP instead of TRANSIT at fulfillments.stops

on_confirm
- updated_at should be equal to timestamp

on_status
- updated_at should be equal to timestamp

Flow-2
on_cancel
- status is missing in authorization (/on_cancel(soft))
- updated_at should be equal to timestamp

**Comment by vikas-Innvonix** [comment]
Hey @sourabhsaini11 , 

on_search_1

- tags are send additionally in fulfillments

**As per your last comment tags are not to be sent in the on_search_1 callback, but the above point says they are. Please clarify.**

The rest of the changes are updated.

**Comment by sourabhsaini11** [comment]
@vikas-Innvonix, kindly get the below issue fixed
on_status
- timestamp must be gretaer than /status timestamp

on_cancel
- TICKET_INFO tag-group should be present in soft_on_cancel instead of confirm_on_cancel

**Comment by 92shreyansh** [comment]
@sourabhsaini11 Also make sure IGM and RSF are also reviewed with Transaction logs

**Comment by vikas-Innvonix** [comment]
@sourabhsaini11, we update the logs please check.

**Comment by sourabhsaini11** [comment]
@vikas-Innvonix, please get the below issue fixed
receiver_recon
- message/orderbook/orders/1/payment/uri must match format \"uri\"

**Comment by vikas-Innvonix** [comment]
@sourabhsaini11, We have updated the logs. Please check them.

**Comment by vikas-Innvonix** [comment]
@sourabhsaini11, is there any update regarding the logs?

**Comment by vikas-Innvonix** [comment]
@sourabhsaini11, are there any updates regarding the logs?

**Comment by JyotiSharma0711** [comment]
**FLOW 1

common error**

- message_id and transaction_id cannot be same

**reciever_recon**

- "/message/orderbook/orders/0/counterparty_diff_amount/value must be string"
- settelement_timestamp is in incorrect ISO format

**Comment by vikas-Innvonix** [comment]
@JyotiSharma0711 @sourabhsaini11  , We have updated the logs. Please check them.

**Comment by 92shreyansh** [comment]
Transactionl Logs, RSF and IGM is Approved

**Pull request merged**
