### PR TITLE
TRV10: NammaYatri v2.0.0

### PR DESCRIPTION
**Pull request by NikithShetty**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@NikithShetty, kindly get the below issues cleared

common_issues
- milliseconds should be precise upto 3 decimal places only, in timestamp
- gps should be precise upto 6 decimal places only

search
- ROUTE_INFO tag group is not part of search call
- SETTLEMENT_TYPE value should be one of upi, neft, rtgs

on_search
- location object must consist of unique identifier (id) alongside gps
- payments array is missing

on_select
- payments array is not part of on_select call
- provider object is missing
- additional title's in quote.breakup, title should be a generic enum specified in developer guide
- descriptor is missing in items
- fulfillments.id should match with one of the id sent in previous call

init
- provider object is missing
- instead of ON_FULFILLMENT, type in payments should be ON-FULFILLMENT
- tags & status is missing in payments

on_init
- status is not part of on_init call
- provider.id mismatches with the id sent in past call
- agent object is not part of on_init, in fulfillments
- descriptor is missing in items
- cancellation_terms are required in on_init
- tags, status & params is missing in payments
- additional title's in quote.breakup, title should be a generic enum specified in developer guide
- instead of ON_FULFILLMENT, type in payments should be ON-FULFILLMENT

confirm
- provider object is missing
- tags, status is missing in payments
- quote.breakup is missing

on_confirm
- additional title's in quote.breakup, title should be a generic enum specified in developer guide
- state & agent details are missing in fulfillments
- descriptor & tags are missing in items
- created_at & updated_at are missing
- tags, status is missing in payments
- cancellation_terms are required in on_init

on_track
- instead of url, location object should be sent


on_status & on_update(ride-assigned)
- incomplete call (missing items, payments, quote etc)

on_cancel
- call is incomplete( missing cancellation_terms, items, payments etc.)
- fulfillments array is incomplete


Rider Cancel Flow
- soft cancel & on_cancel calls are missing

**Comment by 92shreyansh** [comment]
updated comments based on 2.0.0 please check

**Comment by sourabhsaini11** [comment]
@NikithShetty, please look into the below issues

on_search
- descriptor is missing in items

select
- gps should be precise upto 6 decimal places only

on_confirm
- provider.id is missing

on_status, on_update
- provider.id is missing
- cancellation_terms is missing
- params is missing in payments
- items.tags is missing

on_cancel (soft)
- descriptor.code should not be RIDE_CANCELLED at fulfillments

**Comment by sourabhsaini11** [comment]
@NikithShetty, please fix the below issues also

on_status, on_update
- items.tags is missing

on_cancel
- milliseconds should be precise upto 3 decimal places, in context.timestamp (soft on_cancel)
- message_id for /cancel and /on_cancel api should be same
- provider.id is missing
- Vehicle details are incomplete at index
- bank_account_number & bank_code is missing in params in payments
- status & tags are missing in payments
- items.tags is missing

**Comment by 92shreyansh** [comment]
@NikithShetty @RitikaHanish  Transaction logs are Approved.

**Pull request merged**
