### PR TITLE
pre-prod-mm-ondc-api.delhitransport.in

### PR DESCRIPTION
**Pull request by AmanChartr**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@AmanChartr, please get the below issues fixed
common_issue
- breakup is incorrect, title's not defined as per Api-Contract
- price should be precise upto 2 decimal places
- virtual_payment_address is missing in params
- additional tags are present in FARE_POLICY tag-group
- tag SETTLEMENT_TYPE is missing in SETTLEMENT_TERMS for /on_action calls

search
- gps should be precise upto 6 decimal places in fulfillment.stops

on_search
- address is missing in fulfillment.stops
- vehicle should consist of only category, remove other attributes
- additional attribute offered_value in items.price
- short_desc & tags are send additionally in items
- gps should be precise upto 6 decimal places in locations
- status, type are send additionally payments

select
- gps should be precise upto 6 decimal places in fulfillment.stops

on_select
- agent, area_code, city, country, state & variant are sent additionally in fulfillments
- fulfillment.id mismatch between /select & /on_select
- tags are missing
- location_ids is missing in items
- payments is not part of /on_select

init
- area_code, city, country, state, & variant are sent additionally in fulfillments
- tags are not required in /init call

on_init
- cancellation_terms is incomplete
- id, created_at, updated_at are not part of /on_init
- area_code, city, country, state, & variant are sent additionally in fulfillments
- short_desc & offered_value are send additionally in tiems
- INFO tag-group is missing in items

confirm
- area_code, city, country, state, & variant are sent additionally in fulfillments
- tags are not required in /confirm call
- id is missing in payments
- SETTLEMENT_AMOUNT value mismatch between /action & /on_action calls

on_confirm
- milliseconds should be precise upto 3 places in context.timestamp
- cancellation_terms is incomplete
- created_at, updated_at should have milliseconds precise upto 3 places only
- area_code, city, country, state,capacity, color & variant are sent additionally in fulfillments
- short_desc & offered_value are send additionally in tiems
- INFO tag-group is missing in items
- id is missing in payments

on_track
- gps should be precise upto 6 decimal places in location
- milliseconds should be precise upto 3 places in updated_at.updated_at

on_status
- cancellation_terms is incomplete
- created_at, updated_at should have milliseconds precise upto 3 places only
- time, area_code, city, country, state,capacity, color & variant are sent additionally in fulfillments
- short_desc & offered_value are send additionally in tiems
- INFO tag-group is missing in items
- id is missing in payments

on_update
- cancellation_terms is incomplete
- created_at, updated_at should have milliseconds precise upto 3 places only
- time, area_code, city, country, state,capacity, color & variant are sent additionally in fulfillments
- short_desc & offered_value are send additionally in tiems
- INFO tag-group is missing in items
- id is missing in payments

**Comment by sourabhsaini11** [comment]
@AmanChartr, kindly submit /on_action calls as well

**Comment by sourabhsaini11** [comment]
@AmanChartr, please fix the below issues
common_issues
- breakup is incorrect, additional title's present which are not defined in Api-Contract
- price must be precise upto 2 decimal places
- virtual_payment_address is missing in params
- cancellation_terms is incomplete

search
- address is send additionally in stops.location
- tags are send additionally in fulfillment

on_search
- capacity & variant are send additionally in vehicle
- short_desc, offered_value & tags are send additionally in items
- gps must be precise upto 6 decimal places in locations
- status & type is missing in payments

select
- fulfillments is send additionally

on_select
- agent, area_code, city, country, state & variant are sent additionally in fulfillments
- short_desc is sent additionally in items
- payments is not part of /on_select
- location_ids is missing in items

init
- virtual_payment_address is missing in payment.param

on_init
- id, created_at, updated_at are not part of /on_init
- area_code, city, country, state, & variant are sent additionally in fulfillments
- short_desc & offered_value are send additionally in items
- INFO tag-group is missing in items

confirm
- virtual_payment_address is missing in payment.param

on_confirm
- created_at, updated_at should have milliseconds precise upto 3 places only
- address, area_code, city, country, state, capacity, color & variant are sent additionally in fulfillments
- short_desc & offered_value are send additionally in items
- INFO tag-group is missing in items

track
- transaction_id mismatch to what was sent in past calls
- timestamp should be greater than /confirm timestamp

on_track
- gps should be precise upto 6 decimal places in location

on_status
- created_at, updated_at should have milliseconds precise upto 3 places only
- address, area_code, city, country, state, capacity, color & variant are sent additionally in fulfillments
- short_desc & offered_value are send additionally in items
- INFO tag-group is missing in items
- time is send additionally in fulfillments.stops 

on_update
- created_at, updated_at should have milliseconds precise upto 3 places only
- address, area_code, city, country, state, capacity, color & variant are sent additionally in fulfillments
- short_desc & offered_value are send additionally in items
- INFO tag-group is missing in items
- time is send additionally in fulfillments.stops 
- tags are missing for FARE_POLICY tag-group

Flow-2
- soft_cancel pair calls are misssing

on_cancel
- created_at, updated_at should have milliseconds precise upto 3 places only
- address, area_code, city, country, state, capacity, color & variant are sent additionally in fulfillments
- short_desc is send additionally in items
- tags & payment_ids are missing in items
- INFO tag-group is missing in items
- id is missing in payments

**Comment by sourabhsaini11** [comment]
@AmanChartr, kindly fix the below issue as well
confirm
- tag SETTLEMENT_AMOUNT value should be precise upto 2 decimal places only.

**Comment by AmanChartr** [comment]
@sourabhsaini11 

Done please check now.

**Comment by 92shreyansh** [comment]
@AmanChartr Can you make sure the PR only has TRV10 data and not TRV11

**Comment by 92shreyansh** [comment]
Transaction Logs Approved

**Pull request merged**
