### PR TITLE
Log Submission | FIS12 TataDigital Buyer App | ppapi.tatadigital.com

### PR DESCRIPTION
**Pull request by sridharsuri**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@sridharsuri, kindly get the below issues resolved

common_issues
- in LOAN_INFO tag group, COOL_OFF_PERIOD & INSTALLMENT_AMOUNT should be in ISO 8601 duration format

search
- DELAY_INTEREST tag is missing in SETTLEMENT_TERMS tag-group

on_search
- Timestamp for /on_search api should be greater than timestamp of /search api
- tag group code should be GENERAL_INFO instead of General Information at items

on_select
- Timestamp for /on_select api should be greater than timestamp of /select api

init
- status is missing in payments
- payments.id is missing (init_2 & 3)

on_init
- Timestamp for /on_init api should be greater than timestamp of /init api

confirm
- id & status are missing in payments

on_confirm
- Timestamp for /on_confirm api should be greater than timestamp of /confirm api

on_status
- Timestamp for /on_status api should be greater than timestamp of /status api
- LOAN_CANCELLATION is missing in documents


flow 3 & 5
- unsolicited on_update call is missing

flow 4 
- on_update & unsolicited on_update calls are missing

**Comment by sourabhsaini11** [comment]
common_issues
in LOAN_INFO tag group, COOL_OFF_PERIOD should be in ISO 8601 duration format

confirm
- SETTLEMENT_WINDOW, SETTLEMENT_BASIS, MANDATORY_ARBITRATION & COURT_JURISDICTION tags are missing in SETTLEMENT_TERMS tag-group

flow 3 & 5
- unsolicited on_update call is missing

flow 4
- on_update & unsolicited on_update calls are missing

@sridharsuri, kindly get the above issues fixed.

**Comment by sourabhsaini11** [comment]
common_issues
- COOL_OFF_PERIOD value should be in ISO 8601 duration format i.e. PT1D

on_search
- code should be GENERAL_INFO in items

flow-3
on_update (unsolicited)
- installments which had status as NOT-PAID should change to DEFERRED instead of PAID upon foreclosure

flow-5 
missed-emi flow is missing (update, on_update calls)
@sridharsuri, please get the above issues fixed as well

**Comment by sridharsuri** [comment]
Hi @sourabhsaini11 ,

"COOL_OFF_PERIOD value should be in ISO 8601 duration format i.e. PT1D" : This value is given to us from the lender and hence we would not have control to modify the response log.

"code should be GENERAL_INFO in items" : This value is given to us from the lender and hence we would not have control to modify the response log.

"installments which had status as NOT-PAID should change to DEFERRED instead of PAID upon foreclosure" : This value is given to us from the lender and hence we would not have control to modify the response log.

"missed-emi flow is missing (update, on_update calls)" : This has been uploaded post your comment (Had dependency from the lender side, hence wass missed)

**Comment by sridharsuri** [comment]
Hi @sourabhsaini11 ,

For inquiries pertaining to lenders, our process relies on receiving complete logs from the lender. Consequently, we will be able to provide logs regarding lender-related findings once we have received the comprehensive journey details.

**Comment by sourabhsaini11** [comment]
@sridharsuri, below are the issues related to IGM
common_issues
- org.name is incomplete, should be equal to bap_id::domain
- context timestamp should be greater than or equal to updated_at in issue

on_issue
- 'created_at' should match issue's 'created_at'

on_issue_status
- 'created_at' should match issue's 'created_at'

**Comment by sourabhsaini11** [comment]
@sridharsuri, please get the below issue fix
on_issue
- context timestamp should be greater than or equal to updated_at in on_issue

**Comment by sourabhsaini11** [comment]
The rating value can be one of two possible enum values: either 'THUMBS-UP' or 'THUMBS-DOWN'.
Screenshot 2024-04-01 at 6 43 50 PM

**Comment by sridharsuri** [comment]
@sourabhsaini11 ,

**issue(close): rating is missing ** 
This has been fixed and resubmitted for review

**on_issue: context timestamp should be greater than or equal to updated_at in on_issue**
This is the lender response, hence we would not have control to modify the response log.

**Pull request merged**
