### PR TITLE
ONDC:TRV10 (On Demand Ride Booking) Tech Logs

### PR DESCRIPTION
**Pull request by Nirdosh3312**
Submitting the tech logs for the on demand ride booking for verification, Looking forward to your response

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please get the below issues fixed
on_select
- items.price got changed from the price sent on /on_search

on-confirm
- registration should not be present if ride is not assigned
Also, please submit rest of the flows as well

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11, We have fixed the issues and have also added Flow 2 and Flow 3 as well. Looking forward to your response

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please fix the below issue
- tag SETTLEMENT_AMOUNT value is wrong for Flow- 2 & 3

**Comment by Kapil-Kharera** [comment]
Hi @sourabhsaini11, We have fixed the issue of settlement amount in cancel request. Looking forward to your response.

**Comment by KapilKharera** [comment]
Hi @sourabhsaini11, We have fixed the issue of the settlement amount in cancel request. Looking forward to your response.

**Comment by 92shreyansh** [comment]
Transaction Logs Approved

**Pull request merged**
