### PR TITLE
Cybrilla Seller App Logs 

### PR DESCRIPTION
**Pull request by arcybrilla**
Logs are available at `/logs/Cybrilla`.

### CODE REVIEW

**Comment by anuj-ondc** [comment]
@arcybrilla Please fix below findings:

common issues:
  - Incorrect context version should be 2.0.0
  - Extra data-key `key` is present in context(for on_action calls)
  - Invalid timestamp format, should be in RFC3339 format(for on_action calls)

Flow 1:(full_pull)

search:
- BPP_TERMS should not be present.
- bpp_uri & bpp_id should not be present as part of search payload.

on_search:
- Extra categories are found like, OPEN_ENDED_DEBT, OPEN_ENDED_DEBT_BANKING_AND_PSU_FUND,OPEN_ENDED_DEBT_CORPORATE_BOND_FUND, OPEN_ENDED_DEBT_CREDIT_RISK_FUND etc. Please check developer
      guide for the list.
- In fulfillments -> THRESHOLDS - > extra tags are found ADDITIONAL_AMOUNT_MIN & ADDITIONAL_AMOUNT_MULTIPLES
- In items, tag group SCHEME_INFORMATION -> LOCKIN_PERIOD_IN_DAYS, NFO_START_DATE, NFO_END_DATE, NFO_ALLOTMENT_DATE, NFO_REOPEN_DATE, ENTRY_LOAD, EXIT_LOAD are missing.

FLow 2:(incremental_pull) 

search:
- Extra INCREMENTAL_PULL present at category level.

Flow 3: (SIP creation new folio)

select 1 & 2:
  - BPP_TERMS should not present
  - Extra tag group PLAN_INFORMATION
  - In items, tags should not be present
  - In fulfillments, tracking key is extra
  - In fulfillments, tags should not present
    
on_select 1 & 2:
  -  In items, fulfillment_ids are missing.
  -  parent_item_id is mising
  -  BAP_TERMS terms should not present(for all on_select calls)
  -  Duplicate tag-group PLAN_INFORMATION, PLAN_IDENTIFIERS & PLAN_OPTIONS.
  -  Duplicate enrties of BPP_TERMS

init: 
- In items, tags should not be present
- In fulfillments, tracking key is extra
- In fulfillments, tags should not present
- xinput should not be present.
- collected_by should be BPP not bpp.


on_init:  
- Duplicate tag-group PLAN_INFORMATION, PLAN_IDENTIFIERS & PLAN_OPTIONS .
- xinput should not be present.
- collected_by should be BPP not bpp.
confirm:
- xinput should not be present.

on_confirm:

- payment_ids is missing 
- xinput should not be present.


on_status: 
- fulfillment Id is not matching with on_confirm.
- value not present for FREQUENCY_DATES

Flow 4, 5, 6:

select 1:
- BPP_TERMS should not present (for all select calls)

on_select 1 & 2:  
-  In items, fulfillment_ids are missing (for all on_select calls).
-  parent_item_id is mising
-  BAP_TERMS terms should not present (for all on_select calls).
-  Duplicate enrties of BPP_TERMS

select 2:
- BPP_TERMS should not present & found duplicate entries also.

on_select 2:
 - BAP_TERMS should not present

on_status:
- In items, quantity key is missing.
- In fulfillments, stops are missing.

init:   
- xinput should not be present & submission_id is incorrect
- BPP_terms should not presnt & duplicate entries for BPP_TERMS found

on_init:
- xinput should not be present.
- BAP_TERMS should not present 
- collected_by should be BPP not bpp.
- Duplicate enrties of BPP_TERMS
    

Extra select & on_select are found with incorrect payload 
- 11_select
- 12_on_select
- 13_select
- 14_on_select


Note: Feedback for the remaining flows will be provided shortly.

**Comment by anuj-ondc** [comment]
@arcybrilla Please fix below findings as well

FLow 7: SIP Instalment
on_update: 
- BAP_TERMS are missing
- value not present for FREQUENCY_DATES

on_confirm:
-  fulfillment type is changed to SIP_INSTALLMENT but ID is same as in previous on_update
- BAP_TERMS are missing
- payment status should not be PAID
- value not present for FREQUENCY_DATES
- fulfillment state is missing

on_status:
- In fulfillments, customer creds are missing 
- BAP_TERMS are missing
- FOLIO_INFORMATION tag group is not present
- cancellation_terms is missing 
- fulfillment state is missing

Flow 8 : SIP Instalment - Payment Failure

on_update_1: 
- BAP_TERMS are missing
- value not present for FREQUENCY_DATES
on_confirm:
- fulfillment type is changed to SIP_INSTALLMENT but ID is same as in previous 

on_update:
- BAP_TERMS are missing
- payment status should not be PAID
- value not present for FREQUENCY_DATES  
- fulfillment state is missing
 

on_update_2: 
- BAP_TERMS are missing
- value not present for FREQUENCY_DATES 
- fulfillment state is missing 

Flow 9 :SIP Instalment - Failure

on_update_1:
  - BAP_TERMS are missing
  - value not present for FREQUENCY_DATES
 on_confirm:
  - fulfillment type is changed to SIP_INSTALLMENT but ID is same as in previous on_update
- BAP_TERMS are missing
- payment status should not be PAID
- value not present for FREQUENCY_DATES  
- fulfillment state is missing

on_status:
- In fulfillments, customer creds are missing 
- BAP_TERMS are missing
- FOLIO_INFORMATION tag group is not present
- cancellation_terms is missing 
- fulfillment state is missing 
 

Flow 10:  SIP Auto Cancellation  
on_update_1:
  - BAP_TERMS are missing
  - value not present for FREQUENCY_DATES

FLow 11: SIP cancellation by the investor
on_update:
- BAP_TERMS are missing
- value not present for FREQUENCY_DATES 

Flow 12: SIP Completion
on_update:
- BAP_TERMS are missing
- value not present for FREQUENCY_DATES

Flow 13: Lumpsum Investment
select_1:
- BPP_TERMS should not present 

on_select_1: 
- BAP_TERMS should not present 
- Duplicate entries for BPP_TERMS 
- Quote is missing

select_2:
- BPP_TERMS should not present

on_select_2: 
- BAP_TERMS should not present 
- Duplicate entries for BPP_TERMS

init: 
- xinput should not present
- Extra key documents


on_init:
- xinput should not present
- Duplicate entries for BPP_TERMS 

confirm: 
- xinput should not present
- Duplicate entries for BPP_TERMS

on_confirm:
- xinput should not present

on_status: 
- BAP_TERMS are missing

Flow 14 Lumpsum Investment - Payment Retry:  


update:
  - BAP_TERMS tags should not present 
on_update:
  - BPP_TERMS are not present 
on_status:
  - BAP_TERMS are not present
  - In Payments, 2nd payment object is missing 
on_update_2:
  - BAP_TERMS are not present 

Flow 15 Redemption & 16 (Redemption Failure ):

select:
- BPP_TERMS should not present

on_select:
- BAP_TERMS should not present
- Duplicate entries for BPP_TERMS  

init:

- Extra key documents

on_init:
 - Extra key documents
 - Duplicate entries for BPP_TERMS  

confirm:
- Duplicate entries for BPP_TERMS 

on_confirm:
- Duplicate entries for BPP_TERMS  

on_update:
- Missing BAP_TERMS

**Comment by arcybrilla** [comment]
@anuj-ondc As discussed, please find the tag information to be updated in the developer docs.

1. List of categories supported.

```
OPEN_ENDED
OPEN_ENDED_DEBT
OPEN_ENDED_SOLUTION_ORIENTED
OPEN_ENDED_EQUITY
OPEN_ENDED_OTHER
OPEN_ENDED_HYBRID
OPEN_ENDED_HYBRID_AGGRESSIVE_HYBRID_FUND
OPEN_ENDED_HYBRID_BALANCED_HYBRID_FUND
OPEN_ENDED_EQUITY_FLEXI_CAP_FUND
OPEN_ENDED_DEBT_DYNAMIC_BOND
OPEN_ENDED_DEBT_MEDIUM_DURATION_FUND
OPEN_ENDED_DEBT_MONEY_MARKET_FUND
OPEN_ENDED_EQUITY_DIVIDEND_YIELD_FUND
OPEN_ENDED_DEBT_GILT_FUND_WITH_10_YEAR_CONSTANT_DURATION
OPEN_ENDED_EQUITY_ELSS
OPEN_ENDED_DEBT_ULTRA_SHORT_DURATION_FUND
OPEN_ENDED_DEBT_LIQUID_FUND
OPEN_ENDED_DEBT_LONG_DURATION_FUND
OPEN_ENDED_DEBT_GILT_FUND
OPEN_ENDED_EQUITY_MULTI_CAP_FUND
OPEN_ENDED_HYBRID_ARBITRAGE_FUND
OPEN_ENDED_SOLUTION_ORIENTED_RETIREMENT_FUND
OPEN_ENDED_DEBT_OVERNIGHT_FUND
OPEN_ENDED_EQUITY_LARGE_CAP_FUND
OPEN_ENDED_OTHER_FOF_DOMESTIC
OPEN_ENDED_EQUITY_SECTORAL_THEMATIC
OPEN_ENDED_EQUITY_MID_CAP_FUND
OPEN_ENDED_OTHER_INDEX_FUNDS
OPEN_ENDED_EQUITY_LARGE_MID_CAP_FUND
OPEN_ENDED_DEBT_BANKING_AND_PSU_FUND
OPEN_ENDED_DEBT_LOW_DURATION_FUND
OPEN_ENDED_EQUITY_FOCUSED_FUND
OPEN_ENDED_EQUITY_CONTRA_FUND
OPEN_ENDED_HYBRID_MULTI_ASSET_ALLOCATION
OPEN_ENDED_OTHER_FOF_OVERSEAS
OPEN_ENDED_EQUITY_SMALL_CAP_FUND
OPEN_ENDED_HYBRID_EQUITY_SAVINGS
OPEN_ENDED_OTHER_OTHER_ETFS
OPEN_ENDED_DEBT_CREDIT_RISK_FUND
OPEN_ENDED_DEBT_FLOATER_FUND
OPEN_ENDED_EQUITY_VALUE_FUND
OPEN_ENDED_SOLUTION_ORIENTED_CHILDREN_FUND
OPEN_ENDED_HYBRID_CONSERVATIVE_HYBRID_FUND
OPEN_ENDED_DEBT_MEDIUM_TO_LONG_DURATION_FUND
OPEN_ENDED_HYBRID_DYNAMIC_ASSET_ALLOCATION_OR_BALANCED_ADVANTAGE
OPEN_ENDED_DEBT_CORPORATE_BOND_FUND
OPEN_ENDED_DEBT_SHORT_DURATION_FUND
```

2. Following tags are optional in THRESHOLDS under fullfilments and they are populated based on the fullfilment[].type. 

```
ADDITIONAL_AMOUNT_MIN
ADDITIONAL_AMOUNT_MIN
AMOUNT_MAX
UNITS_MIN
UNITS_MAX
UNITS_MULTIPLES
FREQUENCY
FREQUENCY_DATES
INSTALMENTS_COUNT_MIN
INSTALMENTS_COUNT_MAX
CUMULATIVE_AMOUNT_MIN
```

Note: Each fulfillment type has some constant set of tags supported. 

3. Following tags are optional in SCHEME_INFORMATION

```
LOCKIN_PERIOD_IN_DAYS
NFO_START_DATE
NFO_END_DATE
NFO_ALLOTMENT_DATE
NFO_REOPEN_DATE
ENTRY_LOAD
EXIT_LOAD
```

**Comment by arcybrilla** [comment]
@92shreyansh @anuj-ondc Please help us with the following queries as well.

1. In exactly which /action and /on_action calls , the bap and bpp terms must be sent?
2. Should object of item.parent_id must also be present in select and further calls? I noticed in other other domains where only the `parent_item_id` is being passed. Let us know if only the `parent_item_id` is sufficient.

**Comment by anuj-ondc** [comment]
@arcybrilla 
- Action calls up to init will contain only BAP_TERMS, and on_action calls up to on_init can contain BPP_TERMS. From the confirm call onward, both action and on_action calls can include both BAP and BPP terms.
- parent_item_id needs to be part of child itemId object and adding parent_id as object is optional.

**Comment by arcybrilla** [comment]
@92shreyansh @anuj-ondc 

We have resubmitted the logs after fixing the items from previous comment. Kindly review.

Please note that we now added the logs for the major flows and we want this to get it reviewed before submitting the rest. Since, the data points and structure are almost similar in all the flows, we feel it would be inefficient to collect and submit for all the flows together incase if there is an error found even in a single attribute. For example, an error in a context attribute will repeat in all flows and all of them required to resubmitted. 

We feel it would be efficient and time saving for both parties to get the major flows reviewed first and once these are good, we can re-submit rest as well. Kindly let us know if there are any concerns.

**Comment by arcybrilla** [comment]
> @92shreyansh @anuj-ondc
> 
> We have resubmitted the logs after fixing the items from previous comment. Kindly review.
> 
> Please note that we now added the logs for the major flows and we want this to get it reviewed before submitting the rest. Since, the data points and structure are almost similar in all the flows, we feel it would be inefficient to collect and submit for all the flows together incase if there is an error found even in a single attribute. For example, an error in a context attribute will repeat in all flows and all of them required to resubmitted.
> 
> We feel it would be efficient and time saving for both parties to get the major flows reviewed first and once these are good, we can re-submit rest as well. Kindly let us know if there are any concerns.

**Comment by anuj-ondc** [comment]
@arcybrilla please fix below issues:
common_issues:
  - created_at & updated_at is missing. All calls from on_init should include this.(for on_action calls)
  - In context, timestamp format is incorrect, should be in UTC.



Incremental Pull: 

search:
- bpp_id & bpp_uri is missing.

SIP CREATION NEW FOLIO

init:
- In fulfillments tracking key is extra.
- Collect_by shoule be BPP not bpp.
- key `documents` is extra.
- code value for OFFLINE_CONTRACT is incorrect.
- BPP_TERMS -> STATIC_TERMS  value not matching with previous call.

on_init:
- key `documents` is extra.
- code value for OFFLINE_CONTRACT is incorrect.

confirm:
- key `documents` is extra.
- code value for OFFLINE_CONTRACT is incorrect.

on_confirm:
- In items, payment_ids is not matching with payments ID.
- code value for OFFLINE_CONTRACT is incorrect.

on_status:
- code value for OFFLINE_CONTRACT is incorrect.

on_update:
- code value for OFFLINE_CONTRACT is incorrect.

SIP_INSTALLMENT:

on_update:
- code value for OFFLINE_CONTRACT is incorrect.

on_confirm:
- no value found for FREQUENCY_DATES.
- code value for OFFLINE_CONTRACT is incorrect.

on_status:
- fulfillment Id is not matcing with on_confirm call.
- code value for OFFLINE_CONTRACT is incorrect.

on_update:
  - code value for OFFLINE_CONTRACT is incorrect.


LUMPSUM NEW FOLIO:

common issues:
- code value for OFFLINE_CONTRACT is incorrect.
- key `documents` is extra.

init:
- BPP_TERMS -> STATIC_TERMS  value not matching with previous call.

on_init:
- key `documents` is extra.

on_confirm:
- In payments, type needs to be PRE_FULFILLMENT not  PRE-FULFILLMENT
on_status:
- cancellation_terms are missing.

LUMPSUM PAYMENT RETRY

on_update 1:
- In payments, type needs to be PRE_FULFILLMENT not  PRE-FULFILLMENT
update:
- Tags are not required for payment retry.

on_update_2:
- BPP_TERMS are missing.  

on_status:
- cancellation_terms are missing. 
- In payments, type needs to be PRE_FULFILLMENT not  PRE-FULFILLMENT

REDEMPTION:

common issues:
- code value for OFFLINE_CONTRACT is incorrect.
- key `documents` is extra.

init:
- key `documents` is extra.
- BPP_TERMS -> STATIC_TERMS  value not matching with previous call.

on_init:
- BPP_TERMS -> STATIC_TERMS  value not matching with previous call.

**Comment by arcybrilla** [comment]
@anuj-ondc 

Kindly mark the tag `CREATED_ON` as optional in `FOLIO_INFORMATION`. This was missed previous list.

**Comment by anuj-ondc** [comment]
@char-star Please submit these flows:
- search incremental full pull 
- search incremental pull 
- sip creation new folio with kyc
- sip instalment (fulfillment success will be covered)
- sip installment payment failure.
- lumpsum existing folio
- lumpsum payment retry (both payment failure and retries will be covered)
- redemption & redemption failure(part of single flow)

**Comment by char-star** [comment]
@anuj-ondc we had submitted all flows since we had collected them this time. Please review only subset as required and let us know.

**Comment by anuj-ondc** [comment]
@arcybrilla, Please fix below findings:
common issues:
  - In confirm, static terms are not matching with previous api call.


****Incremental Search****:
  search:
  - remove decriptor for INCREMENTAL_PULL.

****SIP EXISTING FOLIO****:   
  - extra select_2 & on_Select_2 calls


****LUMPSUMP PAYMENT RETRY****: 
  update:
    - remove tags, as this update request is for payments only.
    - In payments, remove paymentID

**Comment by 92shreyansh** [comment]
Transactional Logs Approved for BPP.

**Comment by 92shreyansh** [comment]
Please move the logs to FIS14/Cybrilla instead of logs/Cybrilla

**Comment by arcybrilla** [comment]
@92shreyansh 

The logs are move to `FIS14/Cybrilla`.

**Pull request merged**
