### PR TITLE
Purchase finance logs

### PR DESCRIPTION
**Pull request by Ashu-14-oct**
Submitting Logs for Credit - ONDC:FIS12 (Purchase finance) for Verification

### CODE REVIEW

**Comment by simranOndc** [comment]
Hi @92shreyansh  This is for Pramaan

**Comment by anuj-ondc** [comment]
@Ashu-14-oct, Please fix below issues

common issues:
  - Missing BAP_TERMS & BPP_TEMS tag group.
  - Incorrect fulfillments type
  - CHECKLISTS tag group is missing.
  - In payaments, `BREAKUP` tag group is missing
  - In quote, change PRINCIPAL to PRINCIPAL_AMOUNT & INTEREST to INTEREST_AMOUNT.
  - Order status is missing
  - created_at & updated_at is missing, should be part of payload from on_confirm call.
  - Second fulfillment is missing of type BASE_ORDER

search:

on_search 1 & 2:
  - In items, descriptor code is incorrect.


on_Select_1(Applicable to all on_Select calls):
  - In INFO tag group, extrat tags OFFER_VALIDITY, OTHER_CHARGES, NET_DISBURSED_AMOUNT, INSURANCE_CHARGES, OTHER_UPFRONT_CHARGES, PROCESSING_FEE, PRINCIPAL_AMOUNT.
  - In quote, change PRINCIPAL to PRINCIPAL_AMOUNT & INTEREST to INTEREST_AMOUNT.

     


on_init 1:
  - message_id is not matching with init call.
  - In INFO tag group, extrat tags OFFER_VALIDITY, OTHER_CHARGES, NET_DISBURSED_AMOUNT, INSURANCE_CHARGES, OTHER_UPFRONT_CHARGES, PROCESSING_FEE, PRINCIPAL_AMOUNT.
  - In quote, change PRINCIPAL to PRINCIPAL_AMOUNT & INTEREST to INTEREST_AMOUNT.
  - Incorrect fulfillments type

on_init 3:
  - In payaments, `BREAKUP` tag group is missing
  - In INFO tag group, extrat tags OFFER_VALIDITY, OTHER_CHARGES, NET_DISBURSED_AMOUNT, INSURANCE_CHARGES, OTHER_UPFRONT_CHARGES, PROCESSING_FEE, PRINCIPAL_AMOUNT.
  - In quote, change PRINCIPAL to PRINCIPAL_AMOUNT & INTEREST to INTEREST_AMOUNT.
  - Incorrect fulfillments type  

on_confirm:
  - order status is missing
  - created_at & updated_at is missing
  - Second fulfillment is missing of type BASE_ORDER


Loan Foreclosure:
  - on_update_2:
    - Payment with ON_ORDER type should be PAID.
    - timestamp is missing for EMI with FORECLOSURE label.

Missed EMI:
  - on_update_2:
    - timestamp is missing for EMI with MISSED_EMI_PAYMENT label.

**Comment by Ashu-14-oct** [comment]
Hi @anuj-ondc , We have fixed the mentioned issues and have updated the logs, Kindly verify them.

Thanks

**Comment by Ashu-14-oct** [comment]
Hi @anuj-ondc, We have fixed the mentioned issues and have updated the logs, Kindly verify them.

Thanks

**Comment by Ashu-14-oct** [comment]
Hi @anuj-ondc , We have fixed the mentioned issues and have updated the logs, Kindly verify them.

Thanks

**Comment by simranOndc** [comment]
@anuj-ondc Please have a look at the logs shared. Thanks!

**Comment by anuj-ondc** [comment]
Transaction logs Approved for FIS12-2.2.0, PR will be merged soon.

**Pull request merged**
