### PR TITLE
IGM

### PR DESCRIPTION
**Pull request by paisabazaartech**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@paisabazaartech, please get the below issues cleared
issue
- context timestamp should be greater than or equal to updated_at in issue

issue (close)
- updated_by must have required property 'person' in complainant_actions
- updated_by must have required property 'phone in complainant_actions
- complainant_actions/1/complainant_action must be equal to one of the allowed values (OPEN,ESCALATE,CLOSE)'
- context.action should be issue
- context timestamp should be greater than or equal to updated_at in issue_close

on_issue
- context timestamp should be greater than or equal to updated_at in on_issue

**Comment by sourabhsaini11** [comment]
@paisabazaartech, please get the below issues fixed
on_issue
- updated_at should be always greater than and equals to created_at

on_issue_status
- updated_at should be always greater than and equals to created_at

**Comment by paisabazaartech** [comment]
Dear Team, These issues are on the seller end and are not on our side. Everything else has been closed from our end. Request you to please approve the logs and merge this PR

**Comment by 92shreyansh** [comment]
IGM logs Approved under exception as seller timestamp system is having challenges

**Pull request merged**
