### PR TITLE
Tech Logs for DMRC (ONDC:TRV11)

### PR DESCRIPTION
**Pull request by Nirdosh3312**
Submitting Tech Logs for Verification for ONDC:TRV11 (Metro)

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kindly get the below issue fixed
search 
- payment.collected_by must be present

on_search(stations)
- fulfillments must NOT have additional properties (line)
- GPS coordinates(longitude) must be precise upto six decimal places

on_confirm
- virtual_payment_address, bank_account_number, bank_code must match with the value sent in past call

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11, I have updated the logs for the issues you have mentioned. Can you Please verify the logs. 
Looking forward to your response.

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kindly get the below issues fixed
common_issue
DELAY_INTEREST value mismatch between /action & /on_action

on_confirm
- order is missing in message
- timestamp, created_at & updated_at values must be same
- params.transaction_id value mismatch between /confirm & /on_confirm

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kindly get the following issues fixed
on_search(1)
- GPS coordinates must be precise upto six decimal places only in longitude at fulfillments.stops            

on_search(2)
- GPS coordinates must be precise upto six decimal places only in longitude for stops_13, 16 & 18. at fulfillments.stops

on_select
- GPS coordinates must be precise upto six decimal places only in longitude for stops_13, 16 & 18. at fulfillments.stops

init
- params should not be present if collector is BAP

on_init
- GPS coordinates must be precise upto six decimal places only in longitude for stops_13, 16 & 18. at fulfillments.stops

confirm
- bank_code, bank_account_number & virtual_payment_address must be present at payments.params

on_confirm
- GPS coordinates must be precise upto six decimal places only in longitude for stops_13, 16 & 18. at fulfillments.stops
- authorization.status either be one of UNCLAIMED or CLAIMED

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11 , The logs for the issues you have mentioned have been updated. Can you Please verify the logs.
Looking forward to your response.

**Comment by 92shreyansh** [comment]
@Nirdosh3312 Can you please add the flow for delayed cancellation.

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please fix the below issues
common_issue
- DELAY_INTEREST value should remain same across /action /on_action calls

on_init
- SETTLEMENT_TERMS, Term code 'SETTLEMENT_TYPE' is not present in tag.list

Flow-2
- /on_update call is missing post /on_cancel

on_cancel
- price.value at quote should be of type string

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11 , We have updated the logs for the issues you have mentioned, Kindly have a look at them.

PS: We haven't yet completed the implementation of the on_update call post on_cancel call.

Looking forward to your response

**Comment by 92shreyansh** [comment]
Transaction Logs are Approved for BPP

**Pull request merged**
