### PR TITLE
Tech Logs Submission for TRV12 - Mobility Airline

### PR DESCRIPTION
**Pull request by KapilKharera**
Submitting Tech logs for Flow 1 and Flow 2 for ONDC:TRV12 Mobility Airline for verification.

### CODE REVIEW

**Comment by sourabhsainii** [comment]
@KapilKharera, kindly get the below issues fixed
common_issues
- label should contain appropraite name at stops.time

on_search
- timestamp value shouldn't be same for START & END stops
- quantity will consist of attribute 'selected' instead of 'maximum' & 'minimum'
- time, cancellation_terms & refund_terms are missing in items
- tag 'FARE_BREAK_UP' is missing in items
- id shouldn't be present

select_1
- add_ons should not be part of item consisting attribute id, should be part of a seprate object with attribute parent_item_id

select_2
- tag-group SEAT_GRID should be part of a seprate fulfillment object
- type is not requried in fulfillments
- items object containing parent_item_id is missing (each individual item object will be representing a single selected quantity, add_ons & must be refering to parent item object), Also add_ons should not be part of parent items.

on_select
- fulfillments with SEAT_GRID tag-group is missing
- items object containing parent_item_id is missing (each individual item object will be representing a single selected quantity, add_ons & must be refering to parent item object), Also add_ons should not be part of parent items.
- mutplie FARE_TYPE tag-groups present in provider (on_select_1 only)
- FARE_TYPE tag-group is missing in provider (on_select_2 only)

init
- tax_id should be present instead of email at billing
- customer should be part of a seprate fulfillment object
- items object containing parent_item_id is missing (each individual item object will be representing a single selected quantity, add_ons & must be refering to parent item object), Also add_ons should not be part of parent items.
- if collector is BAP, then params should be sent in BPP

on_init
- fulfillments objects with customer & SEAT_GRID tag-group is missing
- items object containing parent_item_id is missing (each individual item object will be representing a single selected quantity, add_ons & must be refering to parent item object), Also add_ons should not be part of parent items.
- FARE_TYPE tag-group is missing in provider
- id should be created on /on_confirm
- FARE_TYPE tag-group is missing in items

confirm
- id should be created on /on_confirm
- tax_id should be present instead of email at billing
- customer should be part of a seprate fulfillment object
- items object containing parent_item_id is missing (each individual item object will be representing a single selected quantity, add_ons & must be refering to parent item object), Also add_ons should not be part of parent items.
- if collector is BAP, then params should be sent in BPP

on_confirm
- fulfillments objects with customer & SEAT_GRID tag-group is missing
- items object containing parent_item_id is missing (each individual item object will be representing a single selected quantity, add_ons & must be refering to parent item object), Also add_ons should not be part of parent items.
- FARE_TYPE tag-group is missing in provider
- FARE_TYPE tag-group is missing in items

**Comment by KapilKharera** [comment]
Hi @92shreyansh, I have updated the logs for the airline. Please check them.

**Comment by sourabhsaini11** [comment]
@KapilKharera, please get the below issues fixed
on_search
- quantity should consist of selected instead of maximum & minimum in items
- tag-group FARE_BREAK_UP, cancellation_terms, refund_terms & time is missing in items

select_1
- quantity.selected.count should be 1 for items object which have parent_item_id present in them. Subsequently each individual ticket should be associated with it's own item object.
- items object referring to parent_item_id I1 is missing

on_select_1
- START & END stops timestamp should be different
- 6 fulfillments objects with type TICKET are present while selected tickets were only 3
- refund_terms is missing in items
- selected.count should be 1 instead of 2 for CHILD_TICKET in items(1 was ADULT_TICKET count in /search)
- selected.count should be 2 instead of 4 for ADULT_TICKET in items(2 was ADULT_TICKET count in /search)
- time is missing in items


select_2
- no of total fulfillments object should be selected tickets + 1
- quantity.selected.count should be 1 for items object which have parent_item_id present in them. Subsequently each individual ticket should be associated with it's own item object.
- items object referring to parent_item_id I1 is missing

on_select_2
- START & END stops timestamp should be different
- tag-group VEHICLE_GRID should be present for object having type TICKET
- additional tag-group VEHICLE_AVAIBALITY is present
- tag SELECTED_SEAT should be present instead of AVAILABLE in SEAT_GRID tag-group
- 6 fulfillments objects with type TICKET are present while selected tickets were only 3
- refund_terms is missing in items
- selected.count should be 1 instead of 2 for CHILD_TICKET in items(1 was ADULT_TICKET count in /search)
- selected.count should be 2 instead of 4 for ADULT_TICKET in items(2 was ADULT_TICKET count in /search)
- time is missing in items

init
- no of total fulfillments object should be selected tickets + 1
- quantity.selected.count should be 1 for items object which have parent_item_id present in them. Subsequently each individual ticket should be associated with it's own item object.
- items object referring to parent_item_id I1 is missing

on_init
- billing details are missing
- START & END stops timestamp should be different
- tag-group VEHICLE_GRID should be present for object having type TICKET
- additional tag-group VEHICLE_AVAIBALITY is present
- tag SELECTED_SEAT should be present instead of AVAILABLE in SEAT_GRID tag-group
- 6 fulfillments objects with type TICKET are present while selected tickets were only 3
- refund_terms is missing in items
- selected.count should be 1 instead of 2 for CHILD_TICKET in items(1 was ADULT_TICKET count in /search)
- selected.count should be 2 instead of 4 for ADULT_TICKET in items(2 was ADULT_TICKET count in /search)
- time is missing in items
- invalid title BASE_PRICE at quote.breakup


confirm
- no of total fulfillments object should be selected tickets + 1
- quantity.selected.count should be 1 for items object which have parent_item_id present in them. Subsequently each individual ticket should be associated with it's own item object.
- items object referring to parent_item_id I1 is missing

on_confirm, on_cancel
- billing details are missing
- START & END stops timestamp should be different
- tag-group VEHICLE_GRID should be present for object having type TICKET
- additional tag-group VEHICLE_AVAIBALITY is present
- tag SELECTED_SEAT should be present instead of AVAILABLE in SEAT_GRID tag-group
- 6 fulfillments objects with type TICKET are present while selected tickets were only 3
- refund_terms is missing in items
- selected.count should be 1 instead of 2 for CHILD_TICKET in items(1 was ADULT_TICKET count in /search)
- selected.count should be 2 instead of 4 for ADULT_TICKET in items(2 was ADULT_TICKET count in /search)
- time is missing in items
- invalid title BASE_PRICE at quote.breakup

**Comment by sourabhsaini11** [comment]
@KapilKharera, kindly get the below issues fixed
common_issues
- START stop timestamp must be greater than context.timestamp
- in quote.breakup, total objects with add_ons for id A2 should be 1 only
- in quote.breakup, add_ons for id A3 are missing
- in quote.breakup, price.value should be of type string for title TAX
- in quote.breakup, objects which have TAX tag-group in them should contain unique id which should refer to item.id

on_select_1
- tag SEAT_NUMBER value must be different for each fulfillment object in SEAT_GRID tag-group
- additional tag-group FARE_BREAK_UP present in items
- CHILD_TICKET count should be 1 & ADULT_TICKET count should be 2 as sent in /search call
- in items on basis of adult & child tickets count, 1 ref(parent_item_id) to id I1 should be present while 2 objects referring to id I2 should be there.

on_select_2
- tag SEAT_NUMBER & SELECTED_SEAT value must be different for each fulfillment object in SEAT_GRID tag-group
- CHILD_TICKET count should be 1 & ADULT_TICKET count should be 2 as sent in /search call
- in items on basis of adult & child tickets count, 1 ref(parent_item_id) to id I1 should be present while 2 objects referring to id I2 should be there.

init
- dob is missing in fulfillments.customer
- I1 count should be 1 while count of I2 should be 2

on_init
- dob is missing in fulfillments.customer
- tag SEAT_NUMBER & SELECTED_SEAT value must be different for each fulfillment object in SEAT_GRID tag-group
- CHILD_TICKET count should be 1 & ADULT_TICKET count should be 2 as sent in /search call
- in items on basis of adult & child tickets count, 1 ref(parent_item_id) to id I1 should be present while 2 objects referring to id I2 should be there.

confirm
- dob is missing in fulfillments.customer
- I1 count should be 1 while count of I2 should be 2

on_confirm
- fulfillment object having type as TRIP should not contain TICKET_INFO tag-group
- dob is missing in fulfillments.customer
- tag SEAT_NUMBER & SELECTED_SEAT value must be different for each fulfillment object in SEAT_GRID tag-group
- CHILD_TICKET count should be 1 & ADULT_TICKET count should be 2 as sent in /search call
- in items on basis of adult & child tickets count, 1 ref(parent_item_id) to id I1 should be present while 2 objects referring to id I2 should be there.

Note:-
Flow-1 should have Adult x1
Flow-2 should have Adult x2 child x1

**Comment by KapilKharera** [comment]
Hi @sourabhsaini11, I have updated the logs for the airline. Please check them.

**Comment by sourabhsaini11** [comment]
@KapilKharera, please get the below issues fixed as well
common_issues
- for tag PROHIBITED_ITEMS provide a descriptive value instead of "list of items"
- CANCELLATION_CHARGES & REFUND are missing in quote.breakup
- additional object refund_terms present in message.order

Kindly provide flows based on this sequence
- Flow-1 should have Adult x1
- Flow-2 should have Adult x2 child x1
- Flow-3 flight cancellation

**Comment by KapilKharera** [comment]
Hi @sourabhsaini11, I have updated the logs for the airline. Please check them.

**Comment by sourabhsaini11** [comment]
@KapilKharera, please get the below issues fixed
common_issues  
- value should be present instead of list for tag PROHIBITED_ITEMS
- for title REFUND type should be string, at quote.breakup

**Comment by KapilKharera** [comment]
Hi @sourabhsaini11, I have updated the logs for the airline. Please check them

**Comment by sourabhsaini11** [comment]
@KapilKharera, kindly get the below issue fixed as well
- message_id mismatch between /cancel & /on_cancel

**Comment by KapilKharera** [comment]
Hi @sourabhsaini11, I have updated the logs for the airline. Please check them.

**Comment by KapilKharera** [comment]
Hi @sourabhsaini11, I have updated the logs for the airline. Please check them.

**Pull request merged**
