### PR TITLE
InsuranceDekho logs submission

### PR DESCRIPTION
**Pull request by mohitpalsingh-ID**
InsuranceDekho logs submission for marine insurance FLOW 1.

### CODE REVIEW

**Comment by anuj-ondc** [comment]
common issues:

-   location: country & city can't be empty
-   bpp_id: incorrect bpp_id.
-   providerId: is incorrect, should match with previous ones.

on_search:

-   tags: Incorrect tag group "All_Risk_Cover" & "Basic_Risk_Cover"  

select_1:

-   Fulfillments: fulfillment_Id needs to be removed.

on_select:
-   tags: extra tag values:CARGO_DETAILS, COVERAGE_TO, PACKAGING_DETAILS
-   quote: incorrect title values, should match with the one form developer guide.

select_2
-  tags: incorrect tag group "KYC Process"

on_select_2:
-  xinput: Incorrect values for cur & max.
-  quote: incorrect title values, should match with the one form developer guide.

on_init:
-  provider: should not have the payment object
-  quote: incorrect title values, should match with the one form developer guide.

on_confirm:
-  Order_id is missing.
-  Order status is missing. 

@mohitpalsingh-ID Please fix the above issues.

**Comment by mohitpalsingh-ID** [comment]
@anuj-ondc solved the issues and updated the PR

**Comment by anuj-ondc** [comment]
@mohitpalsingh-ID, please provide logs from pre-prod environment.

**Comment by mohitpalsingh-ID** [comment]
> @mohitpalsingh-ID, please provide logs from pre-prod environment.

just updated the logs for preprod

**Comment by anuj-ondc** [comment]
on_search
  - In xinput form heading should be Individual Information
  - Incorrect name MARINE_INFO for tags should be GENERAL_INFO
  - payment should be payments

select_1
  - In xinput -> form id is missing  
  
on_select_1
  - Order Id should not be present in this call.
  - In xinput -> headings, second form heading is missing.
  - ProviderID is not matching with previous calls.


select_2
  - In xinput -> form id is missing 
  - ProviderID is not matching with previous calls.

on_select_2
  - Order Id should not be present in this call.
  - In xinput -> headings, first form heading is missing.
  - ProviderID is not matching with previous calls.

init
  -  Start date is incorrect form range.
  -  ProviderID is not matching with previous calls.

on_init
  -  Order Id should not be present in this call.
  -  End date is incorrect form range.
  - In payments range values are missing for end.
  -  ProviderID is not matching with previous calls.
  - In fulfillments, fulfillmentId is missing


confirm
  - Please remove xinput
  - In payments transactionId is missing
  - Incorrect ProviderId

on_confirm  
  - Incorrect Tag Group POLICY_DOCUMENT in fulfillments.
  - In fulfillments, fulfillmentId is missing
  - Incorrect values for POLICY_DETAILS tag group.
  
  @mohitpalsingh-ID, please fix above issues.

**Comment by anuj-ondc** [comment]
common issues
  - category_ids is missing in items.
  - quotes vales needs to be in enumised format like BASE_PRICE & PROCESSING_FEE.
  - Buyer Finder fee Tag group is missing for payments
  - In items, range values should be in date-time format

on_search
  - Buyer Finder fee Tag group is missing for payments
  - DELAY_INTEREST is missing in settlement_terms
  - invalid value for MANDATORY_ARBITRATION

on_select
  - Price is missing at item level

on_select 2
  - Price is missing at item level
  - Items, CARGO_DETAILS, PACKAGING_DETAILS  are extra tags

init
  - In xinput formId is missing
  
on_init
  - STATIC_TERMS is missing
  - SETTLEMENT_WINDOW has incorrect value
  - COMMODITY_LIST, MODE_OF_CONVEYANCE is extra tag

confirm
  - In tags INVOICE_DATE is missing & incorrect  value for INVOICE_NUMBER
  - Payment tags are missing

on_confirm
  - invalid POLICY_DETAILS tag group values
  - invalid url in documents.
  - In items price should be excluding tax & processing Fee.  
  
  @mohitpalsingh-ID, Please fix above issues.

**Comment by sourabhsaini11** [comment]
@mohitpalsingh-ID, kindly get these issues resolved

Common
- In SETTLEMENT_TERMS OFFLINE_CONTRACT values are missing.

on_search
- In settlement_terms, MANDATORY_ARBITRATION, COURT_JURISDICTION are missing.

on_init
- COMMODITY_LIST is extra tag value.

on_confirm
- In POLICY_DETAILS, COMMODITY_TYPE is missing.
- In payments, transaction_id is missing.
- order Id is missing.
- order status is missing.
- In item, price is not matching with previous calls.
- invalid value for POLICY_START_DATE.

**Comment by sourabhsaini11** [comment]
@mohitpalsingh-ID, please get the below issues fixed

on_search   
- additional tags CLAIM_SETTLEMENT_RATIO, INITIAL_WAITING_PERIOD, BASE_PRICE, CONVIENCE_FEE, PROCESSING_FEE, OFFER_VALIDITY in  POLICY_DETAILS tag-group
- multiple OFFLINE_CONTRACT tags present in SETTLEMENT_TERMS tag-group

on_select_2   
- missing tag INVOICE_NUMBER in POLICY_DETAILS tag-group
- additional tags COVERAGE_FROM, COVERAGE_TO, CARGO_DETAILS, PACKAGING_DETAILS in  POLICY_DETAILS tag-group

init
- start timestamp must be in RFC3339 format at time.range in items

on_init   
- value is missing for dob & address in fulfillments
- start timestamp must be in RFC3339 format at time.range in items
- BUYER_FINDER_FEES tag-group is missing in payments
- OFFLINE_CONTRACT tag is missing in SETTLEMENT_TERMS tag-group
- start timestamp mum mst be in RFC3339 format at time.range in payments

confirm 
- value is missing for dob in fulfillments
- missing tags COMMODITY_TYPE, MODE_OF_CONVEYANCE, BASIS_OF_VALUATION additional in POLICY_DETAILS tag-group
- start timestamp must be in RFC3339 format at time.range in items

on_confirm 
- cancellation_terms is missing
- missing tag-group PERSON_ADDITIONAL_DETAILS in fulfillments
- value is missing for dob in fulfillments
- missing tags COMMODITY_TYPE, MODE_OF_CONVEYANCE, BASIS_OF_VALUATION additional in POLICY_DETAILS tag-group
- additional tag-group GENERAL_INFO in items
- start timestamp must be in RFC3339 format at time.range in items
- transaction_id is missing in params at payments
- BUYER_FINDER_FEES tag-group is missing in payments
- start timestamp must be in RFC3339 format at time.range in payments
- additional tags CLAIM_SETTLEMENT_RATIO, INITIAL_WAITING_PERIOD, BASE_PRICE, CONVIENCE_FEE, PROCESSING_FEE, OFFER_VALIDITY in  POLICY_DETAILS tag-group

on_status_2
- value is missing for address in fulfillments
- start timestamp must be in RFC3339 format at time.range in items

**Comment by sourabhsaini11** [comment]
@mohitpalsingh-ID, please get the below issues fixed
common_issues
- SETTLEMENT_AMOUNT should be calculated, cannot be used as a placeholder
- TAX should be precise to 2 decimal places in quote

on_init
- COMMODITY_TYPE value is not similar to what was sent in previous call

on_status_1
- fulfillments, payments and items.time are missing

**Comment by sourabhsaini11** [comment]
@mohitpalsingh-ID, kindly get the below issues cleared
init
- additional attributes category_ids, descriptor, price, tags present in items(recommended to fix)
- type is missing in payments
- status should be either of NOT-PAID or PAID in payments.

on_init
- milliseconds should be precise upto 3 decimal places only for start & end time.
- status should be either of NOT-PAID or PAID in payments.
- additional attributes time present in payments
- type is missing in payments

confirm
- milliseconds should be precise upto 3 decimal places only for start & end time.
- type is missing in payments
- additional attributes time present in payments

on_confirm
- milliseconds should be precise upto 3 decimal places only for start & end time.
- type is missing in payments
- additional attributes time present in payments

**Comment by sourabhsaini11** [comment]
@mohitpalsingh-ID, kindly get the below issue fixed
common_issues
- person.gender value is incorrect, should be either of male or female.
- price.value(591.00) should be precise to summation of breakup value's (591.18).
- on_status calls which are coming as an unsolicated for any form submission, should be same as the previous call.

on_search
- tag SETTLEMENT_AMOUNT is not part of /on_search call, in payments.

on_select_2
- If submission_id will be sent by seller through unsolicated /on_status_1 call then form.mime_type should be application/html.

init
- SETTLEMENT_TYPE tag is missing in payments.

confirm
- SETTLEMENT_TYPE tag is missing in payments.

on_status_1 
- cancellation_terms, fulfillments, payments should not be part of /on_status call (as these object's were not present in /on_select_2 call)

**Comment by 92shreyansh** [comment]
Transaction logs has been Approved. IGM logs are pending please raise a seprate PR for the same

**Pull request merged**
