### PR TITLE
Vistar RSF 2.0 Logs(updated)

### PR DESCRIPTION
**Pull request by Saifurrahmanemon**

### CODE REVIEW

**Comment by ParneetkaurDev** [comment]
**## Submitted Logs with Flows**

Refer to this [Google Document](https://docs.google.com/document/d/1rHmQ8joTsT2HDmZdXhPlUKy5QSrJiQuEkTAjLDcNVoA/edit) for details.

---

### **Settle**

- `context/bap_uri` is incorrect for all the calls; it does not match your `subscriber_uri`.
- `context/ttl` is missing.
- `message.receiver_app_id` must be the same as `receiver_id`.

---

### **On_settle**

- `settle` and `on_settle` call `message_id` do not match.
- `message.settlement.orders[0].inter_participant.settled_amount` format is incorrect.
- `message.settlement.orders[0].providers.reference_no` is missing.
- `message.settlement.orders[0].providers.status` is missing.

---

### **On_report**

- `message.message_id` does not match the report call.
- `message.settlement.orders[0].inter_participant.settled_amount` format is incorrect.

---

### **Recon**

- `context.transaction_id` is incorrect and does not match the `settle` call.

---

### **On_recon**

- `context.transaction_id` is incorrect and does not match the `settle` call.

**Comment by ParneetkaurDev** [comment]
- **Report**:  
  - `ref_transaction_id` should not match with the `message_id` and `transaction_id` of the report call.  
  - `transaction_id` and `message_id` should not be the same.

**Comment by Saifurrahmanemon** [comment]
> The flows we have mentioned in document are you supporting those?
yes.

**Comment by sandeepshahi** [comment]
Logs approved for RSF v2.0.0

@Saifurrahmanemon

**Pull request merged**
