### PR TITLE
ONDC:FIS13 Tech Logs Submission for Motor Insurance

### PR DESCRIPTION
**Pull request by Nirdosh3312**
Submitting Tech Logs for Motor Insurance of ONDC:FIS13

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please get the below issues fixed
on_search1
- descriptor.name should be 'Vehicle Details' as defined in api contract at xinput

search2
- bpp_id & bpp_uri are missing in context

on_select
- quantity is missing in items.add_ons
- tags 'PROCESSING_FEE' & 'TAX' are not part of 'GENERAL_INFO' tag-group at items

on_select2
- quantity is missing in items.add_ons
- tags 'BASE_PRICE', 'PROCESSING_FEE', 'TAX', 'OFFER_VALIDITY', 'IDV_MIN_VALUE', 'IDV_MAX_VALUE' & 'CONVIENCE_FEE' are not part of 'GENERAL_INFO' tag-group at items

init1
- items.category_ids is missing
- quantity is missing in items.add_ons

on_init1
- quantity is missing in items.add_ons
- tags 'BASE_PRICE', 'PROCESSING_FEE', 'TAX', 'OFFER_VALIDITY', 'IDV_MIN_VALUE', 'IDV_MAX_VALUE' & 'CONVIENCE_FEE' are not part of 'GENERAL_INFO' tag-group at items
- time is additional in payments

init2
- category_ids & fulfillment_ids are missing in items
- quantity is missing in items.add_ons

confirm
- quantity is missing in items.add_ons
- category_ids & fulfillment_ids are missing in items

on_confirm
- person is misssing in fulfillments.customer
- quantity is missing in items.add_ons
- tags 'BASE_PRICE', 'PROCESSING_FEE', 'TAX', 'OFFER_VALIDITY', 'IDV_MIN_VALUE', 'IDV_MAX_VALUE' & 'CONVIENCE_FEE' are not part of 'GENERAL_INFO' tag-group at items
- time is additional in payments

unsolicited_status.json
- file name should be unsolicited_on_status
- quantity is missing in items.add_ons
- tags 'BASE_PRICE', 'PROCESSING_FEE', 'TAX', 'OFFER_VALIDITY', 'IDV_MIN_VALUE', 'IDV_MAX_VALUE' & 'CONVIENCE_FEE' are not part of 'GENERAL_INFO' tag-group at items

**Comment by Nirdosh3312** [comment]
Hii @sourabhsaini11, I have fixed and resubmitted the logs for the issues you have mentioned, Please verify them. Looking forward to your response.

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please get the below issues cleared
select
- category_ids are send additionally

on_init
- tag-group VAHAN_DETAILS is send additionally 

confirm
- transaction_id is missing

on_confirm
- price is send additionally in items.add_ons

Flow-2
unsolicited_on_update_renew_1
- transaction_id shouldn't be part of payments[1].params

unsolicited_on_update_renew_2
- code should be 'GRANTED' at fulfillments[1].state

**Comment by Nirdosh3312** [comment]
Hii @sourabhsaini11, 

I have fixed the issues and resubmitted the logs. Please verify them 

For this Point
> unsolicited_on_update_renew_2
>  * code should be 'GRANTED' at fulfillments[1].state
 
We are changing the 1st indexed fulfillment to CLAIM_PROCESSED, while the 0th element has the state GRANTED. This was cleared by you <a href="https://github.com/ONDC-Official/verification-logs/pull/1529#issuecomment-2121924242">here</a>. 

Looking forward to your response

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please get the below issues fixed
Flow-2
unsolicited_on_update_renew_2
- code should be 'GRANTED

Flow-3
on_status_2
- message_id shouldn't be same as message_id sent in on_status_1

Kindly submit Flow-4(Cancel) as well

**Comment by Nirdosh3312** [comment]
Hii @sourabhsaini11, I have updated the logs and have also submitted the logs for Flow 4 as mentioned. Please review the PR

**Comment by 92shreyansh** [comment]
Approved Pramaan logs

**Pull request merged**
