### PR TITLE
Abhibus verification logs

### PR DESCRIPTION
**Pull request by prithvi-triffy**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@prithvi-triffy, please get the below issues fixed
common_issue
- tag BUYER_FINDER_FEES_TYPE is missing in BUYER_FINDER_FEES tag-group

on_init, on_confirm, on_cancel
- virtual_payment_address is missing in params

receiver_recon
- /message/orderbook/orders/0/state must be equal to one of the allowed values (Completed)
- /message/orderbook/orders/0/provider/name must be object
- /message/orderbook/orders/0/payment/params/amount must be number
- /message/orderbook/orders/0/payment/@ondc1org1return_window must match format \"duration\

on_receiver_recon
- /message/orderbook/orders/2 must have required property 'transaction_id
- /message/orderbook/orders/2 must have required property 'settlement_id'
- /message/orderbook/orders/2 must have required property 'settlement_reference_no"
- /message/orderbook/orders/2 must have required property 'message"

**Comment by prithvi-triffy** [comment]
@sourabhsaini11 The VPA is not required as the settlement won't happen via UPI.

**Comment by sourabhsainii** [comment]
@prithvi-triffy, please get the below issues fixed
/receiver_recon
/message/orderbook/orders/0/state must be equal to one of the allowed values (Completed)
/message/orderbook/orders/0/provider/name must be object
/message/orderbook/orders/0/payment/params/amount must be number
/message/orderbook/orders/0/payment/@ondc1org1return_window must match format \"duration\
orders.receiver_app_uri additional field 

/on_receiver_recon
/message/orderbook/orders/2 must have required property 'transaction_id
/message/orderbook/orders/2 must have required property 'settlement_id'
/message/orderbook/orders/2 must have required property 'settlement_reference_no"
"/message/orderbook/orders/2 must have required property 'settlement_reference_no"/message/orderbook/orders/2 must have required property 'settlement_reference_no"
/message/orderbook/orders/2 must have required property 'message"

**Comment by prithvi-triffy** [comment]
@sourabhsaini11 We updated the logs, please do the needful. 
"/message/orderbook/orders/0/payment/params/amount must be number"

The [Dataset](https://docs.google.com/spreadsheets/d/1_CCvX8eHaiproR9IdXP_0LCmnmoJaU5-/edit?gid=482333148#gid=482333148) mentions the parameter to be a string.

**Comment by sourabhsainii** [comment]
@prithvi-triffy, please segregate the RSF calls on the basis of 'Success' Flow & 'Correction' Flow. For 'amount' keep it as a string only.

**Comment by prithvi-triffy** [comment]
@sourabhsaini11 it is done

**Comment by sourabhsainii** [comment]
@prithvi-triffy, please add on_receiver_recon for correction flow as well.

**Comment by prithvi-triffy** [comment]
on_receiver_recon wont be sent when all the order are settled properly.

**Comment by sourabhsainii** [comment]
@prithvi-triffy, It will be sent with recon-status 1.Please go through the below docs for RSF flows
https://docs.google.com/document/d/1tx86sypacIRXgL9nlNBdvHz7cYQjQoyC/edit#heading=h.5vjft1c1kj0t
Also, I'm attaching shopify logs for ref purpose
https://github.com/ONDC-Official/v1.2.0-logs/tree/master/WITSLAB/shopify/RSF

**Comment by prithvi-triffy** [comment]
@sourabhsaini11 Sending back settled orders is not mandatory as it will increase the size of the payload even after batching. The orders for which on_receiver_recon is not received are deemed as settled. This is is sole reason we have a return _window as well as the [order_recon_status](https://github.com/ONDC-Official/protocol-network-extension/blob/main/specifications/rsp/enums/order_recon_status.json) '03' which is "Deemed Settled".

**Comment by sourabhsainii** [comment]
@prithvi-triffy, please get the below issues fixed
Success Flow
/receiver_recon 
      - wrong timestamp format
      - @ondc/org/collected_by_status - should be relatable value
      - @ondc/org/withholding_amount_status - should be relatable value
      - @ondc/org/return_window_status - should be relatable value
      - @ondc/org/settlement_basis_status - should be relatable value
      - @ondc/org/settlement_window_status - should be relatable value
      - /message/orderbook/orders/1/receiver_app_uri additional field 

/on_receiver_recon
      - order_recon_status different
      - /message/orderbook/orders/0/counterparty_diff_amount/value should be 20
      - /message/orderbook/orders/0/counterparty_diff_amount/value should be 0

Correction Flow
/receiver_recon 
      - /message/orderbook/orders/0/provider/name must be object
      - @ondc/org/collected_by_status - should be relatable value
      - @ondc/org/withholding_amount_status - should be relatable value
      - @ondc/org/return_window_status - should be relatable value
      - @ondc/org/settlement_basis_status - should be relatable value
      - @ondc/org/settlement_window_status - should be relatable value
      - /message/orderbook/orders/0/receiver_app_uri additional field 
      - orders.correction is additional field

**Comment by prithvi-triffy** [comment]
@sourabhsaini11 Changed the timestamp format and removed the receiver_app_uri. But the other fields seem similar to the approved logs for Rapido. I'm talking about the @ondc/org/*status values being relatable. And, in addition to that, the counterparty_diff_amount/value is also correct. The correction object is necessary for the correction flow as mentioned in the documentation for the receiver_recon correction flow.

**Comment by RupalSingla** [comment]
Hi team these are few of the findings :
Success Flow :
Receiver _Recon
- settlement timestamp should be less than created_at and updated_at timestamp. Because settlement will be happening before the receiver recon call
@prithvi-triffy

**Comment by prithvi-triffy** [comment]
We have made the changes, please check now

**Comment by 92shreyansh** [comment]
Transaction & RSF logs are Approved for Buyer App

**Pull request merged**
