### PR TITLE
added the NammaYatri Rsf logs for both success and Correction Flow

### PR DESCRIPTION
**Pull request by ManiTeja-17**

### CODE REVIEW

**Comment by RupalSingla** [comment]
Receiver_recon:

- "@ondc/org/settlement_window": "", "@ondc/org/settlement_window_status": "",  "settlement_reference": "settlement_timestamp": "" these are few of the attributes for which value needs to be provided
- Different transaction _id in both the API's 
- Same values of transcation and message id 
@ManiTeja-17

**Comment by RupalSingla** [comment]
Receiver_recon:

- Format of settlement timestamp , created_at and updated _at is wrong.
- Value of settlement timestamp and created_at is marked same , settlement timestamp should be less than created_at and updated_at 
- Wrong enums used for the attributes params . transaction_status": "SUCCESS " , this needs to be Paid , similarly enum for order.status needs to be Paid not success
@ManiTeja-17

**Comment by Shiva21212121** [comment]
@RupalSingla 
For the comment - Format of settlement timestamp , created_at and updated _at is wrong, can you please share us the sample format for the timestamp which you are expecting here?

**Comment by RupalSingla** [comment]
As per our previous discussion, I trust everything has been addressed comprehensively.

@Shiva21212121

**Comment by ManiTeja-17** [comment]
Yes we made our first call yesterday in prod

**Comment by Shiva21212121** [comment]
> As per our previous discussion, I trust everything has been addressed comprehensively.
> 
> @Shiva21212121

This is clarified that there should only be three digits after the decimal, made this and the other two changes at our end

**Comment by RupalSingla** [comment]
Logs Cleared @Shiva21212121

**Pull request merged**
