### PR TITLE
Appreciate wealth - lump sum, redemption and search pre prod logs

### PR DESCRIPTION
**Pull request by padmakshi-n-appreciate**

### CODE REVIEW

**Comment by anuj-ondc** [comment]
@padmakshi-n-appreciate Please fix below findings:

common issues:
  - Extra data-key `key` is present in context(for on_action calls)
  - Invalid timestamp format, should be in RFC3339 format(for on_action calls)


**flow 1 search_logs:**

search:
- bpp_uri_ & bpp_id should not be the part of context.

**flow 2 redemption:**

select:
- In fulfillments, type of ID should be string

on_select:
- BAP_TERMS should not be present.
- In items, fulfillment_ids is missing.

init:
- fulfillment ID  is different from last on_select call.
- In fulfillments, type of ID should be string.

on_init:
- fulfillment ID  is different from last on_select call.
- BAP_TERMS should not be present.

confirm: 
- BPP_TERMS are missing 

on_init:
- BAP_TERMS should not be present.

on_update: 
- BAP_TERMS should not be present.

**Flow 3 Lumpsum new folio:**
select 1 & 2:
- In fulfillments, type of ID should be string
- Extra key type present.

on_select 1:
- BAP_TERMS should not be present.
- quote is missing

on_select 2:
- BAP_TERMS should not be present.

init:
- collected_by value needs to be BPP.
- xinput object should not be there.
- Extra key documents should not present.
- Extra key type present.

on_init:
- Extra key documents should not present.
- xinput should not present.
- BAP_TERMS should not be present.

confirm:
- Extra key type present.
- Extra key documents should not present.
- Incomplete payments array.
- BPP_TERMS are missing.
- xinput should not present.
- In fulfillments, type of ID should be string.

on_confirm:
- Extra key documents should not present.
- xinput should not present.
- In fulfillmenst extra key tracking is present.

on_status: 
- BAP_TERMS are missing.
- cancellation_terms is missing.

on_update: 
- fulfillment ID  is different from last call.
- cancellation_terms is missing.
- invalid value for CREATED_ON.
- BAP_TERMS are missing.

**Flow 4 Lumpsum existing folio:**

select:
- In fulfillments, type of ID should be string
- Extra key type present.

on_select:
- BAP_TERMS should not be present.

init:
- collected_by value needs to be BPP.
- Extra key documents should not present.
- Extra key type present.

on_init:
- Extra key documents should not present.
- BAP_TERMS should not be present.

confirm:
- Extra key type present.
- Extra key documents should not present.
- Incomplete payments array.
- BPP_TERMS are missing.
- In fulfillments, type of ID should be string.

on_confirm:
- Extra key documents should not present.
- In fulfillments extra key tracking is present. 

on_status: 
- BAP_TERMS are missing.
- cancellation_terms is missing.

on_update: 
- cancellation_terms is missing.
- invalid value for CREATED_ON.
- BAP_TERMS are missing. 



select & on_select calls are missing for xinput flow, for submissionID.

**Comment by padmakshi-n-appreciate** [comment]
@anuj-ondc 
The changes mentioned in the comments for all the actions calls are done and updated in the MR. 
All the changes mentioned for on_actions will be done by seller side. We have updated the response we are getting on these actions.
Requesting you to have a look at these.

**Comment by anuj-ondc** [comment]
@padmakshi-n,  Logs submitted for second iteration are from staging env. Please submit the logs from pre-prod environment.

**Comment by padmakshi-n-appreciate** [comment]
@anuj-ondc resubmitted the logs from pre prod. Please have a look

**Comment by anuj-ondc** [comment]
@padmakshi-n-appreciate, please fix below findings

common_issues:
  - created_at & updated_at is missing. All calls from on_init should include this.(for on_action calls)
  - In context, timestamp format is incorrect, should be in UTC.

**flow 2 redemption**:  
 
 on_select:
- In items, fulfillment_ids is missing.
   init:
- In fulfillments, type of ID should be string.
- In items, fulfillment_ids type should be string. 

on_init:
  - PAYOUT_BANK_ACCOUNT tag is missing.

confirm:
- In fulfillments, type of ID should be string. 
- In items, fulfillment_ids type should be string.

**Flow 3 Lumpsum new folio**:

on_select_1:
- quote is missing

select_2:
- message_id should be unqiue, but same as previous select call.

on_select_2:
-  message_id should be unqiue, but same as previous on_select call.

init:
- In items, fulfillment_ids type should be string.

confirm:
- In fulfillments, type of ID should be string.    

**Flow 4: lumpsum_existing folio**

on_select:
- In FOLIO_INFORMATION, incorrect value of CREATED_ON.
- Missing select & on_select call for form submission  

init: 
- In fulfillments, type of ID should be string.

on_init:
- In FOLIO_INFORMATION, incorrect value of CREATED_ON.

confirm:
- In fulfillments, type of ID should be string.

on_confirm:
- In FOLIO_INFORMATION, incorrect value of CREATED_ON.

on_update:
- Fulfillment_id is not matching with previous calls.

on_status:
- Fulfillment type is incorrect.

**Comment by padmakshi-n-appreciate** [comment]
@anuj-ondc  changes are done as below:

common_issues:

- [ ] created_at & updated_at is missing. All calls from on_init should include this.(for on_action calls)
- [ ] In context, timestamp format is incorrect, should be in UTC.


flow 2 redemption:

on_select:
- [ ] In items, fulfillment_ids is missing. 
Init:
- [x] In items, fulfillment_ids type should be string. -- fixed
- [x] In fulfillments, type of ID should be string. —> Already a string

on_init:
- [ ] PAYOUT_BANK_ACCOUNT tag is missing.

confirm:
- [x] In items, fulfillment_ids type should be string. -- fixed
- [x] In fulfillments, type of ID should be string. -- fixed


Flow 3 Lumpsum new folio:

on_select_1:
- [ ] quote is missing

select_2:
- [x] message_id should be unqiue, but same as previous select call. --> fixed

on_select_2:
- [ ] message_id should be unqiue, but same as previous on_select call.

init:
- [x] In items, fulfillment_ids type should be string. --> fixed

confirm:
- [x] In fulfillments, type of ID should be string. --> fixed

Flow 4: lumpsum_existing folio

on_select:
- [ ] In FOLIO_INFORMATION, incorrect value of CREATED_ON.
- [ ] Missing select & on_select call for form submission 

init:
- [x] In fulfillments, type of ID should be string. --> fixed

on_init:
- [ ] In FOLIO_INFORMATION, incorrect value of CREATED_ON.

confirm:
- [x] In fulfillments, type of ID should be string. --> fixed

on_confirm:
- [ ] In FOLIO_INFORMATION, incorrect value of CREATED_ON.

on_update:
- [ ] Fulfillment_id is not matching with previous calls.

on_status:
- [ ] Fulfillment type is incorrect.


All the changes mentioned for on_actions will be done by seller side. We have updated the response we are getting on these actions.

**Comment by anuj-ondc** [comment]
@padmakshi-n, Please fix below issues:
common_issues:
- created_at & updated_at is missing. All calls from on_init should include this.(for on_action calls)
- In context, timestamp format is incorrect, should be in UTC.

***LUMPSUMP NEW FOLIO***:

common issues:
- code value for OFFLINE_CONTRACT is incorrect.

on_select 1:
- quote is missing.

on_init: 

-In payments, type should be PRE_FULFILLMENT.

confirm:
- static_terms value is not matching with previous call's static terms(on_init)

LUMPSUMP EXISTING FOLIO:

on_select:
- remove xinput for existing folio.
- In FOLIO_INFORMATION, incorrect value of CREATED_ON.

on_init:
- In FOLIO_INFORMATION, incorrect value of CREATED_ON.

on_confirm:
- In FOLIO_INFORMATION, incorrect value of CREATED_ON.

on_update:
- Fulfillment_id is not matching with previous calls.

on_status:
- Fulfillment type is incorrect.


***REDEMPTION***:

on_select:
- In items, fulfillment_ids is missing.

on_init:
- PAYOUT_BANK_ACCOUNT tag is missing.

confirm:
- extra key `type` is present.

**Comment by padmakshi-n-appreciate** [comment]
@anuj-ondc 

**Fixed issues:**

common_issues:
In context, timestamp format is incorrect, should be in UTC. -- Its already in UTC for action calls
 

LUMPSUMP NEW FOLIO:
common issues:
code value for OFFLINE_CONTRACT is incorrect. -- We cross verified the format for this from swagger for action calls and looks correct.

confirm:
static_terms value is not matching with previous call's static terms(on_init)

REDEMPTION:
extra key type is present. 

All the changes mentioned for on_actions will be done by seller side. We have updated the response we are getting on these actions.

**Comment by anuj-ondc** [comment]
@padmakshi-n-appreciate, if you are not proceeding with SIP, then Please provide other remaining flows for incremental pull, lumpsum payment retry & redemption failure.

**Comment by padmakshi-n-appreciate** [comment]
@anuj-ondc 
Added remaining logs for incremental pull, lumpsum payment retry and redemption failure.

**Comment by padmakshi-n-appreciate** [comment]
@anuj-ondc updated the logs with recent change logs

**Comment by padmakshi-n-appreciate** [comment]
@anuj-ondc updated payment id in lumpsum flows

**Comment by 92shreyansh** [comment]
Transactional Logs are Approved

**Comment by 92shreyansh** [comment]
Can you please move the logs inside the FIS14 directory instead of the logs directory

**Comment by padmakshi-n-appreciate** [comment]
@92shreyansh 
logs are moved to FIS14 directory

**Pull request merged**
