### PR TITLE
Health Insurance Tech Logs Submission for Verification 

### PR DESCRIPTION
**Pull request by Nirdosh3312**
Tech Logs Submissions for Health Insurance ONDC:FIS13

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kindly get the below issues resolved
common_issues:
- In general info tags, ROOM_CATEGORY is missing.
- Item price is not matching with BASE_PRICE in quote.
- Price for add_ons are missing.
- In quote, breakup for add_ons is missing.

init
- person.name is missing in fulfillments
- payments.type value must be in a generic enum format i.e. ON-ORDER

on_init
- person.name is missing in fulfillments
- payments.type value must be in a generic enum format i.e. ON-ORDER

confirm
- id is missing in fulfillments
- person.name is missing in fulfillments
- payments.type value must be in a generic enum format i.e. ON-ORDER
- quote is missing at message.order.

on_confirm
- person.name is missing in fulfillments
- payments.type value must be in a generic enum format i.e. ON-ORDER

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11, I have updated the logs with the reference to the issues that you have mentioned. Kindly review the logs and the PR

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kindly get the below issues fixed
on_search_1
- heading should be 'Insured Personal Details' at items.

on_search_2
- tags BASE_PRICE, CONVIENCE_FEE, PROCESSING_FEE, TAX & OFFER_VALIDITY in GENERAL_INFO tag-group should only be present for items which are referring parent_item_id.

on_init
- time is additional in payments.

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11, We have updated the logs with references to the issues that you have mentioned. Please review the updated logs and the PR

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kindly get the below issues fixed
on_search
- tag 'OFFLINE_CONTRACT' is missing in payments.

on_init
- cancellation_terms are missing
- SETTLEMENT_AMOUNT value should be equal to amount of buyer_finder_fee_percent

on_confirm
- cancellation_terms are missing
- SETTLEMENT_AMOUNT value should be equal to amount of buyer_finder_fee_percent

on_update
- fulfillment_ids should also contain reference to the second fulfillment index.
- cancellation_terms are missing
- SETTLEMENT_AMOUNT value should be equal to amount of buyer_finder_fee_percent

on_status
- cancellation_terms are missing
- fulfillment_ids should also contain reference to the second fulfillment index.
- SETTLEMENT_AMOUNT value should be equal to amount of buyer_finder_fee_percent
- code should change to 'CLAIM_PROCESSED' at fulfillments in on_status(2).

**Comment by Nirdosh3312** [comment]
Sure, @sourabhsaini11. Can you please help me with this question 

> code should change to 'CLAIM_PROCESSED' at fulfillments in on_status(2).

Is this for the 0th indexed fulfillment that is having state as GRANTED which needs to be changed to CLAIM_PROCESSED as well, because we are changing the 1st indexed fulfillment to CLAIM_PROCESSED? Please let us know about this

**Comment by sourabhsaini11** [comment]
@Nirdosh3312,it is fine if you are changing the status to 'CLAIM_PROCESSED' at 1st fulfillment index. Consider the above issue as a False Positive in that scenario.

**Comment by KapilKharera** [comment]
Hi @sourabhsaini11 , We have updated the logs with references to the issues that you have mentioned. Please review the updated logs and the PR

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kindly get the below issues fixed
common_issues
- params.amount should be 1100 at payments

on_select
- additional tags BASE_PRICE, CONVIENCE_FEE, PROCESSING_FEE, TAX & OFFER_VALIDITY in GENERAL_INFO tag-group
- tag PROPOSAL_ID is missing in GENERAL_INFO tag-group

init_1
- provider is missing

on_init_1
- additional tags BASE_PRICE, CONVIENCE_FEE, PROCESSING_FEE, TAX & OFFER_VALIDITY in GENERAL_INFO tag-group
- tag PROPOSAL_ID is missing in GENERAL_INFO tag-group

on_init_2
- additional tags BASE_PRICE, CONVIENCE_FEE, PROCESSING_FEE, TAX & OFFER_VALIDITY in GENERAL_INFO tag-group
- tag PROPOSAL_ID is missing in GENERAL_INFO tag-group

confirm
- PERSON_ADDITIONAL_DETAILS tag-group is not part of /confirm call

on_confirm
- additional tags BASE_PRICE, CONVIENCE_FEE, PROCESSING_FEE, TAX & OFFER_VALIDITY in GENERAL_INFO tag-group
- tag PROPOSAL_ID is missing in GENERAL_INFO tag-group

on_update
- additional tags BASE_PRICE, CONVIENCE_FEE, PROCESSING_FEE, TAX & OFFER_VALIDITY in GENERAL_INFO tag-group
- tag PROPOSAL_ID is missing in GENERAL_INFO tag-group

on_status
- xinput is not required in items (flow-2 on_status 1 & 2 only)
- additional tags BASE_PRICE, CONVIENCE_FEE, PROCESSING_FEE, TAX & OFFER_VALIDITY in GENERAL_INFO tag-group
- tag PROPOSAL_ID is missing in GENERAL_INFO tag-group

**Comment by Nirdosh3312** [comment]
Hii @sourabhsaini11, We have updated the logs and have fixed the issues that you have mentioned. Kindly review the logs. Looking forward to your response. 

Regards

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please fix the below issues
select
- fulfillments is additional

on_confirm
- transaction_id is missing in payments.params

**Comment by Nirdosh3312** [comment]
Hii @sourabhsaini11, We have fixed both the mentioned issues and resubmitted the logs. Please verify them. 

Looking forward to your response. Regards

**Comment by 92shreyansh** [comment]
Approved Pramaan Logs

**Pull request merged**
