### PR TITLE
Paytm Metro Verification logs

### PR DESCRIPTION
**Pull request by gagan200591**

### CODE REVIEW

**Comment by RupalSingla** [comment]
@gagan200591  here are few of the findings for the logs that u had submitted.

search (fare):
- Tags inside payment are empty .

search(station)
- list inside tags is empty

on_search(fare):

- provider.time is empty.
- payment.type is having wrong enum

init:

- transaction id mismatch with search and on_search Api
- params are  empty 
- Tags inside payment are empty .


on_init

- payments tags are missing
- breakup/item object, id && price object missing , quote/id is extra

confirm:

- transaction_id missmatch with Search /on_search API
- payment.tags are empty
-

on_confirm:
stops
  start
- id missing
- authorization/status missing
- gps missing

end
- gps missing
- id missing
- parent_stop_id missing
- instructions object missing

- payment tags are missing
- order/updatedat && created_at missing

**Comment by 92shreyansh** [comment]
The ask with payment tags is independent of the payment, mainly the ask is with the settlement terms and static payment deatisl independent to the actual payment.
Transaction Id is decoupled but if the session is the same which can always be a possiblity can we not have the same transaction id?
We can ignore the the transaction_id check here as you are explicitly caching.

**Comment by keshav4kumar** [comment]
Added new logs for preprod env. Getting NACK status in confirm api when we are adding tags under payment.

**Comment by keshav4kumar** [comment]
After fixing the amount datatype ( by Prithvi ), submitted the logs again. Now all the logs are coming properly. Also resolved the concerns mentioned previously.

**Comment by sourabhsaini11** [comment]
@keshav4kumar, kindly get these below issues fixed as well

common_issues
- transaction_id should be same throughout the calls

on_search
- parent_stop_id is missing for stop type 'INTERMEDIATE_STOP'

init
- name should be valid instead of 'N/A' in billing
- provider.id should be same as sent in on_search call
- params object must be valid

on_init
- name should be valid instead of 'N/A' in billing
- provider.id should be same as sent in init call
- params object must be valid

confirm
- name should be valid instead of 'N/A' in billing
- provider.id should be same as sent in on_init call
- incorrect attribute 'value' in params, should be 'amount' instead

on_confirm
- name should be valid instead of 'N/A' in billing
- millisecond should be precise upto 3 digit at order.created_at & order.updated_at
- bank_code, bank_account_number & virtual_payment_address are missing in params 

on_status
- name should be valid instead of 'N/A' in billing
- millisecond should be precise upto 3 digit at order.created_at & order.updated_at
- bank_code, bank_account_number & virtual_payment_address are missing in params

**Comment by praneeth-naganathahalli** [comment]
@sourabhsaini11 transaction_id need not be the same across all API calls. This has been discussed with @92shreyansh in community discussions.

**Comment by 92shreyansh** [comment]
the transaction_id can differ across api only when considering search, select & init as the transaction session can start from eaither of the 3 stage.

But once a transaction/session journewy is initated with a specific transaction journey all following calls if part of the same transaction/session should remain the same including post order apis

**Comment by keshav4kumar** [comment]
added new logs for the above comments.

**Comment by sourabhsaini11** [comment]
@gagan200591 @keshav4kumar kindly look into the below issues

common_issues
- bap_id must be the domain part of your bap_uri

init
- email must be valid at billing
- SETTLEMENT_DETAILS tag group is missing at payments

confirm
- email must be valid at billing

**Comment by keshav4kumar** [comment]
what is the expected value for SETTLEMENT_DETAILS @sourabhsaini11 cc @92shreyansh

**Comment by sourabhsaini11** [comment]
@keshav4kumar  SETTLEMENT_DETAILS tag group will consist of a list item SETTLEMENT_TYPE, you can check one of the seller logs that you have submitted for ref.

**Comment by keshav4kumar** [comment]
added new logs after fixing above comments. please check.

**Comment by sourabhsaini11** [comment]
Hii @keshav4kumar, please get these below issues fixed

on_search (station)
- start & end should not be empty at time.range 

on_search (fare)
- start & end should not be empty at time.range 
- count is missing at quantity.maximum

**Comment by praneeth-naganathahalli** [comment]
@sourabhsaini11 We have discussed this with Rishabh in the ONDC community call. These have to be fixed on the Seller side & we don't see any other fixes needed from the Buyer app in the comments. 

@92shreyansh Are we good to close the Pre Prod Logs then?

**Comment by praneeth-naganathahalli** [comment]
@92shreyansh As discussed, @keshav4kumar from our Tech Team has added the Logs for search (stations), on_search (stations), search (fare) & on_search (fare). 

Can we close the Logs verification for Paytm now?

**Comment by 92shreyansh** [comment]
@praneeth-naganathahalli Please provide dates for IGM and RSF dates by when you would be submitting the logs.

All Transaction Tech logs are fine

**Comment by praneeth-naganathahalli** [comment]
@92shreyansh Expected Go Live Date for Metro is 2nd Feb 2024. 

PFB the dates for IGM & RSP from our end considering the above Go Live date. 

IGM - 19th March 2024
RSP - 3rd April 2024

**Comment by 92shreyansh** [comment]
Transaction logs are Approved with exception based on dates for IGM and RSF as mentioned

**Pull request merged**
