### PR TITLE
Easy Pay FIS Flow 1

### PR DESCRIPTION
**Pull request by ep-aws**
ONDC FIS SEARCH.json added

### CODE REVIEW

**Comment by ep-aws** [comment]
ONDC FIS SEARCH.json added

**Comment by RupalSingla** [comment]
Common issue

- Timstamp trail needs to correct format , request cannot be greater than responce , all the api's needs to have a well defined timestamp 
- value inside code needs to be in a well defined manner 
- value inside the title needs to be in defined manner

search :

- additonal settlement  are present

on_search: 

- timestamp for on_search cannot be less than search 
- catagory.descriptor.code is in wrong format .
- buyer finder fee cannot be null
- Buyer finder fee percent need to have a defind value.

on_select1 :
timestamp for on_select cannot be less than select  
no such enum valued CONSENT_CREATED is defined , value needs to got changed in form_responce .status

select2 :

- form.id is misssing


on_select2:

- item.descriptor.code is in wrong format
- quote object , all title are in wrong format. all the quote.breackup.title needs to be in well defined format
- quote object , all the breackup.price.value cannot be NA.

select3:
- form.id is missing

on_select3:

- timestamp for on_select cannot be less than select  
- item.descriptor.code is in wrong format.
- value inside breakup.title needs to be in correct format
- quote object , all the breackup.price.value cannot be NA.

on_init1

- value inside breakup.title needs to be in correct format
- descriptor.code is in wrong format 
- state , descriptor.name is null
- cancellation terms needs to be redefined , no NA values arec accepted

on_init2:

- descriptor.code is in wrong format 
- state , descriptor.name is null
- value inside breakup.title needs to be in correct format
- label needs to be enums.
- cancellation terms needs to be redefined , no NA values arec accepted

on_init3:

- why payment.type": "POST_FULFILLMENT in the payload.
- state , descriptor.name is null
- value inside breakup.title needs to be in correct format
- label needs to be enums.
- cancellation terms needs to be redefined , no NA values arec accepted


confirm:
- quote.breakup.title needs to be in correct format

on_confirm:
- Xinput cannot be null

on_status KYC_Unsolicted :
- Form.Id ids missing

**Comment by ep-aws** [comment]
@RupalSingla  I have resolved the issues you mentioned. Kindly review the pull request and approve it.

**Comment by anuj-ondc** [comment]
**Common issue**:
  1) In context city code should be * in each call not  "std:*"

**search**
  1) No need of bpp_uri & bpp_id in search's payload, please remove.

**on_init 1**
  1) Cancellation fee should be 0 not empty(Applicable to all next payloads).

**on_init 3**
  1) In Payments, create enum for labels like Installment 1=INSTALLMENT(Applicable to all next payloads)
  
  @ep-aws, kindly resolve above issues as well.

**Comment by anuj-ondc** [comment]
@ep-aws Please submit all the flows.

**Comment by sourabhsaini11** [comment]
Hii @ep-aws, kindly resolve the below issues

flow 3
update
- update_target is missing

on_update (unsolicated)
- payment status should be DEFERRED for objects whose status were NOT-PAID before foreclose

flow 4
- PRE_PART_PAYMENT update & on_update calls are missing

flow 5
update
- update_target is missing

on_update
- payment object with DELAYED status is missing
- range is missing for payment object of MISSED_EMI_PAYMENT

on_update(unsolicated) call is missing

**Comment by ep-aws** [comment]
@sourabhsaini11 : I have updated the logs as you suggested.

Note: Lender does not support flow 4.

**Comment by ep-aws** [comment]
@sourabhsaini11  : I have updated the logs as you suggested.

flow 3
update

update_target is missing - Solved

on_update (unsolicated)

payment status should be DEFERRED for objects whose status were NOT-PAID before foreclose - Exception Provided, we will incorporate this change by January 30th, 2024.

flow 4

PRE_PART_PAYMENT update & on_update calls are missing -Lender is not Supported PRE_PART_PAYMENT.
flow 5
update

update_target is missing -Solved
on_update

payment object with DELAYED status is missing - Exception Provided, we will incorporate this change by January 30th, 2024.
range is missing for payment object of MISSED_EMI_PAYMENT -Solved

**Comment by sourabhsaini11** [comment]
@ep-aws, below are the issues related to IGM logs

issue
- description.images must be string
- updated_by must have required property person
- org.name should be NP's subscriber_id::domain
- context timestamp should be greater than or equal to updated_at in issue

on_issue
- org.name should be NP's subscriber_id::domain
- context timestamp should be greater than or equal to updated_at in issue

on_issue_status
- message_id should be the same as sent in issue_status call
- action_triggered must be equal to one of the allowed values (REFUND,REPLACEMENT,RETURN,CANCEL,NO-ACTION)
- created_at should match issue's created_at
- gro_type value should be TRANSACTION-COUNTERPARTY-NP-GRO

issue_close
- updated_by must have required property 'person'
- context timestamp should be greater than or equal to updated_at in issue
- org.name should be bap_id::domain

**Comment by ep-aws** [comment]
@sourabhsaini11  We have resolved the issues you mentioned. Kindly review the pull request.

**Comment by 92shreyansh** [comment]
Logs Approved under exceptions to fix the few findings by January 30th, 2024.

**Pull request merged**
