### PR TITLE
Logs for stagingondc.kynhost.com subsriber ID for ONDC:FIS12 domain.

### PR DESCRIPTION
**Pull request by amit2311**
Please verify and merge, if any comments please adds in this PR.

Thanks

### CODE REVIEW

**Comment by amit2311** [comment]
Hi @sourabhsaini11 ,
Flow-1
**On_search**

1. message.catalog.providers[0].tags[0].list[4].descriptor.code >> GRO_DESIGNATION, GRO_ADDRESS are additional.

**Comment**: These extra parameters are coming from pramaan only, should I remove them?

**Search**

1. Additional signature keys are added but not defined in the contract.
Comment: These are coming as part of pramaan logs only which we downloaded through pramaan app.
3. An empty search call is logged.
Comment: I am not finding the empty search (Can u please explain these?)

I have some queries related to your comments, can we please connect and resolve these?

Thanks

**Comment by amit2311** [comment]
Flow 4, Flow3 , Flow2
**on_update**

1. message.order.cancellation_terms.fulfillment state “Disbursed” is missing in the payload.
**Comment**: This is what we are getting from pramman side.
2. message.order.cancellation_terms.fulfillment state.descriptor.code “Loan_Cancellation” is missing in the payload.
**Comment**: This is what we are getting from pramman side.

**on_update** unsolicitated
message.order.items.tags.descriptor_code.CONSENT_INFO and CONSENT_HANDLER is not required in the payload as per the contract.
**Comment**:  Resolved

**Comment by amit2311** [comment]
**Flow-2** Pre part payment
**on_status**

"/message/order/payments/2/status must be equal to one of the allowed values (PAID,NOT-PAID)"
**Comment:** Resolved

**Comment by amit2311** [comment]
**Flow-3 MISSED_EMI_PAYMENT**

On_update_unsolicited is missing in the payload.
**Comment**: Resolved

**on_select_1**:

"/message/order/items/0/xinput/form_response/submission_id must match format "uuid""
**Comment**: Resolved

"select_2":

"Timestamp for /select api should be greater than timestamp of /on_search API"
**Comment**: Resolved

"select_3":

"Timestamp for /select api should be greater than timestamp of /on_search api",
"/message/order/items/xinput/form_response/status in item[0] should be 'SUCCESS'"
**Comment**: Resolved

"init_1":

"form.id: aa5afe02-0a94-45f5-bb6e-f563a0ccea39 mismatches with form.id sent in past call"
**Comment**: Resolved

on_update:

"/message/order/payments/3/status must be equal to one of the allowed values (PAID,NOT-PAID)"
: I verified with different pre-prod logs of FIBE (Buyer app) I saw instead of paid and not paid we have delayed also.
Please check and let me know.

**Comment by sourabhsaini11** [comment]
@amit2311, please fix below issues as well
init_2 & 3
- tags DELAY_INTEREST & SETTLEMENT_TYPE are missing in SETTLEMENT_TERMS tag-group

confirm
- tags DELAY_INTEREST & SETTLEMENT_TYPE are missing in SETTLEMENT_TERMS tag-group


FLow-3
select_3
- Timestamp for /select api should be greater than timestamp of /on_search api
- items/xinput/form_response/status in item[0] should be 'SUCCESS''

init_1
- form.id: 68a92f55-6cdf-4b24-9e45-6fd0e25edb7c mismatches with form.id sent in past call

IGM
issue, issue(close)
- issue_actions/complainant_actions/0/updated_by/contact must have required property 'email'

**Comment by amit2311** [comment]
**common_issues**
1. **init_2 & 3**

tags DELAY_INTEREST & SETTLEMENT_TYPE are missing in SETTLEMENT_TERMS tag-group

2. **confirm**

tags DELAY_INTEREST & SETTLEMENT_TYPE are missing in SETTLEMENT_TERMS tag-group

**Flow-3**

1. **select_3**

Timestamp for /select api should be greater than timestamp of /on_search api
items/xinput/form_response/status in item[0] should be 'SUCCESS''

2. **init_1**

form.id: 68a92f55-6cdf-4b24-9e45-6fd0e25edb7c mismatches with form.id sent in past call

**IGM**
1. **issue, issue(close)**

issue_actions/complainant_actions/0/updated_by/contact must have required property 'email'
**Comment** :  Resoved

**Comment by sourabhsaini11** [comment]
@amit2311, get this issues fixed as well
Flow-3
select_3
- items/xinput/form_response/status in item[0] should be 'SUCCESS' in an enum format

**Comment by amit2311** [comment]
Hi @sourabhsaini11 ,
Please check now.
Thanks.

**Comment by sourabhsaini11** [comment]
@amit2311, please get the below issues fixed
common_issue
- params is missing in payments

Flow-3
select_3
- form.id mismatches with the form.id sent in past call(i.e. on_select_2)

**Comment by amit2311** [comment]
Hi @sourabhsaini11 ,
Flow-3
select_3

1. form.id mismatches with the form.id sent in past call(i.e. on_select_2)
**Comment**: Resolved

common_issue

2. params is missing in payments
I have already added params like SETTLEMENT_TYPE, DELAY_INTEREST in payments.

**Comment by amit2311** [comment]
Hi @sourabhsaini11 ,
As discussed can u please check now.
1. params is missing in payments
**Comment :** Resolved

**Comment by 92shreyansh** [comment]
Transaction & IGM logs Approved for BAP

**Pull request merged**
