### PR TITLE
TRV11: NammaYatri IGM Logs

### PR DESCRIPTION
**Pull request by vsaimanohar**

### CODE REVIEW

**Comment by RupalSingla** [comment]
Issue _close call is missing in the payload @vsaimanohar

**Comment by vsaimanohar** [comment]
> Issue _close call is missing in the payload @vsaimanohar

@RupalSingla added issue _close payload, you can check on-demand payloads here:- https://github.com/ONDC-Official/verification-logs/pull/1522

**Comment by RupalSingla** [comment]
on_issue_status:
resolution_action needs to have  Resolved action in the payload

issue _close :
issue c;lose cannot be have action- close  if the resolution is not resolved 

@vsaimanohar

**Comment by vsaimanohar** [comment]
> on_issue_status:
> resolution_action needs to have  Resolved action in the payload
> 
> issue _close :
> issue c;lose cannot be have action- close  if the resolution is not resolved 
> 
> @vsaimanohar 
> 
> 

@RupalSingla the on_issue_status payload is from DMRC they are not sending us a resolved status as of now.

**Comment by vsaimanohar** [comment]
> > on_issue_status:
> > resolution_action needs to have  Resolved action in the payload
> > issue _close :
> > issue c;lose cannot be have action- close  if the resolution is not resolved
> > @vsaimanohar
> 
> @RupalSingla the on_issue_status payload is from DMRC they are not sending us a resolved status as of now.

checked this with @Nirdosh3312 , on_issue_status will be sending resolution field only if they resolve igm_issue from their Dashboard

**Comment by amitsinha07** [comment]
## Common Issues
- **bpp_id** is incorrect
- **issue_id** should be the same in all API calls
- **transaction_id** should be the same in all API calls

### issue_close
- **created_at** is not matching with the issue's **created_at**

### on_issue_status
- **created_at** is not matching with the issue's **created_at**
- **respondent_actions[0].updated_at** is not matching with the on_issue's **respondent_actions[0] updated_at**

@vsaimanohar

**Comment by vsaimanohar** [comment]
> ## Common Issues
> 
>     * **bpp_id** is incorrect
> 
>     * **issue_id** should be the same in all API calls
> 
>     * **transaction_id** should be the same in all API calls
> 
> 
> ### issue_close
> 
>     * **created_at** is not matching with the issue's **created_at**
> 
> 
> ### on_issue_status
> 
>     * **created_at** is not matching with the issue's **created_at**
> 
>     * **respondent_actions[0].updated_at** is not matching with the on_issue's **respondent_actions[0] updated_at**
> 
> 
> @vsaimanohar

hey @amitsinha07 fixed mentioned issues, pls review

**Comment by RupalSingla** [comment]
Log cleared for version 1.0.0 @vsaimanohar

**Pull request merged**
