### PR TITLE
Added logs for preprod env

### PR DESCRIPTION
**Pull request by g-arpit**

### CODE REVIEW

**Comment by g-arpit** [comment]
Reply for some of the comments above:

* `Based on selected ticket count, fulfillment array must consist of 4 indexes each representing an individual ticket`
We had clarified this with `intracity` team, this is not mandatory to follow. We can send one fulfillment object for any number of tickets.
* `soft_cancel api-pair calls are missing`
We do not need this functionality. We only need confirm_cancel.
* `tag-group ROUTE_INFO is incomplete`
What is missing? Can you elaborate.
* `cancellation_terms is missing`
We don't need this.
* `SETTLEMENT_TERMS tag-group is incomplete`
I have added SETTLEMENT_DETAILS tag-group. I think only one of them is enough.
* `billing is missing`
We have clarified this with `intracity` team, this is optional.
* `tag-group TICKET_INFO is missing`
I think this is also not mandatory.
* `bank_account_number & bank_code are missing in params`
If we are using vpa then account no and code is not mandatory.
* `OFFER & TOLL are missing in breakup`
What if we don't have any OFFER or TOLL?
* `tag BUYER_FINDER_FEES_TYPE is missing in BUYER_FINDER_FEES tag-group`
I think this is also optional.
* `stops.code must be in an enum format`
How can this be an enum? `stops.code` must be unique in order to uniquely identify a stop.
* `gps should be precise upto 6 decimal places only`
Is this mandatory? What if we are storing them with less than 6 decimal places in our system?
* `code should be one of SJT, SFSJT, RJT, PASS at items.descriptor`
Again, this has to be unique to identify the product type. How can we restrict these to be an enum?


I'll be addressing rest of the comments.

**Comment by 92shreyansh** [comment]
@sourabhsaini11 Please update the comments

**Comment by sourabhsaini11** [comment]
@g-arpit, please fix the below issues
common_issues
- tag BUYER_FINDER_FEES_TYPE is missing in BUYER_FINDER_FEES tag-group
- breakup.title should be BASE_FARE instead of 'Base Fare' at quote
- OFFER & TOLL are missing in quote.breakup
- code should be one of SJT, SFSJT, RJT, PASS only at items.descriptor
- gps should be precise upto 6 decimal places only.
- ROUTE_DIRECTION is missing in ROUTE_INFO tag-group
- soft_cancel api pair calls are missing

search
- instead of SETTLEMENT_DETAILS tag-group name should be SETTLEMENT_TERMS.Also, tag SETTLEMENT_WINDOW is not part of /search call
-  bpp_id & bpp_uri are missing(/search_2 only)

on_search_1
- bpp_id & bpp_uri are missing
- payments array should be inside providers
- items is not part of /on_search_1 call
- type should be 'ROUTE' instead of 'TRIP' for  /on_search_1 call
- instead of SETTLEMENT_DETAILS tag-group name should be SETTLEMENT_TERMS

on_search_2
- payments array should be inside providers

init
- instead of SETTLEMENT_DETAILS tag-group name should be SETTLEMENT_TERMS.Also, tags SETTLEMENT_AMOUNT & STATIC_TERMS should also be present in it.

on_init
- cancellation_terms
- ROUTE_DRECTION is missing in ROUTE_INFO tag-group
- instead of SETTLEMENT_DETAILS tag-group name should be SETTLEMENT_TERMS.Also, tags MANDATORY_ARBITRATION, COURT_JURISDICTION, SETTLEMENT_AMOUNT & STATIC_TERMS should also be present in it.

confirm
- id should be created on /confirm call
- transaction_id should not be null in payments.params
- instead of SETTLEMENT_DETAILS tag-group name should be SETTLEMENT_TERMS.Also, tags SETTLEMENT_AMOUNT & STATIC_TERMS should also be present in it.

on_confirm
- created_at & updated_at are missing
- status is missing in stops.authorization
- tag-group TICKET_INFO is missing
- type is missing in fulfillments
- instead of SETTLEMENT_DETAILS tag-group name should be SETTLEMENT_TERMS.Also, tags MANDATORY_ARBITRATION, COURT_JURISDICTION, SETTLEMENT_AMOUNT & STATIC_TERMS should also be present in it.

on_cancel
- type is missing in fulfillments
- instead of SETTLEMENT_DETAILS tag-group name should be SETTLEMENT_TERMS.Also, tags MANDATORY_ARBITRATION, COURT_JURISDICTION, SETTLEMENT_AMOUNT & STATIC_TERMS should also be present in it.

Flow-3
Please submit correction-flow as well

**Comment by sourabhsaini11** [comment]
**Based on selected ticket count, fulfillment array must consist of 4 indexes each representing an individual ticket
We had clarified this with intracity team, this is not mandatory to follow. We can send one fulfillment object for any number of tickets.**
- All the participants were requested to develop 2.0.1 but in case you have already developed for 2.0.0 then that is fine.However in the next version, you will need to send multiple fulfillments.

**soft_cancel api-pair calls are missing
We do not need this functionality. We only need confirm_cancel.**
- You might not need it in your buyer app but this is but this is a more of an implementtion for other buyer app as well & this needs to be supported by all the participants.

**gps should be precise upto 6 decimal places only
Is this mandatory? What if we are storing them with less than 6 decimal places in our system?**
- Similarly to above, You might not need it in your app but this needs to be supported by all the participants.

**cancellation_terms is missing
We don't need this.**
- cancellation_terms are mandatory for all the participants to have.

**SETTLEMENT_TERMS tag-group is incomplete
I have added SETTLEMENT_DETAILS tag-group. I think only one of them is enough.**
- All the tags as defined in the Api-contract under SETTLEMENT_DETAILS are required.

**tag-group TICKET_INFO is missing
I think this is also not mandatory.**
- No, TICKET_INFO tag-group is required post order creation.

**OFFER & TOLL are missing in breakup
What if we don't have any OFFER or TOLL?**
- If there's no TOLL & OFFER charges then send 0 as value.

**tag BUYER_FINDER_FEES_TYPE is missing in BUYER_FINDER_FEES tag-group
I think this is also optional.**
- no, BUYER_FINDER_FEES_TYPE tag is mandatory.

**code should be one of SJT, SFSJT, RJT, PASS at items.descriptor
Again, this has to be unique to identify the product type. How can we restrict these to be an enum?**
- As per ONDC model implementation model you need to use these codes as defined by ONDC

**Comment by g-arpit** [comment]
@sourabhsaini11 What are correction-flows you mentioned above?

**Comment by sourabhsainii** [comment]
@g-arpit, you can refer here for correction-flow
https://docs.google.com/document/d/1ubUPAWpbbUJ4vG2h5TQ74srZBjYjrO0P/edit

**Comment by g-arpit** [comment]
@sourabhsaini11 Can you review the logs again. I have addressed the comments.

**Comment by sourabhsainii** [comment]
@g-arpit, below are the Issues related to transactional calls only. Kindly get these fixed
common_issues
- init onwards transaction_id should remain same for each api call
- cancel(soft) api pair calls is missing in Flow-2 

search
- tag SETTLEMENT_BASIS at SETTLEMENT_TERMS tag-group should be sent by the seller App (search_1 only)
- timestamp should be greater than the timestamp of /on_search_1 call (search_2 only)
- tag STATIC_TERMS is missing in SETTLEMENT_TERMS tag-group

on_search
- transaction_id & message_id should be same as /search api's transaction_id & message_id
- remove empty items array (on_search_1 only)
- collected_by is missing in payments
- tags MANDATORY_ARBITRATION, COURT_JURISDICTION, STATIC_TERMS are missing in SETTLEMENT_TERMS tag-group
- time is misisng in items

select
- timestamp should be greater than the timestamp of /on_search_2 call

on_select
- timestamp should be greater than the timestamp of /select call
- time is misisng in items

init
- tags MANDATORY_ARBITRATION, COURT_JURISDICTION, STATIC_TERMS are missing in SETTLEMENT_TERMS tag-group

on_init
- id should not be created on /on_init call
- tags MANDATORY_ARBITRATION, COURT_JURISDICTION, STATIC_TERMS are missing in SETTLEMENT_TERMS tag-group
- timestamp should be greater than the timestamp of /init call
- time is misisng in items

confirm
- id should not be present on /confirm call
- tags MANDATORY_ARBITRATION, COURT_JURISDICTION, STATIC_TERMS are missing in SETTLEMENT_TERMS tag-group

on_confirm
- cancellation_terms are missing
- token validity should be greater than the current timestamp, at token.authorization
- TICKET_INFO tag-group is missing
- tags MANDATORY_ARBITRATION, COURT_JURISDICTION, STATIC_TERMS are missing in SETTLEMENT_TERMS tag-group
- timestamp should be greater than the timestamp of /confirm call
- time is misisng in items

on_cancel
- cancellation_terms are missing
- tags MANDATORY_ARBITRATION, COURT_JURISDICTION, STATIC_TERMS are missing in SETTLEMENT_TERMS tag-group
- time is misisng in items

**Comment by g-arpit** [comment]
@sourabhsainii Hi, regarding TICKET_INFO and SOFT_CANCEL, we have already discussed this with @92shreyansh that we can opt out of this for now. Shreyansh has also commented above confirming the same.
I have addressed rest of the comments. Please review them.

**Comment by sourabhsaini11** [comment]
@g-arpit, please get the below issues cleared
Chalo
- id is missing in payments

on_cancel
- tag-group name should be SETTLEMENT_TERMS instead of SETTLEMENT_DETAILS

**Comment by g-arpit** [comment]
@sourabhsainii Addressed it. It was a copy-paste error.

**Comment by g-arpit** [comment]
@sourabhsaini11 All good now?

**Comment by sourabhsaini11** [comment]
@g-arpit, please fix the below one

**Comment by g-arpit** [comment]
@sourabhsainii Addressed.

**Comment by 92shreyansh** [comment]
Transaction log Approved. Please update the PR and create new PR for RSF & IGM

**Comment by g-arpit** [comment]
@92shreyansh This PR already had RSF logs. As for IGM, I think we had a discussion with you guys that IGM will be an offline process for now.

**Comment by 92shreyansh** [comment]
@g-arpit The request is to have this PR only Transaction logs so can merge that. 

For RSF Please create a new PR, so can merge the transaction logs

**Comment by g-arpit** [comment]
@92shreyansh Removed RSF logs from this PR.

**Comment by g-arpit** [comment]
@92shreyansh Raised a new PR for RSF logs [here](https://github.com/ONDC-Official/verification-logs/pull/1603).
One question, Since they were reviewed together, why didn't we merge them together with transaction logs in this PR?

**Pull request merged**
