### PR TITLE
log submission tc

### PR DESCRIPTION
**Pull request by nemishzalavadiya**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@nemishzalavadiya, kindly change every submitted flow file into a flow folder where each action/on_action calls will be further segregated onto different files.

**Comment by nemishzalavadiya** [comment]
@sourabhsaini11 this is how we receive it from pramaan. Any reason for converting it manually to some another format?

**Comment by nemishzalavadiya** [comment]
> @sourabhsaini11 this is how we receive it from pramaan. Any reason for converting it manually to some another format?

@yoge

**Comment by nemishzalavadiya** [comment]
@sourabhsaini11 please check now

**Pull request closed without merging**
