### PR TITLE
adding new file

### PR DESCRIPTION
**Pull request by prajyotjambekar**

### CODE REVIEW

**Comment by prajyotjambekar** [comment]
adding new file

**Review by prajyotjambekar — COMMENTED** [review]
[on_select2.json](https://github.com/user-attachments/files/16976134/on_select2.json)
[on_status.json](https://github.com/user-attachments/files/16976136/on_status.json)
[Uploading on_status2.json…]()

**Comment by prajyotjambekar** [comment]
[on_select2.json](https://github.com/user-attachments/files/16976142/on_select2.json)
[on_status.json](https://github.com/user-attachments/files/16976143/on_status.json)
[on_status2.json](https://github.com/user-attachments/files/16976144/on_status2.json)
[search.json](https://github.com/user-attachments/files/16976146/search.json)
[select.json](https://github.com/user-attachments/files/16976147/select.json)
[select2.json](https://github.com/user-attachments/files/16976148/select2.json)
[confirm.json](https://github.com/user-attachments/files/16976149/confirm.json)
[init.json](https://github.com/user-attachments/files/16976150/init.json)
[on_confirm.json](https://github.com/user-attachments/files/16976151/on_confirm.json)
[on_init.json](https://github.com/user-attachments/files/16976152/on_init.json)
[on_search.json](https://github.com/user-attachments/files/16976153/on_search.json)
[on_select.json](https://github.com/user-attachments/files/16976154/on_select.json)

**Comment by 92shreyansh** [comment]
@prajyotjambekar Please submit logs in priscribed format

**Pull request closed without merging**
