### PR TITLE
Invoicepe Preprod Logs (Invoice Based Loans)

### PR DESCRIPTION
**Pull request by Avijeet-Blocsol**
Looking forward to your feedback

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Avijeet-Blocsol, you have multiple open [PR (161)](https://github.com/ONDC-Official/verification-logs/pull/1613/), [PR(1562](https://github.com/ONDC-Official/verification-logs/pull/1562/files) present for Invoice-loan. Either get those PR's closed or continue using the old threads only.

**Comment by Avijeet-Blocsol** [comment]
Hello Team,

We have closed PR161. PR1562 is with regards to our "reference seller application". The current PR is for our buyer application for Invoice Based Loans. Please review the PR and help us close the issue as soon as possible.

Regards












---- On Wed, 25 Sep 2024 13:18:57 +0530 sourabhsaini11 ***@***.***> wrote ---





https://github.com/Avijeet-Blocsol, you have multiple open https://github.com/ONDC-Official/verification-logs/pull/1613/, https://github.com/ONDC-Official/verification-logs/pull/1562/files present for Invoice-loan. Either get those PR's closed or continue using the old threads only.

**Comment by Avijeet-Blocsol** [comment]
Hello Team,

I hope you are doing well. I wanted an update on our log submission for our buyer application for FS12: Invoice Based Loans.

Looking forward to hear from you soon.

Regards,












---- On Thu, 26 Sep 2024 10:40:08 +0530 Avijeet ***@***.***> wrote ---



Hello Team,

We have closed PR161. PR1562 is with regards to our "reference seller application". The current PR is for our buyer application for Invoice Based Loans. Please review the PR and help us close the issue as soon as possible.

Regards












---- On Wed, 25 Sep 2024 13:18:57 +0530 sourabhsaini11 ***@***.***> wrote ---













https://github.com/Avijeet-Blocsol, you have multiple open https://github.com/ONDC-Official/verification-logs/pull/1613/, https://github.com/ONDC-Official/verification-logs/pull/1562/files present for Invoice-loan. Either get those PR's closed or continue using the old threads only.

**Comment by Avijeet-Blocsol** [comment]
Hello Team,

We have updated the flow 1 logs. A few observations:

1. tags.descriptor.interest rate conversion charges value should be "NA".

In case the value of the charges are zero, why is there is requirement for NA. Buyer applications parsing numerical values from the string will face unnecessary errors.

2. fulfillment.state should be "SANCTIONED" in on_confirm:

Pramaan provides the ability to mark the loan as sanctioned separately which is the reason it is not SANCTIONED in on_confirm but in the corresponding on_status.

For Flow 2 and Flow 3, the pointed conflicts are with the Pramaan tool. Let us know in case it is a blocker. We will get in touch with the team to get this resolved at the earliest.

**Comment by sourabhsaini11** [comment]
@Avijeet-Blocsol, please get below issues fixed
search_1
- tags COURT_JURISDICTION, MANDATORY_ARBITRATION, SETTLEMENT_TYPE, DELAY_INTEREST, SETTLEMENT_BASIS, SETTLEMENT_WINDOW should be sent by the BPP first instead of BAP

confirm
- tag MANDATORY_ARBITRATION is missing in SETTLEMENT_TERMS tag-group

**Comment by Avijeet-Blocsol** [comment]
Updated the LOGS as per the comments. Please verify and merge the logs

**Comment by JyotiSharma0711** [comment]
### Flow 1

- **search_1**: 
  - `message.intent.payment.tags[1].list[0].descriptor.code.DELAY_INTEREST` is missing in the payload.

- **on_search_3**: 
  - `message.catalog.providers[0].items[2].tags[0].list[23].descriptor.code.KFS_LINK` and `INSURANCE_CHARGES` are missing in the payload.

- **on_select_1, on_select_2**: 
  - `message.catalog.providers[0].items[1].tags[0].list[5].value` should be `NA` as per the contract.
  - `message.order.items[0].tags[0].list[15].descriptor.code.KFS_LINK` is missing in the payload.

- **init_1**: 
  - `message.order.payments[0].tags[1].list.descriptor.code` includes unnecessary entries: `MANDATORY_ARBITRATION`, `SETTLEMENT_BASIS`, `SETTLEMENT_WINDOW`, and `COURT_JURISDICTION`.

- **init_2**: 
  - `message.order.payments[0].params` is not required in the payload.
  - `message.order.payments[0].tags[0].descriptor.PAYMENT_COLLECTOR` is missing in the payload.
  - `message.order.payments[0].tags[1].list.descriptor.code` includes unnecessary entries: `MANDATORY_ARBITRATION`, `SETTLEMENT_BASIS`, `SETTLEMENT_WINDOW`, and `COURT_JURISDICTION`.

- **init_3, init_4**: 
  - `message.order.payments[0].tags[1].list.descriptor.code` includes unnecessary entries: `MANDATORY_ARBITRATION`, `SETTLEMENT_BASIS`, `SETTLEMENT_WINDOW`, and `COURT_JURISDICTION`.

- **on_confirm**: 
  - `message.catalog.providers[0].items[1].tags[0].list[5].value` should be `NA` as per the contract.

### Flow 2

- **readme**: 
  - README is included; please remove it.

- **on_update**: 
  - `message.order.items[0].tags[0].list[15].descriptor.code.KFS_LINK` is missing in the payload.

**Comment by Avijeet-Blocsol** [comment]
@92shreyansh @JyotiSharma0711 

The observations you have provided contradict some of the previous observations that we have been provided in this log verification process. 

Flow 1

    Current: search_1:
        message.intent.payment.tags[1].list[0].descriptor.code.DELAY_INTEREST is missing in the payload.
        
    Previously: tags COURT_JURISDICTION, MANDATORY_ARBITRATION, SETTLEMENT_TYPE, DELAY_INTEREST, SETTLEMENT_BASIS, SETTLEMENT_WINDOW should be sent by the BPP first instead of BAP
    
    Comment: If the tag has to be first sent by the BPP, it is obvious that the delay interest would be missing in our payload. Your current comment is in direct contradiction to your previous comment

    on_search_3:
        message.catalog.providers[0].items[2].tags[0].list[23].descriptor.code.KFS_LINK and INSURANCE_CHARGES are missing in the payload.
        
    Comment: Callback calls are not in the control of the BAP

    on_select_1, on_select_2:
        message.catalog.providers[0].items[1].tags[0].list[5].value should be NA as per the contract.
        message.order.items[0].tags[0].list[15].descriptor.code.KFS_LINK is missing in the payload.
        
    Comment: Callback calls are not in the control of the BAP
    
    on_confirm:
        message.catalog.providers[0].items[1].tags[0].list[5].value should be NA as per the contract.
    Comment: In case the value of the charges are zero, why is there is requirement for NA. Buyer applications parsing numerical values from the string will face unnecessary errors. Also , callback calls are not in the control of the BAP

Flow 2

    on_update:
        message.order.items[0].tags[0].list[15].descriptor.code.KFS_LINK is missing in the payload.

   Comment:  Callback calls are not in the control of the BAP


We have been trying to get these logs verified for over a month but still there are contradictions in the observations made by the QA team. Please clarify the issue so that we can get the logs verified and pushed at the earliest.

Regards,
Avijeet Singh

**Comment by Avijeet-Blocsol** [comment]
We have updated the flow 1 logs as per the new changes and observations provided. Looking forward to a resolution to the challenges and merge of the logs with the repo

**Comment by sourabhsaini11** [comment]
@Avijeet-Blocsol, please fix below issues 
search
- tag DELAY_INTEREST is missing in tag-group SETTLEMENT_TERMS

init_2
- tag-group PAYMENT_COLLECTOR is not-required

IGM
issue
- /message/issue must have required property 'description'

issue(close)
- /message/issue must have required property 'rating'

**Comment by amitsinha07** [comment]
@Avijeet-Blocsol 

## Issue
### Context

- **Expected_Resolution_Time**: Should be P1D according to the contract.
- **Source/Network-ID_Participants_ID**: Incorrect; it should be `bap_id`.
- **Issue_Actions/Complaint_Actions/0/Updated_By/Org/Name**: Should include `bap_id`.
- **Status**: "Close" is incorrect.
- **Complaint_Actions/0/Complaint_Actions**: Should be "OPEN".

---

## Issue_CLOSE
- No "issue close" call exists.
- Issue (1) call is a duplicate of issue (2) call.

---

## On_Issue
### Context
- **Timestamp**: Should be greater than or equal to the `context/timestamp` of the issue.

### Message
- **ID Mismatch**: Between `/issue` and `/on_issue`.
- **Created_At**: Should match the issue's `created_at`.

---

## Issue_Status
### Context
- **Core_Version**: The context must include the required `core_version` property.
- **TTL**: Should be `PT30S` as per the API contract.

### Message
- **Issue_ID**: Does not match the `issue_id` in the issue call.

---

### Message
- **Created_At**: Should match the issue's `created_at`.

**Comment by Avijeet-Blocsol** [comment]
Hello @amitsinha07 

Regarding the raised issues, please help us with the following items:

1. core_version: Can you point me to the offical docs where this key is included in the context object? We have a version key which are using at the moment. 

2. on_issue: Since we are a BAP and on_issue calls are sent by BPP, we do not have any control over this call.

Looking forward to your clarification on the mentioned points.

Regards

**Comment by amitsinha07** [comment]
@Avijeet-Blocsol 

You can skip core_verison issue
And just correct only action calls like issue, issue_close and issue status

**Comment by Avijeet-Blocsol** [comment]
We have updated the IGM Logs according to the feedback. Looking forward to a quick closure of this pull request

**Comment by amitsinha07** [comment]
@Avijeet-Blocsol 
## Feedbacks for IGM

### **Issue**
- `TTL`: Should be `PT30S` as per the API contract.

### **Issue_CLOSE**
- `message/issue/issue_actions/complainant_actions/0/complainant_action/open`: Should be present as per the API contract.
- `message/issue/rating`: Must be equal to one of the allowed values:
  - `THUMBS-UP`
  - `THUMBS-DOWN`
- `TTL`: Should be `PT30S` as per the API contract.

**Comment by amitsinha07** [comment]
@Avijeet-Blocsol 

## Issue
- issue/type should be "ISSUE" not "GRIEVANCE"

## Issue_CLOSE
**Validation**:
  - created_at in the issue_close call is mismatched with created_at in the issue call.

**Comment by Avijeet-Blocsol** [comment]
We have updated the IGM Logs as per recommendation. Looking forward to closure

**Comment by Avijeet-Blocsol** [comment]
@amitsinha07  Any updates on the Logs submitted?

**Comment by amitsinha07** [comment]
@Avijeet-Blocsol 
Logs are approved for IGM 1.0.0

**Comment by anuj-ondc** [comment]
@Avijeet-Blocsol, Since you have another active [PR](https://github.com/ONDC-Official/verification-logs/pull/1832) whose transactional logs are already approved, Could you please remove the transactional logs from here or you can update this [PR](https://github.com/ONDC-Official/verification-logs/pull/1832) with IGM logs.

**Comment by Avijeet-Blocsol** [comment]
@anuj-ondc The PR you mentioned is for our reference seller app logs. This PR is for our buyer application. We have already submitted the IGM Logs. Please merge the logs so that we can then go ahead and subscribe to the production registry

**Comment by anuj-ondc** [comment]
@Avijeet-Blocsol, Understood. The confusion is in your 1802 PR, where both the buyer and seller are from InvoicePe.
@sourabhsaini11 Please check.

**Pull request merged**
