### PR TITLE
RSF Logs

### PR DESCRIPTION
**Pull request by Ashwini1797**

### CODE REVIEW

**Comment by Ashwini1797** [comment]
@92shreyansh 
Please review the logs and let us know if there is anything we need to change
Additionally, could you add the respective label to the logs..

**Comment by RupalSingla** [comment]
"receiver_recon": {
                "schemaErr0": "/message/orderbook/orders must NOT have fewer than 5 items",
                "schemaErr1": "/message/orderbook/orders/0 must have required property 'invoice_no'",
                "schemaErr2": "/message/orderbook/orders/0 must have required property 'order_recon_status'",
                "schemaErr3": "/message/orderbook/orders/0/state must be equal to one of the allowed values (Completed)",
                "schemaErr4": "/message/orderbook/orders/0/payment/uri must match format \"uri\"",
                "schemaErr5": "/message/orderbook/orders/0/payment/params/amount must be number",
                "schemaErr6": "/message/orderbook/orders/0/payment/@ondc1org1buyer_app_finder_fee_type must be equal to one of the allowed values (percent,amount)",
                "schemaErr7": "/message/orderbook/orders/0/payment/@ondc1org1buyer_app_finder_fee_amount must be number",
                "schemaErr8": "/message/orderbook/orders/0/payment/@ondc1org1buyer_app_finder_fee_amount must be number",
                "schemaErr9": "/message/orderbook/orders/0/payment/@ondc1org1settlement_details/0/settlement_type must be equal to one of the allowed values (upi,neft,rtgs)",
                "schemaErr10": "/message/orderbook/orders/0/payment/@ondc1org1settlement_details/0/settlement_ifsc_code must match pattern \"^[A-Z]{4}0[A-Z0-9]{6}$\"",
                "schemaErr11": "/message/orderbook/orders/0/withholding_tax_gst/value must be number",
                "schemaErr12": "/message/orderbook/orders/0/withholding_tax_tds/value must be number",
                "schemaErr13": "/message/orderbook/orders/0/deduction_by_collector/value must be number",
                "respTime": "context timestamp should be greater than updated_at"
            },
            "on_receiver_recon": {
                "schemaErr0": "/message/orderbook/orders must NOT have fewer than 5 items",
                "schemaErr1": "/message/orderbook/orders/0 must have required property 'settlement_id'",
                "schemaErr2": "/message/orderbook/orders/0/order_recon_status must be equal to one of the allowed values (02)",
                "schemaErr3": "/message/orderbook/orders/0/counterparty_diff_amount/value must be number",
                "schemaErr4": "/message/orderbook/orders/0/counterparty_diff_amount must be null"
            }
        },

@Ashwini1797

**Comment by Ashwini1797** [comment]
@RupalSingla , invoice_no is optional, and the rest of the parameters are in string format according to the documentation. 
However, do I still need to change them to numbers?
@92shreyansh , could you please confirm this for the following parameters?
 params are 
 1. /payment/params/amount
 2. /payment/@ondc1org1buyer_app_finder_fee_amount
 3. /withholding_tax_gst/value
 4. /withholding_tax_tds/value
 5. /deduction_by_collector/value
 
Please review the logs and let us know if there is anything we need to change.

**Comment by RupalSingla** [comment]
Log cleared for version 1.0.0 @Ashwini1797

**Pull request merged**
