### PR TITLE
FIS13 health logs for verification by Cateina

### PR DESCRIPTION
**Pull request by nukeu666**
FIS13 BAP health logs for verification by Cateina

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@nukeu666, kindly get the below issues fixed
search_1
- OFFLINE_CONTRACT is missing in SETTLEMENT_TERMS tag-group

search_2
- BAP_OFFLINE_CONTRACT is not part of SETTLEMENT_TERMS tag-group
- status should be SUCCESS at items.form

on_search_2
- value for tag COVERAGE_AMOUNT should be of type string

select
- fulfillments are not part of /select call

on_select
- value for tag COVERAGE_AMOUNT should be of type string

on_init
- value for tag COVERAGE_AMOUNT should be of type string
- tags MANDATORY_ARBITRATION & COURT_JURISDICTION are missing in SETTLEMENT_TERMS tag-group

on_confirm
- value for tag COVERAGE_AMOUNT should be of type string
- transaction_id is missing in payments.params

**Comment by nukeu666** [comment]
We have fixed following points you provided in comments for our BAP
    search_1
        OFFLINE_CONTRACT is missing in SETTLEMENT_TERMS tag-group
    search_2
        BAP_OFFLINE_CONTRACT is not part of SETTLEMENT_TERMS tag-group

Other points can not be fixed as it comes as a /on_X response from the ONDC mockseller, details given below:

1. status should be SUCCESS at items.form
ONDC mockseller gives us the below response on form submission, therefore we must also respond with status=Successful
The mockseller response must be updated to give the correct {"status":"SUCCESS"} as you require
{
    "status": "Successful",
    "submission_id": "95f9a254-8b61-409d-89a4-393278db131b"
} 

2. value for tag COVERAGE_AMOUNT should be of type string in on_search/on_select/on_init/on_confirm
The ONDC mockseller is sending us an invalid NUMBER type rather than the expected STRING type
This needs to be corrected by ONDC as the buyer is not allowed to change any data sent to it
I have already highlighted the issue with mohit monga but have not received a response

3. tags MANDATORY_ARBITRATION & COURT_JURISDICTION are missing in SETTLEMENT_TERMS tag-group
As above, these values must be provided by the ONDC mockseller
We are doing the verification for BAP and cannot edit data sent by BPP

4. transaction_id is missing in payments.params in on_confirm
As above, these values must be provided by the ONDC mockseller
We are doing the verification for BAP and cannot edit data sent by BPP

**Comment by sourabhsaini11** [comment]
@nukeu666, kindly get the below issue fixed as well
init_1
- form.id should match with the form id sent in /on_select call

Also, please provide rest of the flows as well.

**Comment by nukeu666** [comment]
Hi,
I have added an additional commit at /logs/cateina-bpp for verification of BPP logs on staging environment hosted by Cateina
The BAP logs remain on /logs/cateina
Thanks

**Comment by nukeu666** [comment]
> @nukeu666, kindly get the below issue fixed as well init_1
> 
>     * form.id should match with the form id sent in /on_select call
> 
> 
> Also, please provide rest of the flows as well.

Hi, Above init_1 has been fixed
What do you mean by the other flows?
We have integrated for health fulfilment flows

**Comment by sourabhsaini11** [comment]
@nukeu666 other flows includes CLAIM & RENEW, you can check these flows on developer contract under **Flow Set** Dropdown.

**Comment by nukeu666** [comment]
> @nukeu666 other flows includes CLAIM & RENEW, you can check these flows on developer contract under **Flow Set** Dropdown.
Hi,
The claim and renew triggers are not done on protocol
The customer is redirected to the insurer's site for any claim and renewal to be done via a link on the BAP UI
The BPP may then send unsolicited on_status updates to the BAP

**Comment by nukeu666** [comment]
> > @nukeu666 other flows includes CLAIM & RENEW, you can check these flows on developer contract under **Flow Set** Dropdown.
> 
> Hi, The claim and renew triggers are not done on protocol The customer is redirected to the insurer's site for any claim and renewal to be done via a link on the BAP UI as you can see as step 2 on each of the flows The BPP may then send unsolicited updates to the BAP

Do you need any further info?
Claims/renewal are not on protocol

**Comment by 92shreyansh** [comment]
> > > @nukeu666 other flows includes CLAIM & RENEW, you can check these flows on developer contract under **Flow Set** Dropdown.
> > 
> > 
> > Hi, The claim and renew triggers are not done on protocol The customer is redirected to the insurer's site for any claim and renewal to be done via a link on the BAP UI as you can see as step 2 on each of the flows The BPP may then send unsolicited updates to the BAP
> 
> Do you need any further info? Claims/renewal are not on protocol

Please refer the flow-ui for these flows in the devloper-guide

**Comment by 92shreyansh** [comment]
Log submissions for Tech Validations needs to submit logs for transaction performed in pre-prod
@sourabhsaini11 Please validate the subsciber_id in the logs should be from pre-prod.

**Comment by nukeu666** [comment]
> > > > @nukeu666 other flows includes CLAIM & RENEW, you can check these flows on developer contract under **Flow Set** Dropdown.
> > > 
> > > 
> > > Hi, The claim and renew triggers are not done on protocol The customer is redirected to the insurer's site for any claim and renewal to be done via a link on the BAP UI as you can see as step 2 on each of the flows The BPP may then send unsolicited updates to the BAP
> > 
> > 
> > Do you need any further info? Claims/renewal are not on protocol
> 
> Please refer the flow-ui for these flows in the devloper-guide

I have seen them and need clarity on the BAP involvement in the flows?
Which BAP logs are required for them?
On flow-ui page:
The claims flow has /on_update originating from BPP, there is no action from BAP
The renewal flow is the same, /on_update originates from BPP, there is no action from BAP

**Comment by nukeu666** [comment]
@sourabhsaini11 Please detail what you need for renew and claim flows?
This is BPP functionality and should be sent by your ondc mock seller if you want those logs
Can we have call regarding this since it has been stuck for 2 weeks

**Comment by nukeu666** [comment]
@sourabhsaini11 @92shreyansh 
I've added cancel.json for the cancel flow which originates from BAP
Please detail which logs do you require for renew/claim from BAP since it is not a BAP functionality

**Comment by sourabhsainii** [comment]
@nukeu666, BAP can initiate the CLAIM & RENEW flows by filling the redirect form that he will be receiving from the seller through /on_confirm.

**Comment by nukeu666** [comment]
> @nukeu666, BAP can initiate the CLAIM & RENEW flows by filling the redirect form that he will be receiving from the seller through /on_confirm.

Please check the claims on flow-ui, step 2 which says:
_1) Buyer app will be redirected to a new page using the link provided in the previous step.
"This will redirected to different html page"_

Step 1(on_confirm): BPP sends redirection link for claims
Step 2(not an ondc call): The customer clicks on the link and BAP is redirected to abcinsurance.com
Step 3+(on_update/on_status): All remaining steps on the flow-ui are generated by the BPP
There are no buyer logs generated here

Please send me a meeting request on the health advanced implementation whatsapp group to close it out ASAP
It has been pending for over 2 weeks now!

**Comment by nukeu666** [comment]
Hi, seller side renew states and claim states added

**Comment by sourabhsainii** [comment]
@nukeu666, please get the below issues fixed
init
- id & type is missing in fulfillments (init_2 only)
- SETTLEMENT_AMOUNT value should be 1 percent of quote.price

confirm
- person & type is missing in fulfillments

on_update
- code must be in an enum format at add_ons.descriptor
- If 1 add_on was selected on /select, then 1 add_on should be present at items for rest of the calls also
- additional tags BASE_PRICE, CONVIENCE_FEE, PROCESSING_FEE, TAX, OFFER_VALIDITY & ROOM_CATEGORY present at GENERAL_INFO tag-group
- SETTLEMENT_AMOUNT value should be 1 percent of quote.price
- parent_item_id attribute is not required
- the 2nd payment index capturing form renewal is missing in payments array(renewal on_update calls only)
- code should be GRANTED at fulfillments[1] (renew-granted api only)
- tag-group 'INFO' is not required at fulfillments[1] (renew-granted api only)

Note- Kindly seggregate the api calls on the basis of flows as defined in api-contract.

**Comment by sourabhsaini11** [comment]
@nukeu666, please get the below issues fixed
init_2
- id & type are missing in fulfillments
- SETTLEMENT_AMOUNT value should be 1 percent of quote.price i.e. 190.4

confirm
- person & type are missing in fulfillments
- SETTLEMENT_AMOUNT value should be 1 percent of quote.price i.e. 190.4

CLAIM flow
unsolicated /on_status is missing for claim flow

on_update
- id should not be null at fulfillments
- params.amount at payments should be 1100 as defined at quote.price
- SETTLEMENT_AMOUNT value should be 1 percent of quote.price

RENEW flow
unsolicated /on_status should be sent instead of /on_update_2(message_id: 5dec7215-4a88-4e73-8084-17861930121a)

on_update
- id should not be null at fulfillments
- params.amount at payments should be 1100 as defined at quote.price
- SETTLEMENT_AMOUNT value should be 1 percent of quote.price

CANCEL flow
- on_action calls are missing

Note- Please seggregate the api calls on the basis of flows as defined in api-contract.Also, raise a seprate PR for cateina-bpp logs.

**Comment by nukeu666** [comment]
Hi,
All flows uploaded. Pramaan shows 100% for all the flows

**Comment by sourabhsaini11** [comment]
Hi, 
We require 4 flows to be submitted which are namely Health, Renew, Claim & Cancel & each flow should contain only the required action-on_action api's based upon requirement of that particular flow.You can refer to Log-submission ui on the api-contract for more info.Furthermore, here's a ref. to logs submitted by [pramaan](https://github.com/ONDC-Official/verification-logs/tree/main/FIS13/Pramaan/Marine%20Insurance) for a different use-case.

**Comment by nukeu666** [comment]
4 flows uploaded as requested

**Comment by sourabhsaini11** [comment]
@nukeu666, kindly fix the below issues 
init_2
- type is missing in fulfillments

confirm
- type is missing in fulfillments

flow-4
- on_update call is missing

on_cancel
- status should be CANCELLATION_INITIATED instead of CANCELLED

flow- 2 & 3
- flows are incomplete (post /on_confirm calls are missing)

**Comment by nukeu666** [comment]
logs updated with pramaan

**Comment by sourabhsaini11** [comment]
@nukeu666, please get the below issues fixed
common_issues
- tags MANDATORY_ARBITRATION & COURT_JURISDICTION are missing in SETTLEMENT_TERMS tag-group
- timestamp for /action & /on_action calls shouldn't be same

**Comment by nukeu666** [comment]
logs updated, added those 2 tags in init&confirm

**Comment by nukeu666** [comment]
not required anymore

**Pull request closed without merging**
