### PR TITLE
Jtechnoparks pre prod logs for review

### PR DESCRIPTION
**Pull request by sudhakara11**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@sudhakara11, please get the below issues fixed
confirm
- Timestamp for /confirm api should be greater than timestamp of /on_init api

Flow-3
- on_update(MISSED_EMI_PAYMENT) call is missing

Flow-4
- update(pre_part_payment) & unsolicited_on_update(pre_part_payment) calls are missing

Foreclosure & IGM flows are missing

**Comment by sudhakara11** [comment]
Dear @sourabhsaini11 

Have fixed the confirm,flow3 and flow4 issues.

[](https://github.com/ONDC-Official/verification-logs/pull/1644)

confirm

Timestamp for /confirm api should be greater than timestamp of /on_init api  - **Fixed** 

Flow-3

on_update(MISSED_EMI_PAYMENT) call is missing - **Flow 3 is force closure - Have added missed files** 

Flow-4

update(pre_part_payment) & unsolicited_on_update(pre_part_payment) calls are missing  - **Flow 4 - Have added the missed files**

Foreclosure & IGM flows are missing - **Force closure files have been added & IGM will be submitted next week.**



Thanks,

**Comment by sudhakara11** [comment]
Dear @sourabhsaini11,

As requested closed the new PR and added flow3 and flow4 fixes files in the #1633 PR.

Kindly review and confirm.

Regards,
Sudhakar G

**Comment by sourabhsaini11** [comment]
@sudhakara11, kindly get the below issues fixed
Flow-3
- payload is exchanged between files on_update_unsolicited_monitoring_consent & on_update_forceclosure

flow-4
- payload is exchanged between files on_update_unsolicited_monitoring_consent & on_update_pre_part_payment

flow-5
- on_update_request_missed_emi_payment doesn't contain missed_emi object
- update(missed_emi) & on_update_unsolicated(missed_emi) are missing

**Comment by sudhakara11** [comment]
Dear @sourabhsaini11 

Have fixed flow3,flow4 and flow5 issues have been fixed

https://github.com/ONDC-Official/verification-logs/pull/1633

Flow-3 - Fixed

payload is exchanged between files on_update_unsolicited_monitoring_consent & on_update_forceclosure
flow-4 - Fixed

payload is exchanged between files on_update_unsolicited_monitoring_consent & on_update_pre_part_payment
flow-5 - Fixed
on_update_request_missed_emi_payment doesn't contain missed_emi object
update(missed_emi) & on_update_unsolicated(missed_emi) are missing

Regards,
Sudhakar G

**Comment by sourabhsaini11** [comment]
@sudhakara11, kindly get the below issue fixed
FLow-5
on_update_unsolicited_mark_missed_emi
- installment object with label MISSED_EMI_PAYMENT is missing in payments

**Comment by sudhakara11** [comment]
@sourabhsaini11 

Flow5 missed emi payment issue fixed, kindly verify and confirm.

Regards,
Sudhakar G

**Comment by 92shreyansh** [comment]
Transaction Logs for BAP is Approved

**Pull request merged**
