### PR TITLE
Logs for Kochi Metro

### PR DESCRIPTION
**Pull request by Lancy-Joy-Lobo**
added cancellation logs to the existing directory

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Lancy-Joy-Lobo, please submit in a standard format of flow 1 & flow 2.

**Comment by 92shreyansh** [comment]
@Lancy-Joy-Lobo Please update the flow 2 with existing directory to update cancellation flow not required to update it per metro. The requirement here is to update as the previous logs didnt support cancellation as this has user cancellation so would have this up to date.

Logs need not be submitted for future metro's unless there are specific requirements

**Comment by Lancy-Joy-Lobo** [comment]
@92shreyansh Updated the logs in the existing directory. Kindly check

**Comment by sourabhsaini11** [comment]
@Lancy-Joy-Lobo
on_cancel
- value is missing for tag SETTLEMENT_AMOUNT in payments

**Comment by Lancy-Joy-Lobo** [comment]
@sourabhsaini11 I have updated the logs. Please check

**Comment by sourabhsaini11** [comment]
@Lancy-Joy-Lobo, kindly get the below issues fixed as well

cancel
- additional attribute cancellation_reason in message

**Comment by Lancy-Joy-Lobo** [comment]
@sourabhsaini11  updated the logs Please check

**Comment by 92shreyansh** [comment]
@Lancy-Joy-Lobo Transaction logs are Approved

**Pull request merged**
