### PR TITLE
rapido metro verifications logs

### PR DESCRIPTION
**Pull request by ravikumar19997**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
Hii @ravikumar19997, kindly resolve the below issues

common_issues
- transaction_id should be same throughout the user journey
- message_id should be same only between pair calls i.e. search & on_search, init & on_init

search
- Timestamp should be in UTC-Format (YYYY-MM-DDTHH:MN:SS.MSSZ)   
- bpp_id & bpp_uri are not part of search call
- STATIC_TERMS is missing in SETTLEMENT_TERMS

on_search
- Timestamp should be greater than the timestamp of search call
- time, payments, tags are missing
- Each stops object must consist of a unique id


search
- Timestamp should be in UTC-Format (YYYY-MM-DDTHH:MN:SS.MSSZ)  
- STATIC_TERMS is missing in SETTLEMENT_TERMS

on_search
- Timestamp should be greater than the timestamp of search call
- Each stops object must consist of a unique id
- time, payments, tags & cancellation_terms are missing

init
- Timestamp should be in UTC-Format (YYYY-MM-DDTHH:MN:SS.MSSZ)  
- SETTLEMENT_TERMS tag group is incomplete
- provider.id doesn't match with provider.id of on_ssearch


on_init
- Timestamp should be greater than the timestamp of init call
- order.id is not part of on_init
- category.id should be the same as sent in past calls
- selected.count is missing in items
- Each stops object must consist of a unique id
- tags are missing in payments
- cancellation_terms & order.tags are missing

confirm
- Timestamp should be in UTC-Format (YYYY-MM-DDTHH:MN:SS.MSSZ)  
- order.id is not part of confirm
- SETTLEMENT_DETAILS are not part of confirm
- SETTLEMENT_TERMS tag group is incomplete


on_confirm
- Timestamp should be greater than the timestamp of confirm call
- order.status should be a generic enum as defined in developer guide
- provider object is missing
- authorization.status is missing in fulfillments
- quote.id & payments.id is not same as send in past call
- bank_code, bank_account_number & virtual_payment_address should be same as sent in on_init call
- amount, currency & transaction_id is missing in payments.params
- order.created_at, order.updated_at is missing

status
- Timestamp should be in UTC-Format (YYYY-MM-DDTHH:MN:SS.MSSZ)  

on_status
- Timestamp should be greater than the timestamp of status
- quote, payments, provider, items, billing, order.created_at and order.updated_at are missing


cancel 
- Timestamp should be in UTC-Format (YYYY-MM-DDTHH:MN:SS.MSSZ)  
 
soft_on_cancel
- Timestamp should be greater than the timestamp of cancel call
- breakup.title should be REFUND instead of REFUND_AMOUNT
- fulfillments, payments, provider, items and billing are missing

**Comment by ravikumar19997** [comment]
@sourabhsaini11 resolved the above issue can you please check now

**Comment by 92shreyansh** [comment]
@ravikumar19997 BFF should be part of search

**Comment by ravikumar19997** [comment]
@92shreyansh as part of search call, what bpp info we need to pass be it bg info:
`"bpp_id": "preprod.gateway.ondc.org",
		"bpp_uri": "https://preprod.gateway.ondc.org/",`

**Comment by mofahsan** [comment]
Hi @ravikumar19997 

please resolve the below issues 

search
* STATIC_TERMS is missing in SETTLEMENT_TERMS

on_init
* Each stops object must consist of a unique id
* tags are missing in payments

confirm
* order.id is not part of confirm

on_confirm
* provider.time.range should be in utc format
* authorization.status is missing in fulfillments
* breakup.item missing along with id ,breakup.price missing
* order.created_at, order.updated_at is missing
* payments tags missing

on_status
* breakup.item missing along with id ,breakup.price missing
* payments tags missing
* stops id missing
* order. created at and updated at missing

**Comment by sourabhsaini11** [comment]
@ravikumar19997, kindly get the below issues fixed

on_search(1)
- parent_stop_id is missing in stops objects

search (with code)
- STATIC_TERMS is missing in SETTLEMENT_TERMS

confirm
- order.id is not part of confirm

on_confirm
- millisecond should be precise upto 3 digit at  order.created_at & order.updated_at

on_status
- millisecond should be precise upto 3 digit at  order.created_at & order.updated_at


FLow-3
cancel (confirm)
- millisecond should be precise upto 3 digit at context.timestamp

on_cancel (confirm)
- tag group 'TICKET_INFO' is not part of on_cancel(confirm)

**Comment by ravikumar19997** [comment]
@92shreyansh order.id is not part of confirm --> can you check this as discussed in community call we are getting this in on_confirm response

**Comment by sourabhsaini11** [comment]
@ravikumar19997, order.id will be generated when the order is created from seller side. Also submit the fixed/updated logs from seller side.

**Comment by ravikumar19997** [comment]
@sourabhsaini11 removed the order.id from order

**Comment by sourabhsaini11** [comment]
@ravikumar19997 Please provide dates for IGM and RSF dates by when you would be submitting the logs.

All Transaction Tech logs are fine

**Comment by ravikumar19997** [comment]
@sourabhsaini11 @92shreyansh As per the discussion with Sreenivas, the scheduled go-live date is February 02. Taking this into consideration, the IGM phase is planned for March 02, followed by the RSF flow on April 02.

**Comment by 92shreyansh** [comment]
Logs Approved with marked dates for pending activities.

**Pull request merged**
