### PR TITLE
Verification logs for Seller and Buyer FIS:12 (PL)

### PR DESCRIPTION
**Pull request by Nirdosh3312**
PR for tech logs of buyer and seller of Sequelstring for FIS:12 (Credit) for PL

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kindly get the below issues fixed
on_select_1
- descriptor.code is missing in items

on_init
- status must be equal to one of the allowed values (PAID,NOT-PAID) in payments
- SETTLEMENT_AMOUNT tag is missing in SETTLEMENT_TERMS

on_confirm
- status must be equal to one of the allowed values (PAID,NOT-PAID) in payments

on_update
- status must be equal to one of the allowed values (PAID,NOT-PAID) in payments
- descriptor.code should be CONSENT_REQUIRED instead of CONSENT_CREATED (unsolicated)

on_status
- status must be equal to one of the allowed values (PAID,NOT-PAID) in payments

on_update unsolicated (FORECLOSURE)
- descriptor.code should be COMPLETE instead of COMPLETED
- status of NOT-PAID installments should change to DEFERRED upon foreclosure

on_update (PRE_PART)
- title should be OUTSTANDING_PRINCIPAL instead of OUTSTANDING_PRINCIPLE at quote.breakup
- status of NOT-PAID installments should change to DEFERRED upon foreclosure
- status should be change to DEFERRED for installments captured during pre-part payment

**Comment by sourabhsaini11** [comment]
@Nirdosh3312 , in LOAN_INFO tag group, COOL_OFF_PERIOD & INSTALLMENT_AMOUNT should be in ISO 8601 duration format

**Comment by Nirdosh3312** [comment]
@sourabhsaini11 I have updated the tech logs for PL for the issues you have mentioned 

> @Nirdosh3312 , in LOAN_INFO tag group, COOL_OFF_PERIOD & INSTALLMENT_AMOUNT should be in ISO 8601 duration format

Kindly review the pull request

**Comment by Nirdosh3312** [comment]
@sourabhsaini11 

Can you please check for this issue in the tech logs that you have mentioned [here](https://github.com/ONDC-Official/verification-logs/pull/1467#issuecomment-1980550885) 

> on_update unsolicated (FORECLOSURE)
>  * descriptor.code should be COMPLETE instead of COMPLETED

We're referring the swagger UI as well as logs validation utility where it is mentioned that it should be COMPLETED 

> if (
          flow == fisFlows.LOAN_FORECLOSURE &&
          action == FisApiSequence.ON_UPDATE_UNSOLICATED &&
          fulfillment?.state?.descriptor?.code &&
          fulfillment.state.descriptor.code !== 'COMPLETED'
        ) {
          onUpdateObj.fulfillmentState = Fulfillment[${i}] state descriptor code should be 'COMPLETED'
        }
 
Kindly review this and do let us know of the correct one among them

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, correct value for descriptor.code is COMPLETED only. Also, please fix the below issue as well

confirm
- id is missing in payments

**Comment by Nirdosh3312** [comment]
@sourabhsaini11 Thank You for the clarification. I have fixed the mentioned issues and submitted the logs again here 95e7d98
Please review the pull request

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, there are no more findings in PL,Invoice Based Loan logs will be reviewed in separate PR.So please remove the v2_1_0/Invoice Based Loan from here.

**Comment by Nirdosh3312** [comment]
@sourabhsaini11 I have removed v2_1_0/Invoice Based Loan from here. Kindly approve the pull request

**Pull request merged**
