### PR TITLE
TSP Tech logs for Gift Card

### PR DESCRIPTION
**Pull request by Nirdosh3312**
Submitting Tech Logs for ONDC:FIS10 (Gift Card) for Verification

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kindly get the below issues fixed
common_issues
- value should be of type string in quote
- post /select fulfillments should contain 8 objects each representing an individual selected item.
- post /select tags are send additionally in offers

search
- Either percentage or value is to be sent in BUYER_FINDER_FEES
- value should be of type string in BUYER_FINDER_FEES

on_search
- type should be BPP_ONLINE_EMAIL_SMS at fulfillments[0]
- Enums are DISCOUNT, FREEBIE, BXGX only for code at offers.descriptor

on_select
- sellers shall be sending either duration or timestamp at items.time
- tag EXPIRY_PERIOD is not required
- price is incomplete at items[1].price

on_init
- tag PREVIEW_IMAGE is missing in CUSTOMIZATION
- price is incomplete at items[1].price

confirm
- tag PREVIEW_IMAGE is missing in CUSTOMIZATION
- price is incomplete at items[1].price

on_confirm
- created_at & updated_at are missing
- tag PREVIEW_IMAGE is missing in CUSTOMIZATION
- price is incomplete at items[1].price
- authorization is missing in stops
- id & params are missing in payment.params

on_status, on_update
- tag PREVIEW_IMAGE is missing in CUSTOMIZATION
- price is incomplete at items[1].price
- authorization is missing in stops
- id & params are missing in payment.params
- CANCELLED_BY should contain Subscriber id of the NP initiating the cancellation request (/unsolicited_on_update_2 only)
- REASON_ID value should be either of 001 - Seller initiated cancellation; 002 - IGM initiated cancellation (/unsolicited_on_update_2 only)
- TIMESTAMP value should be current timestamp (/unsolicited_on_update_2 only)

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11 , We have updated the logs for the mentioned issues and have added other flows as well. Kindly verify them. 

Looking forward to your response.

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kindly fix below issues
common_issue
- for each selected item, total fulfillment id's associated to that individual object/item should be equal to quantity.count of that object. Hence in your case, each fulfillment_ids should contain 5 id's only
- OFFER should not be applied on GC3 as DISCA100 is selected for item.id GC1 only, at quote.breakup

on_search
- items are incomplete, missing PARENT item objects are missing

on_select
- quantity is missing in items

confirm
- incorrect payload, contains /on_init call

on_status
- created_at should match /on_confirm created_at

Flow-2
on_cancel
- order.status should be CANCELLED

Flow-3
on_update
- updated_at should not match past call updated_at

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11, We have fixed the mentioned issues and have updated the logs, Kindly verify them.

Looking forward to your response. Regards

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11, We have fixed the mentioned issues and have updated the logs, Kindly verify them.

Looking forward to your response. Regards

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please fix below issues also
common_issue
- offered_value is missing for title 'ITEM' at quote.breakup 

on_cancel
- created_at should match past call's created_at

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11, We have fixed the mentioned issues and have updated the logs, Kindly verify them.

Thanks

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please fix the below issues as well
common_issue
- authorization shouldn't be present if state.code is PENDING, at fulfillments

on_status
- updated_at should not match past call's updated_at if payload is changed/updated in current call

**Comment by Ashu-14-oct** [comment]
Hi @sourabhsaini11 , We have fixed the mentioned issues and have updated the logs, Kindly verify them.

Thanks

**Comment by 92shreyansh** [comment]
Transaction Logs Approved.

**Pull request merged**
