### PR TITLE
EasyPay FIS12 Invoice Based Logs Submission

### PR DESCRIPTION
**Pull request by ep-aws**
EasyPay FIS12 Invoice Based Logs Submission

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@ep-aws, kindly get the below issue fixed
Common_issue
- Tag  OFFLINE_CONTRACT is missing in SETTLEMENT_TERMS tag-group
- Remove signature from payload

Init(2, 3 & 4 only)
- Id is missing in payments
	
Confirm
- Id is missing in payments
- Tags SETTLEMENT_WINDOW and SETTLEMENT_BASIS are missing in SETTLEMENT_TERMS tag-group

**Comment by ep-aws** [comment]
We have updated the changes. Kindly review it and let's know if any changes needed.

**Comment by sourabhsaini11** [comment]
@ep-aws, please get the below issue fixed
common_issue
- tag SETTLEMENT_TYPE value must be in an enum format i.e. UPI

Flow-3
- remove additional IGM calls

Flow-5
- only IGM calls should be present, remove additional files
- issue_status call is missing

**Comment by ep-aws** [comment]
@sourabhsaini11 We have resubmitted the logs. Please check them.

**Comment by 92shreyansh** [comment]
Transaction & IGM logs are Approved for Buyer App

**Pull request merged**
