### PR TITLE
Marine Insurance Reference Buyer Application Logs

### PR DESCRIPTION
**Pull request by Avijeet-Blocsol**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Avijeet-Blocsol, you already have a [PR](https://github.com/ONDC-Official/verification-logs/pull/1684) open for MARINE-ins. Please close this PR & get your logs updated in the old one so that a single trail can be maintain.

**Comment by Avijeet-Blocsol** [comment]
We have closed the old PR

**Comment by anuj-ondc** [comment]
@Avijeet-Blocsol  fix below issues:


Flow 1

- on_select 1:
  - quote base price & item price is not matching.
  
- confirm:
  - fulfilment id is not matching with on_init call.

- on_confirm: 
  - In documents, remove RENEW_DOC(supported documents are POLICY_DOC & CLAIM_DOC).
  - Invalid fulfilment state, needs to be GRANTED.

Flow 2:
  - on_update 1:
    - Invalid fulfilment state of type POLICY, needs to be GRANTED. 

  - Missing 1st on_update (check developer guide)
  - on_update_2.json is not required, this information can be sent by on_status call.
  - Missing last on_update for REF_ID tag value (check developer guide)

 FLow 3: 
  - on_cancel & on_update: 
    - Invalid fulfilment state of type POLICY

**Comment by Avijeet-Blocsol** [comment]
Hello Anuj,

Regarding the following points, we cannot control them since we are a buyer application:

on_cancel & on_update:

    Invalid fulfilment state of type POLICY



on_update_2.json is not required, this information can be sent by on_status call.



on_update 1:

    Invalid fulfilment state of type POLICY, needs to be GRANTED.



on_select 1:

    quote base price & item price is not matching.




on_confirm:

    In documents, remove RENEW_DOC(supported documents are POLICY_DOC & CLAIM_DOC).
    Invalid fulfilment state, needs to be GRANTED.


We will fix the other points and resubmit the logs

**Comment by Avijeet-Blocsol** [comment]
We have updated our side of the logs as per the feedback. We do not have control over callback requests so we cannot update those logs ourselves. 

Looking forward to the closure of the PR.

**Comment by anuj-ondc** [comment]
@Avijeet-Blocsol, The transactional logs for the buyer app have been approved. Your PR will be merged soon.

**Pull request merged**
