### PR TITLE
redbus trv10 logs

### PR DESCRIPTION
**Pull request by Lancy-Joy-Lobo**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Lancy-Joy-Lobo, please get the below issues fixed
common_issues
- invalid tags TIME_CHARGE, DISTANCE_CHARGE & PICKUP_CHARGE_MAX present in FARE_POLICY tag-group
- vehicle.category should be one of AUTO_RICKSHAW,CAB

on_search
- payments is missing

on_init
- customer is missing for fulfillments
- tag SETTLEMENT_AMOUNT is missing
- Either percentage or amount.currency & amount.value should be present, but not both, for cancellation_terms

confirm
- tag SETTLEMENT_AMOUNT is missing

on_confirm
- id is additional in agent.person
- tag SETTLEMENT_AMOUNT is missing
- Either percentage or amount.currency & amount.value should be present, but not both, for cancellation_terms
- incorrect tags at ROUTE_INFO tag-group, should contain tags 'ENCODED_POLYLINE' & 'WAYPOINTS' instead.
- created_at timestamp should have milliseconds precise upto 3 places only.
- additional title PICKUP_CHARGE & PICKUP_CHARGE present in quote.breakup

on_update
- id is additional in agent.person
- tag SETTLEMENT_AMOUNT is missing
- Either percentage or amount.currency & amount.value should be present, but not both, for cancellation_terms
- incorrect tags at ROUTE_INFO tag-group, should contain tags 'ENCODED_POLYLINE' & 'WAYPOINTS' instead.
- created_at timestamp should have milliseconds precise upto 3 places only.
- additional title PICKUP_CHARGE & PICKUP_CHARGE present in quote.breakup

on_status
- id is additional in agent.person
- tag SETTLEMENT_AMOUNT is missing
- Either percentage or amount.currency & amount.value should be present, but not both, for cancellation_terms
- incorrect tags at ROUTE_INFO tag-group, should contain tags 'ENCODED_POLYLINE' & 'WAYPOINTS' instead.
- created_at timestamp should have milliseconds precise upto 3 places only.
- additional title PICKUP_CHARGE & PICKUP_CHARGE present in quote.breakup

Flow-2
-flow name should be Drive cancel

on_cancel
- id is additional in agent.person
- rating is additional in agent
- tag SETTLEMENT_AMOUNT is missing
- breakup is missing in quote
- invalid tag-group 'RETRY_INFO'
- Either percentage or amount.currency & amount.value should be present, but not both, for cancellation_terms
- created_at timestamp should have milliseconds precise upto 3 places only.
- incorrect tags at ROUTE_INFO tag-group, should contain tags 'ENCODED_POLYLINE' & 'WAYPOINTS' instead.

Flow-3
-flow name should be Rider cancel

on_cancel
- id is additional in agent.person
- tag SETTLEMENT_AMOUNT is missing
- breakup is missing in quote
- Either percentage or amount.currency & amount.value should be present, but not both, for cancellation_terms
- created_at timestamp should have milliseconds precise upto 3 places only.
- incorrect tags at ROUTE_INFO tag-group, should contain tags 'ENCODED_POLYLINE' & 'WAYPOINTS' instead.

**Comment by Lancy-Joy-Lobo** [comment]
@sourabhsaini11 Will resolve the comment on confirm call that you have put.
But rest all of the comments are related to the responses that we get from the seller apps.

**Comment by yashb042** [comment]
@sourabhsaini11 Any updates on this? How should we get the logs changed from the seller side.

**Comment by 92shreyansh** [comment]
@Lancy-Joy-Lobo Transaction logs for the buyer app are Approved.

**Pull request merged**
