### PR TITLE
Added WeCredit in FIS12

### PR DESCRIPTION
**Pull request by sibashis-wecredit**
We have added logs for all 6 flows in the WeCredit folder, under the FIS12 domain .

### CODE REVIEW

**Comment by sibashis-wecredit** [comment]
We have added logs for all 6 flows in the WeCredit folder, under the FIS12 domain .

**Comment by sourabhsaini11** [comment]
@sibashis-wecredit, kindly get the below issues fixed
common_issues
- tag SETTLEMENT_AMOUNT value mismatch between /action & /on_action calls
- id is missing in payments(init_2 & init_3 only)

Flow-2
- Incomplete Flow(Calls missing post on_select)
select_1 & 2
- form.id mismatches with form.id sent in past call

Flows-1 & 3
init
- form.id mismatches with form.id sent in past call (init_2 only)
- form_response.status should be 'SUCCESS' at xinput (init_1 & 3 only)

confirm
- form.id mismatches with form.id sent in past call

Flows-4 & 5
select_3
- form.id mismatches with form.id sent in past call

init
- form_response.status should be 'SUCCESS' at xinput

**Comment by sibashis-wecredit** [comment]
We have added IGM in wecredit folder under FIS12 domain in this pull request.

**Comment by sibashis-wecredit** [comment]
Flow-2

Incomplete Flow(Calls missing post on_select)
select_1 & 2

I am confused about the above point. Please can you clarify a bit more?

**Comment by sourabhsaini11** [comment]
@sibashis-wecredit, kindly fix the below IGM issues as well
issue
- complainant_actions[0].updated_by must have required property 'person'
- org.name should be bap_id::domain

issue(close)
- context.timestamp should be greater than or equal to updated_at
- org.name should be bap_id::domain
- 'created_at' should match issue's 'created_at'

on_issue_status
- 'created_at' should match issue's 'created_at'
- org.name at issue_actions.respondent_actions[32] should be bpp_id::domain

**Comment by sibashis-wecredit** [comment]
We have fixed all the issues in the 6 flows mentioned in the previous message.

**Comment by sibashis-wecredit** [comment]
We have fixed all the issues in the IGM.

**Comment by sourabhsaini11** [comment]
@sibashis-wecredit, kindly fix the below issues
common_issue
- bap_uri must remain same across all calls

select_2
- status in item[0] should be 'APPROVED'

IGM
issue
- context timestamp should be greater than or equal to updated_at in issue

issue(close)
- org.name should be bap_id::domain at complainant_actions

**Comment by sibashis-wecredit** [comment]
We have fixed all the issues mentioned in the previous feedback.

**Comment by sourabhsaini11** [comment]
@sibashis-wecredit, please fix below issues
common_issue
- bap_uri must remain same across all calls

IGM
-remove additional transactional calls apart from IGM

issue(close)
- org.name should be bap_id::domain at complainant_actions[0]

**Comment by sibashis-wecredit** [comment]
I've fixed the issue with IGM.

**Comment by sourabhsaini11** [comment]
@sibashis-wecredit, kindly fix the below issue as well
- bap_uri must remain same across all calls

**Comment by 92shreyansh** [comment]
@sibashis-wecredit is the bap_uri issue fixed?

Once fixed please update the logs

**Comment by sibashis-wecredit** [comment]
Please check. We have fixed the bap_uri.

**Comment by 92shreyansh** [comment]
Transaction logs & IGM for BAP is Approved

**Pull request merged**
