### PR TITLE
IGM Logs

### PR DESCRIPTION
**Pull request by Ashwini1797**

### CODE REVIEW

**Comment by Ashwini1797** [comment]
@92shreyansh
Please review the logs and let us know if there is anything we need to change
Additionally, could you add the respective label to the logs..

**Comment by RupalSingla** [comment]
issue:
message.issue.order_details.status is having enum "UNCLIAMED" which is not correct

on_issue_status
Before the issue is  closed,it is mandatory to Resolved the issue , so respondent action needs to have respondent action= "Resolved".
@Ashwini1797

**Comment by Ashwini1797** [comment]
@RupalSingla 
We have tried to resolve all the listed issues.
Please review the logs and let us know if there is anything else we need to change.

**Comment by Ashwini1797** [comment]
@92shreyansh @RupalSingla 
Any update about the logs...

**Comment by Ashwini1797** [comment]
@RupalSingla 
Any update about the logs...

**Comment by RupalSingla** [comment]
Logs approved @Ashwini1797

**Comment by 92shreyansh** [comment]
IGM Logs are Approved

**Pull request merged**
