### PR TITLE
add zyapaar logs - Easy Pay

### PR DESCRIPTION
**Pull request by ep-aws**
add zyapaar logs - Easy Pay

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@ep-aws, please get the below issues cleared
common_issues
- OFFLINE_CONTRACT tag is missing in SETTLEMENT_TERMS tag-group
- SETTLEMENT_BASIS should be in a generic enum format INVOICE_RECEIPT

on_select
- descriptor is missing at items[0].descriptor

init
- id is missing in payments(init 2 & 3)

confirm
- id is missing in payments

flow-3
on_update (unsolicited)
- status as NOT-PAID should change to DEFERRED instead of PAID upon foreclosure

flow-5
on_update
- missed INSTALLMENT status should be DELAYED instead of NOT-PAID

on_update (unsolicited)
- status for missed INSTALLMENT should change to DEFERRED post fulfillment

**Comment by sourabhsaini11** [comment]
@ep-aws, kindly get the below issues fixed
- update, on_update & on_update(unsolicated) calls are missing

select_2
- incorrect payload.

init_2
- incorrect payload.

flow-4
- submit complete flow for pre-part instead of NACK resp.

**Comment by sourabhsaini11** [comment]
@ep-aws, please get the below issues fixed
search
- bpp_uri & bpp_id are not part of search call

select
- form.id should match to the form.id sent in past call

init
- form.id should match to the form.id sent in past call

confirm
- form.id should match to the form.id sent in past call

on_status
- OTHER_UPFRONT_CHARGES is missing in quote.breakup

- update api-pair & on_update(unsolicated) call capturing Monitoring Consent are missing

Flow-4
on_update
- incorrect payload

**Comment by sourabhsaini11** [comment]
@ep-aws, please get the below issues fixed
common_issues
- At fulfillments in customer.contact, email is missing
- SETTLEMENT_AMOUNT value mismatch between action & on_action calls

confirm
- id is missing in payments

**Comment by anuj-ondc** [comment]
@ep-aws, kindly get the below issues fixed


 **Common issues:**
      - Fulfillments state needs to be changed accordingly for  on_confirm & on_update calls.
    - Settlement amount difference b/w action & on_action call still persisted.

**Flow 3, 4, 5**
  on_update(for all on_update calls)
    - The status of payment with type ON_ORDER needs to be PAID.

Flow 5
  - on_update
    - In payments, the status for payment object with "id": "1" needs to be PAID(with start date: 2024-07-01T10:49:49.275Z)   
      as the status of next payment with "id": "2"(with start date: 2024-08-01T10:49:49.275Z") object is DELAYED

**Comment by ep-aws** [comment]
@anuj-ondc These issues are all from the seller's side (Praman) and cannot be fixed by the buyer's apps.

**Comment by 92shreyansh** [comment]
Transaction Logs for Buyer App is Approved

**Comment by 92shreyansh** [comment]
Please resolve the merge conflict

**Comment by sourabhsaini11** [comment]
> Please resolve the merge conflict

reminder!!

**Comment by ep-aws** [comment]
resolved conflict

**Comment by ep-aws** [comment]
Resolved the conflict

**Pull request merged**
