### PR TITLE
Pre-prod Tech Logs for TRV11

### PR DESCRIPTION
**Pull request by dunowgithub**
Pre-prod Tech Logs for TRV11

### CODE REVIEW

**Comment by dunowgithub** [comment]
@sourabhsaini11 Submitting TRV11 Pre-Prod Logs for your review. Let us know if you need anything else.

**Comment by sourabhsaini11** [comment]
@dunowgithub, please submit /on_action calls and missing flows as well

**Comment by dunowgithub** [comment]
sourabhsaini11 - Missing files have been uploaded. Please check

**Comment by sourabhsaini11** [comment]
@dunowgithub, please submit search_1 api pair call & seggregate calls on basis of flows as well

**Comment by dunowgithub** [comment]
sourabhsaini11 - Done. Please have a look. You may please delete the files that are outside the "Flow" folder

**Comment by sourabhsaini11** [comment]
@dunowgithub, please fix below issue 
search
- collected_by is missing in payments
- bpp_uri & bpp_id is missing in context (for /search_2 only)

**Comment by dunowgithub** [comment]
> @dunowgithub, please fix below issue search
> 
> * collected_by is missing in payments
> * bpp_uri & bpp_id is missing in context (for /search_2 only)

collected_by is missing in payments - This can be fixed
bpp_uri & bpp_id is missing in context (for /search_2 only)  - Our Journey starts directly with Search_2. We cache the station codes and indicate that in START & END and wait for Sellers to respond. So we will NOT know bpp_i and bpp_uri. We will know only in on_search2 - So this should observation should be discarded.

**Comment by dunowgithub** [comment]
> @dunowgithub, please fix below issue search
> 
> * collected_by is missing in payments
> * bpp_uri & bpp_id is missing in context (for /search_2 only)

Over to you.. 

#1) collected_by is missing in payments - FIXED
#2) bpp_uri & bpp_id is missing in context (for /search_2 only) - Our Journey starts directly with Search_2. We cache the station codes and indicate that in START & END and wait for Sellers to respond. So we will NOT know bpp_id and bpp_uri. We will know only in on_search2 - So this should observation should be discarded.

**Comment by sourabhsaini11** [comment]
@dunowgithub, please get below issues fixed as well
common_issue
- tag SETTLEMENT_WINDOW value mismatch between /action & /on_action calls

search1
- payment.collected_by is missing

confirm
- bank_account_number & bank_code are mising in params

**Comment by dunowgithub** [comment]
> @dunowgithub, please get below issues fixed as well common_issue
> 
> * tag SETTLEMENT_WINDOW value mismatch between /action & /on_action calls
> 
> search1
> 
> * payment.collected_by is missing
> 
> confirm
> 
> * bank_account_number & bank_code are mising in params

Hey,

We are committing to settlement to the seller in 3 days though the seller wants in 30 days. How is that a problem?

**Comment by dunowgithub** [comment]
> > @dunowgithub, please get below issues fixed as well common_issue
> > 
> > * tag SETTLEMENT_WINDOW value mismatch between /action & /on_action calls
> > 
> > search1
> > 
> > * payment.collected_by is missing
> > 
> > confirm
> > 
> > * bank_account_number & bank_code are mising in params
> 
> Hey,
> 
> We are committing to settlement to the seller in 3 days though the seller wants in 30 days. How is that a problem?

Whose bank_account_number & bank_code are mising in params?

**Comment by sourabhsaini11** [comment]
@dunowgithub, please fix the below issues
common_issue
- tag SETTLEMENT_WINDOW value mismatch between /action & /on_action calls (what if BPP is asking P1D or PT1H as SETTLEMENT_WINDOW instead of P30D, will you guys still settle for P3D or agree to settle at their time-frame. Thus in such cases there's need to be clear terms defined in the contract or such discrepancy will occur)

on_confirm
- fulfillments.id & payments.id mismatch between /on_init & /on_confirm

**Comment by dunowgithub** [comment]
@92shreyansh @sourabhsaini11 We have resubmitted the logs. Please review and let us know on the same.

https://github.com/dunowgithub/verification-logs/tree/main/TRV11/Miles%20%26%20Kilometres

**Comment by sourabhsaini11** [comment]
@dunowgithub 
common_issue
- How can for each action calls, milliseconds be having same value i.e. 000Z at context.timestamp
- virtual_payment_address is not required if SETTLEMENT_TYPE is not UPI

search_1
- additional tag SETTLEMENT_WINDOW present
- additional attributes data & type present at root level of payload

search_2
- bpp_uri & bpp_id are missing (they are required for 2nd search call)

init
- missing MANDATORY_ARBITRATION & COURT_JURISDICTION tags at SETTLEMENT_TERMS

confirm
- additional attributes data & type present at root level of payload

on_init
- additional attributes data & type present at root level of payload

on_confirm
- payments.id mismatch between /on_init & /on_confirm
- additional attributes data & type present at root level of payload

**Comment by dunowgithub** [comment]
> @dunowgithub common_issue
> 
> * How can for each action calls, milliseconds be having same value i.e. 000Z at context.timestamp
> * virtual_payment_address is not required if SETTLEMENT_TYPE is not UPI
> 
> search_1
> 
> * additional tag SETTLEMENT_WINDOW present
> * additional attributes data & type present at root level of payload
> 
> search_2
> 
> * bpp_uri & bpp_id are missing (they are required for 2nd search call)
> 
> init
> 
> * missing MANDATORY_ARBITRATION & COURT_JURISDICTION tags at SETTLEMENT_TERMS
> 
> confirm
> 
> * additional attributes data & type present at root level of payload
> 
> on_init
> 
> * additional attributes data & type present at root level of payload
> 
> on_confirm
> 
> * payments.id mismatch between /on_init & /on_confirm
> * additional attributes data & type present at root level of payload

@92shreyansh @sourabhsaini11 We have resubmitted the logs. Please review and let us know on the same.

https://github.com/dunowgithub/verification-logs/tree/main/TRV11/Miles%20%26%20Kilometres

**Comment by dunowgithub** [comment]
> * complainant_actions

@amitsinha07 

The domain in context is "TRV:11" and in message/issue/issue_actions/complainant_actions/[0]/updated_by/org/name is "dunow.co.in::ONDC::TRV11" -- Is the double ":" the issue?  

The created_at timestamp in the issue_close call does not match the created_at timestamp in the issue call. -- OK, Will fix and let you know

message/issue/id must be consistent. -- Can you Check one more time and let me know if you are still seeing this? If you are still seeing this error - Can you help me spot it?

The domain of the organization in the /issue API:  (Can you tell me what is expected? )
For complainant_actions/[0], it does not match the domain in the context. -- Is the double ":" the issue?  
For complainant_actions/[1], it does not match the domain in the context. -- Is the double ":" the issue?  

message/issue/issue_actions/respondent_actions/resolved should be present, as resolution_provider is provided in on_issue_status. -- This is not under my control. It comes from the Seller App - Ignore this?

**Comment by dunowgithub** [comment]
> @amitsinha07

If we can briefly speak? - I need to understand what do you mean by "message/issue/issue_actions/respondent_actions/resolved should be present, as resolution_provider is provided in on_issue_status" -

**Comment by sourabhsaini11** [comment]
@dunowgithub, transactional-logs are approved, please get IGM issues cleared as well.

**Comment by dunowgithub** [comment]
> @dunowgithub, transactional-logs are approved, please get IGM issues cleared as well.

@sourabhsaini11 Thank you!

**Comment by dunowgithub** [comment]
> @amitsinha07

We have taken care of all observations that you had posted related to IGM. Kindly do take a look and let us know if there anything. If everything is as per your expectation, please provide us with your approval for the IGM part.

https://github.com/dunowgithub/verification-logs/tree/main/TRV11/Miles%20%26%20Kilometres

**Comment by dunowgithub** [comment]
> > @amitsinha07
> 
> We have taken care of all observations that you had posted related to IGM. Kindly do take a look and let us know if there anything. If everything is as per your expectation, please provide us with your approval for the IGM part.
> 
> https://github.com/dunowgithub/verification-logs/tree/main/TRV11/Miles%20%26%20Kilometres

@amitsinha07 - Can you take a look at this and revert?

**Comment by amitsinha07** [comment]
@dunowgithub 
## Feedback for IGM

### Issue:
  - The `created_at` and `updated_at` timestamps for the `/issue` API should match.
  - The `context.timestamp` should be **greater than or equal to** the `updated_at` value in the issue.

### Issue_CLOSE:
  - The value of `message/issue/issue_action/complainant_actions/index[1]/updated_at` should be **less than or equal to** the `updated_at` value in the issue.

**Comment by dunowgithub** [comment]
> amitsinha07

Hello Amit, Your IGM observations have been taken care of. Please have a look and let us know.

https://github.com/dunowgithub/verification-logs/tree/main/TRV11/Miles%20%26%20Kilometres

**Comment by amitsinha07** [comment]
@dunowgithub 
The logs are approved for IGM 1.0.0

**Comment by JyotiSharma0711** [comment]
# TRV11/Miles & Kilometres/RSF 1.0.0

## Receiver Recon
/context/domain must be equal to one of the allowed values (ONDC:NTS10)
/message/orderbook/orders must NOT have fewer than 5 items
"/message/orderbook/orders/0 must have required property 'invoice_no'
/message/orderbook/orders/0/state must be equal to one of the allowed values (Completed)
**Context/Timestamp**: Should be greater than the created_at and updated_at.
**Order Recon Status**: message/orderbook/orders/0/Order_recon_status should be **"1"**.
**Settlement IDs**: 
  - message/orderbook/orders/0/payment/settlement_id and 
  - message/orderbook/orders/0/payment/settlement_reference_id  
  **should not match** with each other.

## On Receiver Recon
/context/domain must be equal to one of the allowed values (ONDC:NTS10)
**Transaction ID**: message/orderbook/orders/0/payment/transaction_id should be in **"uuid"** format.
**Settlement IDs**: 
  - message/orderbook/orders/0/payment/settlement_id and 
  - message/orderbook/orders/0/payment/settlement_reference_id  
  **should not match** with each other.
  
 You can also test  with mock server
 https://github.com/ONDC-Official/mock-server-utility

**Comment by dunowgithub** [comment]
> # TRV11/Miles & Kilometres/RSF 1.0.0
> ## Receiver Recon
> /context/domain must be equal to one of the allowed values (ONDC:NTS10) /message/orderbook/orders must NOT have fewer than 5 items "/message/orderbook/orders/0 must have required property 'invoice_no' /message/orderbook/orders/0/state must be equal to one of the allowed values (Completed) **Context/Timestamp**: Should be greater than the created_at and updated_at. **Order Recon Status**: message/orderbook/orders/0/Order_recon_status should be **"1"**. **Settlement IDs**:
> 
> * message/orderbook/orders/0/payment/settlement_id and
> * message/orderbook/orders/0/payment/settlement_reference_id
>   **should not match** with each other.
> 
> ## On Receiver Recon
> /context/domain must be equal to one of the allowed values (ONDC:NTS10) **Transaction ID**: message/orderbook/orders/0/payment/transaction_id should be in **"uuid"** format. **Settlement IDs**:
> 
> * message/orderbook/orders/0/payment/settlement_id and
> * message/orderbook/orders/0/payment/settlement_reference_id
>   **should not match** with each other.
> 
> You can also test with mock server https://github.com/ONDC-Official/mock-server-utility

@JyotiSharma0711 - Your observations have been addressed. Please have a look and let us know.

/context/domain must be equal to one of the allowed values (ONDC:NTS10) - DONE

/message/orderbook/orders must NOT have fewer than 5 items -- IGNORE (Based on my Discussion with Jyoti)

"/message/orderbook/orders/0 must have required property 'invoice_no' -- IGNORE (Based on my Discussion with Jyoti)

/message/orderbook/orders/0/state must be equal to one of the allowed values (Completed) - DONE

Context/Timestamp: Should be greater than the created_at and updated_at. -- DONE

Order Recon Status: message/orderbook/orders/0/Order_recon_status should be "1". -- DONE

Settlement IDs:
message/orderbook/orders/0/payment/settlement_id and
message/orderbook/orders/0/payment/settlement_reference_id
should not match with each other. -- DONE

Log are at https://github.com/dunowgithub/verification-logs/tree/main/TRV11/Miles%20&%20Kilometres/RSF%201.0.0

**Comment by JyotiSharma0711** [comment]
approved for RSF 1.0

**Pull request merged**
