### PR TITLE
verification-logs for SumaSoft Entity

### PR DESCRIPTION
**Pull request by ashish-sumasoft**
Hello Team ONDC,

Please review this PR and let us know if anything else is required.
We have captured the Following flows : 

1. Happy Flow with ride booking and completed
2. Ride Cancellation from Rider
3. Ride Cancellation from Driver
4. Ride Completed with differential fair(upper or lower)

Thanks

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@ashish-sumasoft, please resolve the below issues for all the flows

search 
- SETTLEMENT_TERMS tag group missing
on_search
- providers.locations[] missing
- items.descriptor.code is missing
- items.location_ids[] is missing
-'Taxi' is not part of enum group provided in providers[1].fulfillments.vehicle.category
select
- provider object is missing in message.order
- if fulfillments is provided then corresponding id, gps & timestamp should also be provided
on_select
-items[0].descriptor.code is missing
-items[0].location_ids is missing
- ttl must be present in quote
- tags missing in place of tags, cancellation terms is present
init
-order id missing
- extra attribute id in fulfillments[0].person
-vehicle missing in fulfillments
-collected_by, status, type missing in payments
- SETTLEMENT_TERMS missing in payments
on_init
-items[0].descriptor.code missing
- items[0].price.maximum_value is lower than items[0].price.value 
- if items.location_ids are present then they should also be present in previous calls.
- vehicle.category missing in fulfillments
- tag group ROUTE_INFO must be present.
- extra attributes amount and currency in payments.params
- SETTLEMENT_TERMS missing in payments
confirm
- extra attributes in items apart from id
- customer.phone missing in fulfillments
- extra attribute agent in fulfillments
- vehicle.category missing in fulfillments
- extra attribute params in payments
- SETTLEMENT_TERMS missing in payments
on_confirm
-[items.id](http://items.id/) cannot be empty
- items.descriptor.code cannot be empty
- price.value is required in items
- location_ids missing in items
- FARE_POLICY tag group missing in items
- value and currency must be present in price attribute
- ttl must be present in quote
- customer.phone missing in fulfillments
- vehicle.category missing in fulfillments
- extra attribute amount and currency in payments.params
- SETTLEMENT_TERMS missing in payments
cancel
- ttl missing in context
- descriptor.code missing in message
on_cancel
- order id mismatch in cancel and on_cancel calls
- descriptor.code missing in items
- price.value missing in items
- FARE_POLICY tag group missing in items

**Comment by ashish-sumasoft** [comment]
Hi @sourabhsaini11 , we have resolved the issues mentioned earlier. Could you please review and approve this pull request?

**Comment by sourabhsaini11** [comment]
@ashish-sumasoft, kindly fix the below issues for all the flows

common issues
- 'ttl' is missing on_search onwards
- gps should be precise to 6 digit, at stop 'End'
- vehicle.category should be in a standard enum format (AUTO_RICKSHAW)
- value should be string containing a positive int or float with decimal percision upto two digits

search
- collected_by is missing in payments

on_search
- payments array in items is not part of on_search
- images array is not part of items, if present, then shoyld be inside items.descriptor
- type is missing in fulfillments
- vehicle.category must be a standard enum(CAB) at fulfillments[1]

select
- provider object should only contain id of the provider for select
- fulfillments object should only contain id if send as part of select call
- payments is not part of select call


on_select
- action is wrong in context
- payments object should not be part of on_select
- payment_ids in items is not part of on_select call
- display is missing for items tags
- value & currency should be part of price in quote
- price.value must be wrapped in ""
- agent should not be assigned in on_select call
- BUYER_FINDER_FEES is not part of quote breakup

init
- id is missing in fulfillments
- agent details are not part of fulfillments
- id should not be present in payments for init

on_init
- action is wrong in context
- display is missing for items tags
- value & currency should be part of price in quote
- price.value must be wrapped in ""
- agent details are not part of fulfillments in on_select
- BUYER_FINDER_FEES is not part of quote breakup

confirm
- order id is not part of confirm call 

on_confirm
- items.id should be valid not empty
- tags are empty in items
- value & currency should be part of price in quote
- BUYER_FINDER_FEES is not part of quote breakup
- id should not be assigned to agent object in fulfillments

on_update
- payments should not be empty
- fulfillments, cancellation_terms, items and provider are missing
- quote is same as the one send in previous call

status
- order_id or ref_id should be present

on_status (all)
- params object is incorrect in payments
- tags are missing for payments & items
- BUYER_FINDER_FEES is not part of quote breakup
- authorization object is not required for 'END' stop
- make & model are missing in vehicle object

flow 2

on_cancel
- ttl is missing in quote
- breakup.title must be a standard enum in quote


Note
- Kindly refrain from using values of tags from mobility developer guide. Those are for demonstrative prupose only.

**Comment by kiranHdvi** [comment]
Hello @sourabhsaini11 ,
Thanks for reviewing the PR.
The team has worked on the PR comments and updated the verification logs.
Please review once again whenever convenient.
Thanks.

**Comment by kiranDev** [comment]
Hello @sourabhsaini11 ,

Thanks for reviewing the PR.
The team has worked on PR comments and updated the verification logs.
Please review the PR once again whenever convenient.
Thanks In Advance.

**Comment by sourabhsaini11** [comment]
common issues
- gps should be precise to 6 digit everywhere

on_select
- descriptor.code value shouldn't be RIDE_ASSIGNED if user is in selection phase, at fulfillments
- type is missing in fulfillments
- price object is missing in items
- cancellation_terms are not part on on_select
- price.value should be a string at quote

on_init
- additional attribute amount at params in payments
- price.value should be a string at quote

confirm
- SETTLEMENT_TERMS list is incomplete at payments
- additional attribute amount at params in payments

on_confirm
- order.id shouldn't be empty
- status is missing at message
- additional attribute amount at params in payments
- price.value should be a string at quote
- invalid attribute fulfillment_id & payment_id at items

on_update
- additional attribute amount & currency at params in payments
- price.value should be a string at quote
- quote object is same as the one send in previous call while in update_target is refering to change in quote

status
- message should not be empty, order_id or ref_id should be present

on_status
- price.value should be a string at quote
- additional attribute amount at params in payments

above issues are common to all the flows

Flow 2 
on_cancel
- action is wrong in context
- additional attribute cancellation at message
- attribute phone for agent should not be empty

flow is incomplete, should consist of 2 on_cancel calls each representing a SOFT_CANEL & CANCELLED status

Flow 3
on_cancel
- action is wrong in context
- order id should not be empty
- price object & tags should not be empty in items
- value & currency should be part of price in quote
- price.value should be a string at quote
- attribute phone for agent should not be empty
- vehicle.category should not be empty
- cancellation_terms should not be empty
- additional attribute cancellation at message
- payment tags are missing
- additional attribute amount at params in payments

Hii @kiranDev
above are the latest issues for the updated PR
Kindly review these as well

**Comment by rajat72588** [comment]
Hey @sourabhsaini11, appreciate the review on the PR!

Could you elaborate on the missing status in 'on_confirm'? More context would be super helpful. Thanks!

**Comment by rajat72588** [comment]
Hey @sourabhsaini11, appreciate the review on the PR!

Could you elaborate on the missing status in 'on_confirm'? More context would be super helpful. Thanks!

**Comment by vishal1661** [comment]
Hello @sourabhsaini11 
Thanks for reviewing the PR.
We are unfamiliar with the statuses of SOFT_CANCEL and CANCELLED. Could you provide more details or clarification on these statuses?

**Comment by kiranDev** [comment]
Hi @sourabhsaini11 ,
Team have updated the verification log with SOFT_CANCEL and CANCELLED Flow jsons.
Please review whenever convenient.
Thanks In Advance.

**Comment by sourabhsaini11** [comment]
Hii @kiranDev, kindly check the below issues as well

soft_cancel
- transaction_id should be same as sent in past calls
- order.id should be same as sent in previous call

soft_on_cancel
- payment.id should be the same as sent in past calls
- descriptor.code at fulfillments[0] should be according to the developer guide
- descriptor.message at fulfillments[0] should be representing rider cancellation 
- invalid vehicle.category at fulfillments[0]
- amount.value at cancellation_terms[1] should be a string
- Quote breakup is missing the following items: CURRENT_FARE_CHARGE, CANCELLATION_CHARGES

confirm_on_cancel
- descriptor.message at fulfillments[0] should be representing rider cancellation 
- amount.value at cancellation_terms[1] should be a string
- invalid vehicle.category at fulfillments[0]
- Quote breakup is missing the following items: CURRENT_FARE_CHARGE

**Comment by rajat72588** [comment]
Hey @sourabhsaini11 , 
I have resolved the PR comments.

Currently I have added the CURRENT_FARE_CHARGE as estimated cost for the ride, Is it correct if not,
Could you elaborate on the same? More context would be super helpful. Thanks!

**Comment by sourabhsaini11** [comment]
Hey @rajat72588, kindly get these below issues fixes

search
- incorrect attribute fulfillments, should be fulfillment

on_search
- images must be an object with property url
- Payments are missing for provider

on_select
- images must be an object with property url
- price/value must be string at payments

init
- person must NOT have additional properties (rateable)

on_init
- customer/person/id must be string
- price/value must be string
- id in fulfillments should be one of fulfillments/id mapped in previous call

confirm
- order/id is not part of /confirm call

on_confirm
- agent/rating must be string
- image must be an object
- cancellation_terms must be array
- price/value must be string
- payments.collected_by must be present
- order.status is missing

on_status (Flow 1)
- agent/rating must be string
- cancellation_terms must be array
- price/value must be string
- descriptor.code is missing at items
- fulfillments.type is missing

soft_on_cancel (Flow 2)
- image must be an object
- Invalid fulfillment state code, should be an enum as defined on developer guide

on_cancel (Flow 2)
- agent/rating must be string
- image must be an object

on_cancel (FLow 3)
- agent/rating must be string
- image must be an object
- price/value must be string
- order.status is missing

on_update (Flow 4)
- agent/rating must be string
- price/value must be string
- descriptor.code is missing at items
- fulfillments.type is missing

**Comment by ashish-sumasoft** [comment]
Hi @sourabhsaini11  ,

Thanks for your feedback. Regarding the missing payments for the provider, the developer guide states that it's not mandatory. I've aligned the implementation accordingly. If you have further concerns, let me know.

**Comment by sourabhsaini11** [comment]
Hii @ashish-sumasoft, kindly resolve the below issues

on_search
- payments are missing for provider

on_init
- /message/order/cancellation_terms/1/cancellation_fee/amount/value must be string

on_confirm
- order.id should be a valid uuid
- descriptor.code should be RIDE_ENROUTE_PICKUP
- order.status is missing

on_status
- agent/rating must be string
- descriptor.code should be a generic enum as defined in developer guide
- fulfillments.type is missing

soft_on_cancel 
- agent/rating must be string
- /message/order/cancellation_terms/1/cancellation_fee/amount/value must be string
- vehicle.category should be valid
- CANCELLATION_CHARGES & CURRENT_FARE_CHARGE is missing in quote breakup

confirm_on_cancel
- agent/rating must be string
- /message/order/cancellation_terms/1/cancellation_fee/amount/value must be string
- CURRENT_FARE_CHARGE is missing in quote breakup
- vehicle.category should be valid
- status should be CANCELLED

on_cancel (flow 3)
- agent/rating must be string
- CURRENT_FARE_CHARGE is missing in quote breakup
- status should be CANCELLED

on_update (Flow 4)
- agent/rating must be string

Please refer the flow-ui tab on developer guide for latest examples

**Comment by kiranHdvi** [comment]
@sourabhsaini11 ,
The team has resolved the requested PR comments.
Please review once again whenever convenient.

Also, please let me know if we have any utility to verify TRV10 mobility logs.
So that we can do a first-pass check at our end.
Thanks in advance.

**Comment by sourabhsaini11** [comment]
Hii @ashish-sumasoft, kindly get these below issues resolved as well

on_search
- payments object should be part of providers

on_init
- fulfillments.id should be the same as mapped in on_select, init

on_status_PAYMENT_COLLECTED
- additional attribute currency at quote
- code at fulfillments.descriptor is invalid, should be one of the enum as defined on developer guide
- payments.params.transaction_id & payments.params.amount are required when payment status is 'PAID'

on_cancel
- SETTLEMENT_DETAILS tag group is missing in payments

common_issues
- ttl should be present wherever quote object is sent

**Comment by sourabhsaini11** [comment]
@kiranDev, TRV10 will be available soon, meanwhile you can refer to the https://github.com/ONDC-Official/log-validation-utility to test your logs locally

**Comment by kiranDev** [comment]
Hi @sourabhsaini11 , Thanks for reviewing PR. 
We will work on these but there is doubt about one change suggested.

1.  About comment : 
    https://github.com/ONDC-Official/verification-logs/pull/1294#issuecomment-1870082320:~:text=string%20at%20quote-,additional%20attribute%20amount%20at%20params%20in%20payments,-above%20issues%20are
    
    
    You have asked to remove **additional attribute amount at params in payments** from on_status protocol. 
    And in todays review comment you have asked to add it. In attribute UI it is indicated as non mandatory.
    
    Please let us know what needs to be done here .
    Thanks.

**Comment by sourabhsaini11** [comment]
@kiranDev below are the issues related to both TRV10 & IGM

Trv10
on_search
- payments should be part of providers object

on_status_DRIVER_AT_PICKUP
- code should be RIDE_ARRIVED_PICKUP, at fulfillments[0].state.descriptor

on_cancel
- person.image should be valid 


IGM
common_issues
- ttl is required in context

issue
- contact.phone must be a string
- The 'updated_at' of message/issue/issue_action/complainant_actions/index[0]/updated_at should be the same as or less than 'message/issue/updated_at'

issue (close)
- /message/issue must have required property 'updated_at'
- contact.phone must be a string
- short_desc is missing at complainant_actions
- complainant_action should be 'CLOSE' at complainant_actions[1]
- complainant_actions[1].updated_by.contact must have required property 'email'

on_issue
- incorrect time format for created_at & updated_at

on_issue_status
- incorrect time format for created_at & updated_at

grievance_issue
- contact.phone must be a string
- /message/issue/resolution must have required property 'short_desc' & 'action_triggered'
- The 'updated_at' of message/issue/issue_action/complainant_actions/index[1]/updated_at should be the same as or less than 'message/issue/update_at' in issue

grievance_on_issue
- respondent_actions[2] must have required property 'short_desc'
- incorrect time format for created_at & updated_at

grievance_on_issue_status
- respondent_actions[2] & respondent_actions[3] must have required property 'short_desc'
- resolution.refund_amount must be string
- incorrect time format for created_at & updated_at

grievance_issue (close) is missing

**Comment by kiranDev** [comment]
Hi @sourabhsaini11 ,
IGM issues resolving is in progress but we have resolved protocol APIs PR comments.
Please review the latest changes as per your convenience.

**Comment by mofahsan** [comment]
Hi @kiranDev 

please resolve the below finding in TRV 10

on_search
- extra attribute catalog.payments

**Comment by kiranHdvi** [comment]
Hello @mofahsan , @sourabhsaini11 ,

Thanks for reviewing the logs.
New Protocol logs are pushed, please take a look at them whenever convenient.
IGM log changes are also pushed, It will be great if you can review them alongside.
Thanks In Advance.

**Comment by sourabhsaini11** [comment]
Hii @ashish-sumasoft ,@kiranHdvi below are the issues related to latest logs.Kindly look into these as well

TRV:10
search
- gps must be precise upto 6 decimal places at stops.type 'START'

on_search
- gps must be precise upto 6 decimal places at stops.type 'START'


IGM
issue(close)
- rating is missing

on_issue
- 'created_at' should match issue's 'created_at'

on_issue_status
- Refund Amount for /on_issue_status should only be when action type is REFUND 
- 'created_at' should match issue's 'created_at'


Flow-2
common_issues
- bpp_id: Seller app's subscriber id should be bap_id in the context of /issue api when on_issue comes from logistics provider
- bpp_uri: Seller app's subscriber uri should be bap_uri in the context of /issue api when on_issue comes from logistics provider

issue
- Time of creation (created_at) and time of updation for /issue api should be the same

**Comment by rajat72588** [comment]
Screenshot 2024-01-23 165021

Hi @sourabhsaini11 @mofahsan 

Thank you for your reviewing the logs. I've reviewed the request body, and I can confirm that the "rating" field is present in the closed issue API request. If there's any confusion or specific details needed, please let me know, I have shared the screenshot of the same.

Thanks!

**Comment by sourabhsaini11** [comment]
Hii @rajat72588, below are the latest findings for the newly submitted logs.

search
- gps must be precise upto 6 decimal places (ex. "gps": "18.560823,73.806912")

on_search
- gps must be precise upto 6 decimal places (ex. "gps": "18.560823,73.806912")

status
- transaction_id should be same as sent in past calls
- timestamp on on_init call cannot be greater than or equal to timestamp sent in status call

on_status
- message_id doesn't match with the message_id sent in status call


IGM
Flow-1
issue(close)
- issue.rating must be equal to one of the allowed values (THUMBS-UP,THUMBS-DOWN)

on_issue_status
- respondent_info.type must be equal to one of the allowed values (INTERFACING-NP,TRANSACTION-COUNTERPARTY-NP,CASCADED-COUNTERPARTY-NP)

Grievance (Flow-2)
common_issues
when transaction is between the seller and logistics provider:
- bap_uri: Seller app's subscriber uri should be bap_uri not of buyer
- bpp_uri: logistics app's subscriber uri should be bpp_uri not of seller
- transaction_id should be the id from the logistics transaction. It should not be the id sent between buyer & seller ??

issue
- gros.gro_type & respondent_info.type must be equal to one of the allowed values (INTERFACING-NP,TRANSACTION-COUNTERPARTY-NP,CASCADED-COUNTERPARTY-NP)

**Comment by sourabhsaini11** [comment]
Hii @rajat72588, below are the new findings for the updated logs.

TRV:10
search
- gps must be precise upto 6 decimal places (ex. "gps": "18.560823,73.806912")

on_search
- gps must be precise upto 6 decimal places (ex. "gps": "18.560823,73.806912")

status
- transaction_id should be same as sent in past calls
- timestamp on on_init call cannot be greater than or equal to timestamp sent in status call

on_status
- message_id doesn't match with the message_id sent in status call


IGM
Flow-1
issue(close)
- issue.rating must be equal to one of the allowed values (THUMBS-UP,THUMBS-DOWN)

on_issue_status
- respondent_info.type must be equal to one of the allowed values (INTERFACING-NP,TRANSACTION-COUNTERPARTY-NP,CASCADED-COUNTERPARTY-NP)

Flow-2
issue
- gros.gro_type & respondent_info.type must be equal to one of the allowed values (INTERFACING-NP,TRANSACTION-COUNTERPARTY-NP,CASCADED-COUNTERPARTY-NP)

**Comment by ashish-sumasoft** [comment]
Hi @sourabhsaini11,
We have resolved the pull request comments. Could you please review them again?

**Comment by sourabhsaini11** [comment]
Hii @ashish-sumasoft, kindly get this issue fixed for below calls

on_select, on_init, on_confirm, on_status & on_cancel
- Total of breakup does not match with price.value at quote

**Comment by ashish-sumasoft** [comment]
Hi @sourabhsaini11,
We have a fixed price for the quote and updated logs. Can you please review it again?

**Comment by ashish-sumasoft** [comment]
Hi @sourabhsaini11,
As stated in the comments earlier, we have excluded extra titles from the breakdown of the quote. Could you please review this and give me your feedback?

**Comment by rajat7258** [comment]
Hi, @sourabhsaini11 @mofahsan 
I'd like to inquire about the IGM logs. Are there any remaining tasks or considerations for the IGM flow, or have the logs been cleared?

**Comment by sourabhsaini11** [comment]
Hii @ashish-sumasoft, below are the pending issues

common_issue
- 'DISTANCE_FARE' is missing in quote.breakup.

on_cancel
- additional title 'CURRENT_FARE_CHARGE' present at quote.breakup.

soft_on_cancel
- additional title 'CURRENT_FARE_CHARGE' present at quote.breakup.
- missing title 'CANCELLATION_CHARGES' at quote.breakup.

refer to examples or enums section at developer guide in case of any doubts or issues

Also, logs related to IGM are cleared

**Comment by kiranDev** [comment]
Hello @sourabhsaini11 , Can you please review the updated logs.

**Comment by sourabhsaini11** [comment]
Hii @ashish-sumasoft, kindly get these last set of issues related to tags fixed as well

on_select
- MIN_FARE_DISTANCE_KM, PICKUP_CHARGE missing in FARE_POLICY tag group in items

on_init
- change occurrences of 'DRIVER_EN_ROUTE_TO_PICKUP' to 'RIDE_ENROUTE_PICKUP'
- MIN_FARE_DISTANCE_KM, PICKUP_CHARGE missing in FARE_POLICY tag group in items

confirm
- MANDATORY_ARBITRATION, COURT_JURISDICTION & SETTLEMENT_AMOUNT are missing in SETTLEMENT_TERMS tag group

on_confirm
- created_at & updated_at are missing in message.order
- MANDATORY_ARBITRATION, COURT_JURISDICTION & SETTLEMENT_AMOUNT are missing in SETTLEMENT_TERMS tag group

on_update
- order.id is missing
- created_at & updated_at are missing in message.order
- MANDATORY_ARBITRATION, COURT_JURISDICTION & SETTLEMENT_AMOUNT are missing in SETTLEMENT_TERMS tag group

on_status (all)
- MANDATORY_ARBITRATION, COURT_JURISDICTION & SETTLEMENT_AMOUNT are missing in SETTLEMENT_TERMS tag group
- created_at & updated_at are missing in message.order
- change occurrences of 'COMPLETE' to 'COMPLETED'

on_status_RIDE_ENDED
- quote.price is different compared to what was send in previous call (on_update)

on_cancel
- change occurrences of 'DRIVER_EN_ROUTE_TO_PICKUP' to 'RIDE_ENROUTE_PICKUP'
- MANDATORY_ARBITRATION, COURT_JURISDICTION & SETTLEMENT_AMOUNT are missing in SETTLEMENT_TERMS tag group

on_cancel (soft)
- status should not be 'RIDE_CANCELLED' in fulfillments
- change occurrences of 'DRIVER_EN_ROUTE_TO_PICKUP' to 'RIDE_ENROUTE_PICKUP'
- MANDATORY_ARBITRATION, COURT_JURISDICTION & SETTLEMENT_AMOUNT are missing in SETTLEMENT_TERMS tag group

**Comment by ashish-sumasoft** [comment]
Hi @sourabhsaini11,

on_select:
PICKUP_CHARGE missing in FARE_POLICY tag group in items.
> Passengers are not charged for pickup. Would it be acceptable to set PICKUP_CHARGE to 0 in the tag group?

on_init:
PICKUP_CHARGE missing in FARE_POLICY tag group in items.
> Passengers are not charged for pickup. Would it be acceptable to set PICKUP_CHARGE to 0 in the tag group?

on_update:
order.id is missing.
> Upon reviewing the attributes_ui, we observed that the "order.id" field is not marked as mandatory.

on_status_RIDE_ENDED:
quote.price is different compared to what was sent in the previous call (on_update).
> Explaining that fares are dynamically updated based on the distance traveled when the passenger reaches the destination. This is why on_status is called with a PAID status after on_update.

**Comment by sourabhsaini11** [comment]
@ashish-sumasoft 
- PICKUP_CHARGE , yes 0 will be considered as a valid value.
- once order gets created at on_confirm call, it's mandatory to send order.id.

**Comment by ashish-sumasoft** [comment]
Hi @sourabhsaini11,
Could you please clarify the fulfillment status that should be set in the `on_cancel(soft)`?

**Comment by sourabhsaini11** [comment]
@ashish-sumasoft, you can send it as 'RIDE_ENROUTE_PICKUP' (as sent in previous on_confirm call) or any generic enum  as defined on developer contract (excluding 'RIDE_CANCELLED' & 'RIDE_ENDED').

**Comment by ashish-sumasoft** [comment]
Hi @sourabhsaini11,
Could you please take another look at the latest logs that were updated?

**Comment by ashish-sumasoft** [comment]
Hi @sourabhsaini11,
Are there any updates on the updated logs?

**Comment by 92shreyansh** [comment]
Transaction and IGM logs are approved. Merging logs subject to interoperability with other NPs

**Pull request merged**
