### PR TITLE
Verification logs for Seller and Buyer FIS:12 (GST Based Loan)

### PR DESCRIPTION
**Pull request by Nirdosh3312**
PR for tech logs of buyer and seller of Sequelstring for FIS:12 (Credit) for GST Based Loan

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Nirdosh3312 , kindly get the below issues cleared

common_issues
- instead of LOAN_INFO, INFO tag group should be present in items
- COOL_OFF_PERIOD & INSTALLMENT_AMOUNT should be in ISO 8601 duration format
- additional title present in quote.breakup (OTHER_UPFRONT_CHARGES, INSURANCE_CHARGES & NET_DISBURSED_AMOUNT)
- INTEREST_RATE_CONVERSION_CHARGE value should be 0 instead of "NA"

on_search
- code SETTLEMENT_AMOUNT is not part on_search, at payments
- instead of general-info, INFO tag group should be present in items
- tag group CONSENT_INFO is missing in items (on_search 3)

init 2, 3 & 4
- payments.id is missing

confirm
- payments.id is missing

**Comment by Nirdosh3312** [comment]
@sourabhsaini11 Kindly review the pull request.
I have resolved the issues that you have mentioned [here](https://github.com/ONDC-Official/verification-logs/pull/1477#issuecomment-1994435692) and have submitted the IBL tech logs again here 33b938c

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, kindly fix the below issue
on_search
- instead of general-info, INFO tag group should be present in items

**Comment by Nirdosh3312** [comment]
@sourabhsaini11 Sorry for the inconvenience. I have fixed the mentioned issue and resubmitted the logs here 81d5035
Kindly review the pull request

**Comment by sourabhsaini11** [comment]
@Nirdosh3312 , kindly get these issues cleared as well

common_issues
- quote.breakup should include following title PRINCIPAL, INTEREST, PROCESSING_FEE, INSURANCE_CHARGES, NET_DISBURSED_AMOUNT & OTHER_CHARGES

on_update (fulfillment)
- CONSENT_INFO tag group is missing

**Comment by Nirdosh3312** [comment]
@sourabhsaini11 I will have them resolved. Though I will request you to kindly provide me some clarification about this  
> * quote.breakup should include following title PRINCIPAL, INTEREST, PROCESSING_FEE, INSURANCE_CHARGES, NET_DISBURSED_AMOUNT & OTHER_CHARGES

As you have previously mentioned this 
> * additional title present in quote.breakup (OTHER_UPFRONT_CHARGES, INSURANCE_CHARGES & NET_DISBURSED_AMOUNT)

[here](https://github.com/ONDC-Official/verification-logs/pull/1477#issuecomment-1994435692) in the very first submission. I have removed them only after that. Please look into it and let me know if I need to have them in the logs or not

**Comment by sourabhsaini11** [comment]
@Nirdosh3312 , we have just updated our developer contract & these enums values will be part of invoice-based-loan flows.

**Comment by Nirdosh3312** [comment]
@sourabhsaini11 Kindly review the pull request. I have resolved the following issues 

> @Nirdosh3312 , kindly get these issues cleared as well
> 
> common_issues
> 
> * quote.breakup should include following title PRINCIPAL, INTEREST, PROCESSING_FEE, INSURANCE_CHARGES, NET_DISBURSED_AMOUNT & OTHER_CHARGES
> 
> on_update (fulfillment)
> 
> * CONSENT_INFO tag group is missing

mentioned [here](https://github.com/ONDC-Official/verification-logs/pull/1477#issuecomment-2006714947)

**Comment by 92shreyansh** [comment]
Approved Pramaan Logs

**Pull request merged**
