### PR TITLE
Miles & Kilometres - TRV11 Tech Logs For Verification

### PR DESCRIPTION
**Pull request by dunowgithub**
Submitting TRV11 Tech Logs For Verification

### CODE REVIEW

**Comment by dunowgithub** [comment]
@sourabhsaini11  - Submitting TRV11 Tech Logs For Verification. Kindly do the needful and let us know if you need anything else. Thanks!

**Comment by sourabhsaini11** [comment]
@dunowgithub, Logs needs to be submitted from pre-prod and not staging

**Comment by dunowgithub** [comment]
Pre-prod (DMRC) - I cannot give you cancel and on_cancel - Are you ok with
it? - I can give you search2, on_search2, init, on_init, confirm,
on_confirm, status & on_status

**Comment by dunowgithub** [comment]
> @dunowgithub, Logs needs to be submitted from pre-prod and not staging

@sourabhsaini11 - Pre-prod (DMRC) - I cannot give you cancel and on_cancel - Are you ok with it? - I can give you search2, on_search2, init, on_init, confirm, on_confirm, status & on_status

**Comment by 92shreyansh** [comment]
@dunowgithub buyer App are certified on the network and not for a specific Seller so even if DMRC is not allowing cancellation as a seller u need to test the flow with Pramaan or other metro seller i.e. kochi, chennai, kanpur etc.

**Comment by dunowgithub** [comment]
> @dunowgithub buyer App are certified on the network and not for a specific Seller so even if DMRC is not allowing cancellation as a seller u need to test the flow with Pramaan or other metro seller i.e. kochi, chennai, kanpur etc.

entire flow of search2, init, confirm, status , cancel (soft cancel) & pramaan report has been tested on staging -- @sourabhsaini11  wants from pre-prod. from where will i get it when DMRC doesnt support cancellation in preprod

**Comment by 92shreyansh** [comment]
Pramaan is available in pre-prod as well, also there are other metro as well in pre-prod not just DMRC

**Comment by 92shreyansh** [comment]
Its not @sourabhsaini11 that is asking for preprod this is a general process of tech validation please adhere to the same

**Comment by 92shreyansh** [comment]
Closing this PR please, feel free to re-open same or new PR once you have pre-prod logs generated

**Pull request closed without merging**
