### PR TITLE
TRV10 IGM LOGS

### PR DESCRIPTION
**Pull request by RaviV-Protean**

### CODE REVIEW

**Comment by RupalSingla** [comment]
issue:
issue.catagory cannot be mobiolity , it should be either item or fulfillment.
issue.sub-catagory  should be from the desierd enums.
created_at and updated_at cannot be different.

on_issue:
context.timestamp cannot be same for issue and on-issue 


There are 2 mandatory flows for igm : for fulfilment and item , pls submit both the flows

@RaviV-Protean

**Comment by RaviV-Protean** [comment]
@RupalSingla, 

As per your feedback we need to add fulfillment and item flows, but as per the sheet provided by ONDC it contains  Enums for fulfillment and not for items.

[Mobility - IGM Category and Sub Category 1.xlsx](https://github.com/user-attachments/files/16976354/Mobility.-.IGM.Category.and.Sub.Category.1.xlsx)

**Comment by RupalSingla** [comment]
The sheet shared is correct pls follow the enums that are shared in the same @RaviV-Protean

**Comment by RupalSingla** [comment]
Logs cleared forIGM  version 1.0.0 @RaviV-Protean

**Pull request merged**
