### PR TITLE
Paisabazaar

### PR DESCRIPTION
**Pull request by paisabazaartech**
Added logs for Flow 1, 2,3,4 and 6. Flow 5 which is part payment is supported by DMI hence couldn't submit logs

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
common_issues
- in LOAN_INFO tag group, COOL_OFF_PERIOD & INSTALLMENT_AMOUNT should be in ISO 8601 duration format

search
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

on_search
- descriptor.code should be GENERAL_INFO instead of General Information in items.tags

select_2
- status in item[0] should be 'APPROVED' at xinput.form_response

init
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format
- bank_code, bank_account_number & virtual_payment_address should have valid values, at payment.params
- status in item[0] should be 'SUCCESS' at xinput.form_response (init_2 & 3)

confirm
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format
- bank_code, bank_account_number & virtual_payment_address should have valid values, at payment.params
- status in item[0] should be 'SUCCESS' at xinput.form_response

flow 3 & 4
- unsolicited on_update call is missing

@paisabazaartech, kindly resolve the above issues & please provide logs from pre-prod environment

**Comment by paisabazaartech** [comment]
Added Logs for Flow 1, 3 and 5 on Pre-prod. Couldn't add logs for other flows as it's not working on preprod.
Fixes have been done as suggested. Some issues raised are for on_search, which we cannot change as we get this as webhook

**Comment by paisabazaartech** [comment]
Please note a few things:
1. We have been unable to add flow 2 due to an issue with DMI on pre-prod, therefore, we have not uploaded this flow
2. We are not receiving unsolicited on_update calls after payment from DMI, therefore, those calls are missing in flows 3 & 4

**Comment by sourabhsaini11** [comment]
@paisabazaartech , please get the below issues resolved

common_issues
- in LOAN_INFO tag group, COOL_OFF_PERIOD should be in ISO 8601 duration format

search
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

on_select 2
- form_response.status in item[0] should be 'APPROVED'

init
- millisecond should be precise upto 3 decimal places in timestamp (YYYY-MM-DDTHH:MN:SS.MSSZ)
- bank_code & bank_account_number should be present with valid values, at payment.params
- status in item[0] should be 'SUCCESS' at xinput.form_response (init_1)
- SETTLEMENT_WINDOW & SETTLEMENT_BASIS tags are missing in SETTLEMENT_TERMS tag-group

confirm
- millisecond should be precise upto 3 decimal places in timestamp (YYYY-MM-DDTHH:MN:SS.MSSZ)
- bank_code & bank_account_number should be present with valid values, at payment.params
- SETTLEMENT_WINDOW, SETTLEMENT_BASIS, MANDATORY_ARBITRATION & COURT_JURISDICTION tags are missing in SETTLEMENT_TERMS tag-group

flow-3
on_update (unsolicited)
- installments which had status as NOT-PAID should change to DEFERRED instead of PAID upon foreclosure

flow-5
on_update (unsolicited)
- status for INSTALLMENT (for month 2024-03-05T00:00:00.000Z) should be DEFERRED

**Comment by paisabazaartech** [comment]
Pls find the updated logs as discussed on call. We have re-shared the logs for FLOW 1.
Below is the reply for your comments:

common_issues
in LOAN_INFO tag group, COOL_OFF_PERIOD should be in ISO 8601 duration format--- **As discussed over the call with Shreyansh and Sumit, this is on lender's end (DMI) and hence cannot be fixed by Paisabazaar**

search
Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format---**This is done**

on_select 2
form_response.status in item[0] should be 'APPROVED'--- **As discussed over the call with Shreyansh and Sumit, this is on lender's end (DMI) and hence cannot be fixed by Paisabazaar**

init
millisecond should be precise upto 3 decimal places in timestamp (YYYY-MM-DDTHH:MN:SS.MSSZ)--- **This is done**
bank_code & bank_account_number should be present with valid values, at payment.params: **This is done**
status in item[0] should be 'SUCCESS' at xinput.form_response (init_1): **This is done**
SETTLEMENT_WINDOW & SETTLEMENT_BASIS tags are missing in SETTLEMENT_TERMS tag-group: **As discussed over the call with Shreyansh and Sumit, this is invalid since the init call does not expect these fields**

confirm
millisecond should be precise upto 3 decimal places in timestamp (YYYY-MM-DDTHH:MN:SS.MSSZ): **This is done**

bank_code & bank_account_number should be present with valid values, at payment.params: **This is done**
SETTLEMENT_WINDOW, SETTLEMENT_BASIS, MANDATORY_ARBITRATION & COURT_JURISDICTION tags are missing in SETTLEMENT_TERMS tag-group: **As discussed over the call with Shreyansh and Sumit, this is invalid since the confirm call does not expect these fields**

flow-3
on_update (unsolicited)
installments which had status as NOT-PAID should change to DEFERRED instead of PAID upon foreclosure: **As discussed over the call with Shreyansh and Sumit, this is on lender's end (DMI) and hence cannot be fixed by Paisabazaar**

flow-5
on_update (unsolicited)
status for INSTALLMENT (for month 2024-03-05T00:00:00.000Z) should be DEFERRED: **As discussed over the call with Shreyansh and Sumit, this is on lender's end (DMI) and hence cannot be fixed by Paisabazaar**

**Comment by sourabhsaini11** [comment]
init_1
- bank_code & bank_account_number should have valid values instead of empty

confirm
- id is missing in payments

@paisabazaartech, kindly get the above issues fixed.Also please provide updated logs for other flows as well.

**Comment by sourabhsaini11** [comment]
@paisabazaartech, please get the below issue fixed as well
common_issues
- value should be of type string for tag SETTLEMENT_AMOUNT, at payments

**Comment by sourabhsaini11** [comment]
@paisabazaartech, please get the below issues cleared
flow-1
select_2
- status in item[0] should be 'APPROVED' at xinput.form_response

flow-2
search
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

select_2
- status in item[0] should be 'APPROVED' at xinput.form_response

select 3
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

**Comment by paisabazaartech** [comment]
The flow 2 changes have been made as well. However, since DMI does not support flow 2, we are unable to upload the latest logs for this flow.

**Comment by paisabazaartech** [comment]
For issues regarding timestamp, we are not able to test it right now due to absence of lender, please provide exception as flow-1 has been corrected & format has been fixed.Post merge whenever the lender is available we will re update the logs with latest changes

**Comment by 92shreyansh** [comment]
Transaction logs conditionally approved

Also please raise a seprate PR for IGM logs

**Pull request merged**
