### PR TITLE
Easemytrip metro logs

### PR DESCRIPTION
**Pull request by naimishemt**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
search (station)
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format
- json structure not correct  (search station)

on_search
- provide valid values inplace of null values
- additional attributes Id, error, context.descriptor & context.gps
- SCHEDULED_INFO tag-group is missing
- collected_by is missing in payments

init
- json structure not correct
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

on_init
- provide valid values inplace of null values
- additional attributes Id, error, context.descriptor & context.gps
- fulfillments, cancellation_terms, billing & quote are not part of provider object
- SCHEDULED_INFO tag-group is missing

confirm
- json structure not correct
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

on_confirm
- provide valid values inplace of null values
- additional attributes Id, error, context.descriptor & context.gps
- id, collected_by, status & type are missing in payments
- SCHEDULED_INFO tag-group is missing
- cancellation_terms object is not correct 

status
- order_id should be valid as created on on_confirm call
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

on_status
- provide valid values inplace of null values
- additional attributes Id, error, context.descriptor & context.gps
- id, collected_by, status & type are missing in payments
- SCHEDULED_INFO tag-group is missing
- cancellation_terms object is not correct 

cancel
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

on_cancel
- provide valid values inplace of null values
- additional attributes Id, error, context.descriptor & context.gps
- fulfillments,cancellation, payments, status,  cancellation_terms, billing & quote are not part of provider object
- SCHEDULED_INFO tag-group is missing
- cancellation_terms object is not correct 

@naimishemt, kindly fix the above issues

**Comment by sourabhsaini11** [comment]
on_search
- Timestamp for /on_search api should be greater than timestamp of /search api
- fulfillments.type should be TRIP for on_search_2
- TRIP_DETAILS tag-group is missing in fulfillments, on_search_2
- start & end are not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format, at provider.time

on_init
- Timestamp for /on_init api should be greater than timestamp of /init api
- cancellation_terms should consist both mimetype & url
- start & end are not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format, at provider.time
- type is missing in fulfillments
- time is missing in items

on_confirm
- Timestamp for /on_confirm api should be greater than timestamp of /confirm api
- cancellation_terms should consist both mimetype & url
- type & locations are missing in fulfillments.stops
- time is missing in provider

on_status
- Timestamp for /on_status api should be greater than timestamp of /status api
- cancellation_terms should consist both mimetype & url
- type & locations are missing in fulfillments.stops
- time is missing in provider

on_cancel
- timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format
@naimishemt, please get the above issues fixed.Also, instead of pushing new files, update the existing calls only.

**Comment by naimishemt** [comment]
on_search

fulfillments.type should be TRIP for on_search_2. "We are getting TOUR instead of TRIP"
TRIP_DETAILS tag-group is missing in fulfillments, on_search_2-- We are not getting this node from seller

**Comment by 92shreyansh** [comment]
@naimishemt : Please provide only one set of logs in the PR not seprate V1 and V2 instead the logs need to be in various folders of Happy Flow, Cancellation Flow & Technical Cancellation refer the PR https://github.com/ONDC-Official/verification-logs/pull/1379/files

**Comment by 92shreyansh** [comment]
Also as discussed please confirm on updating the logs once the seller app is available

Please provide the date for IGM go live

**Comment by 92shreyansh** [comment]
@naimishemt please provide the details

**Comment by naimishemt** [comment]
We have followed the suggestion and pushed the files under Flow 1 & Flow 2 folder,

Also, we are targeting 15th May 2024 for IGM

**Pull request merged**
