### PR TITLE
Easemytrip metor logs

### PR DESCRIPTION
**Pull request by naimishemt**
[after_Cancel_on_status.json](https://github.com/ONDC-Official/verification-logs/files/14811640/after_Cancel_on_status.json)
[after_Cancel_on_status.json](https://github.com/ONDC-Official/verification-logs/files/14811641/after_Cancel_on_status.json)
[after_Cancel_on_status.json](https://github.com/ONDC-Official/verification-logs/files/14811643/after_Cancel_on_status.json)
[hard_cancel.json](https://github.com/ONDC-Official/verification-logs/files/14811644/hard_cancel.json)
[Hard_on_cancel.json](https://github.com/ONDC-Official/verification-logs/files/14811646/Hard_on_cancel.json)
[search_stagion.json](https://github.com/ONDC-Official/verification-logs/files/14811622/search_stagion.json)
[On_SearchMetroStation.json](https://github.com/ONDC-Official/verification-logs/files/14811623/On_SearchMetroStation.json)
[Search.json](https://github.com/ONDC-Official/verification-logs/files/14811624/Search.json)
[On_search.json](https://github.com/ONDC-Official/verification-logs/files/14811625/On_search.json)
[Init.json](https://github.com/ONDC-Official/verification-logs/files/14811626/Init.json)
[On_init.json](https://github.com/ONDC-Official/verification-logs/files/14811627/On_init.json)
[confirm.json](https://github.com/ONDC-Official/verification-logs/files/14811628/confirm.json)
[on_confirm.json](https://github.com/ONDC-Official/verification-logs/files/14811629/on_confirm.json)
[status.json](https://github.com/ONDC-Official/verification-logs/files/14811631/status.json)
[on_status.json](https://github.com/ONDC-Official/verification-logs/files/14811634/on_status.json)
[SoftCancel.json](https://github.com/ONDC-Official/verification-logs/files/14811635/SoftCancel.json)
[SOFT_on_CANCEL.json](https://github.com/ONDC-Official/verification-logs/files/14811637/SOFT_on_CANCEL.json)
[after_softcancel_status.json](https://github.com/ONDC-Official/verification-logs/files/14811639/after_softcancel_status.json)

### CODE REVIEW

**Comment by naimishemt** [comment]
Hi Team Please verify the logs

**Review by naimishemt — COMMENTED** [review]
[Hard_on_cancel.json](https://github.com/ONDC-Official/verification-logs/files/14811732/Hard_on_cancel.json)
[hard_cancel.json](https://github.com/ONDC-Official/verification-logs/files/14811733/hard_cancel.json)
[after_Cancel_on_status.json](https://github.com/ONDC-Official/verification-logs/files/14811734/after_Cancel_on_status.json)
[after_softcancel_status.json](https://github.com/ONDC-Official/verification-logs/files/14811735/after_softcancel_status.json)
[SOFT_on_CANCEL.json](https://github.com/ONDC-Official/verification-logs/files/14811736/SOFT_on_CANCEL.json)
[SoftCancel.json](https://github.com/ONDC-Official/verification-logs/files/14811737/SoftCancel.json)
[on_status.json](https://github.com/ONDC-Official/verification-logs/files/14811738/on_status.json)
[status.json](https://github.com/ONDC-Official/verification-logs/files/14811739/status.json)
[on_confirm.json](https://github.com/ONDC-Official/verification-logs/files/14811741/on_confirm.json)
[confirm.json](https://github.com/ONDC-Official/verification-logs/files/14811742/confirm.json)
[On_init.json](https://github.com/ONDC-Official/verification-logs/files/14811743/On_init.json)
[Init.json](https://github.com/ONDC-Official/verification-logs/files/14811744/Init.json)
[On_search.json](https://github.com/ONDC-Official/verification-logs/files/14811745/On_search.json)
[Search.json](https://github.com/ONDC-Official/verification-logs/files/14811746/Search.json)
[On_SearchMetroStation.json](https://github.com/ONDC-Official/verification-logs/files/14811747/On_SearchMetroStation.json)
[search_stagion.json](https://github.com/ONDC-Official/verification-logs/files/14811748/search_stagion.json)

**Comment by naimishemt** [comment]
kindly verify

**Review by naimishemt — COMMENTED** [review]
[Hard_on_cancel.json](https://github.com/ONDC-Official/verification-logs/files/14811833/Hard_on_cancel.json)
[hard_cancel.json](https://github.com/ONDC-Official/verification-logs/files/14811834/hard_cancel.json)
[after_Cancel_on_status.json](https://github.com/ONDC-Official/verification-logs/files/14811835/after_Cancel_on_status.json)
[after_softcancel_status.json](https://github.com/ONDC-Official/verification-logs/files/14811836/after_softcancel_status.json)
[SOFT_on_CANCEL.json](https://github.com/ONDC-Official/verification-logs/files/14811837/SOFT_on_CANCEL.json)
[SoftCancel.json](https://github.com/ONDC-Official/verification-logs/files/14811838/SoftCancel.json)
[on_status.json](https://github.com/ONDC-Official/verification-logs/files/14811839/on_status.json)
[status.json](https://github.com/ONDC-Official/verification-logs/files/14811840/status.json)
[on_confirm.json](https://github.com/ONDC-Official/verification-logs/files/14811841/on_confirm.json)
[confirm.json](https://github.com/ONDC-Official/verification-logs/files/14811842/confirm.json)
[On_init.json](https://github.com/ONDC-Official/verification-logs/files/14811843/On_init.json)
[Init.json](https://github.com/ONDC-Official/verification-logs/files/14811844/Init.json)
[On_search.json](https://github.com/ONDC-Official/verification-logs/files/14811845/On_search.json)
[Search.json](https://github.com/ONDC-Official/verification-logs/files/14811846/Search.json)
[On_SearchMetroStation.json](https://github.com/ONDC-Official/verification-logs/files/14811847/On_SearchMetroStation.json)
[search_stagion.json](https://github.com/ONDC-Official/verification-logs/files/14811848/search_stagion.json)

**Comment by 92shreyansh** [comment]
Please updated the PR refer other PRs of metro for netter understanding

**Pull request closed without merging**
