### PR TITLE
Indipe Business Loan Logs

### PR DESCRIPTION
**Pull request by lohanaman112**

### CODE REVIEW

**Comment by sourabhsainii** [comment]
@lohanaman112, below are the issues related to above logs.Kindly get these cleared
common_isses
- tasg GRO_DESIGNATION & GRO_ADDRESS are send additionally in CONTACT_INFO tag-group
- title OTHER_UPFRONT_CHARGES is send additionally in quote.breakup
- tag SETTLEMENT_AMOUNT value differs between /action & /on_action calls
- domain part of bap_uri should be equal to bap_id

on_search_1
- heading should contain 'Organization Information' instead of 'Personal Information'

on_search_3
- tags COOL_OFF_PERIOD, INSTALLMENT_AMOUNT, ANNUAL_PERCENTAGE_RATE, REPAYMENT_FREQUENCY & NUMBER_OF_INSTALLMENTS_OF_REPAYMENT are sent additionally in INFO tag-group

on_select
- tags COOL_OFF_PERIOD, INSTALLMENT_AMOUNT, ANNUAL_PERCENTAGE_RATE, REPAYMENT_FREQUENCY, PRINCIPAL, INTEREST, PROCESSING_FEE, OTHER_CHARGES, OFFER_VALIDITY are sent additionally in INFO tag-group

init
- payments.status should be NOT-PAID instead of NOT_PAID

on_init
- tags COOL_OFF_PERIOD, INSTALLMENT_AMOUNT, ANNUAL_PERCENTAGE_RATE, REPAYMENT_FREQUENCY, PRINCIPAL, INTEREST, PROCESSING_FEE, OTHER_CHARGES, OFFER_VALIDITY are sent additionally in INFO tag-group

confirm
- payments.status should be NOT-PAID instead of NOT_PAID

on_confirm
- tags COOL_OFF_PERIOD, INSTALLMENT_AMOUNT, ANNUAL_PERCENTAGE_RATE, REPAYMENT_FREQUENCY, PRINCIPAL, INTEREST, PROCESSING_FEE, OTHER_CHARGES, OFFER_VALIDITY are sent additionally in INFO tag-group

on_update
- tags COOL_OFF_PERIOD, INSTALLMENT_AMOUNT, ANNUAL_PERCENTAGE_RATE, REPAYMENT_FREQUENCY, PRINCIPAL, INTEREST, PROCESSING_FEE, OTHER_CHARGES, OFFER_VALIDITY are sent additionally in INFO tag-group

on_status
- tags COOL_OFF_PERIOD, INSTALLMENT_AMOUNT, ANNUAL_PERCENTAGE_RATE, REPAYMENT_FREQUENCY, PRINCIPAL, INTEREST, PROCESSING_FEE, OTHER_CHARGES, OFFER_VALIDITY are sent additionally in INFO tag-group

Also, please provide logs from preprod env only.staging logs won't be considered for review

**Comment by sourabhsaini11** [comment]
@lohanaman112, kindly get the below issues fixed
common_isses
- tags GRO_DESIGNATION & GRO_ADDRESS are send additionally in CONTACT_INFO tag-group
- title OTHER_UPFRONT_CHARGES is send additionally in quote.breakup
- domain part of bap_uri should be equal to bap_id

on_search_1
- heading should contain 'Organization Information' instead of 'Personal Information'

on_search_3
- additional tags INTEREST, COOL_OFF_PERIOD, INSTALLMENT_AMOUNT, ANNUAL_PERCENTAGE_RATE, REPAYMENT_FREQUENCY, NUMBER_OF_INSTALLMENTS_OF_REPAYMENT, PRINCIPAL present in INFO tag-group

on_init, on_confirm, on_update, on_status
- tags COOL_OFF_PERIOD, INSTALLMENT_AMOUNT, ANNUAL_PERCENTAGE_RATE, REPAYMENT_FREQUENCY, PRINCIPAL, INTEREST, PROCESSING_FEE, OTHER_CHARGES, OFFER_VALIDITY are sent additionally in INFO tag-group

**Comment by 92shreyansh** [comment]
Transaction Logs Approved for Buyer App

**Comment by 92shreyansh** [comment]
Please move the logs under FIS12/Indipe instead of logs Please see othe PL submission for refrence for final merge

**Comment by 92shreyansh** [comment]
Transaction Logs Approved for Buyer App

**Pull request merged**
