### PR TITLE
Yatri Logs commit

### PR DESCRIPTION
**Pull request by Ashwini1797**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Ashwini1797, kindly get the below issues fixed
common_issue
- tag SETTLEMENT_TYPE value is getting changed between /action & /on_action calls

search
- tag BUYER_FINDER_FEES_TYPE needs to be added in BUYER_FINDER_FEES tag-group

init
- remove tag-group SETTLEMENT_DETAILS from payments

confirm
- attributes bank_code & bank_account_number are missing in payments.params

**Comment by Ashwini1797** [comment]
Hie @sourabhsaini11 
We registered as a buyer, and the bank_code and bank_account_number attributes are optional parameters for buyers. Do I still need to include these attributes in the payments.params ?

**Comment by Ashwini1797** [comment]
Hiee @sourabhsaini11 @92shreyansh 
Please review the logs as we addressed the comments...

**Comment by Ashwini1797** [comment]
Hiee @sourabhsaini11 
We have tried to resolve all the listed issues. 
Please review the logs and let us know if there is anything else we need to change.

**Comment by sourabhsaini11** [comment]
@Ashwini1797, kindly get the below issues cleared as well

**Comment by Ashwini1797** [comment]
@sourabhsaini11 @92shreyansh 
We have tried to resolve all the listed issues.
Please review the logs and let us know if there is anything else we need to change.

**Comment by sourabhsaini11** [comment]
@Ashwini1797, kindly fix the below issues
common_issues
- virtual_payment_address is not required if SETTLEMENT_TYPE is NEFT

on_status
- message_id for /status and /on_status api should be same

**Comment by Ashwini1797** [comment]
@sourabhsaini11 
We have tried to resolve all the listed issues.
Please review the logs....

**Comment by sourabhsaini11** [comment]
@Ashwini1797, above issues are still persisting in the current logs.Kindly get them fixed
common_issue
- virtual_payment_address is not required if SETTLEMENT_TYPE is NEFT
on_status
- message_id for /status and /on_status api should be same

**Comment by Ashwini1797** [comment]
@sourabhsaini11 
We have tried to resolve all the listed issues.
Please review the logs and let us know if there is anything else we need to change.

**Comment by 92shreyansh** [comment]
Transaction Logs are Approved. 

Please also initate a PR for RSF for TRV11.

**Pull request merged**
