### PR TITLE
Personal Credit "Reference" Seller Application Logs

### PR DESCRIPTION
**Pull request by Avijeet-Blocsol**
Hello ONDC Team,

We are submitting logs for our FIS 12 Seller Reference Application. 
Looking forward to the feedback.

Regards,
Avijeet Singh Gill

### CODE REVIEW

**Comment by anuj-ondc** [comment]
@Avijeet-Blocsol, please fix below issues:

common issues:
  - In action calls, remove `error` object.


****FLow 1****: 
  - Transactional journey without consent handler is not part of protocol version 2.0.0.

  

****Flow 2*****:


search:
  - Remove `provider` reference.

on_select 1 
  - In items, id is different from previous calls.
  - In items, price value is missing.

on_select 3:
  - In context, timestamp should be greater than previous call.

on_status 1:
  - In quote, id different from previous call.
  - In xinput, remove head, index & form object.



on_init 1:
 - In context, timestamp should be greater than previous call.

 on_status 2:
  - In quote, id different from previous call.
  - In xinput, remove head, index & form object.

 on_status 3: 
  - In xinput, remove head, index & form object.

on_confirm:
  - Invalid fulfillment state.


Note: Account monitoring flow is missing(on_update, update, on_update calls).

Please refer here: https://ondc-official.github.io/ONDC-FIS-Specifications/?branch=release-FIS12-2.0.0&flowId=Personal+Loan&tabId=%23flow&callId=%23The+lender+shares+the+latest+loan+status+with+the+borrower.#The%20lender%20shares%20the%20latest%20loan%20status%20with%20the%20borrower.

update 3: 
  - Remove fulfillments.

on_update 3: (PRE_PART)
  - In context, timestamp should be greater than previous call.

 on_update 4: 
  - Order id is not macthing with previous call.
  - Item id is not macthing with previous call.




****Flow 3 (MISSED_EMI_PAYMENT)****:

  update:
   - Remove fulfillments.
   - Remove params

  on_update 3: 
  
- In payments, MISSED_EMI_PAYMENT -> url is missing.
- In payments, MISSED_EMI_PAYMENT -> range values are not matching with original missed payment object.
- status of original object needs to be DEFERRED.

****Flow 4 FORECLOSURE****: 
 
update 3:
  - Remove fulfillments.
  - Remove params

on_update 4: 
  - Order id is not macthing with previous call.
  - Item id is not macthing with previous call.

**Comment by Avijeet-Blocsol** [comment]
We have updated the logs as per the recommendations. Looking forward to feedback

**Comment by anuj-ondc** [comment]
@Avijeet-Blocsol, fix below findings:

Flow 2:
  - on_update 3: 
    - Two payment objects are found with FORECLOSURE, please correct.

 PRE_PART flow is missing, please submit.
 
Note: In the current logs, there are three flows for FORECLOSURE & 2 flows for loan journey. Please submit only the relevant one.

**Comment by Avijeet-Blocsol** [comment]
We have updated flow 2 with the correct prepayment logs. Looking forward to the closure. The flows now contain 2 Normal Flow, 1 Prepayment Flow, 1 Missed Emi Flow, 2 Foreclosure flows

**Comment by anuj-ondc** [comment]
@Avijeet-Blocsol, The transactional logs are approved, PR will be merged soon.

**Pull request merged**
