### PR TITLE
TRV10 - PreProd - Quick Ride - Logs for all flows

### PR DESCRIPTION
**Pull request by shobhanaquickride**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@shobhanaquickride, logs are to be reviewed under 2.0.0 or 2.0.1?

**Comment by sourabhsaini11** [comment]
@shobhanaquickride, kindly get the below issues fixed
common_issues
- instructions is missing in fulfillments.stops
- valid breakup title are BASE_FARE & DISTANCE_FARE only, remove additional titles from quote
- either remove empty tags from fulfillments or include ROUTE_INFO tag-group as well (/select onwards)
- tags should contain FARE_POLICY & INFO tag-group at items (/select onwards)
- missing tags in SETTLEMENT_TERMS tag-group
- provide.id should be a valid id instead of 'Quick Ride' (Warning)

on_search
- remove empty tags from items

-  provide."id": "Quick Ride"? 

on_init
- payment_ids is missing in items
- id is missing in payments

confirm
- billing in missing
- id is missing in payments

on_confirm
- payment_ids is missing in items
- status & valid_to is missing in stops.authorization
- id is missing in payments

on_update
- created_at should match /on_confirm created_at
- vehicle is missing in fulfillments
- payment_ids is missing in items
- status & valid_to is missing in stops.authorization
- id, params, type are missing in payments
- message_id should be different between unsolicated on_update calls 

on_status
- payment_ids is missing in items
- make is missing in fulfillments.vehicle
- status & valid_to is missing in stops.authorization
- id, params, type & tags are missing in payments
- created_at should match /on_confirm created_at
- cancellation_fee value changed between /on_confirm & /on_status call in cancellation_terms

on_cancel
- payment_ids is missing in items
- make is missing in fulfillments.vehicle
- status & valid_to is missing in stops.authorization
- id, params, type & tags are missing in payments
- created_at should match /on_confirm created_at
- cancellation_fee value changed between /on_confirm & /on_status call in cancellation_terms
- CANCELLATION_CHARGES & REFUND are missing in quote.breakup

**Comment by shobhanaquickride** [comment]
All comments are fixed except for the following:

a) missing tags in SETTLEMENT_TERMS tag-group: All settlement terms which come from the buyer app will be relayed as-is in the subsequent responses since buyer app will decide how it needs to receive the settlement

b) billing in missing: 
id is missing in payments:
Can't fix since this comes from BAP (Pramaan in our case from where logs are generated)

c) status & valid_to is missing in stops.authorization: Mobility specification doesn't explain this: https://ondc-official.github.io/mobility-specification/#attribute What are the valid values for status? As per one of the examples, updated to set the status as "CLAIMED" after the ride is started. Before that, the status is not set. What should it be set to?

**Comment by sourabhsaini11** [comment]
@shobhanaquickride, please fix the below issues as well
common_issues
- additional attribute model sent in fulfillments.vehicle
- additional title's GST_ON_RIDE_FARE, SERVICE_FEES & GST_ON_SERVICE_FEES present in quote.breakup
- tags COURT_JURISDICTION, MANDATORY_ARBITRATION, SETTLEMENT_TYPE, SETTLEMENT_BASIS & SETTLEMENT_WINDOW are missing in SETTLEMENT_TERMS tag-group. Following tags needs to be defined by BPP (Please refer TLC-UI for more info)
- price/percentage/value should be precise upto 2 decimal places
- tag WAYPOINTS is missing in ROUTE_INFO tag-group
- tag NIGHT_SHIFT_START_TIME & NIGHT_SHIFT_END_TIME should be in HH:MM:SS format
- short_desc is missing in stops.instructions(/on_action calls only)

on_confirm
- created_at & updated_at should be either equal or less than context.timestamp

on_update
- params is missing in payments
- tags are incomplete in payments
- vehicle is missing
- status is missing in stops.authorization (valid status values are CLAIMED/UNCLAIMED)

on_status
- state should be RIDE_ENROUTE_PICKUP instead of RIDE_ASSIGNED as on_status is being called post on_update_driver_enroute_pickup
- params & tags are missing in payments

- on_status api capturing payment status as PAID is missing
- post on_update_driver_assigned, on_status should be used instead of on_update for following calls:- on_update_driver_enroute_pickup, on_update_driver_arrived_pickup, on_update_ride_completed & on_update_ride_started

Flow-2
on_cancel
- CANCELLATION_CHARGES value mismatch between soft & confirm on_cancel
- params & tags are missing in payments
- status is missing in stops.authorization

Flow-3
- params & tags are missing in payments
- status is missing in stops.authorization

**Comment by shobhanaquickride** [comment]
All comments are fixed except for the following:
a) additional attribute model sent in fulfillments.vehicle: Vehicle specification given in the Flow UI shows model in fulfillments.vehicle:
          "vehicle": {
            "category": "AUTO_RICKSHAW",
            "make": "Bajaj",
            "model": "Compact RE",
            "registration": "KA-01-AD-9876"
          }

b) additional title's GST_ON_RIDE_FARE, SERVICE_FEES & GST_ON_SERVICE_FEES present in quote.breakup: As mentioned earlier, ONDC should not restrict the breakup elements to only BASE_FARE and DISTANCE_FARE since there are other valid elements like toll charges, parking charges, GST, etc. These must be allowed

c) tag WAYPOINTS is missing in ROUTE_INFO tag-group: WAYPOINTS should not be made mandatory. If there is no specific way point for the route, this will not be set. Adding the lat-lng points on the route as waypoints is not appropriate since there will be hundreds of lat-lng points on the route. WAYPOINTS should be added only if the user has specified any stops in between the start and end loctaions. The route path polyline should be used by the BAPs to display the route.

d) tag NIGHT_SHIFT_START_TIME & NIGHT_SHIFT_END_TIME should be in HH:MM:SS format: These are removed since we do not use these. These make sense only for autos; they don't make sense for cab rides

e) short_desc is missing in stops.instructions(/on_action calls only): Why is this a mandatory field? For start and end points, we have already set the start and end addresses as the long_desc. What can be as short_desc?

**Comment by sourabhsaini11** [comment]
@shobhanaquickride, please fix below issues as well
common_issue
- remove empty arrays/objects from the payload (i.e. locations)
- additional attribute model sent in fulfillments.vehicle (model should be sent when driver has been assigned)
- virtual_payment_address is not required if SETTLEMENT_TYPE is neft
- tags NIGHT_CHARGE_MULTIPLIER, NIGHT_SHIFT_START_TIME, NIGHT_SHIFT_END_TIME are missing in FARE_POLICY tag-group
- additional title's GST_ON_RIDE_FARE, SERVICE_FEES & GST_ON_SERVICE_FEES present in quote.breakup

on_confirm
- created_at & updated_at value should be same
- authorization shouldn't be present if driver is un-assigned

on_status_driver_enroute_pickup
- updated_at should not match past call's updated_at

Flow-2
soft_on_cancel
- fulfillments.state shouldn't be RIDE_CANCELLED

Flow-3
on_status_driver_cancelled.json
- Ride cancellation by driver must be done through /on_cancel action instead of /on_status

IGM
on_issue
- 'created_at' should match issue's 'created_at'
- org.name value must be in bpp_id::domain format

on_issue_status
- 'created_at' should match issue's 'created_at'
- org.name value must be in bpp_id::domain format

**Comment by shobhanaquickride** [comment]
All comments are fixed except for the followong:
a) virtual_payment_address is not required if SETTLEMENT_TYPE is neft: 
This is sent from the BAP (Pramaan in this case) and the same is retained in all calls

**Comment by sourabhsaini11** [comment]
@shobhanaquickride, please fix below issues
common_issue
- id is sent additionally in stops.location

on_search
- locations should also be sent if tems.location_ids are present

on_status_driver_arrived_pickup
- updated_at can't be greater than context.timestamp

on_status_ride_completed
- quote.breakup price mismatch between current & past call

Flow-4
on_status_fare_paid_order_completed
- quote.breakup price mismatch between current & past call

IGM
### `issue_CLOSE` Errors:
1. **Missing Properties**:
   - The `/message/issue` must include the required properties `status` and `rating`.
   - The `/message/issue/issue_actions` must include the required property 
   - The `context.action` should be `issue`.
   - The phone number for the `/issue_close` API is not in the valid range.

### `on_issue` Errors:
   - The phone number for the `/issue_close` API is not in the valid range.

### `on_issue_status` Errors:
   - The phone number for the `/on_issue_status` API is not in the valid range.

**Comment by shobhanaquickride** [comment]
All comments have been fixed and testing with Redbus is completed

**Comment by 92shreyansh** [comment]
Transaction & IGM logs are Approved

**Pull request merged**
