### PR TITLE
TRV10

### PR DESCRIPTION
**Pull request by Sanskargh7**

### CODE REVIEW

**Comment by Sanskargh7** [comment]
Please consider this logs for TRV10 on demand Ride hailing, do let us know if there are any issues

**Comment by sourabhsaini11** [comment]
@Sanskargh7, please get the below issues fixed
common_issues
- gps coordinates must be precise upto 6 places
- quote.price must be precise
- value must be string, at items.price & quote.price
- tag WAITING_CHARGE_PER_MIN value must be of type string
- either of amount or percentage should be present in cancellation_fee, not both

on_search
- attribute variant sent additionally in vehicle
- payments should be an array
- SETTLEMENT_TERMS tag list is in-complete

on_select
- tag-group ROUTE_INFO is missing in fulfillments
- attribute variant sent additionally in vehicle

init
- bpp_id & bpp_uri are missing
- billing details are missing
- attribute variant sent additionally in vehicle
- attribute type sent additionally in fulfillments
- only id is needed in items for /init call
- quote details are not required for /init call

on_init
- bpp_id & bpp_uri are missing
- billing details are missing
- tag-group ROUTE_INFO is missing in fulfillments
- attribute variant sent additionally in vehicle
- payments details are missing

confirm
- billing details are missing
- attribute variant sent additionally in vehicle
- attribute type sent additionally in fulfillments
- only id is needed in items for /init call
- payments details are missing
- quote details are not required for /init call

on_confirm
- attribute variant sent additionally in vehicle
- tag-group ROUTE_INFO is missing in fulfillments
- id is sent additionally in fulfillments.person
- payments details are missing

on_status
- bpp_id & bpp_uri are missing
- attribute variant sent additionally in vehicle
- tag-group ROUTE_INFO is missing in fulfillments
- id is sent additionally in fulfillments.person
- payments details are missing
- quote.price must be same as sent in past calls (on_status_end_ride only)

Flow-2
cancel(soft)
- cancellation_reason_id is missing

on_cancel
- address is sent additionally in stops.location
- attribute variant sent additionally in vehicle
- tag WAITING_CHARGE_PER_MIN(confirm cancel) or NIGHT_SHIFT_END_TIME(soft cancel) value must be of type string
- payments details are missing(confirm cancel)
- payments tags are missing(soft cancel)
- quote.breakup is missing(soft cancel)

Flow-3
on_cancel
- attribute variant sent additionally in vehicle
- tag-group ROUTE_INFO is missing in fulfillments
- id is sent additionally in fulfillments.person
- payments details are missing

**Comment by Sanskargh7** [comment]
fix bugs

**Comment by sourabhsaini11** [comment]
@Sanskargh7, kindly get the below issues fixed
common_issues
- gps coordinates must be precise upto 6 places
- attribute variant is sent additionally in vehicle
- additional title PICKUP_CHARGE & TIME_CHARGE present in quote.breakup
- seconds are missing in tags NIGHT_SHIFT_START_TIME & NIGHT_SHIFT_END_TIME at FARE_POLICY tag-group
- /on_action call timestamp should be greater than timestamp of /action calls

on_search
- attribute offered_value is not required in items.price
- tags are not required in /on_search
- payments are missing

on_select
- incorrect tags present in ROUTE_INFO tag-group
- value must be string, at items.price
- tag WAITING_CHARGE_PER_MIN value must be of type string

init
- attribute type sent additionally in fulfillments

on_init
- incorrect tags present in ROUTE_INFO tag-group
- customer details are missing in fulfillments
- payment_ids is missing in items
- id is missing in payments
- tag SETTLEMENT_TYPE & SETTLEMENT_AMOUNT are missing in SETTLEMENT_TERMS tag-group

confirm
- attribute type sent additionally in fulfillments
- payments are missing

on_confirm
- created_at & updated_at timestamp can't be greater than the created_at.timestamp
- id is sent additionally in fulfillments.person
- incorrect tags present in ROUTE_INFO tag-group
- value must be string, at items.price
- payment_ids is missing in items
- tag WAITING_CHARGE_PER_MIN value must be of type string
- tag SETTLEMENT_TYPE & SETTLEMENT_AMOUNT are missing in SETTLEMENT_TERMS tag-group

on_status
- bpp_id & bpp_uri are missing (driver_pickup only)
- created_at & updated_at timestamp can't be greater than the created_at.timestamp
- id is sent additionally in fulfillments.person
- incorrect tags present in ROUTE_INFO tag-group
- value must be string, at items.price
- payment_ids is missing in items
- tag WAITING_CHARGE_PER_MIN value must be of type string
- tag SETTLEMENT_TYPE & SETTLEMENT_AMOUNT are missing in SETTLEMENT_TERMS tag-group

on_cancel
- breakup is missing in quote(soft cancel only)
- value must be string, at quote.price
- created_at & updated_at timestamp can't be greater than the created_at.timestamp
- value must be string, at items.price
- payment_ids is missing in items
- tag WAITING_CHARGE_PER_MIN value must be of type string
- tag SETTLEMENT_TYPE & SETTLEMENT_AMOUNT are missing in SETTLEMENT_TERMS tag-group

**Comment by Sanskargh7** [comment]
> @Sanskargh7, please get the below issues fixed common_issues
> 
> * gps coordinates must be precise upto 6 places
> * quote.price must be precise
> * value must be string, at items.price & quote.price
> * tag WAITING_CHARGE_PER_MIN value must be of type string
> * either of amount or percentage should be present in cancellation_fee, not both
> 
> on_search
> 
> * attribute variant sent additionally in vehicle
> * payments should be an array
> * SETTLEMENT_TERMS tag list is in-complete
> 
> on_select
> 
> * tag-group ROUTE_INFO is missing in fulfillments
> * attribute variant sent additionally in vehicle
> 
> init
> 
> * bpp_id & bpp_uri are missing
> * billing details are missing
> * attribute variant sent additionally in vehicle
> * attribute type sent additionally in fulfillments
> * only id is needed in items for /init call
> * quote details are not required for /init call
> 
> on_init
> 
> * bpp_id & bpp_uri are missing
> * billing details are missing
> * tag-group ROUTE_INFO is missing in fulfillments
> * attribute variant sent additionally in vehicle
> * payments details are missing
> 
> confirm
> 
> * billing details are missing
> * attribute variant sent additionally in vehicle
> * attribute type sent additionally in fulfillments
> * only id is needed in items for /init call
> * payments details are missing
> * quote details are not required for /init call
> 
> on_confirm
> 
> * attribute variant sent additionally in vehicle
> * tag-group ROUTE_INFO is missing in fulfillments
> * id is sent additionally in fulfillments.person
> * payments details are missing
> 
> on_status
> 
> * bpp_id & bpp_uri are missing
> * attribute variant sent additionally in vehicle
> * tag-group ROUTE_INFO is missing in fulfillments
> * id is sent additionally in fulfillments.person
> * payments details are missing
> * quote.price must be same as sent in past calls (on_status_end_ride only)
> 
> Flow-2 cancel(soft)
> 
> * cancellation_reason_id is missing
> 
> on_cancel
> 
> * address is sent additionally in stops.location
> * attribute variant sent additionally in vehicle
> * tag WAITING_CHARGE_PER_MIN(confirm cancel) or NIGHT_SHIFT_END_TIME(soft cancel) value must be of type string
> * payments details are missing(confirm cancel)
> * payments tags are missing(soft cancel)
> * quote.breakup is missing(soft cancel)
> 
> Flow-3 on_cancel
> 
> * attribute variant sent additionally in vehicle
> * tag-group ROUTE_INFO is missing in fulfillments
> * id is sent additionally in fulfillments.person
> * payments details are missing

@sourabhsaini11 resolved

**Comment by sourabhsaini11** [comment]
@Sanskargh7, kindly get the below issues fixed as well
common_issues
- attribute variant is sent additionally in vehicle
- seconds are missing in tags NIGHT_SHIFT_START_TIME & NIGHT_SHIFT_END_TIME at FARE_POLICY tag-group
- title PICKUP_CHARGE & TIME_CHARGE are sent additionally in quote.breakup
- incorrect tags present in ROUTE_INFO, should consist tags ENCODED_POLYLINE & WAYPOINTS instead

search
- attribute payment should be present instead of payments for /search
- tags SETTLEMENT_WINDOW, SETTLEMENT_BASIS, SETTLEMENT_TYPE, MANDATORY_ARBITRATION, COURT_JURISDICTION present in SETTLEMENT_TERMS tag-group are not part of /search

on_search
- attribute offered_value is sent additionally in items.price
- tag-group FARE_POLICY is not part of /on_search

init
- type is send additionally in fulfillments
- SETTLEMENT_AMOUNT value should be 0.8 if collector is seller app

on_init
- payment_ids is missing in items
- id is missing in payments

confirm
- type is send additionally in fulfillments
- id is missing in payments
- SETTLEMENT_AMOUNT value should be 0.8 if collector is seller app

on_confirm
- id is sent additionally in fulfillments.person
- payment_ids is missing in items
- id is missing in payments

on_status
- message_id & transaction_id are same to what was sent in /on_confirm

on_confirm_cancel
- payload mistmatch (provided payload is of /on_confirm)

**Comment by sourabhsaini11** [comment]
@Sanskargh7, please get the below issues fixed as well
common_issues
- incorrect tags ROUTE_DISTANCE & ROUTE_TIME present in ROUTE_INFO, should consist tags ENCODED_POLYLINE & WAYPOINTS instead
- tag SETTLEMENT_AMOUNT value should be 0.8 if collector is BPP
- attribute variant sent additionally in vehicle

on_search
- tag-group INFO is send additionally in items

on_init
- additional attribute payments_ids send in fulfillments
- payment_ids is missing in items
- tags value are not similar to what was sent in past call, FARE_POLICY tag-group

on_confirm
- seconds are missing in tags NIGHT_SHIFT_START_TIME & NIGHT_SHIFT_END_TIME at FARE_POLICY tag-group
- INFO tag-group is missing
- title WAITING_FARE & PICKUP_CHARGE are send additionally in quote.breakup
- tag SETTLEMENT_AMOUNT is missing

on_status
- incorrect payloads, payload should be of /on_status call

Flow-2
on_cancel
- breakup is missing in quote(soft on_cancel)
- action should be on_cancel(confirm on_cancel)
- cancellation_terms are not same between soft & confirm on_cancel calls
- fulfillments details are changed between soft & confirm on_cancel calls
- seconds are missing in tags NIGHT_SHIFT_START_TIME & NIGHT_SHIFT_END_TIME at FARE_POLICY tag-group
- INFO tag-group is missing
- payment_ids is missing in items

Flow-3
on_cancel
- title WAITING_FARE & PICKUP_CHARGE are send additionally in quote.breakup
- seconds are missing in tags NIGHT_SHIFT_START_TIME & NIGHT_SHIFT_END_TIME at FARE_POLICY tag-group
- INFO tag-group is missing
- id is missing in payments
- payment_ids is missing in items

**Comment by sourabhsaini11** [comment]
@Sanskargh7, please get the below issues fixed as well
common_issues
- BASE_FARE price should be 30 instead of 10 as MIN_FARE value in FARE_POLICY is 30
- incorrect tags ROUTE_DISTANCE & ROUTE_TIME present in ROUTE_INFO, should consist tags ENCODED_POLYLINE & WAYPOINTS instead

on_init
- tag MIN_FARE is changed from what was sent in /on_select
- INFO tag-group is missing

confirm
- attribute variant sent additionally in vehicle

on_confirm
- attribute variant sent additionally in vehicle
- INFO tag-group should be present instead of ROUTE_INFO at items

on_status
- payload should be of on_status instead of /on_confirm
- id is send additionally in fulfillments.person
- SETTLEMENT_AMOUNT should be 0.8
- NIGHT_SHIFT_START_TIME & NIGHT_SHIFT_END_TIME are missing seconds

Flow-2
on_cancel
- id is send additionally in fulfillments.person
- attribute variant sent additionally in vehicle
- NIGHT_SHIFT_START_TIME & NIGHT_SHIFT_END_TIME are missing seconds
- tag SETTLEMENT_AMOUNT is missing in on_cancel(Soft cancel)
- SETTLEMENT_AMOUNT should be 0.8(Confirm cancel)

FLow-3
on_cancel
- action should be of on_cancel
- id is send additionally in fulfillments.person
- incorrect tags ROUTE_DISTANCE & ROUTE_TIME present in ROUTE_INFO
- SETTLEMENT_AMOUNT should be 0.8
- attribute variant sent additionally in vehicle

**Comment by sourabhsaini11** [comment]
@Sanskargh7, please get the below issues fixed
common_issue
- /action & /on_action calls timestamp shouldn't be same
- updated_at should match to context.timestamp

on_confirm
- created_at & context.timestamp should be same

on_status_driver_pickup
- context.timestamp should be greater than on_confirm timestamp

**Comment by sourabhsaini11** [comment]
@Sanskargh7, kindly get the below issues fixed as well
common_issue
- milliseconds should be precise upto 3 places only in context.timestamp, created_at & updated_at

on_init
- payment_ids should be used instead of payments_ids at items

on_cancel
- stops.end are not part of /on_cancel call. Additionally attribute time should also be present in stops.start

**Comment by sourabhsaini11** [comment]
@Sanskargh7, kindly fix the below issues
confirm
- SETTLEMENT_BASIS value should be DELIVERY

on_status_start_ride 
- transaction_id mismatch with past calls

**Comment by 92shreyansh** [comment]
Transaction Logs are Approved

**Pull request merged**
