### PR TITLE
Log Submission for Invoicepe Personal Credit Loan Journey

### PR DESCRIPTION
**Pull request by Avijeet-Blocsol**
Hello ONDC Team,

We are submitting logs for InvoicePe Personal Loan Journey in preprod environment for Flow 1 to Flow 7. We have attached Pramaan Test reports with each flow showcasing full compliance with the protocol. 

Looking forward to your review and subsequent response on this pull request.

Regards

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@Avijeet-Blocsol, kindly get the below issues fixed
init
- payments.id should be present in init2 & init 3 only.

on_confirm
- descriptor.code should be SANCTIONED at fulfillments

update
- order.id should refer to the id created on order creation in /on_confirm instead of referring to item.id
- corresponding on_update call having similar message_id (0cfbb523-42d8-4e92-8ef0-2814c7edfb65) is missing.

Either of Flow-4 or Flow-5 should contain Pre-part flow instead of both containing FORECLOSURE flow

IGM
on_issue
- org.name should be with the bpp_id:domain at respondent_actions

on_issue_status
- org.name should be with the bpp_id:domain at respondent_actions

Also please remove additional .html, .md files & additional folders

**Comment by Avijeet-Blocsol** [comment]
Thanks for the feedback. Just a few points from our side:

1. We have had a discussion with Pramaan guys regarding the last on_update call (subsequent to our update call confirming the loan monitoring consent success). They have told us that as per the protocol, the lender can update us regarding loan disbursement either via an on_update call or on on_status call. When testing and generating logs via the pramaan tool, we get the DISBURSED or SANTIONED state via on_status calls and that is why we have 5 on_status calls for each flow instead of 3 (aadhar kyc, repayment setup and loan agreement).

2. The on_confirm descriptor is once again something which is not in our control as we get this value from Pramaan tool. Also, as per our discussion with lenders, the Loan is sanctioned when the customer provides loan monitoring consent and the Loan is marked as disbursed when the credit finally lands to the customer's bank account. With this, the fulfillment state in on_confirm makes sense as it cannot be SANCTIONED until loan monitoring consent is not provided by the customer. Please correct us in case we have missed something here.

3. As per Pramaan Tool, Flow 2 captures the part-prepayment flow. Flow 4 is for Loan Foreclosure in cool off period and Flow 5 is for Loan Forecloure outside of cool off period. Please find the attached screenshot for reference:

image

We will make the rest of the recommended changes and update regarding the same as soon as possible

**Comment by Avijeet-Blocsol** [comment]
4. We will remove the .md files. The HTML files are pramaan reports which will be required for OPS validations. Should we remove them too?

**Comment by Avijeet-Blocsol** [comment]
We have made the commits and changed the files as per the recommendations.

**Comment by Avijeet-Blocsol** [comment]
Hi, looking forward to your reply to the beforementioned points and the updated log submission.

**Comment by sourabhsaini11** [comment]
@Avijeet-Blocsol, kindly get the below issues cleared as well
on_issue
- org.name value should be bpp_id:domain at respondent_actions

on_issue_status
- 'RESOLVED' respondent_action index is missing in respondent_actions array
- org.name value should be bpp_id:domain at respondent_actions & resolution_provider

issue(close)
- 'CLOSE' complainant_action index is missing in complainant_actions array

**Comment by Avijeet-Blocsol** [comment]
Hello Sourabh,

We have included the necessary change that we could do on our end (Regarding your point 3) and updated the IGM Logs. Please check and verify. 

Looking forward to your response.

**Comment by Avijeet-Blocsol** [comment]
Hello Team,

Looking forward to an update on this from your side. We have made all the necessary changes possible from our side.

**Comment by sourabhsaini11** [comment]
@Avijeet-Blocsol, please fix the below issues
issue
- org.name should be bap_id::domain (i.e. ondc.invoicepe.in::ONDC:FIS12) at complainant_actions

issue(close)
- org.name should be bap_id::domain (i.e. ondc.invoicepe.in::ONDC:FIS12) at complainant_actions
- complainant_actions is missing index containing 'OPEN' complainant_action

**Comment by Avijeet-Blocsol** [comment]
Hello Sourabh,

We have made the necessary changes to IGM flows and verified the same. We have also attached a Pramaan Report along with as well.

Looking forward to your response.

**Comment by 92shreyansh** [comment]
Transaction Logs are cleared, IGM logs are cleared with open items from counter party
Approving the logs.

**Pull request merged**
