### PR TITLE
Added rapido IGM logs

### PR DESCRIPTION
**Pull request by ReddyVineetha**

### CODE REVIEW

**Comment by Hemanth-Rapido** [comment]
@amitsinha07 Addressed your issues. Kindly review this new PR: https://github.com/ONDC-Official/verification-logs/pull/1762.

**Comment by amitsinha07** [comment]
Hii @Hemanth-Rapido 

Feedbacks for #1762 

1. **issue_CLOSE:**
   - `/message/issue must have required property 'rating'`

2. **on_issue:**
   - `context timestamp should be greater than or equal to updated_at in on_issue`

3. **issue_status:**
   - `transaction ID mismatch in /issue and /issue_status`

4. **on_issue_status:**
   - `Message ID mismatch in /issue_status and /on_issue_status`

**Comment by Hemanth-Rapido** [comment]
@amitsinha07 Addressed your issues. Kindly review this new PR: https://github.com/ONDC-Official/verification-logs/pull/1762.

**Comment by amitsinha07** [comment]
@Hemanth-Rapido 

1. **issue_close**
 - complainant_actions[0]/updated_at is not matching with issue's complainant_actions[0]/updated_at

**Comment by ReddyVineetha** [comment]
> @Hemanth-Rapido
> 
> 1. **issue_close**
> 
> * complainant_actions[0]/updated_at is not matching with issue's complainant_actions[0]/updated_at

This is addressed, please check

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 for IGM
@ReddyVineetha

**Pull request merged**
