### PR TITLE
Added flow2, flow3, flow4, flow5, flow6 and IGM logs

### PR DESCRIPTION
**Pull request by ankitaTranzita**

### CODE REVIEW

**Comment by ankitaTranzita** [comment]
Hi @92shreyansh 

I've added logs for all the flows. Please check the PR #[1611](https://github.com/ONDC-Official/verification-logs/pull/1611)

**Comment by sourabhsaini11** [comment]
@ankitaTranzita, logs from staging env are not considered for verification, kindly provide the logs from preprod env.

**Comment by ankitaTranzita** [comment]
HI @sourabhsaini11 

I apologize for the oversight. I've updated the logs for the pre-prod env. Please check the PR: [#1611](https://github.com/ONDC-Official/verification-logs/pull/1611)

**Comment by sourabhsaini11** [comment]
@ankitaTranzita, please get the below issues fixed
issue, issue(close)
- org.name should be equal to bap_id::domain

**Comment by ankitaTranzita** [comment]
Hi @sourabhsaini11 ,

Fixed org.name in issue,  issue(close)

**Comment by 92shreyansh** [comment]
Transaction & IGM logs Approved for Buyer App

**Pull request merged**
