### PR TITLE
Tech Logs for TRV11 (Intracity Bus)

### PR DESCRIPTION
**Pull request by Nirdosh3312**
Submitting Tech logs for Flow 1 and Flow 2 for ONDC:TRV11 (Intracity Bus) for verification

### CODE REVIEW

**Comment by Nirdosh3312** [comment]
Hii @sourabhsaini11, Looking forward to your response. Please verify these logs and the PR

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please get the below issues resolved
comon_issue
- tag BUYER_FINDER_FEES_TYPE is missing in BUYER_FINDER_FEES tag-group
- parent_stop_id is missing for 'INTERMEDIATE_STOP' & 'END' stops.
- id is missing in fulfillments.stops
- type is missing in fulfillments
- timestamp is missing in items.time for descriptor.code 'SJT'

on_search_1
- additional attribute categories present in providers
- additional attribute time present in providers

on_search_2
- additional attribute categories present in providers
- additional attribute time present in providers
- additional attribute category_ids present in items
- tags is missing in items for descriptor.code SFSJT
- code should be in a generic enum format i.e. PASS for items[3]

on_select
- additional attribute category_ids present in items
- time is additional in provider
- OFFER & TOLL are missing in quote.breakup

init
- additional tag-group SETTLEMENT_DETAILS present in payments

on_init
- additional attribute category_ids present in items
- additional tag-group SETTLEMENT_DETAILS present in payments
- time is additional in provider
- OFFER & TOLL are missing in quote.breakup

confirm
- additional tag-group SETTLEMENT_DETAILS present in payments

on_confirm
- additional tag-group SETTLEMENT_DETAILS present in payments
- time is additional in provider
- OFFER & TOLL are missing in quote.breakup

on_cancel
- additional tag-group SETTLEMENT_DETAILS present in payments
- time is additional in provider

**Comment by KapilKharera** [comment]
Hi @sourabhsaini11, I have updated the logs for the bus (Intracity). Please check them.

**Comment by sourabhsaini11** [comment]
@KapilKharera, please get the below issues fixed
INTRACITY
common_issues
- tag BUYER_FINDER_FEES_TYPE is missing in BUYER_FINDER_FEES tag-group
- id is missing in fulfillments.stops
- parent_stop_id is missing for stops.type 'END' & 'INTERMEDIATE_STOP'
- type is missing in fulfillments
- attribute 'count' type must be a number instead of string at items.quantity

search(fare)
- code should be in a generic enum format at fulfillment.stops

init
- tags SETTLEMENT_BASIS, SETTLEMENT_WINDOW are missing in SETTLEMENT_TERMS tag-group

on_init
- tags OPERATIONAL_START_TIME & OPERATIONAL_END_TIME are not part of ROUTE_INFO tag-group for /on_init call
- tags SETTLEMENT_TYPE, DELAY_INTEREST are missing in SETTLEMENT_TERMS tag-group

confirm
- tags SETTLEMENT_BASIS, SETTLEMENT_WINDOW are missing in SETTLEMENT_TERMS tag-group

on_confirm
- tags OPERATIONAL_START_TIME & OPERATIONAL_END_TIME are not part of ROUTE_INFO tag-group for /on_confirm call
- tags SETTLEMENT_TYPE, DELAY_INTEREST are missing in SETTLEMENT_TERMS tag-group

Flow-2
common_issues
- transaction_id should remain same

on_cancel(soft)
- message_id should be same as sent in cancel(soft) call
- invalid object cancellation
- instead of value as '-undefined', valid values should be present for title "REFUND", at quote.breakup.Also remove multiple objects present with title "REFUND".
- id is missing in stops
- parent_stop_id is missing in stops.type END & INTERMEDIATE_STOP
- type is missing in fulfillments
- typeof count must be number instead of string at items.quantity
- tags SETTLEMENT_TYPE, DELAY_INTEREST are missing in SETTLEMENT_TERMS tag-group

cancel(confirm)
- order_id should be same as sent in past calls
- timestamp should be greater than the timestamp of past call

on_cancel(confirm)
- incorrect payload, should be according to Intracity contract instead of Metro's on_cancel call.


METRO
init
- 'SETTLEMENT_DETAILS' tag-group is incorrect, tag 'SETTLEMENT_TYPE' sould be part of 'SETTLEMENT_TERMS' tag-group instead

on_init
- 'SETTLEMENT_DETAILS' tag-group is incorrect, tag 'SETTLEMENT_TYPE' sould be part of 'SETTLEMENT_TERMS' tag-group instead

on_confirm
- 'SETTLEMENT_DETAILS' tag-group is incorrect

on_cancel
- 'SETTLEMENT_DETAILS' tag-group is incorrect, tag 'SETTLEMENT_TYPE' sould be part of 'SETTLEMENT_TERMS' tag-group instead

**Comment by KapilKharera** [comment]
Hi @sourabhsaini11, I have updated the logs for the bus (Intracity). Please check them.

**Comment by sourabhsaini11** [comment]
@Nirdosh3312, please fix the below issues

**Comment by KapilKharera** [comment]
Hi @sourabhsaini11, I have updated the logs for the bus (Intracity). Please check them.

**Comment by sourabhsaini11** [comment]
@KapilKharera,  please get the below issues fixed
common_issue
- if buyer-app is collecting then the SETTLEMENT_AMOUNT value should be quote.price - buyer_finder_fee

cancel(confirm)
- timestamp should be greater than the timestamp of past call.

on_cancel(confirm)
- updated_at should not be similiar to /on_cancel(soft) updated_at.

**Comment by 92shreyansh** [comment]
Approved Pramaan Logs

**Pull request merged**
