### PR TITLE
Happy Flow

### PR DESCRIPTION
**Pull request by lohanaman112**
Missed EMI and IGM Flow are not been supported by the seller NP.

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@lohanaman112, kindly get the below issues fixed
common_issues
- OFFLINE_CONTRACT tag is missing in SETTLEMENT_TERMS tag-group

on_search
- DELAY_INTEREST tag is missing in SETTLEMENT_TERMS tag-group

on_select (2 & 3)
- COOL_OFF_PERIOD value should be in ISO 8601 duration format

on_confirm
- documents array is missing

Note:- 
- Foreclosure & Pre-part payment flows are incomplete(Instead of NACK response please logs showcasing the required journey)
- Missed-emi payment flow is missing

**Comment by sourabhsaini11** [comment]
@lohanaman112, please get the below issues fixed
common_issue
- if fulfillments.state is DISBURSED, then documents array must also contain LOAN_CANCELLATION object.

on_confirm
- order.id is missing

on_update
- order.id is missing

on_status(4, 5)
- order.id is missing

**Comment by sourabhsaini11** [comment]
@lohanaman112, below are the issues related to IGM
on_issue
- bpp_id in respondent_actions.org.name mismatches with the bpp_id sent in context

on_issue_status
- bpp_id in respondent_actions.org.name mismatches with the bpp_id sent in context
- updated_at in respondent_actions must be less then or equal to issue.update_at

**Comment by lohanaman112** [comment]
All the issues which have been raised are seller app IGM issues.
The logs which we have generated are with Pramaan seller app.

**Comment by sourabhsaini11** [comment]
@lohanaman112,  kindly get the below issue fixed
on_confirm
- descriptor.code should be SANCTIONED at fulfillments

update
- update & on_update calls capturing consent approval are missing

Pre-Part
- /on_update_2 call is incomplete

IGM
on_issue
- bpp_id in respondent_actions.org.name mismatches with the bpp_id sent in context

issue_status
- corresponding pair call(on_issue_status) with same message_id is missing.

on_issue_status
- bpp_id in respondent_actions.org.name mismatches with the bpp_id sent in context

**Comment by Nirdosh3312** [comment]
Hi @sourabhsaini11,

I would like to point out certain things regarding the issues mentioned here. Kindly look at them as well. 

- on_confirm 

    For the on_confirm call we keep the fulfillment status as INITIATED only and then we change the status to SANCTIONED and DISBURSED state from our side through subsequent unsolicited on_status calls. That is the implementation at our end.

- on_update_2

    For the on_update call in the Pre-Part flow in the mentioned logs, the file is named as on_update_2 only but it is has ***update*** call's body in it. That is ***not the on_update call***. Please verify that as well. 

- on_issue & on_issue_status 

> on_issue_status
    bpp_id in respondent_actions.org.name mismatches with the bpp_id sent in context

   For this, I am attaching a screen shot from the very logs that are submitted for the reference. Please let me know if it is okay. 

Screenshot 2024-05-21 174207

**Comment by sourabhsaini11** [comment]
@lohanaman112 @Nirdosh3312 
- correction here, org.name should be bpp_id::domain(pramaan.ondc.org/beta/preprod/mock/seller::ONDC:FIS12)
- 2.0 version includes monitoring consent

**Comment by 92shreyansh** [comment]
Transaction logs Approved for Buyer App

**Pull request merged**
