### PR TITLE
Added verification logs for version 2.0.1

### PR DESCRIPTION
**Pull request by rajat7258**
Added verification logs for version 2.0.1

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@rajat7258, kindly submit the logs from pre-prod env for verification.

**Comment by rajat7258** [comment]
Hello @sourabhsaini11 , we've pushed the verification logs from the pre-production environment for version 2.0.1. Could you please review them at your convenience?

**Comment by rajat7258** [comment]
Hello @sourabhsaini11  @anuj-ondc , thanks for the update!

I just have a question regarding this part: "Remove fulfillment type SELF_PICKUP if the request is of Delivery type."

Since we're not specifying any type in the search request, how will the driver side be able to distinguish whether the request is for SELF_PICKUP or DELIVERY?

**Comment by rajat7258** [comment]
Hello @sourabhsaini11 @anuj-ondc 
Another question regarding this part: "In stops, valid_to & status keys are missing."
As the fields are not mandatory we are not sending these values in DELIVERY flow, Do we need to change this?

**Comment by rajat7258** [comment]
Hello @sourabhsaini11 @anuj-ondc, We have resolved the PR comments, please review as per your convenience.

Update regarding these two comment : 1. "In stops, instructions are missing ( Applicable to all calls)" 
2. "In items, location_ids is missing."
These two fields are not mandatory as per the attribute UI, so we are not considering these in the logs.

**Comment by sourabhsaini11** [comment]
@rajat7258, please get the below issues fixed
common_issues
- vehicle.energy_type is missing
- virtual_payment_address is missing in payments.params
- price should be precise upto 2 decimal places, at quote & item
- tags NIGHT_SHIFT_END_TIME & NIGHT_SHIFT_START_TIME should be in HH:MM:SS format
- tags MANDATORY_ARBITRATION, COURT_JURISDICTION, SETTLEMENT_TYPE are missing in SETTLEMENT_TERMS tag-group for on_action calls

search
- tags SETTLEMENT_WINDOW, SETTLEMENT_BASIS, SETTLEMENT_TYPE are sent additionally

on_search
- ROUTE_INFO tag-group is not part of /on_search

select
- fulfillments is sent additionally

on_init
- tag SETTLEMENT_AMOUNT is missing in SETTLEMENT_TERMS tag-group

on_confirm
- status & valid_to are missing
- created_at & updated_at can't be greater than context.timestamp
- tag SETTLEMENT_AMOUNT is missing in SETTLEMENT_TERMS tag-group

on_status
- created_at should match to /on_confirm's created_at
- tag SETTLEMENT_AMOUNT is missing in SETTLEMENT_TERMS tag-group
- status & valid_to are missing

on_update
- invalid attribute FarePolicy & GeneralInformation
- created_at should match to /on_confirm's created_at
- tag SETTLEMENT_AMOUNT is missing in SETTLEMENT_TERMS tag-group
- status & valid_to are missing

on_cancel
- created_at should match to /on_confirm's created_at
- tag SETTLEMENT_AMOUNT is missing in SETTLEMENT_TERMS tag-group
- title REFUND is missing in quote.breakup

**Comment by sourabhsaini11** [comment]
@rajat7258, please fix below issues as well
common_issue
- price should be precise upto 2 decimal places, at quote & item
- quote.breakup summation should match to quote.price

on_search
- tags SETTLEMENT_WINDOW, SETTLEMENT_BASIS, SETTLEMENT_TYPE, MANDATORY_ARBITRATION & COURT_JURISDICTION are missing for SETTLEMENT_TERMS tag-group

on_init
- tag SETTLEMENT_AMOUNT is missing at SETTLEMENT_TERMS tag-group

status 
- either of order_id or ref_id should be used, not both

on_status
- tags should be an array at items
- make is missing in vehicle
- name is sent additionally in items

DELIVERY
on_confirm
- make is missing in vehicle

on_update_RIDE_ENDED
- virtual_payment_address is missing in payments.params
- make is missing in vehicle

Flow-2
on_cancel_CONFIRM_CANCEL
- timestamp same as on_cancel_SOFT_CANCEL's timestamp
- make is missing in vehicle

Flow-3
on_cancel
- message_id same as status's message_id
- make is missing in vehicle

SELF_PICKUP
on_confirm
- invalid attribute Variant, should be variant

on_update
- make is missing in vehicle

on_status_RIDE_ENDED_PAID
- virtual_payment_address is missing in payments.params

on_update_RIDE_ENDED
- virtual_payment_address is missing in payments.params

**Comment by rajat7258** [comment]
Hi @sourabhsaini11 ,
I have addressed the PR comments and uploaded the updated logs for your review.

Let me know if further clarification is needed.

**Comment by sourabhsaini11** [comment]
@rajat7258, please fix the below issues
common_issues
- for tag SETTLEMENT_TYPE, value should be in an enum format i.e. UPI
- quote.breakup total summation(71.72) should match to quote.price(71.00)
- images is missing at items.descriptor for on_status call but the same is present in on_init & on_confirm

on_status
- price should be precise upto 2 decimal places

on_update
- update_target is sent additionally

Flow-2-PassengerCancellation
on_status
 - multiple SETTLEMENT_AMOUNT tags present 

Flow-3
on_cancel
- message_id same as status's message_id

SELF_PICKUP
Flow-1-SuccessfullRideComplition
on_update_RIDE_ASSIGNED
- message_id same as on-confirm's message_id

**Comment by sourabhsaini11** [comment]
@rajat7258, please fix below issues
common_issues
on_update
- update_target is sent additionally

DELIVERY
Flow-1
on_status_RIDE_ASSIGNED
- updated_at can't be greater than context.timestamp

on_status_RIDE_ENDED_PAID
- message_id mismatch between /status & on_status_RIDE_ENDED_PAID

Flow-3
on_status
- updated_at can't be greater than context.timestamp

SELF_PICKUP
common_issue
- authorization.valid_to should be greater than context.timestamp

Flow-1
on_status_RIDE_ENDED_PAID
- message_id mismatch between /status & on_status_RIDE_ENDED_PAID

on_update_RIDE_ASSIGNED
- updated_at can't be greater than context.timestamp

**Comment by rajat7258** [comment]
Hi @sourabhsaini11,
I have addressed the PR comments and uploaded the updated logs for your review.

Let me know if further clarification is needed.

**Comment by rajat7258** [comment]
Hi @sourabhsaini11,
I have addressed the PR comments and uploaded the updated logs for your review (Passenger Cancellation flow SELF_PICKUP).

Let me know if further clarification is needed.

**Pull request merged**
