### PR TITLE
Log Submission for openFinance -PayNearby

### PR DESCRIPTION
**Pull request by AshishM-Protean**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@AshishM-Protean , kindly resolve the below issues

common_issues
- INTEREST_RATE_CONVERSION_CHARGE value should be 0 instead of "Not Applicable"
- COOL_OFF_PERIOD value should be in ISO 8601 duration format

search
- payment.collected_by must be present
- STATIC_TERMS should have a valid value
- additional tag group 'PAYMENT_COLLECTOR'

on_search
- payment.collected_by must be present
- STATIC_TERMS should have a valid value
- additional tag group 'PAYMENT_COLLECTOR'

on_select_1
- form.id & submission_id should be same as sent in prev select call

select_2
- form.id & submission_id should be same as sent in prev select_1 call
- form_response.status should be APPROVED at items

init
- status is missing in payments

on_init
- id & collected_by are missing in payments
- INSTALLMENT breakdown is not part of on_init 1 & 2 call

confirm
- id & status are missing in payments

on_confirm
- id is missing in payments
- Invalid mime_type: should be equal to one of the allowed values (text/html,application/html,application/xml,application/pdf)

on_status
- Invalid mime_type: should be equal to one of the allowed values (text/html,application/html,application/xml,application/pdf)

flow-3, 4:
- unsolicated on_update call is missing

flow-5:
- unsolicated on_update call is missing

on_update
- INSTALLMENT with status "DELAYED" is missing in payments

**Comment by sourabhsaini11** [comment]
common_issues
- COOL_OFF_PERIOD value should be in ISO 8601 duration format i.e. PT1D

search
- additional tag group 'PAYMENT_COLLECTOR'

init
- status is missing in payments

confirm
- id & status are missing in payments

flow-3
on_update (unsolicated)
- installments which had status as NOT-PAID should change to DEFERRED instead of PAID upon foreclosure

flow-5
on_update
- installment with status as DELAYED should be present for missed-emi flow

on_update (unsolicated)
- installments which had status as DELAYED should change to DEFERRED upon successful payment

@AshishM-Protean , kindly fix the above issues as well

**Comment by sourabhsaini11** [comment]
@AshishM-Protean, kindly get the below issues cleared

search
- addtional tag-group SETTLEMENT_DETAILS in payments

init
- id is missing in payments (init 2 & 3)

flow-3
on_update (unsolicited)
- installments which had status as NOT-PAID should change to DEFERRED instead of PAID upon foreclosure

flow-4
on_update (unsolicited)
- installment with DEFERRED status is missing

flow-5
on_update
- installment with DELAYED status is missing

on_update (unsolicited)
- installment with DEFERRED status is missing

Also, provide updated logs for all flows

**Comment by AshishM-Protean** [comment]
@sourabhsaini11 Please find revised log submission 
commit Id: https://github.com/protean-ondc/verification-logs/commit/332cba88e7b0f52db376e7818b57fbeb13891b8c

search

addtional tag-group SETTLEMENT_DETAILS in payments - Rectified
 
init

id is missing in payments (init 2 & 3) - Rectified
 
flow-3

on_update (unsolicited)

installments which had status as NOT-PAID should change to DEFERRED instead of PAID upon foreclosure - as this is received from seller app as a buyer app we do not have control of this
 
flow-4

on_update (unsolicited)

installment with DEFERRED status is missing - as this is received from seller app as a buyer app we do not have control of this
 
flow-5

on_update

installment with DELAYED status is missing - as this is received from seller app as a buyer app we do not have control of this
 
on_update (unsolicited)

installment with DEFERRED status is missing - as this is received from seller app as a buyer app we do not have control of this
 
Also, provide updated logs for all flows - Provided

**Comment by sourabhsaini11** [comment]
common_issues
- confirm call is missing

flow-3
select
-bap_id & bap_uri mismatch in /on_search and /select
@AshishM-Protean , please fix the above issues

**Comment by AshishM-Protean** [comment]
@sourabhsaini11 

Updated 

Commit ID : 09c55048ad0ae1499f0b7763c174abc06c118af3

**Comment by sourabhsaini11** [comment]
@AshishM-Protean, please provide IGM logs as well. Transaction level logs are cleared.

**Comment by SubbaraoBhavaraju-Protean** [comment]
@sourabhsaini11 please update on the IGM logs and clearance on the same

**Comment by SubbaraoBhavaraju-Protean** [comment]
@92shreyansh  need your support on IGM log validation

**Comment by MayurK-protean** [comment]
@sourabhsaini11 please find updated IGM logs

on_issue

context timestamp should be greater than or equal to updated_at in on_issue -  as this is received from seller app as a buyer app we do not have control of this.

**Comment by MayurK-protean** [comment]
@sourabhsaini11 one more point

We have used category 'FULFILMENT' as per swagger reference.

Swagger Link - https://ondc-official.github.io/ONDC-NTS-Specifications/#/Complaint%20lifecycle%20management/post_issue

**Comment by 92shreyansh** [comment]
Tansaction & IGM logs Approved

**Comment by 92shreyansh** [comment]
please resolve the conflicts for merge

**Comment by sourabhsaini11** [comment]
@AshishM-Protean, please resolve conflicts so that we can merge the logs into main.

**Pull request merged**
