### PR TITLE
ondc-preprod.earlysalary.com

### PR DESCRIPTION
**Pull request by om-warule-sw**

### CODE REVIEW

**Comment by om-warule-sw** [comment]
4 flows added for the preprod env. 
Subscriber id : ondc-preprod.earlysalary.com

**Comment by om-warule-sw** [comment]
Hello @92shreyansh,

Added logs of flow1 , flow2 , flow3 and flow4.

**Comment by om-warule-sw** [comment]
Flow 5 is also added here

**Comment by sourabhsaini11** [comment]
@om-warule-sw, kindly fix the below issues
common_issues
- tag SETTLEMENT_AMOUNT is missing in SETTLEMENT_TERMS tag-group for /on_action calls

on_select_2
- Total of quote breakup (72800) does not match with price.value (64000)

on_init_1
- message_id & transaction_id mismatched between /init & /on_init

Flow-2
on_update
- range is missing in time.label at payments
- payment object containing tags are missing

on_update(unsolicated)
- id should remain same as sent in past /on_update for payments object
- url should not be part of payments[0]
- range is missing in time.label at payments
- payment object containing tags are missing

Flow-3
on_update
- INSTALLMENT with status DELAYED is missing
- range is missing in time.label at payments
- payment object containing tags are missing

on_update(unsolicated)
- id should remain same as sent in past /on_update for payments object
- url should not be part of payments[0]
- INSTALLMENT with status DEFFERED is missing
- range is missing in time.label at payments
- payment object containing tags are missing

Flow-4
on_update
- range is missing in time.label at payments
- payment object containing tags are missing

on_update(unsolicated)
- range is missing in time.label at payments
- payments array is incomplete

Flow-5 is not incuded in the logs due to log verifications being done before submission

**Comment by sourabhsaini11** [comment]
@om-warule-sw, please get the below issues fixed
common_issues
- tag INTEREST_RATE_CONVERSION_CHARGE should be just "NA" or "0 INR" if no interest is being charged
- city.code must be "*" (Pan-India)
- start & end timestamp must be in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) format in payments

on_update
- status should be PAID for installment object containing BUYER_FINDER_FEES tag-groups

on_select_1, on_confirm
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

Flow-4
on_update_unsolicited_foreclosure
- installments whose status earlier was NOT-PAID should change to DEFERRED upon foreclosure

Flow-5
on_update
- incorrect payload, action should be of on_update

IGM
common_issue
- created_at should match issue's created_at

issue, issue(close)
- org.name should be bap_id::domain

on_issue
- Message ID mismatch in /issue and /on_issue
- The 'updated_at' of message/issue/issue_action/respondent_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue

on_issue_status
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format
- Message ID mismatch in /issue_status and /on_issue_status
- resolution_support/gros/0 must have required property 'gro_type'
- The 'updated_at' of message/issue/issue_action/respondent_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue_status

**Comment by om-warule-sw** [comment]
For the Points below  
 

- **on_update**
    - **status should be PAID for installment object containing BUYER_FINDER_FEES tag-groups**  - _as we are doing offline contract so here the status should be of NOT-PAID only._

- **issue, issue(close)**
   - **org.name should be bap_id::domain** : _This would be a from pramaan side_

- **on_update_unsolicited_foreclosure**
   - **installments whose status earlier was NOT-PAID should change to DEFERRED upon foreclosure** - This is false positive as discussed with shreyansh on call. 

- We are fixing the remaining points

**Comment by sourabhsaini11** [comment]
@om-warule-sw, kindly get the below issues fixed as well
common_issues
- for title PRINCIPAL value must be 71143.0 as defined in tiem.price
- in payments INSTALLMENT amount should be 11930.0 as defined in tag INSTALLMENT_AMOUNT

on_search
- tag SETTLEMENT_AMOUNT is sent additionally

on_select
- price.value should be precise upto 2 decimal places only at quote.breakup (/on_select_2)

on_confirm
- INSTALLMENT's object id should remain same as sent in past call (/init_3)

Flow-2
on_update
- range is missing at payments[0].time 
- INSTALLMENT status should be DELAYED for missed installment

on_update_unsolicited_pre_part_payment
- range is missing at payments[0].time 
- params.amount is changed/not same as sent in past call at payments[0]

Flow-3
on_update_unsolicited_missed_emi_payment
- range is missing at payments[0].time

**Comment by om-warule-sw** [comment]
Flow-2
on_update

- **range is missing at payments[0].time** : _As this is part payment here we don't have any range for it_
- **INSTALLMENT status should be DELAYED for missed installment**  : _As this is part payment here and customer has no dues till now so no delay is needed to be added here_

on_update_unsolicited_pre_part_payment

- **range is missing at payments[0].time** : _As this is part payment here we don't have any range for it_

- **params.amount is changed/not same as sent in past call at payments[0]** : In on_update we should show how much he can avail for the part_payment. And after the payment is done customer can do part payment of any amount so hence changed the amount.

Other things I will try to fix @sourabhsaini11

**Comment by om-warule-sw** [comment]
@sourabhsaini11 and @92shreyansh We have updated the logs according to the changes previously suggested.

**Comment by sourabhsaini11** [comment]
@om-warule-sw, kindly get the below issues fixed as well
common_issue
- provide genuine values for tags CUSTOMER_SUPPORT_CONTACT_NUMBER & GRO_DESIGNATION at CONTACT_INFO tag-group

on_select_2
- breakup.price summation is not equal to quote.price

on_init_3
- quote.price mismatch to what was sent in past call(/on_init_2)

on_confirm
- INSTALLMENT price is changed from what was sent in past call(/on_init_3)

Flow-4 & 5
on_update(unsolicated)
- descriptor.code should be COMPLETED at fulfillments.state

**Comment by om-warule-sw** [comment]
Hello Shreyansh and Saurabh,

- on_init_3:

          The quote.price is mismatched compared to the previous call (/on_init_2).

- on_confirm:

          The INSTALLMENT price differs from what was sent in the previous call (/on_init_3).


For the above two points, please note that prior to these API calls, the interest and processing fee calculations were not finalized, which led to differences before and after the on_init_3 call. However, these differences are minimal compared to earlier calculations and should be considered as false positives. This was also discussed during the call.

**Comment by 92shreyansh** [comment]
Transaction logs Approved for Seller App

**Pull request merged**
