### PR TITLE
ABFL logs

### PR DESCRIPTION
**Pull request by lohanaman112**
c

### CODE REVIEW

**Comment by lohanaman112** [comment]
For Foreclosure and Part-payment flows we are sending error message with error code.

**Comment by sourabhsaini11** [comment]
@lohanaman112 , kindly resolve the below issues

common_issues
- timestamp should be greater than timestamp of previous call
- if lsp is not assigned then it's value should be "" instead of NA

on_select_1
- submission_id should be same as sent in select_1 call at xinput

on_status
- tag group name loan-info must be in an enum format i.e. LOAN_INFO
- payments & documents shouldn't be empty
- title in breakup must be a generic enum format

emandate_on_status(UNSOLICITED):
- submission_id doesn't matches with submission_id of Emandate form

status & on_status calls are missing.

Flow 5
on_update
- documents array is missing

unsolicated on_update calls is missing

**Comment by lohanaman112** [comment]
For Foreclosure and Part-payment flows we are sending error message with error code.
Need a proper documented api's for unsolicated on_status and on_update calls.

**Comment by 92shreyansh** [comment]
The documentation for all these calls related to the flows is already present in the developer guide. 
At a high level:
unsolicated on_status: in case of any status change triggered/initated from seller/lender side needs to be communicated to the buyer app this call will have the complete order details as on time.
unsolicated on_update: trigger is similar to the abpve but this is triggered when any value or field other than status is getting changed.
If still more details are required lets bring this up in the community call.

**Comment by sourabhsaini11** [comment]
@lohanaman112 below are the issues related with IGM logs

issue
- org.name should be in bap_id::domain

on_issue_status
- contact & person missing in org at respondent_actions[1]. 

issue (close) call is missing

**Comment by sourabhsaini11** [comment]
Context in IGM logs needs to have a similar construct as we are having in the developer guide.
Also, kindly resolve the issues mention in this thread
https://github.com/ONDC-Official/verification-logs/pull/1332#issuecomment-1893286994

**Comment by lohanaman112** [comment]
1) In IGM logs we are following context as per the construct we are having in the developer guide. We could'nt find any issue on this logs. Can you please elaborate it.
2) The thread what you have shared with us, we have already resolved that issues and submitted logs. We have submitted both Flow and IGM logs but you have'nt raised any issue in IGM logs.
Can you please elaborate on queries what we have raised.

**Comment by anuj-ondc** [comment]
**Flow 1**
  Common Issues:
    Timestamp should be greater than previous calls.

  on_init_1
        - quote amount is not matching with previous on_select_3 call's quote value.
        - In quote, price(246960) is not matching with breakup amount(298267)(common for next calls) 
  on_init_3
      - In xinput, incorrect index for cur, should be 2 instead of 1  
  confirm
      - In Payments, status is missing
  on_confirm
      - If current state is DISBURSED then, documents should contain LOAN_CANCELLATION document also. 
      - In cancellation_terms, the fulfillment_state for SANCTIONED is replaced by DISBURSED.

**Flow 3**
  Common Issues:
      All issues of Flow 1
  update
      - order_id is not matching with on_confirm.

**Flow 4**
  Common Issues:
      All issues of Flow 1
  update
      - order_id is not matching with on_confirm.

**Flow 5**
  Common Issues:
      All issues of Flow 1
  update
      - order_id is not matching with on_confirm call.  
  on_update
      - order_id is not matching with on_confirm & update calls.
      - In payments, the emi amount is not matching with on_confirm call.
      - EMI's date is not matching with previous instalments.
      - In MISSED_EMI_PAYMENT, the status of targeting emi for which we are paying should be DELAYED.
        Please refer to develop guide page for more clarity.

  missing one **on_update** call also.    
  
  @lohanaman112 Please resolve above issues.

**Comment by sourabhsaini11** [comment]
Hii @lohanaman112, please resolve below issues

confirm
- payments.status is missing

on_confirm
- If current state is DISBURSED then, documents should contain LOAN_CANCELLATION document also.

status & on_status calls are missing for flow-1

Flow-5
on_update
- MISSED_EMI_PAYMENT's date is not matching with DELAYED installment date

unsolicated on_updated call is missing


For IGM, the attributes of context must follow a similar pattern as we are following for FIS:12
here's an example
{
    "domain": "domain",
    "action": "action",
    "version": "version",
    "bap_id": "bap_id",
    "bap_uri": "bap_uri",
    "transaction_id": "transaction_id",
    "message_id": "message_id",
    "timestamp": "timestamp",
    "ttl": "ttl",
    "bpp_id": "bpp_id",
    "bpp_uri": "bpp_uri",
    "location": {
        "country": {
            "code": "IND"
        },
        "city": {
            "code": "*"
        }
    }
}

**Comment by sourabhsaini11** [comment]
@lohanaman112, kindly get these below issues fixed

FIS12
on_select 3
- value at quote.price should be equal to summation of 'PRINCIPAL', 'INTEREST' & 'PROCESSING_FEE'

on_init
- value at quote.price should be equal to summation of 'PRINCIPAL', 'INTEREST' & 'PROCESSING_FEE'

on_confirm
- value at quote.price should be equal to summation of 'PRINCIPAL', 'INTEREST' & 'PROCESSING_FEE'

on_status
- Timestamp for /on_status api should be greater than timestamp of /status api
- value at quote.price should be equal to summation of 'PRINCIPAL', 'INTEREST' & 'PROCESSING_FEE'

on_status_1
- order.id must be present if fulfillments.state is 'SANCTIONED'
- documents array should not be empty

on_status_2 & on_status_3
- documents array should not be empty

on_confirm (flow 3, 4 & 5)
- In cancellation_terms, SANCTIONED state is missing.

common_issues
- Lsp details shouldn't be empty for tag group 'LSP_INFO'

IGM
issue
- category must be equal to FULFILLMENT instead of FULFILMENT

issue(close)
- /context/action must be equal to constant (issue)
- ttl is missing at context

on_issue, on_issue_status
- ttl is missing at context

**Comment by sourabhsaini11** [comment]
@lohanaman112, kindly get the below issues resolved as well

common_issues
- invoice_receipt should be in a generic enum format (INVOICE_RECEIPT)
- INTEREST_RATE_CONVERSION_CHARGE should be 0 instead of NA if interest is not getting charged

status
- bap_id & bap_uri mismatch compared to past calls
- ref_id should match with transaction_id

on_status
- price.value type should be string at quote
- LOAN_AGREEMENT document must be present if code in fulfillments is 'SANCTIONED'

on_status 3
- form_response must be present instead of head & form at xinput

on_update_unsolicated (flow-5)
- INSTALLMENT status should be 'DEFERRED' instead of 'PAID' at payments[2]

IGM
on_issue_status
- ttl is missing at context
- 'created_at' should match issue's 'created_at'

**Comment by lohanaman112** [comment]
Hi @92shreyansh as per discussion we are submitting FLOW 1 and IGM logs with all the comments resolved.
We will be skipping FLOW 5 logs as we are not maintaining the DEFFERED state for missed emi payment.
We have not submitted FLOW 3 and FLOW 4 logs as we have only issue in happy journey (FLOW 1).
Kindly review and approved at earliest

**Comment by lohanaman112** [comment]
Hi @92shreyansh as per discussion we are submitting FLOW 1 and IGM logs with all the comments resolved.
We will be skipping FLOW 5 logs as we are not maintaining the DEFFERED state for missed emi payment.
We have not submitted FLOW 3 and FLOW 4 logs as we have only issue in happy journey (FLOW 1).
Kindly review and approved at earliest.

**Comment by sourabhsaini11** [comment]
@lohanaman112,
IGM
issue(close)
- context.action should be issue
above issue is from buyer side so should be rectified from their end

**Comment by techitesh** [comment]
> @lohanaman112, IGM issue(close)
> 
> * context.action should be issue
>   above issue is from buyer side so should be rectified from their end

Hi @sourabhsaini11 We  have discussed this with Easy Pay as per them They have made this fixes in prod and they are maintaining separate Branch for Pre Prod and Prod This issue wont be reflected on Prod

**Comment by 92shreyansh** [comment]
@lohanaman112 The buyer app issue can be ignored for now. Please provide timeline for DEFFERED state fix at your end so that we can close the PR

**Comment by techitesh** [comment]
> @lohanaman112 The buyer app issue can be ignored for now. Please provide timeline for DEFFERED state fix at your end so that we can close the PR

hi @92shreyansh  has discussed this issue with Rajiv n Vaibhav, let you all have discussion along with other lenders and buyer apps. Then actionable and timelines can be finalised.

**Comment by 92shreyansh** [comment]
Logs Approved under exceptions to fix the few findings by based on the discussion with BAPs.

**Pull request merged**
