### PR TITLE
Tech logs for ultranet placeorder buyer app for Credit using DMI

### PR DESCRIPTION
**Pull request by pawank**
PR for tech logs for Personal Loan showing all APIs request/responses

### CODE REVIEW

**Comment by anuj-ondc** [comment]
### Log verification findings:
**search**
  1) Payment>Tags >  PAYMENT_COLLECTOR tags should not be there.
  2) Payment>Tags: In SETTLEMENT_TERMS, should not have SETTLEMENT_AMOUNT, MANDATORY_ARBITRATION, SETTLEMENT_TYPE, COURT_JURISDICTION


**on_search**
  1) In providers > id should be valid id not -> "kbl-preprod"
  2) In Items > id should be valid id not -> "PERSONAL_LOAN"
  3) In categories id should be valid one not "PERSONAL_LOAN"
  4) In Items>tags code value for general-info should be GENERAL_INFO in standard enum format.
  5) Payments>Tags: PAYMENT_COLLECTOR tags should not be there.
  6) Payments>Tags: SETTLEMENT_AMOUNT needs to be removed(part of init or on_init)
  7) form > id can't be transaction id.

**select 1**
  1) bpp_id & bpp_uri is different from previous on_search calls(**Applicable to all endpoints**).
  2) provider>id should match with the one in on_search payload(**Applicable to all endpoints**).
  3) item id should match with the one in on_search call.
  4) form > id is not matching.

**on_select 1**
  1) bpp_id & bpp_uri is different from previous on_search calls.
  2) provider>id should match with the one in on_search payload.
  3) In form_response > status should be PENDING not CONSENT_CREATED.
  4) In context city code is missing(applicable to all end-points).
  5) In items > descriptor is missing.


**select 2**
  1) bpp_id & bpp_uri is different from previous on_search calls.
  2) provider>id should match with the one in on_search payload.
  3) item id should match with the one in on_search call.
  4) form_response status should nt APPORVED not CONSENT_APPROVED.
  5) Form id is not matching.

**on_select 2**
  1) In context city code is missing.
  2) In items> descirptor code should be PERSONAL_LOAN not personal-loan(Applicable to all end-points).
  3) OTHER_PENALTY_FEE can't be NA should be 0.
  4) form > id can't be transaction id.
  5) quote > title sholud in be enum format like Principal = PRINCIPAL, Interest = INTEREST applicate to all values(applicable to all endpoints).

**select 3**
  1) bpp_id & bpp_uri is different from previous on_search calls.
  2) provider>id should match with the one in on_search payload.

**on_select 3**
  1) In context city code is missing.
  2) In items> descirptor code should be PERSONAL_LOAN not personal-loan.
  3) In items> Price value is not matching with previous on_select calls.
  4) In items> tags> APPLICATION_FEE should bot be NA, should be 0.
  5) quote > title sholud in be enum format like Principal = PRINCIPAL, Interest = INTEREST applicate to all values(applicable to all endpoints).
  6) in quote >  Other Charges >  value shouldn't be NA, should be 0(Appilcable to all end-points).

**init 1**
  1) payments >tags >  PAYMENT_COLLECTOR tags should not be there(Applicable to init calls).
  2) In payments > tags > COURT_JURISDICTION should not be there.

**on_init 1**
  1) In context city code is missing.
  2) In items> descirptor code should be PERSONAL_LOAN not personal-loan.
  3) In fulfillments > state > descriptor > name can't be null.
  4) IN cancellation_terms cancellation_fee &  external_ref should not be NA.

**init 2**
  1) payments >tags >  PAYMENT_COLLECTOR tags should not be there(Applicable to init calls).
  2) In payments > tags > COURT_JURISDICTION should not be there.

**on_init 2**
  1) In context city code is missing.
  2) In items> descirptor code should be PERSONAL_LOAN not personal-loan.
  3) In fulfillments > state > descriptor > name can't be null.
  4) IN cancellation_terms cancellation_fee &  external_ref should not be NA.

**init 3**
  1) payments >tags >  PAYMENT_COLLECTOR tags should not be there(Applicable to init calls).
  2) In payments > tags > COURT_JURISDICTION should not be there. 

**on_init 3**
  1) In context city code is missing.
  2) In items> descirptor code should be PERSONAL_LOAN not personal-loan.
  3) In fulfillments > state > descriptor > name can't be null.
  4) IN cancellation_terms cancellation_fee &  external_ref should not be NA.
  5) In payments > time > label > values sholud be enum format like Installment 1 = INSTALLMENT for all installments.

**confirm** 
  1) payments >tags >  PAYMENT_COLLECTOR tags should not be there(Applicable to init calls).
  2) In payments > tags > COURT_JURISDICTION should not be there.  

**on_confirm**
  1) In context city code is missing.
  2) In items> descirptor code should be PERSONAL_LOAN not personal-loan. 
  3) In payments > time > label > values sholud be enum format like Installment 1 = INSTALLMENT for all installments.
  4) In fulfillments > state > descriptor > name can't be null.
  5) IN cancellation_terms cancellation_fee &  external_ref should not be NA.

**on_status**
  1) In context city code is missing(Appilcable to all calls).
  2) In items > xinput can not be null.
  3) quote > title sholud in be enum format like Principal = PRINCIPAL, Interest = INTEREST applicate to all values(applicable to all endpoints).
  4) In fulfillments > state > descriptor > name can't be null.

**Comment by anuj-ondc** [comment]
### Common issue
  1) In context city code should be * in each call.
  2) Timestamp mismatch.

**on_search**
  1) In context, difference in timestamp between search/on_search is not correct 2023-12-14T16:26:24.573Z/2023-12-14T21:56:26.101Z

**select 1**
  1) In context timestamp is incorrect(should be greater than on_search's)

**on_Select 1**
  1) Timestamp is not correct.

**select 2**
  1) Timestamp is not correct.

**on_Select 2**
  1) Timestamp is not correct.


  **init 1**
    1) MANDATORY_ARBITRATION should not be part of init call, please check TLC-UI on ondc developer page.

  **on_init 1**
    1) Timestamp is not matching.
    2) percentage can't be empty, should be a value between 0-100

  **on_init 2**
    1) Timestamp is not correct


 **on_init 3**   
  1) In payments > label for each installment must be in a standard enum format (INSTALLMENT)
  2) cancellation_terms:percentage can't be empty, should be a value between 0-100

  **on_status**
    1) In payments > label for each installment must be in a standard enum format (INSTALLMENT)
    2) cancellation_terms:percentage can't be empty, should be a value between 0-100





@pawank , kindly resolve above issues as well

**Comment by pawank** [comment]
@anuj-ondc @92shreyansh tech logs submitted

**Comment by anuj-ondc** [comment]
**on_init 1**
  1) documents should not be the part of the payload(Applicable to app on_init calls).

**on_confirm 1**
  1) In documents, url is missing.
  
**on_status 1**
  1) In documents, url is missing.
  2) fulfillments state should be DISBURSED.
  3) In documents, LOAN_CANCELLATION document is missing.
  
  @pawank, kindly resolve above issues as well

**Comment by pawank** [comment]
@anuj-ondc @92shreyansh Please check the logs now. All buyer app side fixes are done. 
NOTE: 
on_init: documents should not be the part of the payload(Applicable to all on_init calls) - To be done by lender side DMI, I have informed them.

**Comment by anuj-ondc** [comment]
on_init
  1) documents should not be the part of the payload
  
on_confirm
  1) state should be SANCTIONED not INITIATED
  
 on_status
  1) In documents, LOAN_CANCELLATION doc is missing.
  
 As reported previously, this would be fixed by the lender side, however the current logs has the same issues. Once this is fixed, please let us know.

**Comment by pawank** [comment]
@anuj-ondc @92shreyansh 

Please see the comments for 3 points mentioned

on_init

documents should not be the part of the payload
[PK] Fixed
on_confirm

state should be SANCTIONED not INITIATED
[PK] As per DMI, The initial fulfilment state will be INITIATED. After sanction, it will transition to SANCTIONED. Once disbursed, the status will be updated to DISBURSED. You will receive notifications through the on_status call whenever there is a status change.
Also, the state change is manual on preprod .

on_status
In documents, LOAN_CANCELLATION doc is missing.
[PK] DMI doesn't allow cancellations, hence the document URL is empty.

**Comment by sourabhsaini11** [comment]
@pawank, kindly submit rest of the flows also

**Pull request closed without merging**
