### PR TITLE
Karnataka bank - Collections Options added

### PR DESCRIPTION
**Pull request by nemishzalavadiya**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@nemishzalavadiya, please fix the below issues
common_issues
- 'BUYER_FINDER_FEES_TYPE' value must be in a generic enum format i.e. PERCENT_ANNUALIZED

on_select(2 & 3 only)
- tag COOL_OFF_PERIOD value must be in ISO 8601 duration format
- Total of quote breakup does not match with price.value
 
on_init
- email is missing in fulfillments
- Total of quote breakup (45510) does not match with price.value (45460)

on_confirm
- email is missing in fulfillments
- Total of quote breakup (45510) does not match with price.value (45460)


Flow-3
on_update
- id mismatches with the id sent in on_confirm call in payments
- incorrect objects present in payments with time.label 'MISSED_EMI_PAYMENT', 'PRE_PART_PAYMENT'
- incorrect object present in quote.breakup with title 'PRE_PAYMENT_CHARGE'
- additional title OTHER_UPFRONT_CHARGES, PRE_PAYMENT_CHARGE present in quote.breakup

on_update(unsolicated)
- id mismatches with the id sent in on_confirm call in payments
- incorrect objects present in payments with time.label 'MISSED_EMI_PAYMENT', 'PRE_PART_PAYMENT'
- incorrect object present in quote.breakup with title 'PRE_PAYMENT_CHARGE'
- additional title OTHER_UPFRONT_CHARGES, PRE_PAYMENT_CHARGE present in quote.breakup


Flow-4
on_update
- id mismatches with the id sent in on_confirm call in payments
- incorrect objects present in payments with time.label 'MISSED_EMI_PAYMENT'
- additional title OTHER_UPFRONT_CHARGES present in quote.breakup


Flow-5
- id mismatches with the id sent in on_confirm call in payments
- additional title OTHER_UPFRONT_CHARGES, OUTSTANDING_PRINCIPAL, OUTSTANDING_INTEREST, PRE_PAYMENT_CHARGE present in quote.breakup
- title LATE_FEE_AMOUNT is missing in quote.breakup


IGM
on_issue
- org.name should be bpp_id::domain i.e. kbl.lenderbridge.uat.ignosis.ai::ONDC:FIS12 at respondent_actions

on_issue_status
- org.name should be bpp_id::domain i.e. kbl.lenderbridge.uat.ignosis.ai::ONDC:FIS12 at respondent_actions
- org.name should be bpp_id::domain i.e. kbl.lenderbridge.uat.ignosis.ai::ONDC:FIS12 at resolution_provider

**Comment by sourabhsaini11** [comment]
@nemishzalavadiya, 
'BUYER_FINDER_FEES_TYPE' value must be in a generic enum format i.e. PERCENT_ANNUALIZED
- the above is a false positive from our end.

**Comment by nemishzalavadiya** [comment]
@92shreyansh please review again. have updated as requested.

**Comment by nemishzalavadiya** [comment]
@sourabhsaini11 please review again so we can start QA testing

**Comment by sourabhsaini11** [comment]
@nemishzalavadiya, please get the below issues fixed as well
common_issue
- bpp_id & bpp_uri are missing in context for action calls (except /search)
- on_update(unsolicated), update & on_update calls capturing Monitoring consent are missing

select
- additional attributes multiple_sumbissions & resubmit present in xinput

on_select_1
- additional attributes multiple_sumbissions & resubmit present in xinput

on_select (2 & 3)
- tag OTHER_PENALTY_FEE is missing in LOAN_INFO tag-group
- multiple objects with title 'OTHER_UPFRONT_CHARGES' present in quote.breakup (on_select_3 only)

init
- additional attributes multiple_sumbissions & resubmit present in xinput

on_init
- tag OTHER_PENALTY_FEE is missing in LOAN_INFO tag-group
- additional attribute collected_by for indexes having type 'POST_FULFILLMENT' in payments

confirm
- additional attributes multiple_sumbissions & resubmit present in xinput

on_confirm
- tag OTHER_PENALTY_FEE is missing in LOAN_INFO tag-group
- tags COURT_JURISDICTION & MANDATORY_ARBITRATION are missing in tag-group SETTLEMENT_TERMS
- additional attribute collected_by for indexes having type 'POST_FULFILLMENT' in payments

on_status
- tag OTHER_PENALTY_FEE is missing in LOAN_INFO tag-group
- OTHER_UPFRONT_CHARGES is missing in quote.breakup
- additional attribute collected_by for indexes having type 'POST_FULFILLMENT' in payments

Flow-4
on_update(unsolicated)
- upon pre-part payment, installments for which payment is captured their status should change to 'DEFERRED' instead of 'NOT-PAID'

IGM
on_issue
- 'created_at' should match issue's 'created_at'
- 'updated_at' of respondent_actions should be the same as or less than issue/update_at

on_issue_status
- 'created_at' should match issue's 'created_at'
- 'updated_at' of respondent_actions should be the same as or less than issue/update_at

**Comment by nemishzalavadiya** [comment]
>on_update(unsolicated), update & on_update calls capturing Monitoring consent are missing
Monitoring consent not taking in journey.

@sourabhsaini11

**Comment by nemishzalavadiya** [comment]
>on_update(unsolicated)
>
>upon pre-part payment, installments for which payment is captured their status should change to 'DEFERRED' instead of 'NOT->PAID'

we are not settling pre-part payment against any installment. Installment still needs to be paid as it is.

**Comment by sourabhsaini11** [comment]
@nemishzalavadiya, please get the below issues fixed
common_issues
- installments 'start' & 'end' time should remain same across all on_action calls, at time.range in payments.

on_select_1
- additional attribute 'required' present at xinput

on_init
- SETTLEMENT_AMOUNT value should be 205.0 as sent in /init call

on_confirm
- SETTLEMENT_AMOUNT value should be 205.0 as sent in /confirm call

on_status
- OTHER_UPFRONT_CHARGES is missing in quote.breakup
- SETTLEMENT_AMOUNT value should be 205.0 as sent in past calls

on_status(unsolicated)
- additional attributes 'multiple_sumbissions' & 'resubmit' present at xinput.form


IGM
on_issue
- 'created_at' should match /issue call 'created_at'
- 'updated_at' at respondent_actions should be the same as or less than issue.update_at

on_issue_status
- 'updated_at' at respondent_actions should be the same as or less than issue.update_at

**Comment by nemishzalavadiya** [comment]
@sourabhsaini11 @92shreyansh required changes been made please review again.

**Comment by sourabhsaini11** [comment]
@nemishzalavadiya, please get the below issues fixed
on_status
- OTHER_UPFRONT_CHARGES is missing in quote.breakup

common_issue
- SETTLEMENT_AMOUNT value should be buyer_finder_fee percent of total amount.
- message_id should be same for status & on_status api call
- Timestamp for /on_status api should be greater than timestamp of /status api

**Comment by nemishzalavadiya** [comment]
@sourabhsaini11 @92shreyansh please review logs

**Comment by nemishzalavadiya** [comment]
@sourabhsaini11 @92shreyansh please re-review our logs

**Comment by sourabhsaini11** [comment]
@nemishzalavadiya, please get the below issue fixed
- message_id should be same for status & on_status api call (Flow-4 & 5)

**Comment by nemishzalavadiya** [comment]
@92shreyansh @sourabhsaini11 Updated logs sequence please re-review,'

* message_id should be same for status & on_status api call (Flow-4 & 5)

above was due to status <> on_status pair mis-match.

It's been resolved.

**Comment by nemishzalavadiya** [comment]
Hi we have resolved the sequencing issue. Please review

**Comment by 92shreyansh** [comment]
Transaction Logs are Approved

**Pull request merged**
