### PR TITLE
Cliniq360 FIS12 Logs

### PR DESCRIPTION
**Pull request by rachitkh4**
Logs added for following flows:

> PERSONAL LOAN (FIS12)
    - Loan Disbursement (Flow1)
    - Foreclosure (Flow3)
    -  Missed-EMI (Flow4)
    - Pre-Part Payment (Flow5)
    - IGM

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@rachitkh4, please provide logs from pre-prod environment

**Comment by rachitkh4** [comment]
@sourabhsaini11 @92shreyansh  updated all the log files to preprod logs
Request you to please validate the logs.

**Comment by sourabhsaini11** [comment]
@rachitkh4, please get the below issues resolved
common_issues
- in LOAN_INFO tag group, COOL_OFF_PERIOD should be in ISO 8601 duration format
- Timestamp should be in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format (BAP calls)

on_search
- tag-group code should be GENERAL_INFO in items

on_init
- value is missing for tag SETTLEMENT_AMOUNT

flow-3
unsolicated on_update call is missing

**Comment by rachitkh4** [comment]
@sourabhsaini11 @92shreyansh  @harsh-refo 

Updates on the above comments
common_issues

1. in LOAN_INFO tag group, COOL_OFF_PERIOD should be in ISO 8601 duration format --- **This is something that is initiated from the seller side. Requesting DMI team to please check this.**
2. Timestamp should be in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format (BAP calls) -- **Fixed from our end . Will push the updated logs.**

on_search

1. tag-group code should be GENERAL_INFO in items -- **This is something that is initiated from the seller side. Requesting DMI team to please check this.**

on_init

1. value is missing for tag SETTLEMENT_AMOUNT -- **This is something that is initiated from the seller side. Requesting DMI team to please check this.**

flow-3

1. unsolicated on_update call is missing -- **We did not receive this after completing the payment. working with DMI support to fix this. Will share the updated logs.**

**Comment by sourabhsaini11** [comment]
common_issues
- bap_id should be same as the domain part of bap_uri

on_search
- Timestamp for on_search api should be greater than timestamp of search api

on_select
- Timestamp for on_select api should be greater than timestamp of select api

init
- payments array is missing

on_init
- Timestamp for on_init api should be greater than timestamp of init api

confirm
- payments array is missing

on_confirm
- Timestamp for on_confirm api should be greater than timestamp of confirm api
@rachitkh4, kindly get the above issues fixed & provide logs from pre-prod environment only

**Comment by rachitkh4** [comment]
@sourabhsaini11  Please check the updated logs 
Fixed following issues 
common_issues
bap_id should be same as the domain part of bap_uri. - Fixed

init
payments array is missing - Fixed

confirm
payments array is missing - Fixed


For below comments : These values we are getting from lender side and hence we won't be able to modify/fix this.
on_search
Timestamp for on_search api should be greater than timestamp of search api
on_select
Timestamp for on_select api should be greater than timestamp of select api
on_init
Timestamp for on_init api should be greater than timestamp of init api
on_confirm
Timestamp for on_confirm api should be greater than timestamp of confirm api

**Comment by rachitkh4** [comment]
Hi @sourabhsaini11 , Please check updated logs
Fixed following issues

init
status is missing in payments -- Fixed
id is missing in payments (init 2 & 3) -- Fixed

confirm
status is missing in payments -- Fixed
id is missing in payments -- Fixed


IGM
issue
Time of creation (created_at) and time of updation (updated_at) for /issue api should be the same -- Fixed
context timestamp should be greater than or equal to updated_at in issue -- Fixed
org.name is incomplete, should be equal to bap_id::domain -- Fixed


on_issue
context timestamp should be greater than or equal to updated_at in on_issue -- Fixed


issue(close)
call is missing -- Fixed


Please review and let us know if any other changes required.

**Comment by sourabhsaini11** [comment]
@rachitkh4 , please resolve the below issues
flow-5
update
- params.amount should be of type string

issue(close)
- context.action should be issue
- rating is missing

on_issue
- context timestamp should be greater than or equal to updated_at in on_issue

issue_status
- context.action should be issue_status

**Comment by sourabhsaini11** [comment]
The rating value can be one of two possible enum values: either 'THUMBS-UP' or 'THUMBS-DOWN'.
Screenshot 2024-04-01 at 6 42 47 PM

**Comment by rachitkh4** [comment]
Thanks @sourabhsaini11 for the sample payload. 
I have made the changes and pushed the updated logs. 
Please review and let me know if there is anything missing.

flow-5
update 
params.amount should be of type string -- Fixed

issue(close)
context.action should be issue -- Fixed
rating is missing - Fixed

on_issue
context timestamp should be greater than or equal to updated_at in on_issue -- We are getting this from lender side and hence we won't be able to modify/fix this.

issue_status
context.action should be issue_status -- Fixed

**Comment by 92shreyansh** [comment]
Tansaction & IGM logs Approved

**Pull request merged**
