### PR TITLE
pre-prod-ondc-ticketing-api.delhitransport.in

### PR DESCRIPTION
**Pull request by AmanChartr**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@AmanChartr, kindly get the below issues fixed
common_issue
- transaction_id must be same once the user session has been initiated.
- type is missing in fulfillments
- action timetsamp should be less than or equal to on_action timestamp

search
- milliseconds must be precise upto 3 places only at context.timestamp
- registration is additional in fulfillment.vehicle

on-search(1)
- incorrect payload, stops_data attribute not supported by api contract.

on_search(2)
- 'INTERMEDIATE_STOP' stops are missing between 'START' & 'END'
- OPERATIONAL_START_TIME & OPERATIONAL_END_TIME tags are missing in ROUTE_INFO tag-group
- invalid code, should be one of SJT, SFSJT, RIT, PASS only
- gps must be precise upto 6 decimal places
- id & parent_stop_id are msising in stops

select
- milliseconds must be precise upto 3 places only at context.timestamp 

on_select
- message_id should be similar to message_id of /select call
- invalid code, should be one of RIDE, SJT, SESJT, RIT, PASS, SEAT only
- 'INTERMEDIATE_STOP' stops are missing between 'START' & 'END'
- gps must be precise upto 6 decimal places
- quantity should contain selected object instead of maximum & minimum
- instead of Discount use OFFER as title.
- breakup.title should be in a generic enum format ex. BASE_FARE, TOLL 
- id & parent_stop_id are msising in stops


init
- milliseconds must be precise upto 3 places only at context.timestamp
- order.id is not part of /init call
- provider.id should map to actual id of the provider.
- instead of 'SETTLEMENT_DETAILS' tag-group code should be 'SETTLEMENT_TERMS'


on_init
- message_id should be similar to message_id of /init call
- cancellation_terms is missing
- gps must be precise upto 6 decimal places
- invalid code, should be one of RIDE, SJT, SESJT, RIT, PASS, SEAT only
- 'INTERMEDIATE_STOP' stops are missing between 'START' & 'END'
- id & parent_stop_id are msising in stops
- quantity should contain selected object instead of maximum & minimum
- instead of Discount use OFFER as title.
- breakup.title should be in a generic enum format ex. BASE_FARE, TOLL 
- payment object is incorrect, should contain payments array

confirm
- milliseconds must be precise upto 3 places only at context.timestamp
- provider.id should map to actual id of the provider.
- instead of 'SETTLEMENT_DETAILS' tag-group code should be 'SETTLEMENT_TERMS'

on_confirm
- message_id should be similar to message_id of /confirm call
- token must be valid instead of "" at stops.authorization
- gps must be precise upto 6 decimal places
- 'INTERMEDIATE_STOP' stops are missing between 'START' & 'END'
- id & parent_stop_id are msising in stops
- breakup.title should be in a generic enum format ex. BASE_FARE, TOLL 
- descriptor should be an object instead of string at provider
- price.value should be string instead of number at quote 
- bank_code, bank_account_number are missing in params at payments

**Comment by sourabhsaini11** [comment]
@AmanChartr, please get the below issues fixed
common_issues
- BUYER_FINDER_FEES_TYPE tag is missing in BUYER_FINDER_FEES tag-group at payments
- In quote at breakup.title 'BASE_FARE', price & quantity are missing in item
- additional attribute 'item' present for breakup.title's TOLL & OFFER

search
- SETTLEMENT_TERMS tag-group is missing

on_search_2
- type is missing in fulfillments
- time is missing in items
- payments array is missing

on_select
- type is missing in fulfillments
- time is missing in items
- OPERATIONAL_START_TIME & OPERATIONAL_END_TIME tags at ROUTE_INFO tag-group are only required in /on_search call

init
- billing is missing

on_init
- billing is missing
- type is missing in fulfillments
- OPERATIONAL_START_TIME & OPERATIONAL_END_TIME tags at ROUTE_INFO tag-group are only required in /on_search call
- time is missing in items
- params is missing in payments
- BUYER_FINDER_FEES_TYPE tag is missing in BUYER_FINDER_FEES tag-group

confirm
- billing is missing

on_confirm
- billing, created_at & updated_at are missing
- instead of "" string, send a valid value for authorization.token at stops
- authorization.valid_to should be in RFC3339 format & milliseconds must be precise upto 3 places only, at stops.
- type is missing in fulfillments
- OPERATIONAL_START_TIME & OPERATIONAL_END_TIME tags at ROUTE_INFO tag-group are only required in /on_search call
- time is missing in items
- bank_account_number, bank_account_number & virtual_payment_address are missing in params
- timestamp should be greater than the timestamp of /confirm call

**Comment by sourabhsaini11** [comment]
@AmanChartr, please get the below issues fixed
search_1
- milliseconds must be precise upto 3 places only at context.timestamp
- SETTLEMENT_TERMS tag-group is missing in payments
- BUYER_FINDER_FEES_TYPE tag is missing in BUYER_FINDER_FEES tag-group at payments

init
- valid values should be present for attributes email, name & phone instead of ""
- tag BUYER_FINDER_FEES_TYPE is missing BUYER_FINDER_FEES tag-group

on_init
- valid values should be present for attributes email, name & phone instead of ""

confirm
- valid values should be present for attributes email, name & phone instead of ""

on_confirm
- billing is missing
- invalid object & attribute "0" present at fulfillments[0]
- invalid tags TRANSIT_PNR & VALID_TILL present in TICKET_INFO tag-group.
- time is missing in items
- bank_account_number, bank_code & virtual_payment_address are missing in payments.params
- tag BUYER_FINDER_FEES_TYPE is missing BUYER_FINDER_FEES tag-group
- instead of "" string, send a valid value for authorization.token at stops

**Comment by 92shreyansh** [comment]
> Hi, @sourabhsaini11
> 
> * Since, we don’t collect any user information that’s why “billing” key would have empty values for name, email and phone
> * I've added dummy values for these fields bank_account_number, bank_code & virtual_payment_address
> * When a valid token is passed in the authorization.token or a value for NUMBER  present in TICKET_INFO tag-group the PR is getting rejected by Git Guardian saying secrets are present in the code, that's why I've left them as empty string.
> 
> CC: @92shreyansh

For absense of field data donot send empty strings/objects/array or null value please do not have those fields
For Git Guardain check ignore the check we will handle it during merge

**Comment by sourabhsaini11** [comment]
@AmanChartr, kindly get these below issues fixed as well
common_issues
- BASE_FARE must be equal to items.price, at quote.breakup

on_confirm
- value is missing for tag 'NUMBER' at 'TICKET_INFO' tag-group in fulfillments

**Comment by AmanChartr** [comment]
Hi, @sourabhsaini11 

- The "billing" key is completely removed rather than leaving it as empty. This is because we don't collect any user details on our side.
- Also, the "token" and TICKET_INFO.NUMBER are not empty this time and so GitGuardian has failed the checks above.

@92shreyansh

**Comment by 92shreyansh** [comment]
Transaction logs Approved with Exception

**Pull request merged**
