### PR TITLE
Added verification logs for Yaary metro

### PR DESCRIPTION
**Pull request by arung-triffy**

### CODE REVIEW

**Comment by sourabhsaini11** [comment]
@arung-triffy, please get the below issue fixed
common_issues
- gps must be precise upto 6 decimal places for gps
- parent_stop_id is required for stops whose stop.type is 'INTERMEDIATE_STOP' & 'END'

search
- payment is missing 
- bpp_id is not part of search call

on_search
- SCHEDULED_INFO tag-group is missing
- milliseconds are missing in start & end time in range & should be precise upto 3 places
- INTERMEDIATE_STOP stops are missing between 'START' & 'END' (on_search_2)

init
- email is missing in billing
- additional attributes present in items.quantity
- tags are missing in payments

on_init
- email is missing in billing
- INTERMEDIATE_STOP stops are missing between 'START' & 'END'
- virtual_payment_address is missing in params
- SCHEDULED_INFO tag-group is missing
- milliseconds are missing in start & end time in range & should be precise upto 3 places

confirm
- email is missing in billing
- additional attributes present in items.quantity
- tags are missing in payments

on_confirm
- email is missing in billing
- INTERMEDIATE_STOP stops are missing between 'START' & 'END'
- virtual_payment_address is missing in params
- SCHEDULED_INFO tag-group is missing
- milliseconds are missing in start & end time in range & should be precise upto 3 places

on_cancel
- email is missing in billing
- INTERMEDIATE_STOP stops are missing between 'START' & 'END'
- virtual_payment_address is missing in params
- SCHEDULED_INFO tag-group is missing
- milliseconds are missing in start & end time in range & should be precise upto 3 places

**Comment by prithvi-triffy** [comment]
@sourabhsaini11 
- SCHEDULED_INFO is optional and hence not added
- Recon is not done through UPI so virtual_payment_address is not sent
- INTERMEDIATE_STOP, parent_stop_id are not sent as of now, since none of the buyer apps are using it. This may be added in a future release. 

cc: @92shreyansh

**Comment by arung-triffy** [comment]
@sourabhsaini11  Please review the logs as we addressed the comments.
 cc @92shreyansh

**Comment by arung-triffy** [comment]
@sourabhsaini11 Please review the logs as we addressed the comments.
cc @92shreyansh

**Comment by sourabhsaini11** [comment]
@arung-triffy, please fix the below issue
on_search
- multiple objects of tag 'STATIC_TERMS' present in payments, keep only 1 & remove other
- fulfilment.type should be ROUTE(on_search_1 only)

**Comment by prithvi-triffy** [comment]
@sourabhsaini11 The comments are addressed. Please do the needful

**Comment by arung-triffy** [comment]
@sourabhsaini11 @92shreyansh Could you please review and approve this PR for us proceed?

**Comment by sourabhsaini11** [comment]
@arung-triffy, please get the below issues fixed
search
- tag SETTLEMENT_AMOUNT is not part of /search call

on_init
- tag SETTLEMENT_TYPE is missing in SETTLEMENT_TERMS tag-group

confirm
- tags SETTLEMENT_WINDOW, SETTLEMENT_BASIS, MANDATORY_ARBITRATION & COURT_JURISDICTION are missing in SETTLEMENT_TERMS tag-group

on_confirm
- tag SETTLEMENT_TYPE is missing in SETTLEMENT_TERMS tag-group

on_status
- tag SETTLEMENT_TYPE is missing in SETTLEMENT_TERMS tag-group

on_cancel
- tag SETTLEMENT_TYPE is missing in SETTLEMENT_TERMS tag-group

**Comment by arung-triffy** [comment]
@sourabhsaini11 @92shreyansh Could you please review and approve this PR for us proceed?

**Comment by 92shreyansh** [comment]
Transaction Logs are Approved for Buyer App

**Pull request merged**
