### PR TITLE
ATXLabs Buyer App Log Submission

### PR DESCRIPTION
**Pull request by vyom-desai-atx**

### CODE REVIEW

**Comment by anuj-ondc** [comment]
@vyom-desai-atx, please fix the below issues:

****Incremental Search****:
  search:
  - remove object descriptor.code for INCREMENTAL_PULL.
  - In tags, missing INCREMENTAL_PULL.(Please refer to developer guide)

**Comment by anuj-ondc** [comment]
@vyom-desai-atx, please fix the below issues:

Incremental Search:
search:
- In tags, missing INCREMENTAL_PULL.(Please refer to developer guide)
 sample payload
 ``` 
 "tags": [
        {
          "display": false,
          "descriptor": {
            "name": "Incremental Pull",
            "code": "INCREMENTAL_PULL"
          },
          "list": [
            {
              "descriptor": {
                "name": "Register",
                "code": "REGISTER"
              },
              "value": "true"
            }
          ]
        },
 ```

**Comment by vyom-desai-atx** [comment]
Hey, @anuj-ondc. Thanks for the input - sorry for the inconvenience caused due to faulty incremental pull calls. The payload previously shared with us unfortunately did not have the tag. and also missed on the incremental pull mechanism from a particular datetime.

**Comment by anuj-ondc** [comment]
@vyom-desai-atx, Please fix the invalid structure of CHANGES_FROM tag. It should appear as part of INCREMENTAL_PULL tag group.
Also both register and CHANGES_FROM can't be in a single API payload.

**Comment by 92shreyansh** [comment]
Transactional logs are approved for BAP

**Pull request merged**
